<div id="openModal" class="popupLoginModel">
	<div>
	<form class="form-signin" method="post" id="popup-login-form">
		<div class="pop-title">
			<a href="#close" title="Close" class="close">X</a>
			<h2><?php echo $this->__("Log In to Your Account")?></h2>
		</div>
		<div class="body">
			<div id="login_msg_div">
				<span id="login-msg"></span>
			</div>
			<div class="form-group">
	 		    <label class="popup-login-lbl" for="email"><?php echo $this->__("Email Address")?></label>
	  		    <input id='username-login' type="text" name='username-login' class="ele_width form-control required-entry validate-email"/>
			</div>
			<div class="form-group">
	 		    <label class="popup-login-lbl" for="password"><?php echo $this->__("Password")?></label>
	  		    <input id="passwd-login" type="password" name="passwd-login" class="ele_width form-control required-entry"/>
	  		    <input type="hidden" name="wishlist" id="wishlist_input" value=""/>
			</div>
		</div>
	    <div class="pop-link">
			<div class="forget-password">
				<a onclick="openRestPasswordModal()"><?php echo $this->__("Forgot Password")?></a>
			</div>
            <div class="submit-login">
                <span id="popup_loader" class="please-wait-popup" style="display: none;">
                <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="Loading next step..." title="Loading next step..." class="v-middle"></span>
                <button type="button" id="signin-btn-popup" class="button"><?php echo $this->__("Log In")?></button>
            
                <?php //google connect code?>
            	<?php if (Mage::helper('core')->isModuleEnabled('Inchoo_GoogleConnect')):?>
            	<div class="mt-googleconnect-btn">
            		<?php echo $this->getLayout()->createBlock('inchoo_googleconnect/button')
            		  ->setTemplate("inchoo/googleconnect/button.phtml")->toHtml(); ?>
            	</div>
            	<?php endif;?>
            
            </div>

			<div class="benifits">
				<p><strong><?php echo $this->__("Create an account to access these benefits:")?></strong></p>
				<ul class="popup-benifits">
				  <li><?php echo $this->__("Keep track of your jewelry sizes")?></li>
				  <li><?php echo $this->__("See your purchase history")?></li>
				  <li><?php echo $this->__("Faster Checkout")?></li>
				  <li><?php echo $this->__("Share your wishlist")?></li>
				  <li><?php echo $this->__("Receive  personalized online service")?></li>
				  <li><?php echo $this->__("$20 off your next purchase if you subscribe to our newsletter")?></li>
				</ul>
			</div>
			<div class="new_account">
				<a onclick="openRegisterModal()"><?php echo $this->__("Click here to create new account!")?></a>
			</div>
		</div> 
	</form>
	</div>
</div>


<script type="text/javascript">
if (typeof Allure == "undefined") {
	 var Allure = {};
}
Allure.Wishlist='<?php echo Mage::getBaseUrl('web').'myaccount/#wishlist';?>';
Allure.LoginFormKey = '<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>';
Allure.LoginUrlAjax = '<?php echo Mage::getBaseUrl('web').'customers/account/ajaxLogin';?>';
</script> 