<div id="openModal" class="popupResetPasswordModel">
	<div>
	<form class="form-resetpassword" method="post" id="popup-resetpassword-form">
		<div class="pop-title">
			<a href="#close" title="Close" class="close">X</a>
			<h2><?php echo $this->__("Retrieve your password here")?></h2>
		</div>
		<div class="body">
			<div id="resetpassword_msg_div">
				<span id="resetpassword-msg"></span>
			</div>
			<div class="form-group">
	 		    <label class="popup-login-lbl" for="email"><?php echo $this->__("Email Address")?></label>
	  		    <input id='resetEmail' type="text" name='email' class="ele_width form-control required-entry validate-email"/>
			</div>
		</div>
        <div class="pop-link">
            <div class="submit-login">
                <span id="popup_loader_resetpassword" class="please-wait-popup" style="display: none;">
                <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="Loading next step..." title="Loading next step..." class="v-middle"></span>
                <button type="button" id="reset_pass_btn" class="button"><?php echo $this->__("Submit")?></button>
            </div>
        </div>
	</form>
	</div>
</div>


<script type="text/javascript">
 function openRestPasswordModal(){
	jQuery(".popupLoginModel").css({"opacity":"0","pointer-events":"none"});
	jQuery(".popupRegisterModel").css({"opacity":"0","pointer-events":"none"});
	jQuery(".popupResetPasswordModel").css({"opacity":"1","pointer-events":"auto"});
};


jQuery(".close").on('click',function(){console.log('hiee');
jQuery(".popupResetPasswordModel").css({"opacity":"0","pointer-events":"none"});
	});

jQuery("#reset_pass_btn").on('click',function(){

     var myForm = new VarienForm('popup-resetpassword-form', true);
	 if(myForm.validator.validate()){
			var email = jQuery('#resetEmail').val();

            var key='<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>';
            var request = {
                 "email":email,
                 'form_key':key
             };
			jQuery.ajax({
			url : '<?php echo Mage::getBaseUrl('web').'customers/account/forgotPasswordPost';?>',
			dataType : 'json',
			type : 'POST',
			data: {request:request},
                    beforeSend: function() { jQuery('#popup_loader_resetpassword').show(); },
                    complete: function() { jQuery('#popup_loader_resetpassword').hide(); },
			success : function(data){
				if(data.success){
                     jQuery('#resetpassword_msg_div').css('display','block');
                     jQuery('#resetpassword-msg').html(data.msg);
                     setTimeout(function(){
                        jQuery(".popupResetPasswordModel").css({"opacity":"0","pointer-events":"none"});
                    }, 5000);

				}else{
			     jQuery('#resetpassword_msg_div').css('display','block');
				 jQuery('#resetpassword-msg').html(data.msg);
				}
				}
			});
		 } //End of form Validate

	    });
</script> 