<div id="mt-filter-toolbar">
	<div class="toolbar-top">
	   <div class="toolbar">
	      <div class="sorter">
	          <span class="mt-a_sortby filter_by" href="#">
	          	  <img src="/skin/frontend/allure/mariatash/images/filter.png" 
	          	  	height="100%" alt="Show Filters" class="v-top"> Filter 
	          	  <span class="glyphicon glyphicon-triangle-bottom"></span>
	          </span>
	       </div>
		</div>
	</div>

<?php
	$currentFilterStore = $_GET ['m_store'];
	if (empty ( $currentFilterStore ))
		$currentFilterStore = 'all';
							
	$currentSort = $_GET ['m_sort'];
	if(empty($currentSort))
		$currentSort = 'desc';
	
	$stores = Mage::app ()->getStores ();
	$storeArr = array();
	foreach ($stores as $store) {
		$storeArr[$store->getId()] = $store->getName();
	}
	
	$sortOderArr = array('desc'=>'Latest Purchase','asc'=>'Oldest Purchase');
?>

	<div id="narrow-by-list" style="display: none;">
		<div class="block-layered-nav-bg"><i class="glyphicon glyphicon-remove"></i></div>
		<ul class="mt-mb-filter-ul">
			<li class="mt-mb-filter-li">
		        <div class="optionfilter" style="display: block;overflow: hidden">
		            <dt class="odd"><?php echo ($currentFilterStore!='all')?$storeArr[$currentFilterStore]:"ALL STORES"?></dt>
		            <dd class="odd" style="display:none">
						<div class="filter_name">ALL STORES</div>
						<ul class="mt-mb-filter-stores">
			    			<li>
			    			<option value="all" <?php echo ($currentFilterStore=='all')?"class='selected-store'":""?> ><?php echo $this->__('All Stores');?></option>
						<?php
							$stores = Mage::app ()->getStores ();
							foreach ($stores as $store) :
						?>
    						
							<option value="<?php echo $store->getId()?>"
								<?php echo ($currentFilterStore==$store->getId())?"class='selected-store'":""?>>
							<?php echo $store->getName()?>
							</option>
            				
            			<?php endforeach;?>
			               </li>
						</ul>
					</dd>
		        </div>
		    </li>
		    
		    <li class="mt-mb-filter-li">
		     <div class="optionfilter" style="display: block;overflow: hidden;cursor: pointer;">
		        <dt class="odd"><?php echo ($currentSort!='')?$sortOderArr[$currentSort]:"SORT BY"?></dt>
		           <dd class="odd" style="display: none;">
				   		<div class="filter_name">SORT BY</div>
							<ul class="mt-mb-filter-sort">
								<li>
									<?php foreach ($sortOderArr as $key=>$name):?>
									<option value="<?php echo $key?>" <?php echo ($currentSort==$key)?"class='selected-sort-type'":""?>><?php echo $name?></option>
									<?php endforeach;?>
			            		</li>
							</ul>
					</dd>
		        </div>
  			</li>
		    
		</ul>
	</div>

</div>


<script>
	jQuery(document).ready(function(){
		jQuery('#mt-filter-toolbar .sorter').on('click',function(){
			var uri = window.location;
			var hash = uri.hash;
    		if(hash=="#purchase" || hash=="#receipt" || hash=="#openorders"){
        		console.log(jQuery('#narrow-by-list').innerHeight());
   				if(jQuery('#mt-purchase-item-tab .no-purchase-item').length){
   					jQuery('#mt-filter-toolbar #narrow-by-list').css({"position":"relative","margin-top":"-39px"});
   					//jQuery('#mt-purchase-item-tab .cart-mt').css({"height":"245px"});
   				}
   				if(jQuery('#mt-report-tab .no-order-msg').length){
   					jQuery('#mt-filter-toolbar #narrow-by-list').css({"position":"relative"});
   					//jQuery('#mt-report-tab .box').css({"height":"245px"});
   				}
   				if(jQuery('#mt-openorders-tab .no-order-msg').length){
   					jQuery('#mt-filter-toolbar #narrow-by-list').css({"position":"relative"});
   					//jQuery('#mt-openorders-tab .box').css({"height":"245px"});
   				}
    		}
    		jQuery('#mt-filter-toolbar #narrow-by-list').show();
		});

		jQuery('#mt-filter-toolbar #narrow-by-list .glyphicon-remove').on('click',function(){
			jQuery('#mt-filter-toolbar #narrow-by-list').hide();
			if(jQuery('#mt-purchase-item-tab .no-purchase-item').length){
				jQuery('#mt-filter-toolbar #narrow-by-list').css({"position":""});
				//jQuery('#mt-purchase-item-tab .cart-mt').css({"height":""});
			}
			if(jQuery('#mt-report-tab .no-order-msg').length){
				jQuery('#mt-filter-toolbar #narrow-by-list').css({"position":""});
				//jQuery('#mt-report-tab .box').css({"height":""});
			}
			if(jQuery('#mt-openorders-tab .no-order-msg').length){
				jQuery('#mt-filter-toolbar #narrow-by-list').css({"position":""});
				//jQuery('#mt-openorders-tab .box').css({"height":""});
			}
		});


		jQuery('ul.mt-mb-filter-stores li option').click(function(){
            var mval = jQuery(this).val();
			 var uri = window.location;
			 var host = uri.origin;
			 var params = getParams('m_store',mval);
			 var path = uri.pathname + params;
			 var hash = uri.hash;
			 var url = host + path + hash;
			 window.location.href = url;
        });

        jQuery('ul.mt-mb-filter-sort li option').click(function(){
            var mval = jQuery(this).val();
			 var uri = window.location;
			 var host = uri.origin;
			 var params = getParams('m_sort',mval);
			 var path = uri.pathname + params;
			 var hash = uri.hash;
			 var url = host + path + hash;
			 window.location.href = url;
        });

		
	});
</script>

