<?php if(false):?>
<div class="clearer">
    <div class="allure-google-connect">
        <div class="allure-google-connect-inner">
            <a href="<?php echo $this->_getButtonUrl(); ?>"><?php echo $this->_getButtonText(); ?></a>
        </div>
        <div class="allure-google-connect-right"></div>
    </div>
</div>
<?php endif;?>

<div class="clearer">
	<a href="<?php echo $this->_getButtonUrl(); ?>">
    	<img class="gle-img" alt="" src="<?php echo $this->getSkinUrl("allure/googleconnect/images/google-login.png")?>" />
	
    </a>
</div>
