<?php if(false):?>
<div class="allure-google-connect-checkout">
    <div class="col2-set">
        <div class="col-1">
            <h3><?php echo $this->__('Google Connect') ?></h3>
            <p><?php echo $this->__('For even more convenience you can login using your Google credentials.') ?></p>
            <?php echo $this->getChildHtml('allure_googleconnect_checkout_button')?>
        </div>
        <div class="col-2"> </div>
    </div>    
</div>
<?php endif;?>

<div class="mt-googleconnect-btn">
	<?php echo $this->getChildHtml('allure_googleconnect_checkout_button')?>
</div>
