<?php

?>
<div class="allure-google-connect-login">
    <div class="account-login">
        <div class="col2-set">
            <div class="col-1 new-users">
                <div class="content">
                    <h2><?php echo $this->__('Google Connect'); ?></h2>
                    <p><?php echo $this->__('You can also log into our shop using your <strong>Google</strong> account credentials.'); ?></p>
                </div>
            </div>
        </div>
        <div class="col2-set">
            <div class="col-1">
                <div class="buttons-set">
                    <?php echo $this->getChildHtml('allure_googleconnect_login_button'); ?>
                </div>
            </div>
        </div>
    </div>    
</div>
