<div class="tatoo_right_title">
    <a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).($this->getUrlArtist()) ?>"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA). DS .'tattoo' . DS . $this->getImage(); ?>" alt="" width="60" height="60"></a>
</div>
<div class="block">
    <a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).($this->getUrlArtist()) ?>"><h3><span>View other artists</span></h3></a>
</div>