<!-- <div class="page-title title-buttons">
	<h1><?php echo $this->__('My Saved Cards') ?></h1>
</div> -->

<div class="my-account">
	<div class="col2-set">
		<div class="box">
            <div class="breadcrumb-payment">
            <?php echo $this->getLayout()->getBlock('breadcrumbs')->toHtml(); ?>
            </div>
            <div class="box-title">
				<h1><?php echo $this->__('Payment Options') ?></h1>
			</div>

            <?php if( count( $this->getActiveMethods() ) > 1 ): ?>
				<ul class="links">
					<?php foreach( $this->getActiveMethods() as $method ): ?>
						<li <?php if( Mage::registry('method') == $method ): ?>class="active"<?php endif; ?>><a href="<?php echo $this->getUrl( '*/*/*', array( 'method' => $method ) ); ?>"><?php echo Mage::getStoreConfig( 'payment/' . $method . '/title' ); ?></a></li>
					<?php endforeach; ?>
				</ul>
			<?php endif; ?>

			<div class="manage-payment-method">
				<?php echo $this->getChildHtml(); ?>
			</div>
		</div>
	</div>
</div>

<style>
  header .top-bar{
        display: none;
    }
</style>

