<?php
$parentCategory=$this->getParentCategories();

foreach ($parentCategory as $pc):
if($pc->getChildrenCount()):
$childRightSection=array();

if($this->isthumbnailCat($pc->getName())){
    ?>
    <section id="<?= str_replace(" ","_",strtolower($pc->getName())) ?>" class="sub-menu maria-jewelry-extend bg-white <?= str_replace(" ","_",strtolower($pc->getName())) ?>" style="display:none">
      <div class="text-right submenu-upper-section d-lg-none d-block">
          <span class="parent-category float-left"><a href="/<?= $pc->getRequestPath() ?>"><?= strtolower($pc->getName()) ?></a></span>
                        <span class="close-section">Back</span>
                        </div>
        <div class="row menu-inner">
            <div class="col-12 mt-4">
                <div class="row div-row">

<?php foreach ($this->getChildCategories($pc->getId()) as $child) {
                                    if (!$child->getIsActive() || !$this->wholesaleCheck($child->getId()))
                                        continue;
                                    ?>
    <div class="col-lg col-12 piercing_options"> <a href="/<?= $child->getRequestPath() ?>"><img src="<?= $this->getCatThumbnail($child->getId())?>" alt="<?= $child->getName()?>">
    <div class="image-text text-center">
      <h6 class="text-uppercase text-white"><?= $child->getName()?></h6>
    </div>
    </a></div>
             <?php } ?>
                </div>
            </div>
    </section>
<?php }
    else{
        ?>
        <section id="<?= str_replace(" ","_",strtolower($pc->getName())) ?>" class="sub-menu maria-appointment-extend bg-white <?= str_replace(" ","_",strtolower($pc->getName())) ?>" style="display:none">
                                  <div class="text-right submenu-upper-section d-lg-none d-block">
                                      <span class="parent-category float-left"><a href="/<?= $pc->getRequestPath() ?>"><?= strtolower($pc->getName()) ?></a></span>
                                    <span class="close-section ">Back</span>
                                  </div>
            <div class="row piercing-inner">
                <div class="col-lg-12 menu-common-section">
                    <div class="row">
                        <div class="col-lg-7 col-12 left-section">
                            <div class="row inner-box">
                                <?php foreach ($this->getChildCategories($pc->getId()) as $child) {
                                    if (!$child->getIsActive() || !$this->wholesaleCheck($child->getId()))
                                        continue;

                                    if ($this->isJwRightSectionCat($child->getName())) {
                                        $childRightSection[] = $child;
                                        continue;
                                    }
                                    ?>
                                    <div class="col-lg col-12 common-option-div" id="c-<?= $child->getId() ?>">
                                        <div class="menu-head jwl-head text-uppercase">
                                            <span><a href="/<?= $child->getRequestPath() ?>"><?= $child->getName(); ?></a></span>
                                        </div>
                                        <div class="head-child">
                                            <ul class="p-0">
                                                <?php foreach ($this->getChildCategories($child->getId()) as $child2) {
                                                    if (!$child2->getIsActive() || !$this->wholesaleCheck($child2->getId()))
                                                        continue;
                                                    ?>
                                                    <li class=""><a
                                                                href="/<?= $child2->getRequestPath() ?>"><?= $child2->getName() ?></a>
                                                    </li>
                                                <?php } ?>
                                            </ul>
                                        </div>
                                    </div>
                                <?php } ?>
                            </div>
                    </div>
                    <div class="col-lg-5 col-12 text-uppercase right-section">
                        <div class="row">
                            <?php foreach ($childRightSection  as $childR){ ?>
                            <a href="/<?= $childR->getRequestPath() ?>">
                                <div class="col-md col-12 p-0 text-center special-menu">
                                    <img width="228px" src="<?= $this->getCatThumbnail($childR->getId()) ?>">
                                    <div class="product-name image-text"><h6 class="text-uppercase text-white"><?= $childR->getName() ?></h6></div>
                                </div>
                            </a>
                        <?php } ?>
                    </div>
                </div>
                </div>
        </section>
        <?php
    }
    endif;
endforeach;
?>
