<?php
$parentCategory = $this->getParentCategories();

foreach ($parentCategory as $pc):
if($pc->getChildrenCount()):
$childRightSection=array();

if($this->isthumbnailCat($pc->getName())){
    ?>
    <section id="<?= str_replace(" ","_",strtolower($pc->getName())) ?>" class="sub-menu maria-jewelry-extend bg-white <?= str_replace(" ","_",strtolower($pc->getName())) ?>" style="display:none">
      <div class="text-right submenu-upper-section d-lg-none d-block">
          <span class="parent-category float-left"><a href="/<?= $pc->getRequestPath() ?>"><?= strtolower($pc->getName()) ?></a></span>
          <span class="close-section">Back</span>
      </div>
        <div class="row menu-inner">
            <div class="col-12 mt-lg-0 mt-4">
                <div class="row div-row">

<?php foreach ($this->getChildCategories($pc->getId()) as $child) {
        if (!$child->getIsActive() || !$this->wholesaleCheck($child->getId()))
            continue;
        ?>
<div class="col-lg col-12 piercing_options"> <a href="/<?= $child->getRequestPath() ?>"><img src="<?= $this->getCatThumbnail($child->getId())?>" alt="<?= $child->getName()?>">
    <div class="image-text text-center">
      <h6 class="text-uppercase text-white"><?= $this->__($child->getName())?></h6>
    </div>
    </a></div>
             <?php } ?>
                </div>
            </div>
    </section>
<?php }
    else{
        ?>
        <section id="<?= str_replace(" ","_",strtolower($pc->getName())) ?>" class="sub-menu maria-appointment-extend bg-white <?= str_replace(" ","_",strtolower($pc->getName())) ?>" style="display:none">
          <div class="text-right submenu-upper-section d-lg-none d-block">
              <span class="parent-category float-left"><a href="/<?= $pc->getRequestPath() ?>"><?= strtolower($this->__($pc->getName())) ?></a></span>
            <span class="close-section ">Back</span>
          </div>
            <div class="row piercing-inner">
                <div class="col-lg-12 menu-common-section">
                    <div class="row">
                        <div class="col-12 left-section">
                            <div class="row inner-box">
                                <?php foreach ($this->getChildCategories($pc->getId()) as $child) {
                                    if (!$child->getIsActive() || !$this->wholesaleCheck($child->getId()))
                                        continue;

                                    if ($this->isJwRightSectionCat($this->__($child->getName()))) {
                                        $childRightSection[] = $child;
                                        continue;
                                    }
                                    ?>
                                    <div class="common-option-div" id="c-<?= $child->getId() ?>">
                                        <div class="menu-head jwl-head text-uppercase">
                                            <span><a href="<?= (!$child->hasChildren())? "/".$child->getRequestPath() : "#" ?>" class="active"><?= $this->__($child->getName()); ?></a></span>
                                        </div>
                                        <div class="head-child active">
                                            <ul class="p-0">
                                                <?php foreach ($this->getChildCategories($child->getId()) as $child2) {
                                                    if (!$child2->getIsActive() || !$this->wholesaleCheck($child2->getId()))
                                                        continue;
                                                    ?>
                                                    <li class="">
                                                    	<a href="/<?= $child2->getRequestPath() ?>"><?= $this->__($child2->getName()); ?></a>
                                                    </li>
                                                <?php } ?>
                                                <?php  if(count($this->getChildCategories($child->getId()))):?>
                                                <li class="view-all-products">
                                                	<a href="/<?= $child->getRequestPath() ?>"><?= $this->__("View All")?></a>
                                                </li>
                                                <?php endif;?>
                                            </ul>
                                        </div>
                                    </div>
                                <?php } ?>
                            </div>
                    </div>
                    <?php if (false) :?>
                    <div class="col-lg-5 col-12 text-uppercase right-section">
                        <div class="row">
                            <?php foreach ($childRightSection  as $childR){ ?>
                            <a href="/<?php echo $childR->getRequestPath() ?>">
                                <div class="col-md col-12 p-0 text-center special-menu">
                                    <img width="228px" src="<?php echo $this->getCatThumbnail($childR->getId()) ?>">
                                    <div class="product-name image-text"><h6 class="text-uppercase text-white"><?php echo $this->__($childR->getName()); ?></h6></div>
                                </div>
                            </a>
                        <?php } ?>
                    </div>
                    <?php endif;?>
                </div>
             </div>
        </section>
        <?php
    }
    endif;
endforeach;
?>
