<?php //allure code start?>
<div class="giftmessage-order-create">
    <div class="entry-edit">
        <div class="fieldset">
            <div>
                <div style="background-color: #eee;padding: 6px 14px;">
                	<?php 
                	$form = new Varien_Data_Form(array(
                	    'id'        => 'edit_form',
                	));
                	$element = new Varien_Data_Form_Element_Date(
                	    array(
                	        'name' => 'order[created_at]',
                	        'label' => Mage::helper('adminhtml')->__('Date'),
                	        'tabindex' => 1,
                	        'image' => $this->getSkinUrl('images/grid-cal.gif'),
                	        'format' => Mage::app()->getLocale()->getDateFormat(Mage_Core_Model_Locale::FORMAT_TYPE_SHORT),
                	        'value' => Mage::getModel('core/date')->date('m/d/Y')
                	    )
                	    );
                	$element->setForm($form);
                	$element->setId('order_date');
                	echo $element->getElementHtml();
                	?>
                </div>
            </div>
            <div class="clear"></div>
        </div>
    </div>
</div>
<?php //allure code end?>