<ul class="form-list" id="payment_form_applepay" style="display:none;">
    <?php if( $this->getMethod()->isAcceptJsEnabled() === true ): ?>
    <li class="form-alt">Pay with Apple Pay from your Phone
        	<script type="text/javascript">
        		//<![CDATA[
        			
        			var s = document.createElement('script');
        			s.type = "text/javascript";
        			s.src = "<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS, true) . 'allure/applepay.js'; ?>";
        			var fs = document.getElementsByTagName('script')[1];
        			fs.parentNode.insertBefore(s, fs);

        			Allure.ApplePay.BaseUrl = '<?php echo Mage::getUrl('applepay/process', array('_secure' => true)); ?>';
        			Allure.ApplePay.MerchantId = '<?php $this->getMethod()->getConfigData('merchant_id') ?>';
        			Allure.ApplePay.MerchantName = '<?php $this->getMethod()->getConfigData('merchant_name') ?>';
        
            	//]]>
    		</script>
    	</li>
    <?php endif; ?>
 </ul>
