<?php
/**
 * Apple Pay
 *
 * @category    Allure
 * @package     Allure_ApplePay
 * @copyright   Copyright (c) 2017 Allure Inc
 * @license     http://opensource.org/licenses/Apache-2.0  Apache License, Version 2.0
 */
?>
<?php if ($this->isEnabled() && !$this->isLoaded()) : ?>
<!-- Apple Pay Async Script -->
<script async='async' type='text/javascript' src='<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS, true) . 'allure/applepay.js?ts='.now(); ?>'></script>
<div class="applepay-popup modal fade" id="applepay-popup">
    <div class="applepay-popup-container modal-content">
    		<div class="modal-header">
            <h4 class="modal-title">Maria Tash Checkout</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    			<span aria-hidden="true">×</span>
            </button>
        </div>
    		<div class="modal-body">
			<div id="applepay-coupons">
        			<div class="cart-mt">
                    <div class="cart-collaterals">
                        <div class="collat-wrap">
                            <div class="coupons-mt">
                                <div class="coupons">
                                    <div class="discount">
                                        <h2>Gift Cards</h2>
                                    
                                        <div class="discount-form">
                                            <form method="post" action="https://mariatash.sureshinde.in/giftcards/cart/activateGiftCard/" id="applePayActivateGiftCard">
                                                <div class="input-box">
                                                    <input value="" name="giftcard_code" id="giftcard_code" class="input-text">
                                                </div>
                                                <div class="buttons-set">
                                                    <button value="Activate" onclick="giftCardForm.submit(true)" class="button" title="Apply" type="button"><span><span>Apply</span></span>
                                                    </button>
                                                </div>
                                            </form>
                                    
                                                        </div>
                                        <script type="text/javascript">
                                            //&lt;![CDATA[
                                            var ApplePayGiftCardForm = new VarienForm('applePayActivateGiftCard');
                                            //]]&gt;
                                        </script>
                                    
                                    </div>
                                    <br>
                                    <div class="discount">        
                                        <h2>Promo Code</h2>
                                        <div class="discount-form">
                                    		<form id="applepay-discount-coupon-form" action="/checkout/cart/couponPost/" method="post">
                                                <input type="hidden" name="remove" id="remove-coupone" value="0">
                                                <div class="input-box">
                                                    <input class="input-text required-entry" id="coupon_code2" name="coupon_code" value="">
                                                </div>
                                                <div class="buttons-set">                
                                                	<button type="button" title="Apply" class="button" onclick="discountForm.submit()" value="Apply"><span><span>Apply</span></span></button>                
                                                </div>
                                    		</form>
                                        </div>
                                        	<script type="text/javascript">
                                        	//<![CDATA[
                                            	var ApplePayDiscountForm = new VarienForm('applepay-discount-coupon-form');
                                            	Validation.add('emptycustomvalidation','This is a required field',function(myInput){
                                            	    if( myInput != '' )
                                            	    {
                                            	        return true;
                                            	    }
                                            	    return false;
                                            	});
                                            	
                                            	ApplePayDiscountForm.submit = function (remove) {
                                            	    $('coupon_code2').addClassName('required-entry');
                                            	    $('coupon_code2').addClassName('emptycustomvalidation');        
                                            	    $('remove-coupone').value = "0";
                                            	    if (this.validator.validate()) {
                                            	        if (remove) {
                                            	            $('coupon_code2').removeClassName('required-entry');
                                            	            $('remove-coupone').value = "1";            
                                            	        } else {
                                            	            $('coupon_code2').addClassName('required-entry');
                                            	            $('coupon_code2').addClassName('emptycustomvalidation');        
                                            	            $('remove-coupone').value = "0";
                                            	        }
                                            	        return VarienForm.prototype.submit.bind(ApplePayDiscountForm)();
                                            	    }
                                            	   return false;
                                            	}
                                        	//]]>
                                        	</script>               
                                    </div>
                					</div>
                            </div>
                			</div>
                    </div>
                </div>
    			</div>
        </div>
        <div class="modal-footer">
            <button type="button" id="applepay-btn-cancel" class="btn btn-outline-secondary btn-sm" data-dismiss="modal">Cancel</button>
            <button type="button" id="applepay-btn-submit" class="btn btn-secondary btn-sm">Submit</button>
            <button type="button" id="applepay-btn-pay" class="btn btn-secondary btn-sm apple-pay-button apple-pay-button apple-pay-button-black-with-line" onclick="return Allure.ApplePay.Callbacks.ApplePayButtonProductPay();">Apple Pay</button>
        </div>
    </div>
</div>
<script type="text/javascript">
<!--
Allure.ApplePay.modal = jQuery('#applepay-popup').modal({show: false});
//-->
</script>
<?php endif; ?>