<?php
/**
 * Apple Pay
 *
 * @category    Allure
 * @package     Allure_ApplePay
 * @copyright   Copyright (c) 2017 Allure Inc
 * @license     http://opensource.org/licenses/Apache-2.0  Apache License, Version 2.0
 */

$quote = Mage::getSingleton('checkout/session')->getQuote();

$couponCode = '';
$giftCardCodes = array();

if ($quote && $quote->getCouponCode()) {
    $couponCode = $quote->getCouponCode();
}

$giftCardCodes = (array) Mage::getSingleton('giftcards/session')->getCardIds();

?>
<?php if ($this->isEnabled() && !$this->isLoaded()) : ?>
<!-- Apple Pay Async Script -->
<!--<script async='async' type='text/javascript' src='<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS, true) . 'allure/applepay.js?ts='.now(); ?>'></script>-->
<div class="applepay-popup modal fade" id="applepay-popup">
    <div class="applepay-popup-container modal-content">
    		<div class="modal-header">
            <h4 class="modal-title">Maria Tash Checkout</h4>
<!--             <button type="button" class="close" data-dismiss="modal" aria-label="Close"> -->
<!--     			<span aria-hidden="true">×</span> -->
<!--             </button> -->
        </div>
    		<div class="modal-body">
			<div id="applepay-coupons">
        			<div class="cart-mt">
                    <div class="cart-collaterals">
                        <div class="collat-wrap">
                            <div class="coupons-mt">
                                <div class="coupons">
                                    <div class="discount" style="display: none">
                                        <h2>Gift Cards</h2>

                                        <div class="discount-form" >
                                            <form method="post" action="/giftcards/cart/activateGiftCard/" id="applePayActivateGiftCard">
                                            	<?php foreach ($giftCardCodes as $giftCardCode):?>
                                                <div class="input-box">
                                                    <input value="<?php echo $giftCardCode;?>" name="giftcard_code" id="giftcard_code" class="input-text giftcard_code giftcard_code_saved" readonly="readonly">
                                                </div>
                                                <div class="buttons-set">
                                                    <button value="Remove" id="applepay-btn-giftcard-remove" onclick="return Allure.ApplePay.action.removeGiftCard('<?php echo $giftCardCode;?>')" class="button giftcard_button giftcard_button_remove" title="Remove Gift Card" type="button"><span><span>Apply</span></span></button>
                                                </div>
                                                <?php endforeach;?>
                                                <div class="input-box">
                                                    <input value="" name="giftcard_code" id="giftcard_code" class="input-text giftcard_code giftcard_code_new required-entry">
                                                </div>
                                                <div class="buttons-set">
                                                    <button value="Add" id="applepay-btn-giftcard-add" onclick="return Allure.ApplePay.action.addGiftCard()" class="button giftcard_button giftcard_button_remove" title="Add Gift Card" type="button"><span><span>Apply</span></span></button>
                                                </div>
                                            </form>
                                        </div>
                                        <script type="text/javascript">
                                            //&lt;![CDATA[
                                            var ApplePayGiftCardForm = new VarienForm('applePayActivateGiftCard');
                                            //]]&gt;
                                        </script>

                                    </div>
                                    <div class="discount">
                                        <h2>Promo Code</h2>
                                        <div class="discount-form">
                                    		<form id="applepay-discount-coupon-form" action="/checkout/cart/couponPost/" method="post">
                                                <input type="hidden" name="remove" id="remove-coupone" value="0">
                                                <div class="input-box">
                                                    	<input class="input-text required-entry" id="coupon_code2" name="coupon_code" value="<?php echo ($couponCode ? $couponCode : '');?>" <?php echo ($couponCode ? 'readonly="readonly"' : '');?> />
                                                </div>
                                                <div class="buttons-set">
                                                		<button type="button" id="applepay-btn-coupon" title="Coupon Code" class="button" onclick="return Allure.ApplePay.action.toggleCouponCode()" data-action="<?php echo ($couponCode ? 'remove' : 'apply');?>" value="Save"><span><span><?php echo ($couponCode ? 'Remove' : 'Apply');?></span></span></button>
                                                </div>
                                    		</form>
                                        </div>
                                        	<script type="text/javascript">
                                        	//<![CDATA[
                                            	var ApplePayDiscountForm = new VarienForm('applepay-discount-coupon-form');
                                        	//]]>
                                        	</script>
                                    </div>
                					</div>
                            </div>
                			</div>
                    </div>
                </div>
    			</div>
        </div>
        <div class="modal-footer">
            <button type="button" id="applepay-btn-cancel" class="btn btn-outline-secondary btn-sm" data-dismiss="modal">Cancel</button>
            <button type="button" id="applepay-btn-submit" class="btn btn-secondary btn-sm">Submit</button>
            <button type="button" id="applepay-btn-pay" class="btn btn-secondary btn-sm apple-pay-button apple-pay-button apple-pay-button-black-with-line" onclick="return Allure.ApplePay.Callbacks.ApplePayButtonProductPay();">Apple Pay</button>
        </div>
    </div>
</div>
<script type="text/javascript">
<!--
Allure.ApplePay.modal = jQuery('#applepay-popup').modal({show: false});
//-->
</script>
<?php endif; ?>
