<p class="category-image"><img src="<?php echo $this->getSkinUrl('images/redesign/catalog.jpg'); ?>" alt="" title="">
    <div class="page-height">
    <div class="page-title mt-4">
        <h1 class="text-center mb-4 higher-h1"><?php echo $this->__('Thank You ') ?></h1>
    </div>
    <div class="cart-empty">
        <p><?php echo $this->__('Your application has been submitted.') ?></p>
        <p><button class="button continue-shopping-button" type="button" onclick="window.location.href='<?php echo Mage::getBaseUrl()?>jewelry.html'">continue shopping</button></p>
    </div>
</div>
