<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<head>
    <style>
        table{
            border-collapse: collapse;
            border-spacing: 0px;
            border-color:#dedede;
        }
        table,table td, table th, table tr , tbody, thead, tfoot{
            border:0;
        }
        dd, dt {
            display:inline-block;
            margin-left:0;}
        dd th, dd td {
            text-align:left;
            padding:0;
        }
        .payment-method table th {
            text-align:left;
            padding:0;
        }
        dd table {
            border:0;
        }
        </style>
    </head>
<body bgcolor="#ffffff" style="color: #3f4048;font-size: 13px;margin: 0;font-family: Arial, Helvetica, sans-serif">
<table width="1000" border="0" align="center" cellpadding="0" cellspacing="0" style="margin: 0 auto;">
    <tr>
        <td class="header" style="padding: 0;height: 108px; background: url('http://mt-redesign.aws00.allureinc.dev//skin/frontend/mt/default/images/header_mail_bgr.png') repeat-x scroll 0 0 #dedede;">

            <h1 class="logo" style="margin: 0;">
                <a style="color:#3f4048; text-decoration:underline" href="http://mt-redesign.aws00.allureinc.dev/" style="color: #3f4048;text-decoration: underline">
                    <img src="http://mt-redesign.aws00.allureinc.dev//media/wysiwyg/logo.png" border="0" alt="" style="display: block;padding: 15px 0 0 23px; "/>
                    </a>
                </h1>
            </td>
        </tr>
    <tr>
        <td class="body-content" width="956" style="font-size: 13px;padding: 22px;border-bottom:1px solid #cfcfd0; background: #dedede;">
            <!-- ////////////////////////////////////////////////////////////////////// begins dynamic content ////////////////////////////////////////////////////////////////////// -->

            <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse; border-spacing: 0px; border-color:#dedede;">
                <tr>
                    <td valign="top">
                        <h1 style="font-size:32px; font-weight:normal; line-height:40px; margin:0 0 11px 0; text-transform: uppercase;">Hello, Saurabha Pilankar</h1>
                        <p style="font-size: 13px; line-height:17px; margin:0 0 20px 0;">
                            Thank you for your order from Maria Tash.
                            Once your package ships we will send an email with a link to track your order.
                            You can check the status of your order by <a style="color:#3f4048; text-decoration:underline" href="http://mt-redesign.aws00.allureinc.dev/customer/account/">logging into your account</a>.
                            If you have any questions about your order please contact us at <a style="color:#3f4048; text-decoration:underline" href="mailto:customerservice@mariatash.com">customerservice@mariatash.com</a> or call us at <span class="nobr">833 775 8274</span> Monday - Saturday, 12:30pm - 8pm EST, Sunday, 12:30pm - 7pm EST. Your order confirmation is below. Thank you again for your business.</p>
                        </tr>
                <tr>
                    <td style=" padding-left: 10px; background: #d1d1d1; ">
                        <h2 style="font-size:13px; font-weight:normal; margin:0; line-height: 34px; text-transform: uppercase;">Your Order #2019007063-2B</h2>
                        </td>
                    </tr>
                <tr>
                    <td>
                        <table cellspacing="0" cellpadding="0" border="0" width="950" style="border-collapse: collapse; border-spacing: 0px; border-color:#dedede;">
                            <thead>
                            <tr>
                                <th align="left" width="325" style="font-size:13px; padding:0 9px; line-height:17px; background:#DEDEDE;"><h2 style="font-size:13px; font-weight:normal; margin:0; line-height: 34px; text-transform: uppercase;">Order Information</h2></th>
                                </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td align="left" width="475" style="font-size:13px; font-size:13px; padding:0 9px; line-height:17px; font-weight: bold;">Order Date</td>
                                </tr>
                            <tr>
                                <td valign="top" style="font-size:13px; line-height:17px; padding:0 9px 9px; border-bottom:1px solid #d1d1d1;">
                                    November 20, 2019 3:44:41 PM EST
                                    </td>
                                </tr>
                            </tbody>
                            </table>
                        <table cellspacing="0" cellpadding="0" border="0" width="950" style="border-collapse: collapse; border-spacing: 0px; border-color:#dedede;">
                            <thead>
                            <tr>
                                <th align="left" width="475" style="font-size:13px; line-height:17px; padding:9px 9px 0; background:#DEDEDE;">Shipping Information:</th>
                                <th align="left" width="475" style="font-size:13px; line-height:17px; padding:9px 9px 0; background:#DEDEDE;">Shipping Method:</th>
                                </tr>
                            </thead>
                            <tbody>
                            <td valign="top" style="font-size:13px; line-height:17px; padding:0 9px 9px;">
                                <span>Susie Smith</span><br/>

                                10 Ditka Ave , Suite 2500<br />



                                Chicago,  Illinois 60602<br/>
                                United States<br/>
                                Tel: 800-000-0000


                                </td>

                            <td valign="top" style="font-size:13px; line-height:17px; padding:0 9px 9px;">

                                Domestic Expedited
                                <table cellspacing="0" cellpadding="0" border="0" width="475" style="border-collapse: collapse; border-spacing: 0px; border-color:#dedede;">
                                    <thead>
                                    <tr>
                                        <th align="left" width="475" style="font-size:13px; line-height:17px; padding:9px 0px 0; background:#DEDEDE;">Signature Required:</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <td valign="top" style="font-size:13px; line-height:17px; padding:0 0px 9px;">

                                            Signature Required

                                            </td>
                                        </tr>
                                    </tbody>
                                    </table>
                                </td>
                            </tbody>
                            </table>

                        <table cellspacing="0" cellpadding="0" border="0" width="950" style="border-collapse: collapse; border-spacing: 0px; border-color:#dedede;">
                            <thead>
                            <tr>
                                <th align="left" width="475" style="font-size:13px; line-height:17px; padding:9px 9px 0; background:#DEDEDE;">Billing Information:</th>
                                <th align="left" width="475" style="font-size:13px; line-height:17px; padding:9px 9px 0; background:#DEDEDE;">Payment Method:</th>
                                </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td valign="top" style="font-size:13px; line-height:17px; padding:0 9px 9px; border-bottom:1px solid #d1d1d1;">
                                    <span>Saurabh Pilankar</span><br/>

                                    MG Road<br />



                                    Panjim,  Goa 4003001<br/>
                                    India<br/>
                                    Tel: +918390196095


                                    </td>
                                <td valign="top" style="font-size:13px; line-height:17px; padding:0 9px 9px; border-bottom:1px solid #d1d1d1;" class="payment-method">
                                    Credit Card (Secure)
                                    <table>
                                        <tr>
                                            <td>Credit Card Type:</td>
                                            <td>American Express</td>
                                            </tr>
                                        <tr>
                                            <td>Credit Card Number:</td>
                                            <td>XXXX-0005</td>
                                            </tr>
                                        </table>


                                    </td>
                                </tr>
                            </tbody>
                            </table>

                        <table cellspacing="0" cellpadding="0" border="0" width="100%" style="border:1px solid #EAEAEA;">
                            <thead>
                            <tr>
                                <th colspan="10" align="left" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px">Product Name</th>
                                <th align="left" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px">Sku</th>
                                <th align="left" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px">Price</th>
                                <th align="center" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px">Qty</th>
                                <th align="right" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px">Subtotal</th>
                                </tr>
                            </thead>

                            <tbody bgcolor="#F6F6F6">
                            <tr>
                                <td colspan="10" align="left" valign="top"
                                     style="font-size:11px; padding:3px 9px; border-bottom:1px dotted #CCCCCC;">
                                    <strong style="font-size:11px;">7.5mm Diamond Arrow Threaded Stud</strong>
                                    <dl style="margin:0; padding:0;">
                                        <dt>Post Length :</dt>
                                        <dd style="margin:0; padding:0 5px 0 1px;">
                                            5mm                    </dd>
                                        <dt>METAL :</dt>
                                        <dd style="margin:0; padding:0 5px 0 1px;">
                                            Yellow Gold                    </dd>
                                        </dl>
                                    </td>
                                <td align="left" valign="top"
                                     style="font-size:11px; padding:3px 9px; border-bottom:1px dotted #CCCCCC;">XAR75D|YELLOW GOLD</td>
                                <td align="left" valign="top"
                                     style="font-size:11px; padding:3px 9px; border-bottom:1px dotted #CCCCCC;"><span class="price">$215.00</span></td>
                                <td align="center" valign="top"
                                     style="font-size:11px; padding:3px 9px; border-bottom:1px dotted #CCCCCC;">2</td>
                                <td align="right" valign="top" style="font-size:11px; padding:3px 9px; border-bottom:1px dotted #CCCCCC;">
                                    <span class="price">$430.00</span>



                                    </td>
                                </tr>
                            </tbody>

                            <tbody>
                            <tr class="subtotal">
                                <td colspan="12" colspan="12" align="right" style="padding:3px 9px">
                                    Merchandise                    </td>
                                <td colspan="2" colspan="2" align="right" style="padding:3px 9px">
                                    <span class="price">$430.00</span>                    </td>
                                </tr>
                            <tr class="shipping">
                                <td colspan="12" colspan="12" align="right" style="padding:3px 9px">
                                    Shipping                    </td>
                                <td colspan="2" colspan="2" align="right" style="padding:3px 9px">
                                    <span class="price">$27.00</span>                    </td>
                                </tr>
                            <tr class="grand_total">
                                <td colspan="12" colspan="12" align="right" style="padding:3px 9px">
                                    <strong>Total</strong>
                                    </td>
                                <td colspan="2" colspan="2" align="right" style="padding:3px 9px">
                                    <strong><span class="price">$457.00</span></strong>
                                    </td>
                                </tr>
                            </tbody>
                            </table>

                        <p style="margin:0 0 10px 0"></p>
                        </td>
                    </tr>
                <tr>
                    <td align="center" style="text-align:right;"><p style="font-size: 17px; line-height: 40px; text-transform: uppercase; font-weight: bold; margin-top: 0;padding-top: 10px; border-top: 1px solid #d1d1d1;">Thank you!</p></td>
                    </tr>
                </table>

            <!-- ////////////////////////////////////////////////////////////////////// finish dynamic content /////////////////////////////////////////////////////////////////////// -->
            </td>
        </tr>
    <tr>
        <td class="footer-content" style="background: #dedede;"></td>
        </tr>
    </table>
</body>