<script type="text/javascript" language="javascript">
    jQuery.noConflict();

    jQuery(document).ready(function() {

        var startPoint =1;
        if(jQuery(".cur_active").length>0) {
            var startPoint = parseInt(jQuery(".cur_active").attr("data-count")) - 1;
        }
        jQuery('#foo3').jcarousel({
            initCallback: mycarousel_initCallback,
            buttonNextCallback: mycarousel_buttonNextCallback,
            buttonPrevCallback: mycarousel_buttonPrevCallback,
            buttonNextHTML: null,
            buttonPrevHTML: null,
            scroll:1,
            start:startPoint
        });


        jQuery(window).resize();

        jQuery('div.main div.col-main div.category-title').remove();

        if(jQuery('.img-cat').length > 0) {
            jQuery(".img-cat").on("swipeleft", function () {
                console.log('swipeleft');
                jQuery('#next3').click();
            });
            jQuery(".img-cat").on("swiperight", function () {
                console.log('swiperight');
                jQuery('#prev3').click();
            });
        }

    });
    function trigger(carousel)
    {
        var width = jQuery(window).width();
        if ((width < 767)) {
            setTimeout(function () {
                var link = jQuery('.jcarousel-item-' + carousel.first + ' a').attr('href');
                window.location = link;
            }, 2000);
        }
    }

    function mycarousel_initCallback(carousel) {
        jQuery('#prev3').bind('click', function() {
            carousel.prev();
            trigger(carousel);
            return false;
        });

        jQuery('#next3').bind('click', function() {
            carousel.next();
            trigger(carousel);
            return false;
        });
        carousel;
    };

    function mycarousel_buttonNextCallback(carousel, button, enabled) {
        if(enabled){
            jQuery("#next3").css('opacity',1);
        }else{
            jQuery("#next3").css('opacity',0.13);
        }
    };

    function mycarousel_buttonPrevCallback(carousel, button, enabled) {
        if(enabled){
            jQuery("#prev3").css('opacity',1);
        }else{
            jQuery("#prev3").css('opacity',0.13);
        }
    };

    jQuery(window).resize(function() {
        var wi = 0;
        jQuery('ul#foo3 li').each(function(key,element){
            wi += jQuery(element).width();
        });

        if(wi >= document.body.offsetWidth){
            jQuery('#next3, #prev3').show();
        }else{
            jQuery('#next3, #prev3').hide();
        }
    });

</script>
<div class="page-title category-title">
    <?php $_category = Mage::registry('current_category') ?>
    <?php
    if ($_imgUrl = $_category->getImageUrl()) {
        ?>
        <script type="text/javascript" language="javascript">
            jQuery(document).ready(function() {
                jQuery('.col-main').addClass('thumbnail-image');
                jQuery('.top-container').addClass('thumbnail-image');
            });
        </script>
    <?php
    if($_category->getCategoryBleed()) {
        echo '<style type="text/css">
                        div.main div.col-main div.category-title {display: none;}
                        // .caroufredsel_wrapper {margin-top: 240px !important}
                        #productsContainer-wrapper { margin-top: 75px !important; }
                  </style>';
    }
    else {
        echo '<style type="text/css">
                        div.main div.col-main div.category-title {display: none;}
                        #productsContainer-wrapper { margin-top: 75px !important; }
                        .category-products{
                          margin-top: 56px;
                        }
                        .breadcrumbs{
                          margin-top: 26px;
                        }
                        .filter-common-div{
                          top: 269px;
                        }

                        .filterButton:before {left: 0 !important;}
                        @media (min-width:767px) and (max-width:1024px) and (orientation:portrait){
                          .filterButton:before{
                            left: 19px !important;
                          }
                            .category-products{
                              margin-top: 0px;
                            }
                            .catalog-category-view .category-title{
                              margin-top: 0;
                            }
                            .catalog-product-name-display {
                              padding-left: 0;
                            }
                          }
                          @media (min-width:767px) and (max-width:1024px) and (orientation:landscape){
                            #narrow-by-list {
                              margin-left: 61px;
                            }
                          }
                          @media (max-width:1023px){
                            .catalog-product-name-display{
                              margin-top: 20px;
                              padding-left: 0 !important;
                            }
                            #narrow-by-list li div dd{
                              top: 0 !important;
                            }
                            .with-category-image .mb-mana-catalog-leftnav .block-layered-nav-bg, .with-category-image-bleed .mb-mana-catalog-leftnav .block-layered-nav-bg{
                              top: 237px !important;
                            }
                          }
                          @media (max-width:767px) and (orientation:portrait){
                            .catalog-product-name-display{
                              padding-left: 39px;
                            }
                            .filterButton:before{
                              left: 41px !important;
                            }
                            .category-products{
                              margin-top: 0;
                            }
                          }
                          @media (max-width:767px) and (orientation:landscape){
                            .catalog-product-name-display{
                              padding-left: 59px;
                              margin-top: 20px;
                            }
                            .breadcrumbs {
                              padding-left: 21px;
                            }
                            .category-products{
                              margin-top: 0px;
                            }

                          }
                          @media (max-width:767px){
                            .category-products{
                              margin-top: 0;
                            }
                            .filterButton:before {
                              left: 10px !important;
                            }
                            .thumbnail-image #productsContainer-wrapper{
                              margin-top: 25px !important;
                            }
                            .catalog-category-view .category-title{
                              margin-top: 0px;
                            }
                            .catalog-product-name-display{
                              margin-top: 10px;
                            }
                          }

                          
                </style>';
    }
    }
    else {
    ?>
        <script type="text/javascript" language="javascript">
            jQuery(document).ready(function() {
                jQuery('.col-main').addClass('isBleed');
            });
        </script>
        <?php
        echo '<style type="text/css">
                        div.main div.col-main div.category-title {display: none;}
                  </style>';
    }
    ?>

    <h1 class="catalog-product-name-display" style="color: <?php echo $_category->getCategoryColorTitle() ?>"><?php echo $this->getCurrentCategoryName(); ?></h1>
</div>
<?php $_collection = $this->getCategories() ?>
<div class="container cartilage-section position-relative">
    <div class="row" >
        <div class="caroufredsel_wrapper col-12  p-m-0 p-l-0 p-xl-0" >
            <?php if(count($_collection)) { ?>
                <ul id="cartilage-items-slider" class="owl-carousel owl-theme">
                    <?php $i = 1;?>
                    <?php foreach($_collection as $category): ?>
                        <?php $active = strpos(str_replace('.html','',$_SERVER['REQUEST_URI']), str_replace('.html','',str_replace($_SERVER['SERVER_NAME'],'',$category->getUrlPath()))) ? 'class="cur_active"' : '' ?>
                        <li onclick = "Mage.Cookies.set('scroll_to_i',<?php echo $i++?>)">
                            <a <?= $active ?> data-count="<?= $i ?>" href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK) . $category->getUrlPath(); ?>"><h4 class="text-white text-center w-100" <?php echo $active; ?>><?php echo $category->getName(); ?></h4><img class="img-cat" data-id="<?=$i?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'/catalog/category/' . $category->getThumbnail(); ?>" alt="<?php echo $category->getName(); ?>" /></a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            <?php } ?>
        </div>
    </div>
</div>
<script type="text/javascript">
    jQuery(document).ready(function () {
        var $ = jQuery;
        $('#cartilage-items-slider').owlCarousel({
            loop: false,
            margin: 10,
            responsiveClass: true,
            responsive: {
                0: {
                    items: 1,
                    nav: true
                },
                600: {
                    items: 3,
                    nav: false
                },
                1000: {
                    items: 6,
                    nav: true,
                    loop: false
                }
            }
        });
    });
</script>

