<script type="text/javascript" language="javascript">
jQuery.noConflict();

jQuery(document).ready(function() {

    jQuery('#foo3').jcarousel({
        initCallback: mycarousel_initCallback,
        buttonNextCallback: mycarousel_buttonNextCallback,
        buttonPrevCallback: mycarousel_buttonPrevCallback,
        // This tells jCarousel NOT to autobuild prev/next buttons
        buttonNextHTML: null,
        buttonPrevHTML: null
    });

    jQuery(window).resize();

    jQuery('div.main div.col-main div.category-title').remove();

});

function mycarousel_initCallback(carousel) {
    jQuery('#prev3').bind('click', function() {
        carousel.next();
        return false;
    });

    jQuery('#next3').bind('click', function() {
        carousel.prev();
        return false;
    });
};

function mycarousel_buttonNextCallback(carousel, button, enabled) {
    if(enabled){
        jQuery("#prev3").css('opacity',1);
    }else{
        jQuery("#prev3").css('opacity',0.13);
    }
};

function mycarousel_buttonPrevCallback(carousel, button, enabled) {
    if(enabled){
        jQuery("#next3").css('opacity',1);
    }else{
        jQuery("#next3").css('opacity',0.13);
    }
};

jQuery(window).resize(function() {
        var wi = 0;
        jQuery('ul#foo3 li').each(function(key,element){
           wi += jQuery(element).width();
        });

        if(wi >= document.body.offsetWidth){
                jQuery('#next3, #prev3').show();
        }else{
                jQuery('#next3, #prev3').hide();
        }
});

</script>
<div class="page-title category-title">
    <?php $_category = Mage::registry('current_category') ?>
    <?php
    if ($_imgUrl = $_category->getImageUrl()) {
	?>
		<script type="text/javascript" language="javascript">
			jQuery(document).ready(function() {
				jQuery('.col-main').addClass('thumbnail-image');
				jQuery('.top-container').addClass('thumbnail-image');
			});
			</script>
	<?php
        if($_category->getCategoryBleed()) {
            echo '<style type="text/css">
                        div.main div.col-main div.category-title {display: none;}
                        .caroufredsel_wrapper {margin-top: 240px !important}
                        #productsContainer-wrapper { margin-top: 75px !important; }
                  </style>';
        }
        else {
            echo '<style type="text/css">
                        div.main div.col-main div.category-title {display: none;}
                        #productsContainer-wrapper { margin-top: 75px !important; }
                </style>';
        }
    }
    else {
		?>
			<script type="text/javascript" language="javascript">
			jQuery(document).ready(function() {
				jQuery('.col-main').addClass('isBleed');
			});
			</script>
			<?php
        echo '<style type="text/css">
                        div.main div.col-main div.category-title {display: none;}
                        #productsContainer-wrapper { margin-top: 75px !important; }
                        #narrow-by-list{margin-top: 64px;}
                  </style>';
    }
    ?>

    <h1 class="catalog-product-name-display" style="color: <?php echo $_category->getCategoryColorTitle() ?>"><?php echo $this->getCurrentCategoryName(); ?></h1>
</div>
<?php $_collection = $this->getCategories() ?>
<div class="cartilage-section w-100 position-relative">
<div class="caroufredsel_wrapper" >
	<?php if(count($_collection)) { ?>
    <ul id="foo3">
		<?php $i = 1;?>
        <?php foreach($_collection as $category): ?>
            <?php $active = strpos(str_replace('.html','',$_SERVER['REQUEST_URI']), str_replace('.html','',str_replace($_SERVER['SERVER_NAME'],'',$category->getUrlPath()))) ? 'class="active"' : '' ?>
            <li onclick = "Mage.Cookies.set('scroll_to_i',<?php echo $i++?>)">
                <a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK) . $category->getUrlPath(); ?>"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'/catalog/category/' . $category->getThumbnail(); ?>" alt="<?php echo $category->getName(); ?>" /></a>
                <a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK) . $category->getUrlPath(); ?>"><h3 <?php echo $active; ?>><?php echo $category->getName(); ?></h3></a>
            </li>
        <?php endforeach; ?>
    </ul>

	<?php } ?>
</div>
<div class="prev" id="prev3"></div>
<div class="next" id="next3"></div>
</div>
