<script type="text/javascript">
    function toggleCountrySelect() {
        jQuery('#tld_r_ul').toggle(200);
    }
    jQuery.noConflict();
    jQuery(document).ready(function(){
        jQuery('.popbox').each(function() {
            var selector = '#' + jQuery(this).data('tooltip-id');            
            Tipped.create(this, jQuery(selector)[0],{ skin: 'dark_subscribe', offset: { y: -4 }});
        });
        
        Tipped.create('.popbox_ajax',{
            skin: 'dark_subscribe',
			fadeIn: 0,
			fadeOut: 0,
            hideOn: 'click-outside',
            ajax: true,//{type: 'post',cache: false}, 
            hook: 'topmiddle',
            onShow: function(content, element) {
                //<![CDATA[
                var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
                new Varien.searchForm('newsletter-validate-detail', 'email', '<?php echo $this->__('EMAIL ADDRESS') ?>');
                new Varien.searchForm('newsletter-validate-detail', 'first_name', '<?php echo $this->__('FIRST NAME') ?>');
                new Varien.searchForm('newsletter-validate-detail', 'last_name', '<?php echo $this->__('LAST NAME') ?>');
                new Varien.searchForm('newsletter-validate-detail', 'country_subscribe', '<?php echo $this->__('Country') ?>');
                //]]>

//                jQuery("#country").click(function(){		                
//                    jQuery("#tld_r_ul").show(200);
//                });
                // prevent bind event multiple times
                jQuery('#country_subscribe').unbind('click', toggleCountrySelect);
                jQuery('#country_subscribe').bind('click', toggleCountrySelect);
					
                jQuery("#tld_r_ul li").click(function(){
                    var tld=jQuery(this).text();
                    jQuery("#tld_field").val(tld);
                    jQuery("#country_subscribe").val(tld);         
                    jQuery("#tld_r_ul").hide(200);
                });
            }
        }); 
    });
</script>
<?php $links = $this->getAllCustomLinks(); ?>

<div class="container container-footlinks">
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('mobile_footer_links')->toHtml() ?>
    <div class="social-media">
        <div class="sm-fb">
            <a href="<?php echo $this->validURL(Mage::getStoreConfig('ecp_footlinks/footlinks/facebookurl')); ?>" target="_blank"> FB </a>
        </div>
        <div class="sm-tw">
            <a href="<?php echo $this->validURL(Mage::getStoreConfig('ecp_footlinks/footlinks/twitterurl')); ?>" target="_blank"> TW </a>
        </div>
        <div class="sm-pr" style="text-align: left;">
            <a href="<?php echo $this->validURL(Mage::getStoreConfig('ecp_footlinks/footlinks/pinteresturl')); ?>" target="_blank"> P </a>
        </div>
        <div class="sm-insta">
            <a href="<?php echo $this->validURL(Mage::getStoreConfig('ecp_footlinks/footlinks/instaurl')); ?>" target="_blank"> IN </a>
        </div>
        <div class="sm-qr" style="text-align: left;">
            <a href="<?php echo $this->validURL(Mage::getStoreConfig('ecp_yelp/yelp/yelpurl')); ?>" target="_blank"> Y </a>
        </div>
    </div>
</div>
<style>
    #container
    {
        width: 300px;
        overflow: hidden;
    }

    /* THESE ARE THE INDIVIDUAL SLIDE PROPERTIES */
    .slide
    {
        width: 300px;
        height: 70px;
        overflow: hidden;
        float: left;
    }
</style>
