<?php
/**
 * @category    Mana
 * @package     ManaPro_FilterSlider
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */
/**
 * Template for showing options for filter as a slider
 * @author Mana Team
 * Injected instead of standard catalog/layer/filter.phtml in Mana_Filters_Block_Filter_Attribute init() method.
 * This template is overridden by copying (template body was pasted from catalog/layer/filter.phtml
 * and modified as needed). All changes are marked with comments.
 */
/* @var $this Mana_Filters_Block_Filter_Price */
?>
<?php /* @var $_helper Mana_Filters_Helper_Data */ $_helper = Mage::helper(strtolower('Mana_Filters')); ?>
<?php /* @var $_superHelper ManaPro_FilterSuperSlider_Helper_Data */ $_superHelper = Mage::helper(strtolower('ManaPro_FilterSuperSlider')); ?>
<?php /* @var $_slider ManaPro_FilterSlider_Helper_Data */ $_slider = Mage::helper(strtolower('ManaPro_FilterSlider'));?>
<?php /* @var $_filter Mana_Filters_Model_Filter_Price */ $_filter = $this->getFilter(); ?>
<?php $_id = $_helper->getFilterName($_filter,$_filter); ?>
<div class="filter_name">PRICE</div>
<ol class="m-filter-price">
    <li>
<div id="<?php echo $_id ?>-track" class="m-filter-slider">
    <div id="<?php echo $_id ?>-span" class="m-slider-span"></div>
    <div id="<?php echo $_id ?>-from" class="m-slider-from"></div>
    <div id="<?php echo $_id ?>-to" class="m-slider-to"></div>

    <?php if ($_filter->getFilterOptions()->getSliderManualEntry()) : ?>
        <span id="<?php echo $_id ?>-applied" class="m-slider-selected-value">
            <span class="fromprice">
                <?php echo $_superHelper->beforeInput($_filter->getFilterOptions()) ?>
                <input type="text" class="m-slider m-from" size="2" value="<?php echo $_filter->getCurrentRangeLowerBound() ?>" />
                <?php echo $_superHelper->afterInput($_filter->getFilterOptions()) ?>
            </span>

            <span class="toprice">
                <?php echo $_superHelper->beforeInput($_filter->getFilterOptions()) ?>
                <input type="text" class="m-slider m-to"size="2" value="<?php echo $_filter->getCurrentRangeHigherBound() ?>" />
                <?php echo $_superHelper->afterInput($_filter->getFilterOptions()) ?>
            </span>
        </span>
    <?php else: ?>
        <span id="<?php echo $_id ?>-applied" class="m-slider-selected-value">
        <?php echo $_helper->__('<span class="fromprice">%s</span> <span class="toprice">%s</span>', $_superHelper->formatNumber($_filter->getCurrentRangeLowerBound(), $_filter->getFilterOptions()), $_superHelper->formatNumber($_filter->getCurrentRangeHigherBound(), $_filter->getFilterOptions()))?>
    </span>
    <?php endif; ?>
</div>
</li>
</ol>


<script type="text/javascript">

    priceRangeFrom = <?php echo $_filter->getLowestPossibleValue() ?>;

    priceRangeTo= <?php echo $_filter->getHighestPossibleValue() ?>;

    priceAppliedFrom = <?php echo $_filter->getCurrentRangeLowerBound() ?>;

    priceAppliedTO = <?php echo $_filter->getCurrentRangeHigherBound() ?>;

jQuery(document).ready(function($){

    priceRangeFrom = <?php echo $_filter->getLowestPossibleValue() ?>;

    priceRangeTo= <?php echo $_filter->getHighestPossibleValue() ?>;

    priceAppliedFrom = <?php echo $_filter->getCurrentRangeLowerBound() ?>;

    priceAppliedTO = <?php echo $_filter->getCurrentRangeHigherBound() ?>;

    //<![CDATA[
    ManaPro.filterSuperSlider('<?php echo $_id ?>', {
        rangeFrom: <?php echo $_filter->getLowestPossibleValue() ?>,
        rangeTo: <?php echo $_filter->getHighestPossibleValue() ?>,
        appliedFrom: <?php echo $_filter->getCurrentRangeLowerBound() ?>,
        appliedTo: <?php echo $_filter->getCurrentRangeHigherBound() ?>,
        numberFormat: "<?php echo addslashes($_superHelper->currencyFormat()) ?>",
        appliedFormat: '<?php echo $_helper->__('<span class="fromprice">__0__ </span><span class="toprice">__1__</span>') ?>',
        url: '<?php echo $_slider->getUrl($_filter->getRequestVar()) ?>',
        clearUrl: '<?php echo $_slider->getClearUrl($_filter->getRequestVar()) ?>',
        manualEntry: <?php echo $_filter->getFilterOptions()->getSliderManualEntry() ? 1 : 0 ?>,
        formatThreshold: <?php echo $_filter->getFilterOptions()->getSliderThreshold() ? $_filter->getFilterOptions()->getSliderThreshold() : 0 ?>,
        numberFormat2: "<?php echo addslashes($_filter->getFilterOptions()->getSliderNumberFormat2()) ?>",
        existingValues: <?php echo $_filter->getFilterOptions()->getSliderUseExistingValues() ? json_encode($_filter->getExistingValues()) : '{}' ?>,
        decimalDigits: <?php echo $_filter->getFilterOptions()->getSliderDecimalDigits() ?>,
        decimalDigits2: <?php echo $_filter->getFilterOptions()->getSliderDecimalDigits2() ?>
    });
});
//]]>
</script>
