<div id="openModal" class="popupDelMyAccModel">
	<div class="popup-content">
		<div class="pop-title">
			<a href="#close" title="Close" class="close exit-large close-del">
				<img class="d-lg-block d-md-block d-none" src="<?php echo $this->getSkinUrl('images/redesign/login-cross.png'); ?>" alt="x">
				<img class="d-block d-lg-none d-md-none" src="<?php echo $this->getSkinUrl('images/redesign/exit-small-grey.png'); ?>" alt="x">                </a>
				<h1 class="mt-0"><?php echo $this->__("Delete Account")?></h1>
			</div>
			<div class="body">
				<div id="login_msg_div">
					<span id="login-msg"></span>
				</div>
				<p class="del_my_acc_confirm_p para-normal">Do you really want to delete your account and lose the ability to make your shopping better?</p>
				<div>
					<input type="checkbox" name="is_subscribed" title="confirm box" id="popupcheckbox_delmyacc_confirm" class="checkbox">
					<label class="popupcheckbox_lbl_delacc popupcheckbox_lbl para-bold">I understand that I will not be able to recover my data upon deletion.</label>
				</div>
			</div>
			<div class="submit-delete">
				<span id="popup_loader" class="please-wait-popup-del" style="display: none;">
					<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="Loading next step..." title="Loading next step..." class="v-middle"></span>
					<button type="button" id="delmyacc-btn-popup" class="dark-button"><?php echo $this->__("Delete")?></button>
				</div>
			</div>
		</div>


		<script type="text/javascript">
			if (typeof Allure == "undefined") {
				var Allure = {};
			}

			jQuery(document).ready(function() {
				jQuery(".close-del").on('click',function(){
					jQuery("body").css({"overflow": "scroll", "position": "static"});
				});
			});
		</script> 