<?php
/**
 * Magestore
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Magestore.com license that is
 * available through the world-wide-web at this URL:
 * http://www.magestore.com/license-agreement.html
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade this extension to newer
 * version in the future.
 *
 * @category    Magestore
 * @package     Magestore_Webpos
 * @copyright   Copyright (c) 2016 Magestore (http://www.magestore.com/)
 * @license     http://www.magestore.com/license-agreement.html
 */

/**
 * Class Magestore_Webpos_Block_AbstractBlock
 */
class Magestore_Webpos_Block_AbstractBlock extends Mage_Core_Block_Template
{
    /**
     * @var array
     */
    protected $_jsLayout = array();

    /**
     * Constructor
     */
    protected function _construct()
    {
        parent::_construct();
    }

    /**
     * @return mixed
     */
    public function _prepareLayout()
    {
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }

    /**
     * @param $params
     */
    public function setJsLayout($params){
        $jsLayout = $this->_jsLayout;
        if(!empty($params)){
            $jsLayout = $params;
        }
        $this->_jsLayout = $jsLayout;

    }

    /**
     * @return array
     */
    public function getJsLayout($type) {
        return (!empty($type) && isset($this->_jsLayout[$type]))?$this->_jsLayout[$type]:$this->_jsLayout;
    }

    /**
     * @return array
     */
    public function getWebposConfig() {
        return Mage::helper('webpos')->getWebposConfig();
    }

    /**
     * @return string
     */
    public function getBaseUrl()
    {
        if (Mage::app()->getStore()->isFrontUrlSecure()) {
            return Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK, true);
        } else {
            return Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK, false);
        }
    }
}
