<?php
/**
*	Allure checkout step success order.
*/
?>

<?php 
    $isChange = false;
    $_orderIds = array();
    $orderId = Mage::getSingleton("allure_multicheckout/ordered_session")->getLastOrderId();
    $secondOrderId = Mage::getSingleton("allure_multicheckout/backordered_session")->getSecondLastOrderId();
    if($orderId){
        $_orderIds[] = $orderId;
        if(Mage::helper("core")->isModuleEnabled("Allure_Orders")){
            $order = Mage::getModel('sales/order')->load($orderId);
            $storeId = $order->getStoreId();
            $isChange = Mage::helper("allure_orders")->isSuccessPageChange($storeId);
        }
    }
    if($secondOrderId){
        $_orderIds[] = $secondOrderId;
        if(!$isChange){
            if(Mage::helper("core")->isModuleEnabled("Allure_Orders")){
                $order = Mage::getModel('sales/order')->load($secondOrderId);
                $storeId = $order->getStoreId();
                $isChange = Mage::helper("allure_orders")->isSuccessPageChange($storeId);
            }
        }
    }
?>

<?php if($isChange):?>

<div class="multiple-checkout">
    <div class="page-title">
        <h1 class="order-success-title text-center"><?php echo $this->__('Your order has been received') ?></h1>
    </div>
    <div class="checkout-success">
        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
        <h2 class="sub-title info-text-two mb-4"><?php echo $this->__('Thank you for your purchase.') ?></h2>
    	<p class="para-normal"><?php echo $this->__('You will receive an order confirmation email with details of your order and a link to track your progress.') ?></p>
        <p class="para-normal"><?php echo $this->__('Due to COVID-19 and evolving government restrictions, your order may experience shipping and fulfillment delays.') ?></p>
        <p class="para-normal"><?php echo $this->__('If you have any questions regarding your order, please visit our <a class="success-page-text-link-style" href="'.Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB)."contact-us".'">Contact Us</a> page to connect with our customer support team.')?></p>
    </div>
</div>

<?php else:?>

<div class="multiple-checkout">
    <div class="page-title">
        <h1 class="order-success-title text-center"><?php echo $this->__('Your order has been received') ?></h1>
    </div>
    <div class="checkout-success">
        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
        <h2 class="sub-title info-text-two mb-4"><?php echo $this->__('Thank you for your purchase!') ?></h2>
    
        <?php if ($this->getOrderId() && $this->getOrderIdSecond()):?>
            <?php if ($this->getCanViewOrder() && $this->getCanViewOrderSecond()) :?>
                <p class="para-normal"><?php echo $this->__('Your order # is: %s , %s.', sprintf('<a class="para-bold text-underline" href="%s">%s</a>', $this->escapeHtml($this->getViewOrderUrl()), $this->escapeHtml($this->getOrderId())),sprintf('<a class="para-bold text-underline" href="%s">%s</a>', $this->escapeHtml($this->getViewOrderUrlSecond()), $this->escapeHtml($this->getOrderIdSecond()))) ?></p>
            <?php  else :?>
                <p class="para-normal"><?php echo $this->__('Your order # is: %s , %s.', $this->escapeHtml($this->getOrderIdSecond()), $this->escapeHtml($this->getOrderId())) ?></p>
            <?php endif;?>
                <p class="para-normal"><?php echo $this->__('You will receive an order confirmation email with details of your order and a link to track your progress.') ?></p>
            <?php //if ($this->getCanViewOrder() && $this->getCanPrintOrder()) :?>
                <p class="para-normal">
                    <?php echo $this->__('<a class="click-here link-button" href="%s" onclick="this.target=\'_blank\'">Click here</a> to print a copy of your order confirmation.', $this->getPrintUrl()) ?>
                    <?php // echo $this->getChildHtml() ?>
                </p>
            <?php //endif;?>
        <?php endif;?>
        <?php if ($this->getAgreementRefId()): ?>
            <p class="para-normal"><?php echo $this->__('Your billing agreement # is: %s.', sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getAgreementUrl()), $this->escapeHtml($this->getAgreementRefId())))?></p>
        <?php endif;?>
    
        <?php if ($profiles = $this->getRecurringProfiles()):?>
        <p class="para-normal"><?php echo $this->__('Your recurring payment profiles:'); ?></p>
        <ul class="disc">
        <?php foreach($profiles as $profile):?>
        <?php $profileIdHtml = ($this->getCanViewProfiles() ? sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getProfileUrl($profile)), $this->escapeHtml($this->getObjectData($profile, 'reference_id'))) : $this->escapeHtml($this->getObjectData($profile, 'reference_id')));?>
            <li><?php echo $this->__('Payment profile # %s: "%s".', $profileIdHtml, $this->escapeHtml($this->getObjectData($profile, 'schedule_description')))?></li>
        <?php endforeach;?>
        </ul>
        <?php endif;?>
    
        <div class="buttons-set">
            <!-- <button type="button" class="button light-button" title="<?php //echo $this->__('Continue Shopping') ?>" onclick="window.location='<?php //echo $this->getUrl() ?>'"><span><span><?php //echo $this->__('Continue Shopping') ?></span></span></button>-->
        </div>
    </div>
</div>
<?php endif;?>


<?php foreach ($_orderIds as $_orderId): ?>
<?php
    $order = Mage::getModel('sales/order')->load($_orderId); 
    $order_id = $order->getIncrementId(); //the id of the order
    $gtotal = $order->getBaseGrandTotal();//grand total of the order 
    $shippingVal = $order->getBaseShippingAmount();
    $taxAmount = $order->getBaseTaxAmount();
?>
<script type="text/javascript">
    ga('require', 'ecommerce');
    
    ga('ecommerce:addTransaction', {
      'id': '<?php echo $order_id; ?>',		// Transaction ID. Required.
      'affiliation': '',   						// Affiliation or store name.
      'revenue': '<?php echo $gtotal;?>',		// Grand Total.
      'shipping': '<?php echo $shippingVal;?>',	// Shipping.
      'tax': '<?php echo $taxAmount;?>'			// Tax.
    });

<?php $items = $order->getAllItems(); ?>
<?php foreach ($items as $itemId => $item):?>
    ga('ecommerce:addItem', {
      'id': '<?php echo $order_id; ?>',						// Transaction ID. Required.
      'name': '<?php echo $item->getName(); ?>',			// Product name. Required.
      'sku': '<?php echo $item->getSku(); ?>',              // SKU/code.
      'category': '',         								// Category or variation.
      'price': '<?php echo $item->getBasePrice(); ?>',      // Unit price.
      'quantity': '<?php echo $item->getQtyOrdered(); ?>' // Quantity.
    });
<?php endforeach;?> 

	ga('ecommerce:send');

</script>
<?php endforeach;?>

