<?php
/**
 * @category   Allure
 * @package    Allure_CurrencyManager
 * @copyright  Copyright (c) 2016 Allure Inc (http://www.allureinc.co)
 * @contacts   support@allureinc.co
 */
//sometimes our js shown before /js/varien/product.js
//calling this function will update Product.Config to our formatPrice
?>
<script type="text/javascript">
    AllureCurrencyManagerJsConfig = <?php print $this->getJsonConfig();?>;
    try {
        extendProductConfigformatPrice();
    } catch (e) {

    }
</script>