<?php
/**
 * OnePica_AvaTax
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0), a
 * copy of which is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   OnePica
 * @package    OnePica_AvaTax
 * @author     OnePica Codemaster <codemaster@onepica.com>
 * @copyright  Copyright (c) 2009 One Pica, Inc.
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
/* @var $this OnePica_AvaTax_Block_Adminhtml_Landedcost_Parameter_Edit_Form_Renderer_Parameter */
?>
<?php $_htmlClass = $this->getElement()->getClass() ?>
<?php $_htmlName = $this->getElement()->getName() ?>
<?php $_readonly = $this->getElement()->getReadonly() ?>
<?php $_helper = Mage::helper('avatax') ?>

<tr>
    <td class="label"><?php echo $this->getElement()->getLabel() ?></td>

    <td class="grid value">
<!--        <input id="avalara_parameter_type" name="avalara_parameter_type" value="Mass" class="required-entry input-text required-entry" type="text">-->
        <select id="avalara_parameter_type" name="<?php echo $_htmlName ?>" class="select">
            <option value=""><?php echo $this->__('Select one...') ?></option>
            <?php foreach ($this->getAvalaraParameterTypes() as $parameter) { ?>
                <option value="<?php echo $parameter->getData('Name') ?>" <?php
                echo $this->getElement()->getValue() === $parameter->getData('Name')? 'selected="selected"' : '';
                ?>><?php echo $parameter->getData('Name') ?></option>
            <?php }; ?>
        </select>
    </td>
</tr>

<script type="application/javascript">
    jQuery(function ($) {
        $('#avalara_parameter_type').selectize();
    });
</script>
