<div class="container celebrities">
<div class="row">
    <div class="col-12 ">
        <div class="row">
            <?php $counter=1; foreach($this->getCelebritiesCol() as $celebrity):
                    if($celebrity->getStatus()==1):?>
                        <?php $active = ($this->getCurrentCelebrityId() == $celebrity->getId()) ? 'class="active"' : '' ?>
                        <div class="col-12 col-md-6 col-lg-4 mb-5" data-title="<?php echo $celebrity->getCelebrityName(); ?>" data-url="<?php echo $celebrity->getUrl()?>" onclick="setCelebrity(this);" id="<?php echo $counter; $counter++ ?>" <?php echo $active ?>  >
                        <div class="celebrity-img" style="background: url(<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'celebrities' . DS . $celebrity->getDefaultImage() ; ?>);"></div>
                        </div>
                    <?php endif; endforeach; ?>
    </div>
    </div>
</div>
</div>