<p class="category-image"><img src="https://mariatash-design.allureinc.dev/media/catalog/category/catalog.jpg" alt="Jewelry" title="Jewelry"></p>
<div id="category-title" class="page-title category-title simple-page-title">
    <h1>Celebrity Clientele</h1>
</div>
<div class="container celebrities press-custom-container">
    <div class="row">
        <div class="col-12 ">
            <div class="row">
                <?php $counter=1; foreach($this->getCelebritiesCol() as $celebrity):
                    if($celebrity->getStatus()==1):?>
                        <?php $active = ($this->getCurrentCelebrityId() == $celebrity->getId()) ? 'class="active"' : '' ?>
                        <div class="col-12 col-md-6 col-lg-4 celeb-img-block" data-celeb_id="<?= $celebrity->getId() ?>" data-title="<?php echo $celebrity->getCelebrityName(); ?>" data-url="<?php echo $celebrity->getUrl()?>" id="<?php echo $counter; $counter++ ?>" <?php echo $active ?>  >
                            <div id="celebId_<?= $celebrity->getId() ?>" class="celebrity-img" style="background: url(<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'celebrities' . DS . $celebrity->getDefaultImage() ; ?>);" data-id="<?= $celebrity->getId() ?>"></div>
                        </div>
                    <?php endif; endforeach; ?>
            </div>
        </div>
    </div>

    <div id="openModal" class="celebPopup"> <!--do not remove celebPopup class-->
        <div class="pop-up-cover big-popup-cover col-12">
          <div class="row">
            <div class="pop-title modal-header">
                <a href="#close" title="Close" class="close exit-large">
                    <div></div>
                </a>
            </div>
            <div class="body modal-body big-popup-body col-12">
                <div class="row">
                    <div class="big-popup-title d-lg-none d-block col-12 mb-3">
                        <h1 class="celeb-title text-uppercase text-center"></h1><!--do not remove celeb-title class-->
                    </div>
                    <div class="col-lg-6 popup-left-section">
                        <div class="celeb-img big-popup-image row"></div>
                    </div>
                    <div class="col-lg-6 popup-right-section">
                      <div class="row">
                        <div class=" big-popup-title d-lg-block d-none">
                            <h1 class="celeb-title text-uppercase"></h1><!--do not remove celeb-title class-->
                        </div>
                        <div class="para-normal celeb-info"> <!--do not remove celeb-info class-->
                        </div>
                        <div class="product-info"><!--do not remove product-info class-->
                            <ul class="p-0">
                                <li class="product-name"></li>
                                <li class="quick_link"></li>
                            </ul>
                        </div>
                      </div>
                    </div>
                </div>
            </div>
            <div class="prev" data-current="0"></div>
            <div class="next" data-current="0"></div>
            <div class="celeb-loader" style="display: none">
                <img src="<?php echo $this->getSkinUrl('images/gene/loader.gif') ?>" alt="Loading..." >
            </div>
          </div>
        </div>
    </div>
</div>
<script>

    var popupActionUrl="<?= $this->getPopUpActionUrl() ?>";
    var product_info="";
    var current_outfits="";
    var current_outfits_length="";

    jQuery(".celebrity-img").on('click',function(){
        clear();
        jQuery(".celebPopup").css({"opacity": "1", "pointer-events": "auto"});
        jQuery(".celeb-loader").show();
        var celebId=jQuery(this).attr("data-id");
        jQuery.post(popupActionUrl,
            {
                id: celebId
            },
            function(data, status){
                var response=JSON.parse(data);
                jQuery(".celeb-title").html(response.name);
                jQuery(".celeb-info").html(response.des);

                var outfit=response.outfit;
                current_outfits=outfit;
                current_outfits_length=current_outfits.length;
                 setData(0);
                jQuery(".celebPopup .next,.celebPopup .prev").attr("data-celebId",celebId);
                jQuery(".celebPopup .next,.celebPopup .prev").attr("data-current",0);
                jQuery(".celeb-loader").hide();
                setButtons(celebId);
            });
    });

    jQuery(".celebPopup .close").on('click',function(){
        jQuery(".celeb-loader").hide();
        jQuery(".celebPopup").css({"opacity":"0","pointer-events":"none"});
    });
    jQuery(".celebPopup .next").on("click",function () {
        var current_id=parseInt(jQuery(this).attr("data-current"));
        var next_id=current_id+1;
        if(current_outfits_length>1 && current_outfits_length>(next_id))
        {
            setData(next_id);

            if(current_outfits_length!=next_id && next_id!=0)
                jQuery(".celebPopup .next,.celebPopup .prev").removeClass("disBtn");
            else
                setButtons(jQuery(this).attr("data-celebid"));

            jQuery(".celebPopup .next,.celebPopup .prev").attr("data-current",next_id);
        }else {
            nextCeleb(jQuery(this).attr("data-celebId"));
        }
    });
    jQuery(".celebPopup .prev").on("click",function () {
        var current_id=parseInt(jQuery(this).attr("data-current"));
        var prev_id=current_id-1;

        if(current_outfits_length>1 && 0<=prev_id)
        {
            setData(prev_id);

            if(current_outfits_length!=prev_id && prev_id!=0)
                jQuery(".celebPopup .next,.celebPopup .prev").removeClass("disBtn");
            else
                setButtons(jQuery(this).attr("data-celebid"));

            jQuery(".celebPopup .next,.celebPopup .prev").attr("data-current",prev_id);
        }
        else {
            prevCeleb(jQuery(this).attr("data-celebId"));
        }
    });

    function setProduct(item) {
        product_info+='<li>\n' +
            ' <div class="product-name info-text-two">'+item["name"]+'</div>\n' +
            ' <div class="quick_link link-button"><a href="#">Quick View</a></div>\n' +
            '  </li>';
    }
    function setImg(img) {
        jQuery(".celeb-img").css({"background-image":"url("+img+")","background-size":"cover"});
    }
    function clear() {
        jQuery(".celeb-title").html("");
        jQuery(".celeb-info").html("");
        clearOutfit();
    }
    function clearOutfit() {
        jQuery(".celeb-img").css({"background-image":"","background-size":""});
        jQuery(".product-info ul").html("");
       }
    function setData(data_id) {
        clearOutfit();
        setImg(current_outfits[data_id]['img']);
        var products=current_outfits[data_id]['product'];
        if(products!=null) {
            current_outfits[data_id]['product'].forEach(setProduct);
            jQuery(".product-info ul").html(product_info);
        }
        product_info="";
    }
    function nextCeleb(id) {
     var celebId="#celebId_"+id;
     var element=jQuery(celebId);
     var nextCelebId= jQuery(celebId).parent('.celeb-img-block').next().attr("data-celeb_id");
     jQuery("#celebId_"+nextCelebId).trigger("click");
    }
    function prevCeleb(id) {
        var celebId="#celebId_"+id;
        var element=jQuery(celebId);
        var nextCelebId= jQuery(celebId).parent('.celeb-img-block').prev().attr("data-celeb_id");
        jQuery("#celebId_"+nextCelebId).trigger("click");
    }
    function setButtons(id) {
        var celebId="#celebId_"+id;

        if(jQuery(celebId).parent('.celeb-img-block').next().length)
        jQuery(".celebPopup .next").removeClass("disBtn");
        else
        jQuery(".celebPopup .next").addClass("disBtn");


        if(jQuery(celebId).parent('.celeb-img-block').prev().length)
        jQuery(".celebPopup .prev").removeClass("disBtn");
        else
        jQuery(".celebPopup .prev").addClass("disBtn");

    }
</script>
