<div style="display:block" id="order-store-selector">
	<div class="entry-edit">
		<div class="entry-edit-head">
			<div style="float: right;"></div>
			<h4 class="fieldset-legend "><?php echo $this->__('Please Select a Store') ?></h4>


		</div>
		<div class="fieldset">
			<div class="store-scope">
				<?php echo $this->getHintHtml() ?>
				<div class="tree-store-scope">
				<?php foreach ($this->getWebsiteCollection() as $_website): ?>
					<?php $showWebsite=false; ?>
					<?php foreach ($this->getGroupCollection($_website) as $_group): ?>
						<?php $showGroup=false; ?>
						<?php foreach ($this->getStoreCollection($_group) as $_store): ?>
							<?php if ($showWebsite == false): ?>
								<?php $showWebsite = true; ?>
								<h3><?php echo $this->escapeHtml($_website->getName()) ?></h3>
							<?php endif; ?>
							<?php if ($showGroup == false): ?>
								<?php $showGroup = true; ?>
								<h4 style="margin-left:12px;"><?php echo $this->escapeHtml($_group->getName()) ?></h4>
							<?php endif; ?>
							<span class="field-row" style="margin-left:28px;">
								<input type="radio" id="store_<?php echo $_store->getId() ?>" class="radio" onclick="setLocation('<?php echo $this->getUrl('adminhtml/webpos/gotowebpos',array('webpos_storeid'=>$_store->getId(),'webpos_websiteid'=>$_website->getId())) ?>')"/>
								<label for="store_<?php echo $_store->getId() ?>" class="inline"><?php echo $this->escapeHtml($_store->getName()) ?></label>
							</span>
						<?php endforeach; ?>
						<?php if ($showGroup): ?>
						<?php endif; ?>
					<?php endforeach; ?>
				<?php endforeach; ?>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	var list = document.getElementsByClassName('radio');
	for (var i = 0; i < list.length; i++) {
		list[i].checked = false;
	}	
</script>
