<div id="recent-view-ajax" class="w-100"></div>
<?php echo $this->getChildHtml("instagram_product_post");?>

<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Autorelated
 * @version    2.3.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php
$_size = ($this->getRelatedProducts()->getProductQty()) ? $this->getRelatedProducts()->getProductQty() : Mage::getStoreConfig('awautorelated/general/pcount');
$abstractBlock = $this->helper('awautorelated')->getAbstractProductBlock();
$_product = Mage::registry('current_product');
$tmpColl = $this->getCollection();
if ($tmpColl != NULL) {
    $collection = $this->getCollection();
    $collection->setPage(1, $_size)->load();
    $collection->getselect()->order(new Zend_Db_Expr('RAND()'));
} else {
    $this->markAsShowed();
    $relatedCollection = $_product->getRelatedProductCollection();
    $crossCollection = $_product->getCrossSellProductCollection();
    $merged_ids = array_merge($_product->getRelatedProductIds(),
        $relatedCollection->getAllIds());

    $collection = Mage::getModel('awautorelated/product_collection')
        ->setPage(1, $_size)
        ->addFieldToFilter('entity_id', shuffle($merged_ids))
        ->addAttributeToSelect('*')
        ->load();
    $collection->getSelect()->order(new Zend_Db_Expr('RAND()'));
}
if (empty($collection))
    return;

if ($this->getPosition() == AW_Autorelated_Model_Source_Position::INSTEAD_NATIVE_RELATED_BLOCK) {
    $this->iterateBlock();

    if ($collection && $collection->getSize()) {
        $this->markAsShowed();
    } elseif ($this->showNativeBlock()) {
        echo $this->getParent()->getChildHtml('catalog-product-related');

    }
} elseif ($_product && $this->getPosition() == AW_Autorelated_Model_Source_Position::INSIDE_PRODUCT_PAGE) {
    $this->iterateBlock();
    $tmpIds = $_product->getRelatedProductIds();
    if (empty($tmpIds)) {
        if ($collection && $collection->getSize()) {
            $this->markAsShowed();
        } elseif ($this->showNativeBlock()) {
            echo $this->getParent()->getChildHtml('catalog-product-related');
        }
    } else {
        $this->markAsShowed();
        $collection = Mage::getModel('catalog/product')->getCollection()->addFieldToFilter('entity_id', -1);
        $collection = $_product->getRelatedProductCollection()->setPage(1, $_size)
            ->load();
        $collection->getSelect()->order(new Zend_Db_Expr('RAND()'));
    }


}


?>
<?php if (($collection && $collection->getSize())) : ?>
    <div class="you_may_like">
    <div class="image_carousel">
        <div class="block-title text-uppercase mb-3">
            <span class="para-bold"><?php echo $this->__('You may also like') ?></span>
        </div>
        <ul id="product-suggestion-items-slider" class="owl-carousel owl-theme">
            <?php foreach ($collection as $product): ?>
                <?php
                    $product = Mage::getModel('catalog/product')->load($product->getId());
                ?>
                <li class="item">
                    <a class="fancybox fancybox.iframe quickview-youmayalsolike" id='product-quickview-<?php echo $product->getId() ?>' href="<?php echo $product->getProductUrl() ?>">
                        <img  src="<?php echo $this->helper('catalog/image')->init($product, 'thumbnail')->resize(500,500); ?>" alt="<?php echo $this->htmlEscape($product->getName()) ?>" />
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
        <div class="clearfix"></div>
    </div>
    <script type="text/javascript">
        jQuery.noConflict();

        jQuery(document).ready(function () {
        	var $ =  jQuery;
        	$('#product-suggestion-items-slider').owlCarousel({
        	    loop:true,
        	    margin:10,
        	    responsiveClass:true,
        	    responsive:{
        	        0:{
        	            items:1,
        	            nav:true
        	        },
        	        600:{
        	            items:3,
        	            nav:false
        	        },
        	        1000:{
        	            items:4,
        	            nav:true,
        	            loop:false
        	        }
        	    }
        	});

        });
    </script>
<?php endif; ?>
<div class="for-bottom-space p-5"></div>
