<?php
$_product = $this->getProduct(); 
$_product_image_url = NULL;

// Check to see if we have an image for this product.
foreach ($_product->getMediaGalleryImages() as $_product_image) {
    if (!$_product_image->getDisabled()) {
        $_product_image_url = $_product_image->getUrl();
        break;
    }
}
?>
<script text="text/javascript">
  var _learnq = _learnq || [];

  var item = {
    ProductID: "<?php echo $_product->getId(); ?>",
    Name: <?php echo json_encode($_product->getName()); ?>,
    SKU: "<?php echo $_product->getSku(); ?>",
    Price: "<?php echo number_format($_product->getPrice(), 2); ?>",
    SpecialPrice: "<?php echo number_format($_product->getFinalPrice(), 2); ?>",
    URL: "<?php echo $_product->getProductUrl(); ?>",
    <?php if ($_product_image_url) { ?>ImageURL: "<?php echo $_product_image_url; ?>", <?php } ?>
    Categories: <?php echo $this->getProductCategoriesAsJson(); ?>
  };
 
  _learnq.push(['track', 'Viewed Product', item]);
  _learnq.push(['trackViewedItem', {
    Title: item.Name,
    ItemId: item.ProductID,
    Price: item.Price,
    SpecialPrice: item.SpecialPrice,
    Categories: item.Categories,
    <?php if ($_product_image_url) { ?>ImageUrl: item.ImageURL,<?php } ?>
    Url: item.URL
  }]);
</script>