<?php
$currentFilterStore = $this->getCurrentFilterStore();
$currentSort        = $this->getCurrentFilterSortOrder();
$currentOrderStatus = $this->getCurrentFilterAllOrderStatus();
$stores             = $this->getAllStores();
$storeArr           = $this->getStoreListArray();
$sortOderArr        = $this->getSortOrderArray();
$helper             = Mage::helper("myaccount");
$orderStatus        = $this->getOrderFilterStatusArray($helper::ALL_ORDER);
?>
<div class="block-layered-nav-bg">
	<div class="block block-layered-nav mb-mana-catalogsearch-leftnav">
		<div class="block-content">
			<ul id="narrow-by-list-new" class="p-0">
       <!-- 	<li class="filter-label-list"><span>Narrow By: </span></li> -->
       
       <li class="myaccount-filter-store-list order-filter-status">
         <div class="optionfilter input-patern" style="display: block;overflow: hidden;cursor: pointer;">
          <dt class="odd"><?php echo ($currentFilterStore!='all')?$storeArr[$currentFilterStore]:"All Stores"?></dt>
          <dd class="myaccount-filter-store odd" style="display: none;">
            <div class="filter_name"></div>
            <ol class="myaccount-filter-item">
              <li>
               <dd value="all" <?php echo ($currentFilterStore=='all')?"class='selected-store'":""?> ><?php echo $this->__('All Stores');?></dd>
               <?php foreach ($stores as $store) :?>
                 <dd value="<?php echo $store->getId()?>"
                  <?php echo ($currentFilterStore==$store->getId())?"class='selected-store'":""?>>
                  <?php echo $store->getName()?>
                </dd>
              <?php endforeach;?>
            </li>
          </ol>
        </dd>
      </div>
    </li>
    
    <li class="myaccount-filter-sort-order-list order-filter-status">
     <div class="optionfilter input-patern" style="display: block;overflow: hidden;cursor: pointer;">
      <dt class="odd"><?php echo ($currentSort!='')?$sortOderArr[$currentSort]:"SORT BY"?></dt>
      <dd class="myaccount-filter-sort-order odd" style="display: none;">
        <div class="filter_name"></div>
        <ol class="myaccount-filter-item">
          <li>
            <?php foreach ($sortOderArr as $key=>$name):?>
              <dd value="<?php echo $key?>" <?php echo ($currentSort==$key)?"class='selected-sort-type'":""?>><?php echo $name?></dd>
            <?php endforeach;?>
          </li>
        </ol>
      </dd>
    </div>
  </li>
  
  <li class="myaccount-filter-order-status-list all-order-filter order-filter-status">
   <div class="optionfilter input-patern" style="display: block;overflow: hidden;cursor: pointer;">
    <dt class="odd"><?php echo ($currentOrderStatus != "all")? $orderStatus[$currentOrderStatus] :"All Status"?></dt>
    <dd class="myaccount-filter-order-status odd" style="display: none;">
      <div class="filter_name"></div>
      <ol class="myaccount-filter-item">
        <li>
          <?php foreach ($orderStatus as $key=>$name):?>
            <dd value="<?php echo $key?>" <?php echo ($currentOrderStatus==$key)?"class='selected-sort-type'":""?>><?php echo $name?></dd>
          <?php endforeach;?>
        </li>
      </ol>
    </dd>
  </div>
</li>

</ul>
</div>
</div>
</div>
