<?php $items = $this->getMenu(); $current = $this->getCurrent(); ?>
<div class="navigation-menu">
	<select name="look" id="lookSelect">
    <?php foreach($items as $item) { ?>    
    <?php if($current->getId() == $item->getId()) { ?>
        <option class="discover-mt-navigation current-active" selected="selected">
        <?php echo $item->getName()?>
        </option>
    <?php } else { ?>
	<?php if ($item->getName() != 'Blog') { ?>
        <option class="discover-mt-navigation"
			onclick="document.location.href ='<?php echo Mage::getUrl($item->getUrl()) ?>'">
            <?php echo $item->getName()?>
        </option>
	<?php } else { ?>
		<option class="discover-mt-navigation"
			onclick="window.open('<?php echo Mage::getStoreConfig('ecp_menu/menu/blog_link') ?>', '_blank')"><?php echo $this->__('Blog') ?></option>
    <?php } ?>
	<?php } ?>
    <?php } ?>
	</select>
</div>