<?php
/**
 * Login with Amazon
 *
 * @category    Amazon
 * @package     Amazon_Payments
 * @copyright   Copyright (c) 2014 Amazon.com
 * @license     http://opensource.org/licenses/Apache-2.0  Apache License, Version 2.0
 */
?>


<h1 class="mt-4 mb-4"><?php echo $this->__('Verify Your Account'); ?></h1>

<div class="col2-set">

<p class="para-normal">This email address is currently associated with an existing customer account. Please log in to associate your Amazon account with this customer.</p>

    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
        <?php echo $this->getBlockHtml('formkey'); ?>
            <div class="verification-form">
                <div class="content">
                    <ul class="form-list pl-0 mt-4">
                        <li>
                            <label for="email" class="para-normal text-uppercase"><?php echo $this->__('Email Address') ?></label>
                            <div class="input-box mb-4">
                                <?//php echo $this->escapeHtml($this->getEmail()) ?>
                                <span class="para-normal">shruti@allureinc.co</span>
                            </div>
                        </li>
                        <li>
                            <label for="pass" class="para-normal text-uppercase required"><?php echo $this->__('Password*') ?></label>
                            <div class="input-box">
                                <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
                            </div>
                        </li>
                    </ul>
                    <p class="para-lighter required"><?php echo $this->__('* Required Fields') ?></p>
                </div>
                <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="link-button"><?php echo $this->__('Forgot Your Password?') ?></a>
                <div class="buttons-set mt-3">
                    <button type="submit" class="button dark-button pop-up-button text-uppercase" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>
                </div>
            </div>
    </form>
</div>

<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('login-form', true);
//]]>
</script>
