<?php

class Ebizmarts_BakerlooRestful_Block_Adminhtml_Pos_Shifts_Edit_Tab_Json extends Mage_Adminhtml_Block_Widget_Form
{

    protected function _prepareForm()
    {
        $model = Mage::registry('pos_shift');

        $form = new Varien_Data_Form();

        $fieldset = $form->addFieldset('base_fieldset', array());

        $fieldset->addField(
            'json_payload',
            'textarea',
            array(
            'name'     => 'json_payload',
            'label'    => Mage::helper('bakerloo_restful')->__('Json post data'),
            'id'       => 'json_payload',
            'required' => false,
            'style'    => 'height: 400px; width: 500px;',
            )
        );

        $form->setValues($model->getData());

        $this->setForm($form);

        return parent::_prepareForm(); // TODO: Change the autogenerated stub
    }
}
