<?php 
/**
 * @var Ecp_Slideshow_Block_Home $this
 */
?>
<?php $isMobile = $this->isMobile();?>
<?php $jsonImages =  $this->getJsonImages($isMobile);?>
<?php //if(!$isMobile):?>
<script type="text/javascript">
    jQuery.noConflict(); 
    jQuery(document).ready(function() {
        var width = jQuery(window).width();

        if ((width > 1024)) {
            jQuery(".homepageSliderControllers").removeClass("mobile");
            jQuery(".mobile-background-list").hide();

        var transitionEffect=1;
        if (jQuery(window).width() <= 767) {
         transitionEffect=3;
        }
        jQuery.supersized({
            // Functionality
            slide_interval: 5000,// Length between transitions
            transition: transitionEffect,// 0-None, 1-Fade, 2-Slide Top, 3-Slide Right, 4-Slide Bottom, 5-Slide Left, 6-Carousel Right, 7-Carousel Left
            transition_speed: 1000,// Speed of transition
            // Component						
            slide_links: 'blank',// Individual links for each slide (Options: false, 'num', 'name', 'blank')
            slides:// Slideshow Images
                <?php echo $jsonImages; ?>
        });
		jQuery('.std').remove();
        jQuery(".nextS").on("click",function () {
            api.nextSlide();
        });
        jQuery(".prevS").on("click",function () {
            api.prevSlide();
        });
        }else {
            jQuery(".homepageSliderControllers").addClass("mobile");
            jQuery(".mobile-background-list").show();   
        }

    });
</script>
<?php //endif;?>
<div id="controls-wrapper" class="load-item ">
    <div id="controls">
        <!--Slide captions displayed here-->
        <!--Navigation-->
        <ul id="slide-list"></ul>

        <div class="homepageSliderControllers >
        	<?php //if($isMobile): // for mobile ?>
        		<?php $slideShows = json_decode($jsonImages);?>
        		<ul class="ul-mobile-images">
        		<?php foreach ($slideShows as $item):?>
            		<?php if(isset($item->image) && !empty($item->image)):?>
            			<li class="mobile-background-list" style="display:none">
            				<div class="mob-slideshow-container">
                				<div class="mob-slideshow-img">
                					<img class="img-background" src="<?=$item->image?>">
                				</div>
                				<?php if(isset($item->description) && !empty($item->description)):?>
                				<div class="mob-slideshow-content">
                					<?=$item->description?>
                				</div>
                				<?php endif;?>
            				</div>
            			</li>
            		<?php endif;?>
        		<?php endforeach;?>
        		</ul>
        	<?php //else: // for desktop ?>
        		<div class="prevS" title="Previous"></div>
            	<div id="slidecaption"></div>
        		<div class="nextS" title="Next"></div>
        	<?php //endif;?>
        </div>
    </div>        
</div>

