<script type="text/javascript">
    jQuery.noConflict(); 
    jQuery(document).ready(function() {

        var transitionEffect=1;
        if (jQuery(window).width() <= 767) {
         transitionEffect=3;
        }
        jQuery.supersized({
            // Functionality
            slide_interval: 5000,// Length between transitions
            transition: transitionEffect,// 0-None, 1-Fade, 2-Slide Top, 3-Slide Right, 4-Slide Bottom, 5-Slide Left, 6-Carousel Right, 7-Carousel Left
            transition_speed: 1000,// Speed of transition
            // Component						
            slide_links: 'blank',// Individual links for each slide (Options: false, 'num', 'name', 'blank')
            slides:// Slideshow Images
                <?php echo $this->getJsonImages(); ?>
        });
		jQuery('.std').remove();
        jQuery(".nextS").on("click",function () {
            api.nextSlide();
        });
        jQuery(".prevS").on("click",function () {
            api.prevSlide();
        });
    });
</script>
<div id="controls-wrapper" class="load-item ">
    <div id="controls">
        <!--Slide captions displayed here-->
        <!--Navigation-->
        <ul id="slide-list"></ul>

        <div class="homepageSliderControllers">
        <div class="prevS" title="Previous"></div>
            <div id="slidecaption"></div>
        <div class="nextS" title="Next"></div>
        </div>
    </div>        
</div>
