<?php
$collection = $this->getInstagramCollection();
$_feed= null;
$search_action  = Mage::getUrl('adminhtml/allure_instaCatalog_feed/searchAjax').'?isAjax=true';
$block_class =  Mage::getBlockSingleton('allure_instacatalog/adminhtml_custom');
$syncFeedAction = Mage::helper("adminhtml")->getUrl('adminhtml/allure_instaCatalog_feed/syncFeed');
$syncOtherFeedAction = Mage::helper("adminhtml")->getUrl('adminhtml/allure_instaCatalog_feed/syncExistingFeed');
$access_token = Mage::getStoreConfig('allure_instacatalog/feed/access_token');
$syncOtherFeedAction .= "type/allure/akey/mariatash";

?>
<?php if( count($collection)>0):?>

<div class="feed-title-custom">
	<h2>Instagram Feed's</h2>
</div>


<div class="feed-sync-post">
	<a class="button tiny success sync-button" 
		href="<?php echo $syncFeedAction?>"> 
		<span>Sync Post</span>
	</a>
</div>

<div class="feed-sync-post" style="float: right;display: none">
	<a class="button tiny success sync-button" 
		href="<?php echo $syncOtherFeedAction?>"> 
		<span>Other Post</span>
	</a>
</div>

<div class="clearfix"></div>
<div class="pager-instagram">
	<?php echo $this->getPagerHtml(); ?>
</div>
<div >
<?php foreach ($collection as $feed):
$media_id = $feed->getMediaId();
/* Call Instagram API */

	//$_feed = $feed;?>
	<div class="post">
		<div class="img" style="background-image: url('<?php echo $feed->getStandardResolution()?>'); position: relative">
		    <div class="taggable-image-info">
		      <?php 
		      	$taggedProducts = json_decode($feed->getHotspots());
		      	$taggedCnt = count($taggedProducts); 
		      	$type = "";
		      	$mode = $feed->getLookbookMode();
		      	if($mode==1)$type="shop by look";
		      ?>
		      <span id="tag-count-<?php echo $feed->getId()?>"><?php echo ($taggedCnt>0)?$taggedCnt:0 ?></span><span> product's tagged</span>
		    </div>
		     <span class="feed-type-instagram">
		     	<i class="<?php echo ($mode==1)?"fa fa-eye":"fa fa-instagram"?> feed-type"></i></span>
		 </div>
		 
		 
		 <div class="postentry-bottom">
	  		<div class="postentry-controls">
	    		<?php if(1):?>
	    		<label class="visible-label no-select">
	      			<input id="feed-status-<?php echo $feed->getId()?>" onchange="saveFeedStatusAjax(this,1)" data-id="<?php echo $feed->getId()?>"
	      				type="checkbox" <?php echo ($feed->getStatus())?'checked="checked"':'' ?>>
	      			Visible
	    		</label>
	    		<?php endif;?>
	    		<a id="instagram-link-<?php echo $feed->getId()?>" class="button tiny success" style="float:right"
	    		 data-img-src="<?php echo $feed->getStandardResolution() ?>" data-id="<?php echo $feed->getId()?>" 
	    		 data-tag-product='<?php echo $feed->getHotspots()?>'
	             onclick = "openView(this);">
	      			Tag Products
	    		</a>

                <!--<a class="reload" onclick="relaodInstaImage('<?php // echo $feed->getMediaId()?>','<?php // echo $feed->getUsername()?>')">
                    <img alt="" src="<?php //echo Mage::getDesign()->getSkinUrl('images/img_306090.png');?>">
                </a>-->

            </div>
	    	<div class="upper-text">
			    <p class="text-content" style="margin-top: 0">
			    <?php echo (json_decode($feed->getCaption())!="")?json_decode($feed->getCaption()):$feed->getCaption()?>
			    </p>
		  	</div>
		  	
			<div style="padding: 5px 10px 0px;">
			<?php 
				$createDate = $feed->getCreatedTimestamp();
				if($createDate!=null){
					$createDate = date('M d, Y', $createDate);
				}
				?>
				<div class="text-footer">
				    <div class="left"><?php echo $createDate?></div>
				      <div class="right author">
				        <a target="_blank" href="<?php echo $feed->getUsername()?>" class="">
				         
				         <i class="fa fa-instagram"></i> 
				         <?php if(0 && !$mode):?> 
				         <?php //else:?>
				         <i class="fa fa-eye"></i> 
				        <?php endif;?> / maria_tash
				        </a>
				      </div>
				      <div class="clearfix"></div>
			      </div>
			</div>
		  	
	    </div>
	    
	</div>
	<?php endforeach;?>
<?php else:?>
<p>Their is no instagram feeds.</p>
<?php endif;?>
</div>
<div class="pager-instagram">
	<?php echo $this->getPagerHtml(); ?>
</div>

<div id="product-tagged-view" style="display: none;">
	<div class="tagger flex-center schedule-form">
		<div class="imgcontainer">
			<div class="tagger-close" onclick="closeView();" >
		    	<svg width="30" height="30" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg">
		            <g>
		              <path fill="none" stroke-width="1px" d="m0,0 L30,30" stroke="white"></path>
		              <path fill="none" stroke-width="1px" d="m30,0 L0,30" stroke="white"></path>
		            </g>
		        </svg>
		    </div>
			<div id="taggable-container" class="taggable-container">
				<div class="lookbookBlock">
					<img id="LookbookImage" class="tag-img" width="640" height="640"
					src="" />
				</div>
			</div>
			
			<!-- <input id="feed_hotspots" name="feed[hotspots]" value="" type="hidden">
			<input id="feed_id" name="feed[id]" value="" type="hidden"> -->
		</div>
	</div>
</div>

<script>
	if (typeof Allure == "undefined") {
	   var Allure = {};
	}
	Allure.TagProductFormKey = '<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>';
	Allure.TagProductUrl = '<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/allure_instaCatalog_feed/saveAjax', array('_secure' => true));?>';
	Allure.FeedStatusUrl = '<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/allure_instaCatalog_feed/saveFeedStatusAjax', array('_secure' => true));?>';
	Allure.ProductGetUrl = '<?php echo Mage::helper('adminhtml')->getUrl("adminhtml/allure_instaCatalog_lookbook/getproduct")?>';
	Allure.SearchProductUrl = '<?php echo $search_action?>';
	Allure.ReloadImage = '<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/allure_instaCatalog_feed/reloadimage', array('_secure' => true));?>';
</script>

<script>
function openView(e){
	jQuery('#product-tagged-view').show();
	var src = jQuery(e).attr('data-img-src');
	//console.log(src);
	jQuery('#taggable-container').html('<div class="lookbookBlock">'+
			'<img id="LookbookImage" class="tag-img" src="'+src+'" / style="display:none"></div>'+
			'<input id="feed_hotspots" name="feed[hotspots]" value="" type="hidden">'+
			'<input id="feed_id" name="feed[id]" value="" type="hidden">'+
			//'<label class="visible-label" style="color: white;">'+
		//'<input id="feed-status" type="checkbox" onchange="saveFeedStatusAjax(this,2)"> Visible</label>'
			'');
	var taggedProduct = jQuery(e).attr('data-tag-product');
	var feedId = jQuery(e).attr('data-id');
	jQuery('#feed_id').val(feedId);
	var feedStatus = jQuery('#feed-status-'+feedId).is(':checked');
	jQuery('#feed-status').prop('checked',feedStatus);
	//console.log(jQuery('#feed-status').is(':checked'));
	InitHotspotBtn(taggedProduct);
}

function closeView(){
	jQuery("#image-annotate-edit-form").remove();
	jQuery(".image-annotate-area-editable").remove();
	jQuery('#product-tagged-view').hide();
	jQuery(".image-annotate-canvas").remove();
	jQuery(".lookbookBlock").remove();
	jQuery("#image-annotate-edit-form").remove();
	jQuery("#search-list-view").remove();
	
}
function relaodInstaImage(media,username){

	jQuery.ajax({
        url: Allure.ReloadImage,
        dataType : 'json',
		type : 'POST',
		data: {'media_id':media,'username':username,'form_key':Allure.TagProductFormKey},
		
        success: function(data) {
        	location.reload();
        }
    });
    
	//alert(media);
}
</script>
