<!--
/**
 * Sumankcdotcom_AdvInstagram extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Sumankcdotcom
 * @package        Sumankcdotcom_AdvInstagram
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
--> 
<style type="text/css">
    #instafeed a.selected {
        background: #d34704 none repeat scroll 0 0;
    }
</style>
<?php if(0):?>
<script src="//ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/prototype/1.7.2.0/prototype.js"></script>
<script src="<?php echo Mage::getBaseUrl('js').'allure/instacatalog/instafeed.js';?>"></script>
<?php endif;?>

<div class="content-header">
    <h3 class="icon-head head-adminhtml-post">Select from the post appearing below (Click to select)</h3>
</div>
<div id="instafeed"></div>
<br/><button id="load-more">load more</button>
<br/><br/><br/><br/>
<?php 
    $post_type = Mage::getStoreConfig('allure_instacatalog/feed/feed_type');
    $user_id = Mage::getStoreConfig('allure_instacatalog/feed/user_id');
    $access_token = Mage::getStoreConfig('allure_instacatalog/feed/access_token');
    $tagname = Mage::getStoreConfig('allure_instacatalog/feed/tag_name');
    $client_id = Mage::getStoreConfig('allure_instacatalog/feed/client_id');
?>
<?php if($post_type=='hashtag'): ?>
    <script type="text/javascript">
    	jQuery(function($){
        	//console.log("Hiiiiiii");
    	var loadButton = document.getElementById('load-more');
        var feed = new Instafeed({
            get: 'tagged',
            tagName: "<?php echo $tagname;?>",
            clientId: "<?php echo $client_id;?>",
            limit: 14,
            template: '<a href="#"><img data-attr="{{id}}" src="{{image}}" alt="{{caption}}" data-username="{{link}}" /></a>',
            after: function() {
                if (!this.hasNext()) {
                    loadButton.setAttribute('disabled', 'disabled');
                }
            },
        });
        if(loadButton){
    	    loadButton.addEventListener('click', function() {
    	        feed.next();
    	    });
    	}
        feed.run();
    });
    </script>
<?php elseif($post_type=='account'): ?>
    <script type="text/javascript">
        jQuery(function($){
        	//console.log("Hiii");
        var loadButton = document.getElementById('load-more');
        var feed = new Instafeed({
            get: 'user',
            userId: "<?php echo $user_id; ?>",
            accessToken: "<?php echo $access_token; ?>",
            limit: 14,
            template: '<a href="#"><img data-attr="{{id}}" src="{{image}}" alt="{{caption}}" data-username="{{link}}" /></a>',
            after: function() {
                if (!this.hasNext()) {
                    loadButton.setAttribute('disabled', 'disabled');
                }
            },
        });
        if(loadButton){
            loadButton.addEventListener('click', function() {
                feed.next();
            });
        }
        feed.run();
    });
    </script>
<?php endif; ?>
<script type="text/javascript">
jQuery(document).on('click','#instafeed a img',function(){
	jQuery(this).parent().addClass('selected').siblings().removeClass('selected');
    jQuery('#feed_media_id').val(jQuery(this).attr('data-attr'));
    jQuery('#feed_username').val(jQuery(this).attr('data-username'));
    jQuery('#feed_caption').val(jQuery(this).attr('alt'));
    return false;
});    
</script>

<script type="text/javascript">
jQuery(document).on('click','.image-annotate-canvas',function(event){
	jQuery('#image-annotate-add').trigger('click');
	var x = event.offsetX; 
	var y= event.offsetY; 
	console.log(jQuery('.image-annotate-edit-area.ui-resizable.ui-draggable').css('height'));
	jQuery('.image-annotate-edit-area.ui-resizable.ui-draggable').css({'left':x+'px','top':y+'px'});
	/*jQuery('#image-annotate-edit-form').css({'left':event.pageX+'px','top':event.pageY+'px'});*/
});

</script>
