<?php 
/**
 * Allure_InstaCatalog
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category    Allure
 * @package     Allure_InstaCatalog
 * @copyright   Copyright© 2016, Allure Inc
 * @license     http://opensource.org/licenses/mit-license.php MIT License
 * @author      Team Allure <extensions@allureinc.co>
 */
/**
 * Feed list template
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php 
    $post_type = Mage::getStoreConfig('allure_instacatalog/feed/feed_type');
    $user_id = Mage::getStoreConfig('allure_instacatalog/feed/user_id');
    $access_token = Mage::getStoreConfig('allure_instacatalog/feed/access_token');
    $filter_post = Mage::getStoreConfig('allure_instacatalog/feed/filter_feed');
    $limit = Mage::getStoreConfig('allure_instacatalog/feed/limit');
    $link_posts = Mage::getStoreConfig('allure_instacatalog/feed_features/link_feeds');
    $caption = Mage::getStoreConfig('allure_instacatalog/feed_features/caption');
    $likes_count = Mage::getStoreConfig('allure_instacatalog/feed_features/likes_count');
    $comment_count = Mage::getStoreConfig('allure_instacatalog/feed_features/comment_count');

    $tagname = Mage::getStoreConfig('allure_instacatalog/feed/tag_name');
    $client_id = Mage::getStoreConfig('allure_instacatalog/feed/client_id');
    $resolution = Mage::getStoreConfig('allure_instacatalog/feed_features/resolution');
    $filter_feeds = Mage::getStoreConfig('allure_instacatalog/feed/filter_feeds');
    
    //Mage::getModel('allure_instacatalog/cron')->syncFeeds();
    
?>
<?php 	
	$date = Mage::getModel('allure_instacatalog/feed');
	$collection = $date->getCollection();
	$localData = array();
	
	foreach($collection as $date_to) {
		$localData[$date_to->getMediaId()] = $date_to->getData();
	}
?>
<div id="shop_our_instagram">
	<script type="text/javascript">
		var localData = {};
		<?php if (isset($localData) && !empty($localData)):?>
		localData = <?php echo json_encode($localData);?>;
		<?php endif;?>
	</script>
	<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS).'allure/instacatalog/instafeed.js';?>"></script>
	
<?php if(!$filter_feeds): ?>
	<div class="shop-instagram page-title category-title">
		<h1>SHOP OUR INSTAGRAM</h1>
	</div>
    <div id="instagram_posts" class="instacatalog_feeds instagram_posts"></div>
    <div id="load-more">Load More...</div>
    <script type="text/javascript">
	
    	<?php $instagram_logo = $this->getSkinUrl('images/instacatalog/instagram-logo.png');?>
        var instagram_post = instagram_post_image = instagram_caption = instagram_shop = instagram_shop_icon = instagram_shop_button = '';
    	instagram_post_image = '<div class="instagram_post_image"><img src="{{image}}" /></div>';
    	instagram_shop_icon = '<div><i onclick="instagramView.show(this);" media-id="{{id}}" class="fa fa-instagram"></i></div>';//'<img class="instagram_shop_icon" src="<?php echo $instagram_logo;?>" alt="Instagram" />'
        <?php if($link_posts){ ?>
            instagram_shop_button = '<a id="shop-{{id}}" class="instagram_shop_button" href="{{link}}" target="_blank"><span class="shop-it-button">SHOP IT</span></a>';
        <?php } ?>
        <?php if($caption){?> 
        	instagram_caption = '<div class="instagram_caption"><span class="instagram_caption_text">{{caption}}</span></div>'; 
        <?php }?>
        instagram_shop = '<div class="instagram_shop">'+instagram_shop_icon+instagram_shop_button+'</div>';
        instagram_post = '\
           <div id="main_{{id}}" class="instagram-post individual-post col-sm-4 col-xs-6 col-xxs-12 post_item {{post_item_class}}">\
               <div class="instagram_post_wrapper">\
               		'+ instagram_post_image +'\
               		<div class="instagram_post_overlay">\
               			'+instagram_caption + instagram_shop + '\
               		</div>\
               	'+'\
               </div>\
            </div>';
       	var loadButton = document.getElementById('load-more');

       	<?php if ($post_type=='account') :?>
        var feed = new Instafeed({
            target:"instagram_posts",
            get: 'user',
            userId: "<?php echo $user_id; ?>",
            accessToken: "<?php echo $access_token; ?>",
            limit : "<?php echo $limit; ?>",
            resolution : "<?php echo $resolution ?>",
            template: instagram_post,
            localData: localData,
            after: function() {
                // disable button if no more results to load
                if (!this.hasNext()) {
                    loadButton.setAttribute('disabled', 'disabled');
                }
            }
        });
        <?php elseif ($post_type == 'hashtag') :?>
        var feed = new Instafeed({
            target:"instagram_posts",
            get: 'tagged',
            tagName: "<?php echo $tagname; ?>",
            clientId: "<?php echo $client_id; ?>",
            limit : "<?php echo $limit; ?>",
            resolution : "<?php echo $resolution ?>",
            template: instagram_post,
            localData: localData
        });
        <?php endif;?>

        // bind the load more button
        loadButton.addEventListener('click', function() {
        	feed.next();
        });
        <?php if($post_type=='account' || $post_type=='hashtag'){ ?>feed.run();<?php }?>
    </script>
<?php else: ?>
    <?php $_posts = $this->getFeeds(); ?> <!--/ Fetches only the selected posts from backend -->
    <?php if ($_posts->getSize() > 0) :?>
    		<?php if(0):?>
            <div class="post-list-container">
                <?php foreach ($_posts as $_post) : ?>
                    <?php 
                            $media_id = $_post->getMediaId();
                            /* Call Instagram API */
                            $url = 'https://api.instagram.com/v1/media/'.$media_id.'?access_token='.$access_token;
                            $data = file_get_contents($url);
                            $response = json_decode($data);
                            $image = $response->data->images->$resolution->url;
                            $likes = $response->data->likes->count;
                            $link = $response->data->link;
                            $insta_caption = htmlspecialchars($response->data->caption->text);
                            $username = $response->data->caption->from->username;
                            $comments = $response->data->comments->count;

                            echo '<div class="instagram-post">';
                            if($link_posts){ echo '<a href="" target="_blank"><img class="quickview_overlay" src="'.$image.'"/></a>'; }else{ echo '<img class="quickview_overlay" src="'.$image.'"/>'; }
                            if($caption){
                                echo '<span class="insta_caption">'.$insta_caption.'</span>';
                            }if($likes_count){
                                //echo '<span class="insta_likes"> '.$likes.' Likes </span>';
                            }if($comment_count){
                                //echo '<span class="insta_comment"> '.$comments.' Comments</span>';
                            }
                            echo '</div>';
                        ?>
                <?php endforeach;?>
            </div>
            <?php endif;?>
            
            <div id="instagram_posts" class="instacatalog_feeds instagram_posts">
            <?php foreach ($_posts as $_post) : 
            		$media_id = $_post->getMediaId();
            		$username = $_post->getUsername();
            		$class_css = "post_item_with_link";
            		if (strpos($username,'instagram') !== false) 
            			$class_css = "post_item_without_link";
            		$instagramObj = unserialize($_post->getInstagramData());
            ?>
            	<div id="main_<?php echo $media_id?>" class="instagram-post individual-post col-sm-4 col-xs-6 col-xxs-12 post_item <?php echo $class_css?>">
            		<div class="instagram_post_wrapper">               		
            			<div class="instagram_post_image">
            				<img src="<?php echo $instagramObj->images->$resolution->url?>">
            			</div>               		
            			<div class="instagram_post_overlay">               			
            				<div class="instagram_shop">
            					<div>
            						<i onclick="instagramView.show(this);" media-id="<?php echo $media_id?>" class="fa fa-instagram"></i>
            					</div>
            					<a id="shop-<?php echo $media_id?>" class="instagram_shop_button" href="<?php echo $username?>" target="_blank">
            						<span class="shop-it-button">SHOP IT</span>
            					</a>
            				</div>               		
            			</div>               	               
            		</div>            
            	</div>               		
            <?php endforeach;?>
            </div>   
            
    <?php else : ?>
        <?php echo Mage::helper('allure_instacatalog')->__('There are no posts at this moment');?>
    <?php endif;?>
   
<?php endif; ?>
</div>


<div id="instagram-view-container">
	<div id="showcase" class="fs-wide-timeline  fs-desktop fs-prepended-detail" style="display: none;" >
		<div id="fs-timeline-detail-592364" class="fs-timeline-detail">
			<div id="fs-instagram-view-container" class="fs-detail-outer-container ">
				<div class="instagram-loader"></div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
//<![CDATA[
	var instagramView = new InstagramView('fs-instagram-view-container','<?php echo Mage::getBaseUrl('web').'instacatalog/feed/view'?>');
	//]]>
</script>

<?php if(0):?>
<script type="text/javascript">
var xhr = null;
jQuery(window).scroll(function(){
	 if(jQuery(this).scrollTop() ){
		 if( xhr != null ) {
		        xhr.abort();
		        xhr = null;
		 }
		 xhr =	jQuery.ajax({
	        url: '<?php echo Mage::getBaseUrl('web').'instacatalog/feed/loadAjax';?>',
	        dataType : 'json',
			type : 'POST',
			data: {'page':2},
	        success: function(data) {
	        	//instagram_posts
	        	jQuery('#instagram_posts').append(data.data.html);
	        }
	    });
    }
});
</script>
<?php endif;?>
