<?php
/**
 * @category    Allure
 * @package     Allure_ElasticSearch
 * @version     1.0.0
 * @copyright   Copyright (c) 2019 Allure Software, Inc. (https://www.allureinc.co)
 *
 * @var $this Allure_ElasticSearch_Block_Catalogsearch_Suggest
 */
$suggestion = $this->getSuggestion();
?>

<?php if (!empty($suggestion) && Mage::getStoreConfig('catalog/search/elasticsearch_enable_suggest')): ?>
<!--    <h2><em>--><?php //echo $this->__('Did you mean %s?', '<a href="'. $this->getQueryUrl($suggestion) .'">'. $suggestion .'</a>'); ?><!--</em></h2>-->
<?php endif; ?>
