<?php
/**
 * @category    Mana
 * @package     Mana_Core
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/* @var $this Mage_Core_Block_Template */
?>
<div id="m-wait" style="display:none" class="fancybox-overlay fancybox-overlay-fixed">
    <div style="display:block;" id="appointment_loader" class="loading">Loading&#8230;</div>
    <?php /*?><span class="please-wait-filter"><?php echo Mage::helper('adminhtml')->__('Please wait...') ?></span><?php */?>
</div>