{if $prim_act}<a href="https://www.millesima.at/cgv.html" style="color: #FFFFFF; font-weight:bold;">Verkaufs - und Lieferbedingungen Primeurweine 2018 - &Ouml;sterreich</a>.
<strong>Preise</strong>: Unsere Preise sind in &euro; inkl. 20% MwSt. ausgewiesen. {$validitedate} Druckfehler bleiben vorbehalten. Fotos und Abbildungen sind nicht verbindlich. Unsere Angebote richten sich ausschliesslich an Endverbraucher.
<strong>Bestellung/Lieferung</strong>: Bei Bestellung zahlen Sie nur den Preis in &euro; ohne Mehrwertsteuer. Ab einem Rechnungswert von 1800 &euro; inkl. MwSt.  (nur Primeurweine 2018) erfolgt die Lieferung nach &Ouml;sterreich kostenfrei an eine Adresse. Bei Bestellungen unter diesem Betrag stellen wir Ihnen 1,20 &euro; pro 75 cl als anteilige Fracht- und Versicherungskosten in Rechnung.
Sofort nach Bestellung erhalten Sie von uns eine Proformarechnung ohne Mehrwertsteuer und Transportkosten. Diese gilt zusammen mit dem Zahlungsdurchschlag als Eigentumsnachweis. Sobald die Weing&uuml;ter Fr&uuml;hjahr 2021 Ihre Weine zur Verf&uuml;gung stellen werden, erhalten Sie die endg&uuml;ltige Rechnung mit der Nachforderung der zum Lieferzeitpunkt g&uuml;ltigen Mehrwertsteuer und evtl. den Transportkosten. Nach Ausgleich des Restbetrags werden Ihnen die Weine per Spedition zugestellt.
<br />
<a href="https://www.millesima.at/cgv.html#cgv10" style="color: #FFFFFF; font-weight:bold;"><strong>Widerrufsrecht</strong></a>: Subskriptionsbestellungen sind vom gesetzlichen Widerrufsrecht ausgeschlossen.<br />
<a href="https://www.millesima.at/cgv.html" style="color: #FFFFFF; font-weight:bold;"><strong>AGB</strong></a>: Unsere vollst&auml;ndigen AGB k&ouml;nnen Sie im Internet unter www.millesima.at abrufen, bzw. sich auf einfache Anfrage per Post zusenden lassen.<br />
<a href="https://www.millesima.at/cgv#impressum" style="color: #FFFFFF; font-weight:bold;"><span style="color: #FFFFFF;">Hinweispflicht nach der ODR-Verordnung, dem Verbraucherstreitbeilegungsgesetz:</span></a><br />
Plattform der EU zur au&szlig;ergerichtlichen Online-Streitbeilegung: <a href="http://ec.europa.eu/consumers/odr/" style="color: #FFFFFF; font-weight:bold;"><span style="color: #FFFFFF;">http://ec.europa.eu/consumers/odr/</span></a>.{/if}
{if $prim_prec}<a href="https://www.millesima.at/cgv.html" style="color: #FFFFFF; font-weight:bold;">Verkaufs - und Lieferbedingungen Primeurweine 2017 - &Ouml;sterreich</a>.
<strong>Preise</strong>: Unsere Preise sind in &euro; inkl. 20% MwSt. ausgewiesen. {$validitedate} Druckfehler bleiben vorbehalten. Fotos und Abbildungen sind nicht verbindlich. Unsere Angebote richten sich ausschliesslich an Endverbraucher.
<strong>Bestellung/Lieferung</strong>: Bei Bestellung zahlen Sie nur den Preis in &euro; ohne Mehrwertsteuer. Ab einem Rechnungswert von 1800 &euro; inkl. MwSt.  (nur Primeurweine 2017) erfolgt die Lieferung nach &Ouml;sterreich kostenfrei an eine Adresse. Bei Bestellungen unter diesem Betrag stellen wir Ihnen 1,20 &euro; pro 75 cl als anteilige Fracht- und Versicherungskosten in Rechnung.
Sofort nach Bestellung erhalten Sie von uns eine Proformarechnung ohne Mehrwertsteuer und Transportkosten. Diese gilt zusammen mit dem Zahlungsdurchschlag als Eigentumsnachweis. Sobald die Weing&uuml;ter Fr&uuml;hjahr 2020 Ihre Weine zur Verf&uuml;gung stellen werden, erhalten Sie die endg&uuml;ltige Rechnung mit der Nachforderung der zum Lieferzeitpunkt g&uuml;ltigen Mehrwertsteuer und evtl. den Transportkosten. Nach Ausgleich des Restbetrags werden Ihnen die Weine per Spedition zugestellt.
<br />
<a href="https://www.millesima.at/cgv.html#cgv10" style="color: #FFFFFF; font-weight:bold;"><strong>Widerrufsrecht</strong></a>: Subskriptionsbestellungen sind vom gesetzlichen Widerrufsrecht ausgeschlossen.<br />
<a href="https://www.millesima.at/cgv.html" style="color: #FFFFFF; font-weight:bold;"><strong>AGB</strong></a>: Unsere vollst&auml;ndigen AGB k&ouml;nnen Sie im Internet unter www.millesima.at abrufen, bzw. sich auf einfache Anfrage per Post zusenden lassen.<br />
<a href="https://www.millesima.at/cgv#impressum" style="color: #FFFFFF; font-weight:bold;"><span style="color: #FFFFFF;">Hinweispflicht nach der ODR-Verordnung, dem Verbraucherstreitbeilegungsgesetz:</span></a><br />
Plattform der EU zur au&szlig;ergerichtlichen Online-Streitbeilegung: <a href="http://ec.europa.eu/consumers/odr/" style="color: #FFFFFF; font-weight:bold;"><span style="color: #FFFFFF;">http://ec.europa.eu/consumers/odr/</span></a>.{/if}