<?php ?>
<form id="co-delivery-method-form" action="">
       <!-- Content loaded dynamically -->
		<div id="checkout-delivery-method">
       		 <?php echo $this->getChildHtml('delivery_option_details') ?>
    	</div>

</form>

<div class="buttons-set" id="delivery-option-buttons-container">
        <p class="back-link"><a href="#" onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="button" class="button dark-buttpn next-button" onclick="Delivery.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
        <span id="delivery-option-please-wait" class="please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
        </span>
  </div>

<script type="text/javascript">
    //<![CDATA[
        var Delivery = new Delivery('co-delivery-method-form', "<?php echo $this->getUrl('checkout/onepage/saveDeliveryOption') ?>");
    //]]>
   </script>

<script>
jQuery(document).ready(function(){
	var $ = jQuery;
	$('.shipment-delivery-method li').click(function(){
		$('.shipment-delivery-method li').each(function(i){jQuery(this).find('input').removeAttr('checked')});
		$(this).find('input').attr('checked',true);
		if($(this).find('input').hasClass('shipment-one')){
			$('#two-shipping-method-layout').hide();
			$('#shipping-method-two').hide();
		}else{
			$('#two-shipping-method-layout').show();
		}
	});

	$('#select-delivery-shipment').on('change',function(){
		if($(this).val()==2){
			$('#shipping-method-two').show();
		}else{
			$('#shipping-method-two').hide();
		}
	});
});

function switchMethod(that){
	console.log(that.id);
	var $ = jQuery;
	$(that).checked = true;
	if($(that).hasClass('shipment-one')){
		$('#two-shipping-method-layout').hide();
		$('#delivery-shiping-option').hide();
	}else{
		$('#two-shipping-method-layout').show();
		$('#delivery-shiping-option').show();
	}

}
</script>
