<?php
$categories = $this->getCategoriesArray();
$current_location = Mage::registry('current_piercing_location');
//print_r(Mage::app()->getRequest()->getParams());
//die($current_location);
$looks = $this->getLooksByLocation($current_location);
$baseUrl = preg_replace('|https?\:\/\/|', '//', Mage::getBaseUrl());

$currentUrl = Mage::getSingleton('core/url')->parseUrl(Mage::helper('core/url')->getCurrentUrl());
$path = $currentUrl->getPath();
if(substr($path, 0, 1) == '/') {
    $path = substr($path, 1);
}

//if ($current_location) {
//    $url = Mage::getBaseUrl() . 'ecppiercinggallery/index/index/locationtype/' . $current_location .'/';
//} else {
    $url = $this->helper('core/url')->getCurrentUrl();
//}

$url = explode('?', trim($url));
$slide = preg_replace('/\D/', '', $url[1]);
$currentSildeId=$slide;
$slidePos = -1;

if(!empty($slide) && !empty($looks)):
    foreach($looks AS $key=>$look):
        if($look['id'] == $slide) $slidePos = $key;
    endforeach;
endif;
if($slidePos < 0) $slide = $slidePos = 0;
$url = $url[0];
$currentLook = $looks[$slidePos];
?>
<script>
    jQuery(document).ready(function(){
        //jQuery('select').not('select+span').customStyle();
        jQuery('p.note-msg').remove();

        jQuery('div#carousel').click(function(){
            //jQuery('a#play').trigger('click');
        }); 

        jQuery("#lookSelect").change(function(){
			var url = "<?php echo $this->getUrl('ecppiercinggallery/index/index');?>locationtype/"+jQuery(this).val()+'/';
			setLocation(url);
        });

        jQuery('#prev, #next').click(function(){
            jQuery('#prev, #next').removeClass('currentAction');
            jQuery(this).addClass('currentAction');
        });

        jQuery("#accordion").accordion({
            collapsible: true,
            active: <?php echo $this->getCurrentLevel() ?>
        });

        <?php if(count($looks)>0): ?>
        jQuery('#carousel').carouFredSel({
            prev: '#prev',
            next: '#next',
            circular: true,
            infinite: true,
            responsive  : false,
            auto: {
				play: false
            },
            swipe: {
            	onTouch: false,
            },       
            items: {
                start : <?=$slidePos;?>
            },
            onCreate: function (data) {
                    try {
                        FB.XFBML.parse();
                    }
                    catch(ex){}
            },
            scroll: {
                fx: 'fade',
                onBefore: function () {
                    var currentAction = jQuery('a.currentAction');
                    jQuery('#prev, #next').removeClass('currentAction');
                    
                    var lookId = jQuery('div#carousel img.carrousel-images').first().next().attr('data-item-id');
                    var url=jQuery(location).attr('href');
                 
                    var sURLVariables = url.split('?');
                    if(sURLVariables.size()>=2){
                        sURLVariables=sURLVariables[1].split('-');
                        lookId=sURLVariables[1];
                    }
                    
                    if(currentAction.attr('id') == 'prev') {
                        lookId = jQuery('div#carousel img.carrousel-images').first().attr('data-item-id');
                    }
					if(currentAction.attr('id') == 'next') {
                        
                        lookId = jQuery('div#carousel img.carrousel-images').first().next().attr('data-item-id');
                    }
                    jQuery('div.gallery-looks div.products-look').each(function () {
                        jQuery(this).addClass('inactive');
                        jQuery(this).removeClass('active');
                    });
                    
                    setTimeout(function() {
                        jQuery("div#look-products-" + lookId).addClass('active');
                        jQuery("div#look-products-" + lookId).removeClass('inactive');
                    }, 300);
                },
                onAfter: function (data) {
                    var itemID = jQuery(data.items.visible[0]).attr('data-item-id');
                    var itemIdx = jQuery(data.items.visible[0]).attr('index');
                    var imgTitle = jQuery(data.items.visible[0]).attr('data-item-name');
                    var imgSrc = data.items.visible[0].src;
                    var slidePath = '<?=$url;?>?look-' + itemID;

                    jQuery('#slide-count').html(itemIdx + ' of <?=count($looks);?>');
                    history.pushState(null, null, slidePath);

                }
            }

        });
        <?php endif; ?>
        jQuery('.caroufredsel_wrapper').addClass('caroufredsel_wrapper2').removeClass('caroufredsel_wrapper');
        jQuery('a.iframemail').fancybox({
            'transitionIn': 'elastic',
            'transitionOut': 'elastic',
            'type': 'iframe',
            'scrolling': 'no',
            'speedIn': 600,
            'speedOut': 200,
            'minHeight': 510,
            'maxHeight': 510,
            'height': 510,
            'width': 450,
            'overlayShow': false,
            'wrapCSS': 'send-email-popup',
            'overflow': 'hidden'
        });
    });
    var productAddToCartForm = new Array();

    function send(){
    <?php $url2send = str_replace(Mage::getBaseUrl(),'',Mage::helper('core/url')->getCurrentUrl()); ?>
    emailWindow = window.open("<?php echo Mage::getUrl('ecpcelebrities/index/send'); ?>?page=<?php echo $url2send; ?>", "mywindow", "location=1,status=1,scrollbars=1,width=700,height=600");
        //emailWindow = window.open("<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($this) ?>", "mywindow", "location=1,status=1,scrollbars=1,width=700,height=600");
        //emailWindow.moveTo(0, 0);
    }

</script>

<div class="piercing-gallery-mt1">
    <h3><?php echo Mage::getModel('catalog/category')->load(Mage::getStoreConfig('ecp_piercinggallery/piercinggallery/piercing_gallery_category_id'))->getName(); ?></h3>

    <div id="messages_product_view"></div>

    <div class="navigation-menu">
        <select name="look" id="lookSelect">
            <?php foreach ($categories as $cat): ?>
	        	<optgroup label="<?php echo $cat['name']; ?>">
                    <?php if (!empty($cat['locationtype'])):
                        foreach ($cat['locationtype'] as $location):
                            ?>
                            <option id="look-<?php echo $location['id'];?>" value="<?php echo $location['id'];?>" <?php if ($current_location == $location['id']) echo "selected='true'" ?>>
                                    <?php echo $location['name']; ?>
                            </option>
                    <?php endforeach; ?>
                    <?php endif; ?>
	        	</optgroup>
            <?php endforeach; ?>
        </select>
        <?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('piercing_message_block')->toHtml(); ?>
    </div>

    <?php if(count($looks)>0): ?>
    <div class="content" >
        <div id="wrapper">
            <div class="carousel-content">
                <div id="inner">
                	<a href="#" class="jcarousel-control-prev" id="prev">‹</a>
                    <div id="carousel" >
                        <?php $x = 1; ?>
                        <?php foreach ($looks as $look): ?>
                            <img src="<?=$look['img'];?>" class="carrousel-images" index="<?=$x;?>" data-item-id="<?=$look['id'];?>" data-item-name="<?=$look['name'];?>" alt="" title="" width="600" height="400" border="0" />
                            <?php $x++; ?>
                        <?php endforeach; ?>
                    </div>
                    <input type="hidden" id="carouselcount" name="carouselcount" value="<?=count($looks);?>" />
                	<a href="#" class="jcarousel-control-next" id="next">›</a>
                    <span id="slide-count"><?=($slidePos>0)?$slidePos:1;?> of <?=count($looks);?></span>
                </div>
            </div>

            <div class="gallery-looks">
                <div class="title-products-looks"><h3><?php echo $this->__('PURCHASE THIS LOOK') ?></h3></div>
                     <?php 
                    $first = true;
                    if($currentSildeId){
                        $first = FALSE;
                    }
                    foreach ($looks as $look): ?>
 					<?php 
                    if($currentSildeId==$look['id']){
                        $first = true;
                    }?>
                    <div class="products-look <?php echo $first ? 'active' : 'inactive' ?>" id="look-products-<?php echo $look['id'] ?>">
                        <?php if (empty($look['products'])): ?>
                        <p class="products-look-msg"><!--<span id="remove-look-msg" onclick="jQuery('.products-look-msg').fadeOut()" title="<?php echo $this->__('Remove') ?>">x</span>--><?php echo $this->__('There are no products matching the selection') ?></p>
                        <?php endif; ?>
                        <?php foreach ($look['products'] as $product): ?>
                            <?php
                            $showSampleForm = false;
                            if ($product->getSizeSample() == 1) {
                                $showSampleForm = true;
                                $sampleProduct = Mage::getModel('catalog/product')->getCollection()
                                        ->addAttributeToFilter('type_id', 'customproduct')
                                        ->getFirstItem();
                                $sampleProduct = Mage::getModel('catalog/product')->load($sampleProduct->getEntityId());
                            }
                            ?>
        <?php if ($showSampleForm): ?>
                                <div style="display: none;">
                                    <form action="<?php echo $this->helper('checkout/cart')->getAddUrl($sampleProduct) ?>" method="post" id="product_addtocart_form_sample_<?php echo $sampleProduct->getId() . '_' . $look['id']; ?>" <?php if ($sampleProduct->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
                                        <input type="hidden" name="product_sample" value="<?php echo $sampleProduct->getId() ?>" />
                                        <input type="hidden" name="related_product" id="related-products-field" value="" />
                                        <input type="hidden" value="1" />
                                        <input type="hidden" name="qty_sample" id="qty_sample" maxlength="12" value="1" />
                                        <button type="button" title="SIZE SAMPLE" class="button" id="sample-button" onclick="addToShoppingCart(this,this.form)"><span><span>SIZE SAMPLE</span></span></button>
                                    </form>
                                </div>
        <?php endif; ?>
                            <form action="<?php echo $this->helper('checkout/cart')->getAddUrl($product); ?>" method="post" id="product_addtocart_form_<?php echo $product->getId() . '_' . $look['id']; ?>" class="product_addtocart_celebrities_form" <?php if ($product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?> >
        <?php $product = Mage::getModel('catalog/product')->load($product->getId()) ?>
                                <div class="image_thumb_celeb">
                                    <a href="<?php echo $product->getProductUrl() ?>">
                                        <img src="<?php echo $this->helper('catalog/image')->init($product, 'image')->resize(74, 96) ?>"/>
                                    </a>
                                </div>
                                <div class="product-shop">
                                    <div class="product-name">
                                        <a href="<?php echo $product->getProductUrl() ?>">
                                            <h1><?php echo $product->getName() ?></h1>
                                        </a>
                                    </div>
                                    <?php echo $this->getProductPriceBlock($product)->toHtml() ?>
                                    <?php if ($product->getTypeId() == 'configurable' && 1==2): ?>
                                        <script type="text/javascript">
                                            var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig($product) ?>);
                                        </script>
                                        <div class="product-collateral">
                                            <div id="product-options-wrapper" class="product-options">
                                            <?php echo $this->getAttributesBlocks($product)->toHtml() ?>
                                            </div>
                                        </div>
                                    <?php endif; ?>
                                    <div class="product-options-bottom">
                                        <?php // \\echo $this->getAddToCartBlock($product)->toHtml()  ?>
                                        <?php $quickviewUrl = $this->getUrl('quickview/index/index', array('id' => $product->getId())); ?>
                                        <?php $quickviewUrl = preg_replace('|http(s)?\:|', '', $quickviewUrl); ?>
                                        <button class="fancybox fancybox.iframe button piercing-gallery-btn-quickview" id='product-quickview-<?php echo $product->getId() . '_' . $look['id']; ?>' href="<?= $quickviewUrl ?>"><span><span>View Product Details</span></span><span class="glyphicon glyphicon-shopping-cart"></span></button>
                                    </div>
                                </div>
                            </form>
                            <script type="text/javascript">
                                jQuery.noConflict();

                                jQuery("#product_addtocart_form_<?php echo $product->getId() . '_' . $look['id']; ?> .add-to-cart .button").attr('onclick',"productAddToCartForm[<?php echo $product->getId() ?>].submit(this,this.form)");
                                jQuery("#product_addtocart_form_<?php echo $product->getId() . '_' . $look['id']; ?> .add-to-cart #button-sample").attr('onclick',"doClick()");
                                //<![CDATA[
                                productAddToCartForm[<?php echo $product->getId() ?>] = new VarienForm('product_addtocart_form_<?php echo $product->getId() . '_' . $look['id']; ?>');
                                productAddToCartForm[<?php echo $product->getId() ?>].submit = function(button, form) {
                                    if (this.validator.validate()) {
                                        addToShoppingCart(button,form);
                                    }
                                }.bind(productAddToCartForm[<?php echo $product->getId() ?>]);
                                //]]
                            </script>

                            <script type="text/javascript">
                                jQuery(document).ready(function(){
                                    jQuery('.price-box').css('display','block');
                                });
                            </script>
    <?php endforeach; ?>
                    </div>
    <?php $first = false;
endforeach; ?>
            </div>
        </div>
    </div>
    <?php else: ?>
    <div class="content" >
        <div id="wrapper">
         <p class="products-look-msg"><!--<span id="remove-look-msg" onclick="jQuery('.products-look-msg').fadeOut()" title="<?php echo $this->__('Remove') ?>">x</span>--><?php echo $this->__('There are no products matching the selection') ?></p>
            
        </div>
    </div>
    <?php endif ?>
</div>