<?php $items = $this->getMenu(); $current = $this->getCurrent(); var_dump($items);?>
<div class="discover-mt-navigation-menu">
    <ul>
    <?php foreach($items as $item): ?>    
    <?php if($current->getId() == $item->getId()): ?>
        <li class="discover-mt-navigation current-active">
        <?php echo $item->getName() ?>
        </li>
    <?php else: ?>
        <li class="discover-mt-navigation" onclick="document.location.href ='<?php echo Mage::getUrl($item->getUrl()) ?>'">
        <?php /*<li class="discover-mt-navigation" onclick="setLocation('<?php echo $this->getUrl('ecpdiscovernavigation/index/',array('content_id'=>$item->getCategoryId()))?>') "> */ ?>
            <?php echo $item->getName()?>
        </li>
    <?php endif; ?>
        </li>
    <?php endforeach; ?>
    </ul>
</div>
