<?php
	$totalPageSizeItem = $this->getPurchaseOrderCollection()->getLastPageNumber();
?>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl('js'); ?>jquery/jquery.cookie.js"></script>
<div class="cart-mt">
        <fieldset>
        	<?php if($this->getPurchaseOrderCollection()->getSize()>0):?>
        	<div id="purchase-history">
        	<div class="box-content">
            <table id="myaccount-shopping-cart-table" class="data-table cart-table" width="100%" border="0">
                <thead class="shop-titles">
                <tr>
                    <th colspan="2"><?php echo $this->__('Product'); ?></th>
                    <th><?php echo $this->__('Qty '); ?></th>
                    <th><?php echo $this->__('Price'); ?></th>
                    <th>&nbsp;</th>
                </tr>
                </thead>
                <tbody>
                <?php 
                $storeList = array();
                $stores = Mage::app()->getStores();
                
                $storeColorConfig = Mage::helper('myaccount')->getStoreColorConfig();
                
                foreach ($stores as $store) {
                	$storeList[$store->getId()] = $store->getName();
                }
                
                ?>
                    <?php $i = 0; $prices = array(); $skus = array(); ?>
                    <?php foreach ($this->getPurchaseOrderCollection() as $_item): ?>
                        <?php //echo $this->getItemHtml($_item) ?>
                        <?php
                           /*  $prices[$i] = floatval($_item->getPrice());
                            $skus[$i] = $_item->getSku();
                            $i++ */
                        ?>
                        
                        <?php 
                        
                        $productId = Mage::getModel('catalog/product')->getIdBySku($_item->getSku());
                        $product = Mage::getModel('catalog/product')->load($productId);
                        
                        $arrayOfParentIds = Mage::getSingleton('catalog/product_type_configurable')->getParentIdsByChild($_item->getProduct()->getId());
                        $parentId = (count($arrayOfParentIds) > 0 ? $arrayOfParentIds[0] : null);
                        $url = $product->getProductUrl();
                        
                        //$productDescr = $product->getDescription();
                        
                        if(!is_null($parentId)){
                        	$parentProduct = Mage::getModel("catalog/product")->load($parentId);
                        	$url = $parentProduct->getProductUrl();
                        	//$productDescr = $parentProduct->getDescription();
                        }
                        
                        $productName = $product->getName();
                        $typeId = $product->getTypeId();
                        $productNotAvailableClass = "";
                        
                        if(!$product->getId()){
                        	$productName = $_item->getName();
                        	$productNotAvailableClass = "current-item-not-available";
                        	$productDescr = $_item->getDescription();
                        }
                        
                        /* if(!empty($productDescr)){
                        	if(strlen($productDescr)>=70)
                        		$productDescr = substr($productDescr,1,70)."...";
                        } */
                        
                        
                        $receiptUrl = Mage::getUrl("sales/order/print")."order_id/".$_item->getOrderId()."/";
                        $reorderUrl = Mage::getUrl("sales/order/reorderItem")."item_id/".$_item->getId()."/";
                        
                        $storeColor = '';
                        $storeName = $storeList[$_item->getStoreId()];
                        if(array_key_exists($_item->getStoreId(),$storeColorConfig)){
                        	$storeColor .= 'style="';
                        	$frontColor = $storeColorConfig[$_item->getStoreId()]['front_color'];
                        	if(!empty($frontColor))
                        		$storeColor .= 'color:'.$frontColor.';'; 
                        	$backColor = $storeColorConfig[$_item->getStoreId()]['back_color'];
                        	if(!empty($backColor))
                        		$storeColor .= 'background:'.$backColor.';';
                        	$storeColor .= '"';
                        	$storeName = $storeColorConfig[$_item->getStoreId()]['store_label'];
                        }
                        
                        ?>
                        
                      <tr data-id="<?php echo $_item->getId()?>" class="<?php echo $productNotAvailableClass?>">
							<td class="cart_col1">
								<a href="<?php echo $url?>" title="<?php echo $productName?>" 
										class="product-image">
									<img src="<?php echo Mage::helper('catalog/image')
										->init($product, 'thumbnail')->resize(74,96)?>" 
											width="74" height="96" alt="<?php echo $productName?>">
								</a>
								<a data-img="<?php echo Mage::helper('catalog/image')
									->init($product, 'thumbnail')->resize(350,350)?>" class="mt-piercing-photo" 
									href="javascript:void(0);">View Piercing Photo
								</a>
							</td>
			
							<td class="cart_col2">
								<h2 class="product-name <?php echo $typeId?>">
									<a href="<?php echo $url?>"><?php echo $productName?></a>
								</h2>
								<?php if(0 /* && !empty($productDescr) */):?>
									<h2 class="product-descr"><?php //echo $productDescr?></h2>
								<?php endif;?>
				
								<span class="mt-purchase-added-at">Purchased: <?php echo date('M d, Y H:i a',strtotime($_item->getCreatedAt()))?></span>
								<lable <?php echo $storeColor?>  class="purchase-store-name"><?php echo $storeName?></lable>
							</td>
			
							<td class="cart_col4">
								<div class="qty-wrap">
									<span><?php echo number_format($_item->getQtyOrdered())?></span>
								</div>
							</td>
			
							<td class="cart_col3">
								<span class="price_multi"></span>
								<span class="price">
									<?php echo Mage::helper('checkout')->formatPrice($_item->getPrice())?>
								</span>
							</td>
			
							<td class="cart_col6">
								<div class="mt-purchase-btn">
									<button data-url="<?php echo $receiptUrl?>" class="button" onclick="openPurchaseWindow(this)">See Receipts</button>
								</div>
								<?php if($product->getId()):?>
									<div class="mt-purchase-btn">
										<button data-item-id="<?php echo $_item->getId()?>" class="button" onclick="reorderItem(this)">Reorder</button>
									</div>
									<div class="mt-purchase-btn">
										<button class="button">Share</button>
									</div>
								<?php endif;?>
								</td>
							</tr>
                        
                        
                    <?php endforeach ?>
                </tbody>
            </table>
            </div>
            </div>
            <?php else:?>
            	<p class="no-purchase-itemundefined"><?php echo $this->__("You have no purchased item.")?></p>
            <?php endif;?>
        </fieldset>

</div>



<div class="fancybox-overlay fancybox-overlay-fixed" style="width: auto; 
		height: auto; display: none;">
	<div class="fancybox-wrap fancybox-desktop fancybox-type-iframe fancybox-sample-size fancybox-opened" 
			tabindex="-1" style="width: 350px; height: auto; position: absolute; 
			top: 20px; left: 37%; overflow: visible;">
		<div class="fancybox-skin" style="padding: 0px; width: auto; height: auto;">
			<div class="fancybox-outer">
				<div class="fancybox-inner" style="overflow: hidden; 
					width: 350px; height: 350px;">
					<img id="frame-img" alt="" src="" />
				</div>
				<a title="Previous" class="fancybox-nav fancybox-prev" href="javascript:void(0);">
					<span></span>
				</a>
				<a title="Next" class="fancybox-nav fancybox-next" href="javascript:void(0);">
					<span></span>
				</a>
			</div>
			<a title="Close" class="fancybox-item fancybox-close" href="javascript:void(0);"></a>
		</div>
	</div>
</div>




<script>
    jQuery('a.scl-popup').fancybox({
        openEffect  : 'none',
        closeEffect : 'none',
        nextEffect  : 'none',
        prevEffect  : 'none',
        padding     : 0,
        mouseWheel : false,
        loop            : false,
        helpers : {
            title : null
        },
        width: 785,
        minWidth: 785,
        maxWidth: 785,
        height: 572,
        minHeight: 572,
        maxHeight: 572
    });

</script>


<script>
var xhr = null;
var pageItem = 2;
var totalPageItem = <?php echo $totalPageSizeItem?>;
jQuery(function($){
	$('#purchase-history .box-content').bind('scroll', function(){
		if($(this).scrollTop() + $(this).innerHeight()>=$(this)[0].scrollHeight){
			if(pageItem<=totalPageItem){
				 if( xhr == null ) {
				    //xhr.abort();
				    //xhr = null;
				    showLoadingFancybox1('purchase-history');
				 	xhr =	jQuery.ajax({
						//async: false,
				        url: '<?php echo Mage::getBaseUrl('web').'myaccount/index/getPurchasedItems';?>',
				        dataType : 'json',
						type : 'POST',
						data: {'page':pageItem,'limit':5,'m_store':'<?php echo $_GET['m_store']?>','m_sort':'<?php echo $_GET['m_sort']?>'},
				        success: function(data) {
				        	jQuery('#myaccount-shopping-cart-table tbody').append(data.data.html);
				        	jQuery('.loader').css({"display":"none"});
				        	hideLoadingFancybox1('purchase-history');
				        }
				    });
				 	xhr = null;
				 	pageItem ++;
				}
		    }else{
		    	hideLoadingFancybox('purchase-history');
		    }
		}
 	});
});


jQuery(document).ready(function(){
	jQuery(document).on('click','.mt-piercing-photo',function(){
		return false;
		var imgSrc = jQuery(this).attr('data-img');
		jQuery('.mt-piercing-photo').removeClass('active');
		jQuery(this).addClass('active');
		jQuery('#frame-img').attr('src',imgSrc);
		jQuery('.mt-new-purchase .fancybox-overlay-fixed').show();

		var selector = jQuery('.mt-piercing-photo.active').parent().parent().next();
		var next = selector.attr('data-id');
		if(next!="undefined" && next!=null){
			jQuery('.mt-new-purchase .fancybox-nav.fancybox-next').show();
		}else{
			jQuery('.mt-new-purchase .fancybox-nav.fancybox-next').hide();
		}

		var selector = jQuery('.mt-piercing-photo.active').parent().parent().prev();
		var prev = selector.attr('data-id');
		if(prev!="undefined" && prev!=null){
			jQuery('.mt-new-purchase .fancybox-nav.fancybox-prev').show();
		}else{
			jQuery('.mt-new-purchase .fancybox-nav.fancybox-prev').hide();
		}
	});

	jQuery('.fancybox-close').click(function(){
		jQuery('.mt-new-purchase .fancybox-overlay-fixed').hide();
	});

	jQuery('.mt-new-purchase .fancybox-nav.fancybox-prev').click(function(){
		toPrevious();
	});


	jQuery('.mt-new-purchase .fancybox-nav.fancybox-next').click(function(){
		toNext();
	});
	
});

function toNext(){
	var selector = jQuery('.mt-piercing-photo.active').parent().parent().next();
	var next = selector.attr('data-id');
	if(next!="undefined" && next!=null){
		var imgSrc = selector.find('.mt-piercing-photo').attr('data-img');
		jQuery('#frame-img').attr('src',imgSrc);
		jQuery('.mt-piercing-photo').removeClass('active');
		selector.find('.mt-piercing-photo').addClass('active');

		var prevSelector = jQuery('.mt-piercing-photo.active').parent().parent().prev();
		var prev = prevSelector.attr('data-id');
		if(prev!="undefined" && prev!=null){
			jQuery('.mt-new-purchase .fancybox-nav.fancybox-prev').show();
		}

		var nextSelector = jQuery('.mt-piercing-photo.active').parent().parent().next();
		var next = nextSelector.attr('data-id');
		if(next!="undefined" && next!=null){
			jQuery('.mt-new-purchase .fancybox-nav.fancybox-next').show();
		}else{
			jQuery('.mt-new-purchase .fancybox-nav.fancybox-next').hide();
		}
		
	}
}

function toPrevious(){
	var selector = jQuery('.mt-piercing-photo.active').parent().parent().prev();
	var prev = selector.attr('data-id');
	if(prev!="undefined" && prev!=null){
		var imgSrc = selector.find('.mt-piercing-photo').attr('data-img');
		jQuery('#frame-img').attr('src',imgSrc);
		jQuery('.mt-piercing-photo').removeClass('active');
		selector.find('.mt-piercing-photo').addClass('active');

		var nextSelector = jQuery('.mt-piercing-photo.active').parent().parent().next();
		var next = nextSelector.attr('data-id');
		if(next!="undefined" && next!=null){
			jQuery('.mt-new-purchase .fancybox-nav.fancybox-next').show();
		}

		var prevSelector = jQuery('.mt-piercing-photo.active').parent().parent().prev();
		var prev = prevSelector.attr('data-id');
		if(prev!="undefined" && prev!=null){
			jQuery('.mt-new-purchase .fancybox-nav.fancybox-prev').show();
		}else{
			jQuery('.mt-new-purchase .fancybox-nav.fancybox-prev').hide();
		}
	}
}


function openPurchaseWindow(event){
	var url = jQuery(event).attr('data-url');
	window.open(url);
}

function reorderItem(event){
	var item_id = jQuery(event).attr('data-item-id');
	showLoadingFancybox();
	jQuery.ajax({
        url: '<?php echo Mage::getBaseUrl('web').'sales/order/reorderItemAjax';?>',
        dataType : 'json',
		type : 'POST',
		data: {'item_id':item_id},
        success: function(data) {
            if(data.success){
            	/* jQuery('#new-mt-myproduct-cart .totals #shopping-cart-totals-table').html("");
				var content = jQuery(data.total).find('#shopping-cart-totals-table').html();
				jQuery('#new-mt-myproduct-cart .totals #shopping-cart-totals-table').html(content); */

				jQuery('.mt-my-cart').html("");
	        	jQuery('.mt-my-cart').html(data.cart_html);
                
            	jQuery('html, body').animate({
                    scrollTop: 0
                }, 'fast');

            	jQuery('#ajax_cart_content').html(data.top_cart);
                jQuery('#just_added').slideDown(1000);
                jQuery('#topcart-popup').addClass('just_added');
                setTimeout(function() {
                    jQuery('#just_added').slideUp(1000);
                    jQuery('#topcart-popup').removeClass('just_added');
                }, 5000);
            }else{
                alert(data.message);
            }
        	hideLoadingFancybox();
        }
    });
}

</script>
