<?php 
	/*
	 * Allure customized My Account
	 * 
	 */
?>
<?php
$lastProductAddedToCartId = Mage::getSingleton('checkout/session')->getLastAddedProductId();
if ($lastProductAddedToCartId) {
    $productCategoryIdsArray = Mage::getModel('catalog/product')->load($lastProductAddedToCartId)->getCategoryIds();
    $continueShoppingCategoryUrl = Mage::getModel('catalog/category')->load($productCategoryIdsArray[0])->getUrl();
}
$totalPageSizeItem = $this->getPurchasedItems()->getLastPageNumber();
?>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl('js'); ?>jquery/jquery.cookie.js"></script>
<div class="cart-mt">

        <fieldset>
            <table id="myaccount-shopping-cart-table" class="data-table cart-table" width="100%" border="0">
                <thead class="shop-titles">
                <tr>
                    <th colspan="2"><?php echo $this->__('Product'); ?></th>
                    <th><?php echo $this->__('Qty '); ?></th>
                    <th><?php echo $this->__('Price'); ?></th>
                    <th>&nbsp;</th>
                </tr>
                </thead>
                <tbody>
                    <?php $i = 0; $prices = array(); $skus = array(); ?>
                    <?php foreach ($this->getPurchasedItems() as $_item): ?>
                        <?php echo $this->getItemHtml($_item) ?>
                        <?php
                            $prices[$i] = floatval($_item->getPrice());
                            $skus[$i] = $_item->getSku();
                            $i++
                        ?>
                    <?php endforeach ?>
                </tbody>
            </table>
        </fieldset>

</div>



<div class="fancybox-overlay fancybox-overlay-fixed" style="width: auto; 
		height: auto; display: none;">
	<div class="fancybox-wrap fancybox-desktop fancybox-type-iframe fancybox-sample-size fancybox-opened" 
			tabindex="-1" style="width: 350px; height: auto; position: absolute; 
			top: 20px; left: 37%; overflow: visible;">
		<div class="fancybox-skin" style="padding: 0px; width: auto; height: auto;">
			<div class="fancybox-outer">
				<div class="fancybox-inner" style="overflow: hidden; 
					width: 350px; height: 350px;">
					<img id="frame-img" alt="" src="" />
				</div>
				<a title="Previous" class="fancybox-nav fancybox-prev" href="javascript:void(0);">
					<span></span>
				</a>
				<a title="Next" class="fancybox-nav fancybox-next" href="javascript:void(0);">
					<span></span>
				</a>
			</div>
			<a title="Close" class="fancybox-item fancybox-close" href="javascript:void(0);"></a>
		</div>
	</div>
</div>




<script>
    jQuery('a.scl-popup').fancybox({
        openEffect  : 'none',
        closeEffect : 'none',
        nextEffect  : 'none',
        prevEffect  : 'none',
        padding     : 0,
        mouseWheel : false,
        loop            : false,
        helpers : {
            title : null
        },
        width: 785,
        minWidth: 785,
        maxWidth: 785,
        height: 572,
        minHeight: 572,
        maxHeight: 572
    });

</script>


<script>
var xhr = null;
var pageItem = 2;
var totalPageItem = <?php echo $totalPageSizeItem?>;
jQuery(function($){
	$('#myaccount-shopping-cart-table').bind('scroll', function(){
		if($(this).scrollTop() + $(this).innerHeight()>=$(this)[0].scrollHeight){
			if(pageItem<=totalPageItem){
				 if( xhr == null ) {
				    //xhr.abort();
				    //xhr = null;
				    showLoadingFancybox();
				 	xhr =	jQuery.ajax({
						//async: false,
				        url: '<?php echo Mage::getBaseUrl('web').'myaccount/index/getPurchasedItems';?>',
				        dataType : 'json',
						type : 'POST',
						data: {'page':pageItem,'limit':5},
				        success: function(data) {
				        	jQuery('#myaccount-shopping-cart-table tbody').append(data.data.html);
				        	jQuery('.loader').css({"display":"none"});
				        	hideLoadingFancybox();
				        }
				    });
				 	xhr = null;
				 	pageItem ++;
				}
		    }else{
		    	hideLoadingFancybox();
		    }
		}
 	});
});


jQuery(document).ready(function(){
	jQuery(document).on('click','.mt-piercing-photo',function(){
		var imgSrc = jQuery(this).attr('data-img');
		jQuery('.mt-piercing-photo').removeClass('active');
		jQuery(this).addClass('active');
		jQuery('#frame-img').attr('src',imgSrc);
		jQuery('.mt-new-purchase .fancybox-overlay-fixed').show();

		var selector = jQuery('.mt-piercing-photo.active').parent().parent().next();
		var next = selector.attr('data-id');
		if(next!="undefined" && next!=null){
			jQuery('.mt-new-purchase .fancybox-nav.fancybox-next').show();
		}else{
			jQuery('.mt-new-purchase .fancybox-nav.fancybox-next').hide();
		}

		var selector = jQuery('.mt-piercing-photo.active').parent().parent().prev();
		var prev = selector.attr('data-id');
		if(prev!="undefined" && prev!=null){
			jQuery('.mt-new-purchase .fancybox-nav.fancybox-prev').show();
		}else{
			jQuery('.mt-new-purchase .fancybox-nav.fancybox-prev').hide();
		}
	});

	jQuery('.fancybox-close').click(function(){
		jQuery('.mt-new-purchase .fancybox-overlay-fixed').hide();
	});

	jQuery('.mt-new-purchase .fancybox-nav.fancybox-prev').click(function(){
		toPrevious();
	});


	jQuery('.mt-new-purchase .fancybox-nav.fancybox-next').click(function(){
		toNext();
	});
	
});

function toNext(){
	var selector = jQuery('.mt-piercing-photo.active').parent().parent().next();
	var next = selector.attr('data-id');
	if(next!="undefined" && next!=null){
		var imgSrc = selector.find('.mt-piercing-photo').attr('data-img');
		jQuery('#frame-img').attr('src',imgSrc);
		jQuery('.mt-piercing-photo').removeClass('active');
		selector.find('.mt-piercing-photo').addClass('active');

		var prevSelector = jQuery('.mt-piercing-photo.active').parent().parent().prev();
		var prev = prevSelector.attr('data-id');
		if(prev!="undefined" && prev!=null){
			jQuery('.mt-new-purchase .fancybox-nav.fancybox-prev').show();
		}

		var nextSelector = jQuery('.mt-piercing-photo.active').parent().parent().next();
		var next = nextSelector.attr('data-id');
		if(next!="undefined" && next!=null){
			jQuery('.mt-new-purchase .fancybox-nav.fancybox-next').show();
		}else{
			jQuery('.mt-new-purchase .fancybox-nav.fancybox-next').hide();
		}
		
	}
}

function toPrevious(){
	var selector = jQuery('.mt-piercing-photo.active').parent().parent().prev();
	var prev = selector.attr('data-id');
	if(prev!="undefined" && prev!=null){
		var imgSrc = selector.find('.mt-piercing-photo').attr('data-img');
		jQuery('#frame-img').attr('src',imgSrc);
		jQuery('.mt-piercing-photo').removeClass('active');
		selector.find('.mt-piercing-photo').addClass('active');

		var nextSelector = jQuery('.mt-piercing-photo.active').parent().parent().next();
		var next = nextSelector.attr('data-id');
		if(next!="undefined" && next!=null){
			jQuery('.mt-new-purchase .fancybox-nav.fancybox-next').show();
		}

		var prevSelector = jQuery('.mt-piercing-photo.active').parent().parent().prev();
		var prev = prevSelector.attr('data-id');
		if(prev!="undefined" && prev!=null){
			jQuery('.mt-new-purchase .fancybox-nav.fancybox-prev').show();
		}else{
			jQuery('.mt-new-purchase .fancybox-nav.fancybox-prev').hide();
		}
	}
}


function openPurchaseWindow(event){
	var url = jQuery(event).attr('data-url');
	window.open(url);
}

</script>
