<?php $oGiftCardSession = Mage::getSingleton('giftcards/session'); ?>

<div class="discount">
    <div class="discount-form">
        <form method="post" action="<?php echo $this->getUrl('giftcards/cart/activateGiftCard'); ?>" id="activateGiftCard">
            <div class="input-box">
                <input value="" name="giftcard_code" id="giftcard_code" class="input-text" placeholder="Gift Card">
            </div>
        </form>

        <?php $currencySymbol = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); $temp = 0; ?>
        <?php if($oGiftCardSession->getActive())
                    foreach($oGiftCardSession->getFrontOptions() as $k => $v)
                    {
                        if($temp) {
                            echo '<br/><br/>';
                        }
                        echo '<p><b>'.$currencySymbol.$v['applied'].' '.$this->__('applied from Gift Card').' **********'.$v['code'].'.</b><br/>';
                        echo $this->__('Remaining card balance').': '.$currencySymbol.$v['remaining'].'.</p><a href="'.$this->getUrl("giftcards/cart/deActivateGiftCard/id/$k").'" class="button_coupon" style="position:relative; top:-20px;"><span><span>'.$this->__('Remove').'</span></span></a>';
                        $temp = 1;
                    }
        ?>
    </div>
    <script type="text/javascript">
        //&lt;![CDATA[
        var deActivateGiftCardForm = new VarienForm('deActivateGiftCard');
        var giftCardForm = new VarienForm('activateGiftCard');
        //]]&gt;
        jQuery("#giftcard_code").blur(function() {
            giftCardForm.submit(true);
        });
    </script>

</div>
