
                <?php 
                $storeList = array();
                $stores = Mage::app()->getStores();
                
                $storeColorConfig = Mage::helper('myaccount')->getStoreColorConfig();
                
                foreach ($stores as $store) {
                	$storeList[$store->getId()] = $store->getName();
                }
                
                ?>
                    <?php $i = 0; $prices = array(); $skus = array(); ?>
                    <?php foreach ($this->getPurchaseOrderCollection() as $_item): ?>
                        <?php 
                        
                        $productId = Mage::getModel('catalog/product')->getIdBySku($_item->getSku());
                        $product = Mage::getModel('catalog/product')->load($productId);
                        
                        $arrayOfParentIds = Mage::getSingleton('catalog/product_type_configurable')->getParentIdsByChild($_item->getProduct()->getId());
                        $parentId = (count($arrayOfParentIds) > 0 ? $arrayOfParentIds[0] : null);
                        $url = $product->getProductUrl();
                        
                        //$productDescr = $product->getDescription();
                        
                        if(!is_null($parentId)){
                        	$parentProduct = Mage::getModel("catalog/product")->load($parentId);
                        	$url = $parentProduct->getProductUrl();
                        	//$productDescr = $parentProduct->getDescription();
                        }
                        
                        $productName = $product->getName();
                        $typeId = $product->getTypeId();
                        $productNotAvailableClass = "";
                        
                        if(!$product->getId()){
                        	$productName = $_item->getName();
                        	$productNotAvailableClass = "current-item-not-available";
                        	$productDescr = $_item->getDescription();
                        }
                        
                        /* if(!empty($productDescr)){
                        	if(strlen($productDescr)>=70)
                        		$productDescr = substr($productDescr,1,70)."...";
                        } */
                        
                        
                        $receiptUrl = Mage::getUrl("sales/order/review")."order_id/".$_item->getOrderId()."/";
                        $reorderUrl = Mage::getUrl("sales/order/reorderItem")."item_id/".$_item->getId()."/";
                        
                        $storeColor = '';
                        $storeName = $storeList[$_item->getStoreId()];
                        if(array_key_exists($_item->getStoreId(),$storeColorConfig)){
                        	$storeColor .= 'style="';
                        	$frontColor = $storeColorConfig[$_item->getStoreId()]['front_color'];
                        	if(!empty($frontColor))
                        		$storeColor .= 'color:'.$frontColor.';'; 
                        	$backColor = $storeColorConfig[$_item->getStoreId()]['back_color'];
                        	if(!empty($backColor))
                        		$storeColor .= 'background:'.$backColor.';';
                        	$storeColor .= '"';
                        	$storeName = $storeColorConfig[$_item->getStoreId()]['store_label'];
                        }
                        
                        $_order = Mage::getModel('sales/order')->load($_item->getOrderId());
                        
                        ?>
                        
                      <tr data-id="<?php echo $_item->getId()?>" class="<?php echo $productNotAvailableClass?>">
							<td class="cart_col1">
								<a href="<?php echo $url?>" title="<?php echo $productName?>" 
										class="product-image">
									<img src="<?php echo Mage::helper('catalog/image')
										->init($product, 'thumbnail')->resize(74,96)?>" 
											width="74" height="96" alt="<?php echo $productName?>">
								</a>
								<a data-img="<?php echo Mage::helper('catalog/image')
									->init($product, 'thumbnail')->resize(350,350)?>" class="mt-piercing-photo" 
									href="javascript:void(0);">View Piercing Photo
								</a>
							</td>
			
							<td class="cart_col2">
								<h2 class="product-name <?php echo $typeId?>">
									<a href="<?php echo $url?>"><?php echo $productName?></a>
								</h2>
								<?php if(0 /* && !empty($productDescr) */):?>
									<h2 class="product-descr"><?php //echo $productDescr?></h2>
								<?php endif;?>
				
								<span class="mt-purchase-added-at">Purchased: <?php echo date('M d, Y H:i a',strtotime($_item->getCreatedAt()))?></span>
								<label <?php echo $storeColor?>  class="purchase-store-name"><?php echo $storeName?></label>
							</td>
			
							<td class="cart_col4">
								<div class="qty-wrap">
									<span><?php echo number_format($_item->getQtyOrdered())?></span>
								</div>
							</td>
			
							<td class="cart_col3">
								<span class="price_multi"></span>
								<span class="price">
									<?php echo Mage::helper('checkout')->formatPrice($_item->getPrice())?>
								</span>
							</td>
			
							<td class="cart_col6">
							
								<?php  if ($_order->getTracksCollection()->count()) : ?>
                					<div class="mt-purchase-btn">
                						<button class="button" onclick="openTrackOrder('<?php echo Mage::helper('shipping')->getTrackingPopupUrlBySalesModel($_order) ?>')" title="<?php echo $this->__('Track') ?>">
                					<?php echo $this->__('Track') ?></button>
                					</div>
                				<?php endif; ?>
							
								<div class="mt-purchase-btn">
									<button data-url="<?php echo $receiptUrl?>" class="button" onclick="openPurchaseWindow(this)">See Receipts</button>
								</div>
								<?php if($product->getId()):?>
									<div class="mt-purchase-btn">
										<button data-item-id="<?php echo $_item->getId()?>" class="button" onclick="reorderItem(this)">Add to Cart</button>
									</div>
								<?php endif;?>
								</td>
							</tr>
                        
                        
                    <?php endforeach ?>
