<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    OnTap
 * @package     OnTap_Merchandiser
 * @copyright   Copyright (c) 2014 On Tap Networks Ltd. (http://www.ontapgroup.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<fieldset>
    <div class="col-1">
        <table class="merchandiser-hint-table">
            <tr>
                <td><img src="http://www.ontapgroup.com/logos/mer_21.png" /></td>
                <td>&nbsp;</td>
                <td>
                    <h3>Visual Merchandiser <?php echo Mage::helper('merchandiser')->getExtensionVersion() ?></h3>
                    <?php $link = "http://www.ontapgroup.com/magento/customer/account"; ?>
                    <p><?php echo Mage::helper('merchandiser')->__("For support, visit <a href='%s' target='_blank'>%s</a>, login and then raise a Support Ticket." , $link, $link) ?></p>
                </td>
            </tr>
        </table>
    </div>
</fieldset>