<?php
	$totalPageSizeItem = $this->getPurchaseOrderCollection()->getLastPageNumber();
?>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl('js'); ?>jquery/jquery.cookie.js"></script>
<div class="cart-mt">
   <fieldset>
   <?php if($this->getPurchaseOrderCollection()->getSize()>0):?>
	   <div id="purchase-history">
	        <div class="box-content">
				 <table id="purchase-item-table" class="data-table cart-table">
	                <?php 
		                $storeList = array();
		                $stores = Mage::app()->getStores();
		                $storeColorConfig = Mage::helper('myaccount')->getStoreColorConfig();
		                foreach ($stores as $store) {
		                	$storeList[$store->getId()] = $store->getName();
		                }
	                ?>
	             	<tbody>
			            <?php echo $this->getChildHtml('purchased_items_list')?>
			        </tbody>
	             </table>
			</div>
	   </div>
     <?php else:?>
          <p class="no-purchase-itemundefined"><?php echo $this->__("You have no purchased item.")?></p>
     <?php endif;?>
  </fieldset>
</div>

<div style="width: 100%" class="mt-custom-popup-main mt-custom-popup-overlay">
	<div class="mt-custom-popup">
		<h2></h2>
		<a class="mt-popup-close" href="javascript:jQuery('.mt-custom-popup-main').removeClass('active');">&times;</a>
		<div class="mt-custom-content">
			<span id="myaccount-mt-loader-popup" class="please-wait-popup" style="display: none;">
	    		<img src="<?php echo $this->getSkinUrl('aw_ajaxcatalog/images/ajax-loader.gif')?>" alt="Loading next step..." title="Loading next step..." class="v-middle">
	    	</span>
	    	<div class="mt-data-load"></div>
		</div>
	</div>
</div>



<script>
var xhr = null;
var pageItem = 2;
var totalPageItem = <?php echo $totalPageSizeItem?>;
jQuery(function($){
	$('#purchase-history .box-content').bind('scroll', function(){
		if($(this).scrollTop() + $(this).innerHeight()>=$(this)[0].scrollHeight){
			if(pageItem<=totalPageItem){
				 if( xhr == null ) {
				    showLoadingFancybox();
				 	xhr =	jQuery.ajax({
				        url: '<?php echo Mage::getBaseUrl('web').'myaccount/index/getPurchasedItems';?>',
				        dataType : 'json',
						type : 'POST',
						data: {'page':pageItem,'limit':5,'m_store':'<?php echo $_GET['m_store']?>','m_sort':'<?php echo $_GET['m_sort']?>','view_type':'2'},
				        success: function(data) {
				        	jQuery('#purchase-item-table tbody').append(data.data.html);
				        	jQuery('.loader').css({"display":"none"});
				        	hideLoadingFancybox();
				        }
				    });
				 	xhr = null;
				 	pageItem ++;
				}
		    }else{
		    	hideLoadingFancybox();
		    }
		}
 	});
});



function reorderItem(event){
	var item_id = jQuery(event).attr('data-item-id');
	showLoadingFancybox();
	jQuery.ajax({
        url: '<?php echo Mage::getBaseUrl('web').'sales/order/reorderItemAjax';?>',
        dataType : 'json',
		type : 'POST',
		data: {'item_id':item_id},
        success: function(data) {
            if(data.success){

				jQuery('.mt-my-cart').html("");
	        	jQuery('.mt-my-cart').html(data.cart_html);
                
            	jQuery('html, body').animate({
                    scrollTop: 0
                }, 'fast');

            	jQuery('#ajax_cart_content').html(data.top_cart);
                jQuery('#just_added').slideDown(1000);
                jQuery('#topcart-popup').addClass('just_added');
                setTimeout(function() {
                    jQuery('#just_added').slideUp(1000);
                    jQuery('#topcart-popup').removeClass('just_added');
                }, 5000);
            }else{
                alert(data.message);
            }
        	hideLoadingFancybox();
        }
    });
}

function openTrackOrder(url){
	  var lastSlash = url.lastIndexOf(':');
	  var head = url.substring(0, lastSlash)+':';
	  var protocol = window.location.protocol;
	  url = url.replace(head, protocol);
	  jQuery('#mt-purchase-item-tab .mt-custom-popup-main .mt-custom-content .mt-data-load').html("");
	  jQuery('#myaccount-mt-loader-popup').show();
	  jQuery('#mt-purchase-item-tab .mt-custom-popup-main').addClass('active');
	  jQuery('#mt-purchase-item-tab .mt-custom-popup-main .mt-custom-content .mt-data-load').load(url, function(response, status, xhr) {
		  jQuery('#myaccount-mt-loader-popup').hide();	
		  jQuery('.tracking-table-popup').parent().find('.divider').remove();
		  jQuery('.tracking-table-popup tr td a').attr('target','_blank');	
	 }); 
}

</script>
