<?php ?>
<form id="co-delivery-method-form" action="">
    <div id="checkout-delivery-option-load">
       <!-- Content loaded dynamically -->
    </div>

    <div class="shipment-delivery-method">
    	<ul class="form-list">
    		<li class="control shipment-one" style="padding: 10px 0px 10px 10px;width: 100%;">
    			<input id="delivery-shipment-one" value="one_ship" type="radio" name="delivery[method]" checked="checked"  class="radio shipment-one" onclick="switchMethod(this);" />
    			<label class="para-normal">In one shipment - Ship all the items together once all items are available.</label>
    		</li>
    		<li class="control" style="padding: 10px 0px 10px 10px;width: 100%;">
    			<input id="delivery-shipment-two" value="two_ship" type="radio" name="delivery[method]" class="radio" onclick="switchMethod(this);" />
    			<label class="para-normal">In two shipments - Ship what is available today, then ship remaining item(s) once all are available. (Two shipping charges will be applied)</label>
    		</li>
    	</ul>
    </div>

    <div id="two-shipping-method-layout" style="display: none;">
    	<h2>Shipping Method for Second Shipment</h2>
    	<div class="input-box">
			<select id="select-delivery-shipment" class="form-control">
				<option value="1">Use same as above</option>
				<option value="2">Choose different method</option>
			</select>
    	</div>
    </div>

    <div id="shipping-method-two" style="display:none;">
    	<div id="delivery-shiping-option" >
    		<div id="checkout-step-shipping_method">
				<div id="checkout-shipping-method-load">
					<?php echo $this->getLayout()->createBlock('checkout/onepage_shipping_method_available')->setTemplate('checkout/onepage/shipping_method/available.phtml')->toHtml();?>
				</div>
				<div id="onepage-checkout-shipping-method-additional-load">
					<?php //echo $this->getLayout()->createBlock('checkout/onepage_shipping_method_additional')->setTemplate('checkout/onepage/shipping_method/additional.phtml')->toHtml();?>
				</div>
			</div>
		</div>
    </div>

    <script type="text/javascript">
    //<![CDATA[
        var Delivery = new Delivery('co-delivery-method-form', "<?php echo $this->getUrl('checkout/onepage/saveDeliveryOption') ?>");
    //]]>
    </script>

    <div class="buttons-set" id="delivery-option-buttons-container">
        <p class="back-link"><a href="#" onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="button" class="button dark-button next-button float-right" onclick="Delivery.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
        <span id="delivery-option-please-wait" class="please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
        </span>
    </div>
</form>


<script>
jQuery(document).ready(function(){
	jQuery('.shipment-delivery-method li').click(function(){
		//console.log(jQuery(this).find('input').attr('id'));
		jQuery('.shipment-delivery-method li').each(function(i){jQuery(this).find('input').removeAttr('checked')});
		jQuery(this).find('input').attr('checked',true);
		if(jQuery(this).find('input').hasClass('shipment-one')){
			jQuery('#two-shipping-method-layout').hide();
			jQuery('#shipping-method-two').hide();
		}else{
			jQuery('#two-shipping-method-layout').show();
		}
	});

	jQuery('#select-delivery-shipment').on('change',function(){
		if(jQuery(this).val()==2){
			jQuery('#shipping-method-two').show();
		}else{
			jQuery('#shipping-method-two').hide();
		}
	});
});

function switchMethod(that){
	console.log(that.id);
	jQuery(that).checked = true;
	if(jQuery(that).hasClass('shipment-one')){
		jQuery('#two-shipping-method-layout').hide();
		$j('#delivery-shiping-option').hide();
	}else{
		jQuery('#two-shipping-method-layout').show();
		$j('#delivery-shiping-option').show();
	}

}
</script>
