<?php
/**
 * @category    Wyomind
 * @package     Wyomind_Elasticsearch
 * @version     4.5.0
 * @copyright   Copyright (c) 2017 Wyomind (https://wyomind.net)
 */
/**
 * @var $this Wyomind_Elasticsearch_Block_Catalogsearch_Autocomplete
 */
?>

<?php $url = $this->getResultUrl(); ?>
<?php $url = substr($url, 0, strpos($url, "q=") + 2); ?>
<?php $url = preg_replace("/(.*)(\?SID=.*)(catalog.*)/", "\$1\$3", $url);?>
<div class="dropdown-arrow"><div class="arrow-outer"></div><div class="arrow-inner arrow-inner-label"></div></div>
<ul class="wyomind-elasticsearch">
    <li style="display:none;"></li>
    <?php if ($this->isNoResult() && !count($this->getSuggests())): ?>
        <li class="search-no-result"><a href="#"><?php echo $this->getLabel('No Result') ?></a></li>
    <?php else: ?>
        <?php if (count($this->getSuggests())): ?>
            <li class="title">Popular suggestions</li>
            <?php foreach ($this->getSuggests() as $suggest) : ?>
                <li class="search-suggestions"><a href='<?php echo $url . $suggest; ?>'/><?php echo $suggest; ?></a></li>
            <?php endforeach; ?>
        <?php endif; ?>

        <?php foreach ($this->getAllResults() as $_entity => $_results): ?>
            <?php if (count($_results)): ?>
                <li class="title search-product-title"><?php echo $this->getEntityTitle($_entity) ?></li>
                <?php foreach ($_results as $_result): /** @var Varien_Object $_entity */ ?>
                    <?php echo $this->getEntityHtml($_entity, $_result) ?>
                <?php endforeach; ?>
            <?php endif; ?>
        <?php endforeach; ?>
        <?php if (!$this->isNoResult()): ?>
            <a href="<?php echo $this->escapeUrl($this->getResultUrl()) ?>" class="all_results">
            <li class="all-results">
                    <?php echo $this->getAllResultsLabel() ?>
            </li>
            </a>
        <?php endif; ?>
    <?php endif; ?>
</ul>
