<div class="menu-top">
    <?php $collection = Mage::getModel('ecp_menu/menu')->getCollection()->setOrder('main_table.order','asc')->addFilter('status',1)->addOrder('"order"','asc')->setPageSize(3);?>
    <?php //$counter=0;?>
    <?php foreach ($collection as $item) {?>    
        <?php //if( $counter < 3 ){?> 
            <a class="level-top-submenu" href="<?php echo $item->getUrl();?>"> 
                <span><?php echo $this->__($item->getTitle());?></span>
            </a>
        <?php //}?> 
        <?php //$counter++;?>
    <?php }?>    
</div>