<div id="account-modal-wrapper" class="modal-wrapper">
	<?php echo $this->getChildHtml();?>

    <script type="text/javascript">
        if (typeof Allure == "undefined") {
             var Allure = {};
        }
        Allure.RegisterModelFormKey = '<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>';
        Allure.RegisterModelUrlAjax = '<?php echo Mage::getBaseUrl('web').'customers/account/createCustomer';?>';

        jQuery(document).ready(function(){
            var $body = jQuery('body'); 

            /* bind events */
            jQuery(document).on('focus', '#account-modal-wrapper input', function() {
                console.log('focus');
                $body.addClass('modal-popup-body');
            }).on('blur', '#account-modal-wrapper input', function() {
                console.log('blur');
                $body.removeClass('modal-popup-body');
            });
        });
    </script> 
</div>