<div id="openModal" class="popupLoginModel">
	<div>
	<form class="form-signin" method="post" id="popup-login-form">
		<div class="pop-title">
			<a href="#close" title="Close" class="close">X</a>
			<h2>Log In to Your Account</h2>
		</div>
		<div>
			<div class="form-group">
	 		    <label class="popup-login-lbl" for="email">Email Address</label>
	  		    <input id='username' type="text" name='username' class="ele_width form-control required-entry validate-email"/>
			</div>
			<div class="form-group">
	 		    <label class="popup-login-lbl" for="password">Password</label>
	  		    <input id='passwd' type="password" name='passwd' class="ele_width form-control required-entry"/>
			</div>
		</div>
		<div class="pop-link">
			<a>Forget Password</a>
			<span id="login-msg">&nbsp;</span>
			<button type="button" id="signin-btn-popup" class="button">Log In</button>
			<p>Don't have account with us? <a onclick="openRegisterModal()" >Create a new account</a></p>
		</div> 
	</form>
	</div>
</div>


<script type="text/javascript">


jQuery("#sign_in_label").on('click',function(){
	jQuery(".popupLoginModel").css({"opacity":"1","pointer-events":"auto"});
});

jQuery(".close").on('click',function(){console.log('hiee');
jQuery(".popupLoginModel").css({"opacity":"0","pointer-events":"none"});
	});

jQuery("#signin-btn-popup").on('click',function(){

	 var myForm = new VarienForm('popup-login-form', false); 
	 if(myForm.validator.validate()){ 
		var usrname = jQuery('#username').val();
		var passwd = jQuery('#passwd').val();

		var request = {
				"usrname":usrname,
				"passwd":passwd
				};
				
		jQuery.ajax({
		url : '<?php echo $this->getUrl('customers/account/ajaxLogin',array('_secure' => true));?>',
		dataType : 'json',
		type : 'POST',
		data: {request:request},
		success : function(data){
			if(data.success){
				 jQuery(".modalDialog").css({"opacity":"0","pointer-events":"none"});
				 location.reload();
			}else{
			 jQuery('#login-msg').html(data.error);
			}
			}
		});
	 } //End of form Validate

    });

 </script> 