<div id="openModal" class="popupResetPasswordModel">
    <div>
        <form class="form-resetpassword" method="post" id="popup-resetpassword-form">
            <div class="pop-title">
                <a href="#close" title="Close" class="close">X</a>
                <h2><?php echo $this->__("Retrive  password")?></h2>
            </div>
            <div class="body">
                <div id="resetpassword_msg_div">
                    <span id="resetpassword-msg"></span>
                </div>
                <div class="form-group">
                    <label class="popup-login-lbl" for="email"><?php echo $this->__("Email Address")?></label>
                    <input id='resetEmail' type="text" name='email' class="ele_width form-control required-entry validate-email"/>
                </div>
            </div>
            <div class="pop-link">
                <div class="submit-login">
                    <button type="button" id="reset_pass_btn" class="button"><?php echo $this->__("Submit")?></button>
                </div>
            </div>
        </form>
    </div>
</div>


<script type="text/javascript">
    function openRestPasswordModal(){
        jQuery(".popupLoginModel").css({"opacity":"0","pointer-events":"none"});
        jQuery(".popupRegisterModel").css({"opacity":"0","pointer-events":"none"});
        jQuery(".popupResetPasswordModel").css({"opacity":"1","pointer-events":"auto"});
    };


    jQuery(".close").on('click',function(){console.log('hiee');
        jQuery(".popupResetPasswordModel").css({"opacity":"0","pointer-events":"none"});
    });

    jQuery("#reset_pass_btn").on('click',function(){

        var myForm = new VarienForm('popup-resetpassword-form', true);
        if(myForm.validator.validate()){
            var email = jQuery('#resetEmail').val();

            var key='<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>';
            var request = {
                "email":email,
                'form_key':key
            };
            jQuery.ajax({
                url : '<?php echo $this->getUrl('customers/account/forgotPasswordPost',array('_secure' => true));?>',
                dataType : 'json',
                type : 'POST',
                data: {request:request},
                success : function(data){
                    if(data.success){
                        jQuery('#login_msg_div').css('display','block');
                        jQuery('#resetpassword-msg').html(data.msg);
                        setTimeout(function(){
                            jQuery(".modalDialog").css({"opacity":"0","pointer-events":"none"});
                            location.reload();
                        }, 5000);

                    }else{
                        jQuery('#resetpassword_msg_div').css('display','block');
                        jQuery('#login-msg').html(data.msg);
                    }
                }
            });
        } //End of form Validate

    });
</script>