<div id="openModal" class="popupResetPasswordModel">
    <div id="resetpassword-modal-container" class="modal-container">
        <form class="form-resetpassword" method="post" id="popup-resetpassword-form">
            <div class="pop-title">
                <a href="#close" title="Close" class="close">X</a>
                <h2><?php echo $this->__("Retrieve  password")?></h2>
            </div>
            <div class="pop-content">
                <div id="resetpassword_msg_div">
                    <span id="resetpassword-msg"></span>
                </div>
                <div class="form-group">
                    <label class="popup-login-lbl" for="email"><?php echo $this->__("Email Address")?></label>
                    <input id='resetEmail' type="text" name='email' class="ele_width form-control required-entry validate-email"/>
                </div>
            </div>
            <div class="pop-link">
                <div class="submit-login">
                    <button type="button" id="reset_pass_btn" class="button"><?php echo $this->__("Submit")?></button>
                </div>
            </div>
        </form>
    </div>
    <script type="text/javascript">
        if (typeof Allure == "undefined") {
             var Allure = {};
        }
        Allure.ResetPassFormKey = '<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>';
        Allure.ResetPassUrlAjax = '<?php echo Mage::getBaseUrl('web').'customers/account/forgotPasswordPost';?>';
    </script>
</div>