
<?php echo $this->getChildHtml('checkout.onepage.login.extra')?>
<div class="col-md-12">

	<div class="col-1">
	
        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
        <form id="login-form" action="<?php echo $this->getPostAction() ?>" method="post">
        <fieldset>
            <?php echo $this->getBlockHtml('formkey'); ?>
            <?php if(0):?>
            <h4><?php echo $this->__('Already registered?') ?></h4>
            <p><?php echo $this->__('Please log in below:') ?></p>
             <?php endif;?>
            <ul class="form-list">
                <li class="persistent-email">
                    <label for="login-email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                    <div class="input-box">
                        <input type="text" class="input-text required-entry validate-email" id="login-email" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" />
                    </div>
                </li>
                <li>
                    <label for="login-password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                    <div class="input-box">
                        <input type="password" class="input-text required-entry" id="login-password" name="login[password]" />
                    </div>
                </li>
                
                <li class="note">
                	<a href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>?footerLinkMenu=1" id="fancybox-forgotpwd" class="fancybox.ajax forgotpwd f-left">Forgot your password?</a>
                </li>
                
                <li class="buttons-set">
		            <span class="required"><?php echo $this->__('* Required Fields') ?></span>
		            <button type="submit" class="button" onclick="onepageLogin(this)"><span><span><?php echo $this->__('Sign In') ?></span></span></button>
		        </li>
                <?php echo $this->getChildHtml('form.additional.info'); ?>
            </ul>
        </fieldset>
        </form>
    </div>
	
    <?php echo $this->getChildHtml('login_before')?>
    <div class="col-2">
    	<div class="row">
    		<div class="step-title">
        		<h2><?php echo $this->__('New Customers')?></h2>
        	</div>
        	
        <div class="col-md-12 sub-step facebook-checkout-login">
	    <?php if(0):?>
	        <h3><?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?><?php echo $this->__('Checkout by login to your account or Register') ?><?php else: ?><?php echo $this->__('Register to Create an Account') ?><?php endif; ?></h3>
	    <?php endif; ?>
	    
	    
	    <?php if (Mage::helper('core')->isModuleEnabled('Allure_GoogleConnect')):?>
    	<?php echo $this->getChildHtml('allure_googleconnect_checkout')?>
    	<?php endif;?>
	    
        <?php echo $this->getChildHtml('col1_before')?>
        
        <div class="facebook-login-checkout">            
     	<?php echo $this->getChildHtml('facebook_login_checkout')?>
	 	</div>
	 	
	 	<br />
		<p class="facebook-connect-p-or"><strong>- <?php echo $this->__('OR'); ?> -</strong></p>
		<br />

        <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
            <p><?php echo $this->__('Register with us for future convenience:') ?></p>
        <?php else: ?>
            <p><strong><?php echo $this->__('Register and save time!') ?></strong><br />
            <?php echo $this->__('Register with us for future convenience:') ?></p>
            <ul>
                <li><?php echo $this->__('Fast and easy check out') ?></li>
                <li><?php echo $this->__('Easy access to your order history and status') ?></li>
            </ul>
        <?php endif; ?>
        <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
            <ul class="form-list">
                <?php if(false && $this->getQuote()->isAllowedGuestCheckout() ): ?>
                <li class="control">
                    <input type="radio" name="checkout_method" id="login:guest" value="guest"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_GUEST): ?> checked="checked"<?php endif; ?> class="radio" /><label for="login:guest"><?php echo $this->__('Checkout as Guest') ?></label>
                </li>
                <?php endif; ?>
                <li class="control">
                    <input type="radio" name="checkout_method" id="login:register" value="register"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_REGISTER || !$this->getQuote()->isAllowedGuestCheckout()): ?> checked="checked"<?php endif ?> class="radio" /><label for="login:register"><?php echo $this->__('Register') ?></label>
                </li>
                
                <li class="buttons-set">
		            <p class="required">&nbsp;</p>
		
		            <?php if ($this->getQuote()->isAllowedGuestCheckout()): ?>
		                <button id="onepage-guest-register-button" type="button" class="button" onclick="checkout.setMethod();"><span><span><?php echo $this->__('Continue') ?></span></span></button>
		            <?php elseif ($this->helper('checkout')->isCustomerMustBeLogged()): ?>
		                <button id="onepage-guest-register-button" type="button" class="button" onclick="window.location='<?php echo $this->helper('checkout/url')->getRegistrationUrl();?>'"><span><span><?php echo $this->__('Register') ?></span></span></button>
		            <?php else: ?>
		                <button type="button" class="button" onclick="checkout.setMethod();"><span><span><?php echo ($this->getQuote()->isAllowedGuestCheckout() ? $this->__('Continue') : $this->__('Register')) ?></span></span></button>
		            <?php endif; ?>
      			 </li>
                
            </ul>
            <!--
            <h4><?php echo $this->__('Register and save time!') ?></h4>
            <p><?php echo $this->__('Register with us for future convenience:') ?></p>
            <ul class="ul">
                <li><?php echo $this->__('Fast and easy check out') ?></li>
                <li><?php echo $this->__('Easy access to your order history and status') ?></li>
            </ul>
            -->

        <?php else: ?>
            <input type="hidden" name="checkout_method" id="login:register" value="register" checked="checked" />
        <?php endif; ?>
    		</div>
    	</div>
    </div>
    
</div>


<script type="text/javascript">
//<![CDATA[
    var loginForm = new VarienForm('login-form', true);
    $('login-email').observe('keypress', bindLoginPost);
    $('login-password').observe('keypress', bindLoginPost);
    function bindLoginPost(evt){
        if (evt.keyCode == Event.KEY_RETURN) {
            loginForm.submit();
        }
    }
    function onepageLogin(button)
    {
        if(loginForm.validator && loginForm.validator.validate()){
            button.disabled = true;
            loginForm.submit();
        }
    }
//]]>
    jQuery.noConflict();
    jQuery('#fancybox-forgotpwd').fancybox({
		'width': 125
	});
</script>
