<?php
/**
 * nordstorm popup
 */
?>

<div id="appointments-popup-wrapper">
    <?php echo $this->getChildHtml("appointments_popup_top");?>
    <?php echo $this->getChildHtml("appointments_popup_menu");?>
    <?php echo $this->getChildHtml("appointments_popup_register");?>
    <?php echo $this->getChildHtml("appointments_popup_pickdatetime");?>
    <?php echo $this->getChildHtml("appointments_popup_register_end");?>
    <?php echo $this->getChildHtml("appointments_popup_faq");?>
    <?php echo $this->getChildHtml("appointments_popup_footer");?>
</div>

<script type="text/javascript">
    if (typeof Allure == "undefined") {
        var Allure = {};
    }
    Allure.appointmentId = '<?php echo $this->getRequest()->getParam('id')?>';
    //console.log(Allure.appointmentId);
    Allure.ajaxGetTimeUrl = '<?php echo $this->getTimeActionUrl()?>';
    Allure.ajaxGetWorkingDaysUrl = '<?php echo $this->getWorkingDaysActionUrl()?>';
    Allure.getSupportDetailsActionUrl = '<?php echo $this->getSupportDetailsActionUrl()?>';

    function formatDate(date) {
        var monthNames = [
            "Jan", "Feb", "Mar",
            "Apr", "May", "Jun", "Jul",
            "Aug", "Sep", "Oct",
            "Nov", "Dec"
        ];

        var day = date.getDate();
        var monthIndex = date.getMonth();
        var year = date.getFullYear();

        return monthNames[monthIndex] + ' ' +  day + ', ' + year;
    }
</script>

<script type="text/javascript">
        var appointmentForm = new VarienForm('appointemnet_form');

        Allure.UtilPath = "<?= Mage::getDesign()->getSkinUrl(); ?>js/phone_validation/utils.js";

        //initialize itel tel input
        var input = document.querySelector("#phonenumber")
        var iti = window.intlTelInput(input, {
            autoFormat: false,
            autoHideDialCode: false,
            autoPlaceholder: false,
            nationalMode: false,
            utilsScript: Allure.UtilPath
        });

        // take phone number and check if it exist
        // if it does not exist then
        // first check if we can get Geo Location based Country Code if its there then set it
        // otherwise set default as country as 'us'
        // Magento module - Allure/GeoLocation
        var phone = "<?php if($f_telephone):echo $f_telephone;else:echo $telephone;endif;?>";
        //console.log('[signing_register.phtml] length',phone.length)
        if(phone.length <= 0){
            var country_code = "<?= Mage::getSingleton('allure_geolocation/geoLocation')->getCountryCode();?>";

            if (country_code == undefined || country_code == null || country_code == "") {
                country_code = "us"
            }

            iti.setCountry(country_code.toLowerCase());
        } else if (phone.charAt(0) != '+') {

            <?php if ((isset($f_cntry) && !empty($f_cntry))) { ?>
            var country_code = '<?php echo $f_cntry;?>';
            iti.setCountry(country_code.toLowerCase());
            <?php } ?>

            <?php if ((isset($cntry) && !empty($cntry))) { ?>
            var country_code = '<?php echo $cntry;?>';
            iti.setCountry(country_code.toLowerCase());
            <?php } ?>
        }

        //custom validator for itel tel input
        //FileName - intel-tel-validation.js
        allureIntlTelValidate(jQuery("#phonenumber"),iti);
</script>
