<!--FOOTER SECTION START-->
<div id="footer" class="container-fluid">
    <div class="footer">
        <div class="container">
            <div class="row footer-links hidden-xs">
              <div class="col-12 links-section">
                <div class="row justify-content-center">
                  <div class="footer-redirections">
                    <a class="footer-subtitle-small translate-popup" href="#top" id="footer-link-top"><?php echo $this->__('POP UP INFORMATION')?></a>
                  </div>
                  <div class="footer-redirections">
                    <a class="footer-subtitle-small translate-popup" href="#booking" id="footer-link-booking"><?php echo $this->__('BOOKING & PRICING')?></a>
                  </div>
                  <div class="footer-redirections">
                    <a class="footer-subtitle-small translate-popup" href="#about-maria" id="footer-link-about"><?php echo $this->__('ABOUT MARIA TASH')?></a>
                  </div>
                  <div class="footer-redirections">
                    <a class="footer-subtitle-small translate-popup" href="#faq" id="footer-link-profiles">FAQ</a>
                  </div>
                  <div class="footer-redirections mr-0">
                    <a target="_blank" class="footer-subtitle-small" href="https://www.mariatash.com/" id="footer-link-main">MARIATASH.COM</a>
                  </div>
                </div>
              </div>
              <div class="footer-frm col-12">
  <!--                <form action="--><?php //echo $this->getSubscribeUrl()?><!--" method="post" id="appointemnet_form">-->
                  <div class="row justify-content-center">
                      <div class="col-md-12 form-group m-0">
                          <p class="footer-subtitle-medium text-center translate-popup"><?php echo $this->__('Sign Up for Our Newsletter')?></p>
                      </div>
                      <div class="col-12">
                        <div class="row justify-content-center form-section ml-0">
                          <div class="col-lg-8 col-md-8 form-group text-right">
                              <input class="input-box translate-popup" type="email" name="subscribe_email" id="subscribe_email" placeholder="<?php echo $this->__('Email')?>">
                          </div>
                          <div class="col-lg-4 col-md-2 form-group px-0">
                              <div class="btnSub">
                                  <button id="btnSubscribe" class="input-box btn translate-popup"  type="submit" onclick="subscribe()"><?php echo $this->__('sign up')?></button>
                              </div>
                          </div>
                      </div>
                    </div>
                  </div>
              </div>
              <div class="col-md-12">
                <div class="row justify-content-center">
                    <a id="footer-top-link" href="#top"  class="link-top" >
                        <img src="<?php echo $this->getSkinUrl("images/allure/popup/popup-down-arrow-wt.png")?>" class="down-arrow-size " >
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
<!--FOOTER SECTION END-->
<!--LOADER-->
<div id='loadingmessage' class="overlay">
    <img src="<?php echo $this->getSkinUrl('images/allure/popup/white-spinner.gif')?>"/>
</div>
<script type="text/javascript">
    jQuery("a.nav-link,a.footer-subtitle-small,a.link-down,#btnBookTop a,#btnBookBottom a").click(function(e) {
        var targetElement = jQuery(jQuery(this).attr('href'));
        jQuery('html, body').animate({
            scrollTop: targetElement.offset().top - jQuery('.navbar').outerHeight()
        }, 1000);

        if (jQuery(window).outerWidth() <= 767) {
            jQuery('ul#navbar-menu').hide();
        }
    });

    jQuery("a.link-top").click(function(e) {
        jQuery('html, body').animate({
            scrollTop: 0
        }, 1000);
    });

    jQuery('.navbar-toggler').click(function() {
        console.log(jQuery(this).attr('aria-expanded'));
        if (jQuery(this).attr('aria-expanded')  == undefined || jQuery(this).attr('aria-expanded') == false || jQuery(this).attr('aria-expanded') == 'false') {
            jQuery('body').addClass('navbar-active');
        } else {
            jQuery('body').removeClass('navbar-active');
        }
    });


</script>
<!--Subscribe Mailing List Jquery-->
<script>
    var subscribeUrl ="<?php echo $this->getSubscribeUrl();?>" ;
    function subscribe() {

        var  email= jQuery('#subscribe_email').val();

        if (!ValidateEmail(email)) {
            alert('Please Enter Valid Email Id');
        }
        else {
            jQuery.ajax({
                url: subscribeUrl,
                // dataType: 'json',
                type: 'POST',
                data: {'email': email},
                success: function (response) {
                    response=JSON.parse(response);
                    console.log(response.msg);
                    if (response.status != "OK") {
                        alert(response.msg);
                        jQuery('#subscribe_email').val('');
                    }
                    else {
                       alert(response.msg);
                        jQuery('#subscribe_email').val('');
                    }

                },
            });
        }
    }
</script>

<script>
    function ValidateEmail(mail)
    {
        var mailformat = /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/;
        if(mailformat.match(mail))
        {
            return (true)
        }

        return (false)
    }
</script>
