
<!--FOOTER SECTION START-->
<div class="container-fluid">
    <div class="footer">
        <div class="container">
            <div class="footer-frm">
                <div class="row">
                    <div class="col-md-4">
                        <p class="footer-subtitle-medium">SIGN UP FOR OUR NEWSLETTER</p>
                    </div>
                    <div class="col-md-4">
                        <input class="input-box" type="text" name="subscribe_email" id="subscribe_email" placeholder="EMAIL">
                    </div>
                    <div class="col-md-4">
                        <div class="btnSub">
                            <button  id="btnSubscribe" class="input-box btn"  type="submit">sign up</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row footer-links">
                <div class="col-md-4">
                    <div class="row ">
                        <a class="footer-subtitle-small" href="#top" id="footer-link-top">POP UP INFORMATION</a>
                    </div>
                    <div class="row">
                        <a class="footer-subtitle-small" href="#booking" id="footer-link-booking">BOOKING & PERCING</a>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="row">
                        <a class="footer-subtitle-small" href="#about-maria-nav" id="footer-link-about">ABOUT MARIA TASH</a>
                    </div>
                    <div class="row">
                        <a class="footer-subtitle-small" href="#" id="footer-link-profiles">PIERCER PROFILES</a>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="row">
                        <a class="footer-subtitle-small" target="_blank" href="https://www.mariatash.com/" id="footer-link-main">POP UP INFORMATION</a>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
<!--FOOTER SECTION END-->

<script>
    jQuery("#top-nav").click(function() {
        jQuery('html, body').animate({
            scrollTop: jQuery("#top").offset().top
        }, 1000);
    });

    jQuery("#booking-nav").click(function() {
        jQuery('html, body').animate({
            scrollTop: jQuery("#booking").offset().top
        }, 1000);
    });
    jQuery("#about-maria-nav").click(function() {
        jQuery('html, body').animate({
            scrollTop: jQuery("#about-maria").offset().top
        }, 1000);
    });
    jQuery("#about-maria-arrow").click(function() {
        console.log('IN about maria');
        jQuery('html, body').animate({
            scrollTop: jQuery("#about-maria").offset().top
        }, 1000);
    });
    jQuery("#faq-nav").click(function() {
        jQuery('html, body').animate({
            scrollTop: jQuery("#faq").offset().top
        }, 1000);
    });
    jQuery("#faq-arrow").click(function() {
        jQuery('html, body').animate({
            scrollTop: jQuery("#faq").offset().top
        }, 1000);
    });
    jQuery("#booking-dwn").click(function() {
        jQuery('html, body').animate({
            scrollTop: jQuery("#booking").offset().top
        }, 1000);
    });
    jQuery("#btnBooking").click(function() {
        jQuery('html, body').animate({
            scrollTop: jQuery("#booking").offset().top
        }, 1000);
    });

</script>
