<!--MENU BAR-->
<nav id="navbar" class="navbar navbar-expand-sm bg-dark navbar-dark mt-bg sticky-top navbar-toggleable-sm nav-dropdown-sm">
    <a class="navbar-brand" href="#top">MARIA TASH</a>
    <a id="navbar-icon" class="navbar-toggler navbar-close pull-xs-right" href="#navbar-menu" data-toggle="collapse" data-target="#navbar-menu" area-expanded="false">
        <i class="fa fa-bars"></i>
        <i class="fa fa-close"></i>
    </a>
    <ul id="navbar-menu" class="collapse navbar-nav nav-dropdown pull-xs-right">
        <li class="nav-item">
            <a class="nav-link" href="#top" id="top-nav">POP-UP INFO</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#booking" id="booking-nav">BOOKING & PRICING</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#about-maria" id="about-maria-nav">ABOUT MARIA TASH</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#faq" id="faq-nav">FAQ</a>
        </li>
    </ul>
</nav>
<!--END OF MENU BAR-->
