<!--MENU BAR-->
<a href="#navbar-menu" id="navbar-icon" class="navbar-toggler pull-xs-right hidden-md-up" data-toggle="collapse" data-target="#navbar-menu" aria-expanded="false">
    <i class="fa fa-bars"></i>
</a>
<nav id="navbar-menu" class="collapse navbar-expand-sm mt-bg navbar-dark sticky-top pull-xs-right nav navbar-toggleable-sm nav-dropdown-sm">
    <a class="navbar-toggler navbar-close" href="#navbar-menu" data-toggle="collapse" data-target="#navbar-menu">
        <i class="fa fa-close"></i>
    </a>
    <a class="navbar-brand" href="#top">MARIA TASH</a>
    <ul class="navbar navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="#top" id="top-nav">POP-UP INFO</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#booking" id="booking-nav">BOOKING & PRICING</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#about-maria" id="about-maria-nav">ABOUT MARIA TASH</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#faq" id="faq-nav">FAQ</a>
        </li>
    </ul>
</nav>
<!--END OF MENU BAR-->
