<?php
//To modify the appointment get the data from registry start
$fetch_model = Mage::registry('apt_modify_data');

if($fetch_model){

    $f_pickurday = $fetch_model->getAppointmentStart();
    $timestamp = strtotime($f_pickurday);
    $fetch_date = date('m/d/Y', $timestamp);
}
//To get the ajax call block
$workingdays = $this->getData("workingdays");
$workingdaysArray=json_decode($workingdays);

//$arr = array('11-01-2012', '01-01-2014', '01-01-2015', '09-02-2013', '01-01-2013');
function date_sort($a, $b) {
    return strtotime($a) - strtotime($b);
}
usort($workingdaysArray, "date_sort");
//print_r($workingdaysArray);

if (!$fetch_date){
    //   $dateCurrent=Mage::getModel('core/date')->date('m/d/Y');
    foreach ($workingdaysArray as $value){
        if($dateCurrent<=$value){
            $fetch_date =$value ;
            break;
        }
    }
}
?>
<input name="date" id="appointment_date" type="text" class="input-box required-entry">

<script type="text/javascript">
    var currentDate = new Date();
    var currentDateString = currentDate.getMonth()+'/'+currentDate.getDate()+'/'+currentDate.getYear();

    jQuery("#appointment_date").val(currentDateString);

    jQuery('#appointment_date').datepicker({
        startDate: currentDateString,
        endDate: '',
        datesDisabled: ['04/02/2019','03/22/2019']
    }).on('changeDate', function(e) {
        // `e` here contains the extra attributes
        console.log(jQuery(this).val())
        loadSlotAvailability(jQuery(this).val());
    });;
</script>

<?php return; ?>

<!--<strong id="availablewdays" data-original='--><?php //echo $workingdays;?><!--'></strong>-->

<input  name="app_date"  class="input-box"  id="datepicker-13_hidden"  value="<?php if($fetch_date):echo $fetch_date;endif;?>" />

<script>
    //Pick ur day updated with custom calendar code
    jQuery('#datepicker-13_hidden').dcalendarpicker();
</script>
<script>
    var date=new Date();
    var val=(date.getMonth()+1)+"/"+date.getDate()+"/"+date.getFullYear();
    document.getElementById("appointment_date").value = val;
</script>
