<?php
//To modify the appointment get the data from registry start
$fetch_model = Mage::registry('apt_modify_data');;

if ($fetch_model) {

    $f_pickurday = $fetch_model->getAppointmentStart();
    $timestamp = strtotime($f_pickurday);
    $fetch_date = date('d M Y', $timestamp);

}

?>

<input name="app_date" id="appointment_date" type="text" class="input-box required-entry"
       value="<?php if ($fetch_date):echo $fetch_date;endif; ?>">

<script type="text/javascript">
    slots = '<?=json_encode((Mage::getModel("appointments/slots"))::SLOTS)?>';
    Allure.getAvlblSlotsUrl = '<?php echo $this->getUrl('*/popup/getAvailableSlots', array('_secure' => true)) ?>';
    var getWorkingDaysUrl = "<?php echo $this->getWorkingDaysActionUrl();?>";
    var storeid ='<?= $this->getStoreId() ?>';
    var workingDays = loadWorkingDays(getWorkingDaysUrl, storeid);
    var datesAvailable = workingDays['dates'];
    var currentDateString=workingDays['today'];

    <?php if(empty($fetch_date)):?>
    jQuery("#appointment_date").val(currentDateString);
    <?php endif;?>

    jQuery.fn.datepicker.dates['en'] = {
        ...jQuery.fn.datepicker.dates['en'],
        daysMin: ["S", "M", "T", "W", "T", "F", "S", "S"],
        titleFormat: 'MM'
    };

    jQuery('#appointment_date').datepicker({
        format:'d  M  yyyy',
        startDate: currentDateString,
        endDate: '',
        beforeShowDay: function (date) {
            var enabled = false;
            var currentDate = parseInt(1 + date.getMonth()).pad(2) + '/' + date.getDate().pad(2) + '/' + date.getFullYear();

            if (datesAvailable.indexOf(currentDate) != -1) {
                enabled = true;
            }
            return {
                enabled: enabled
            }
        }
    }).on('changeDate', function (e) {
        getAvailableSlots();
    });

    jQuery(document).ready(function () {
        calculateTime();
    });


</script>

