<div id="datetime-box" class="datetime-box form-group col-md-12">
    <div class="row">
        <div class="date-box col-md-6 col-6" id="pick_ur_date_div">
            <?php echo $this->getChildHtml("appointments_popup_pickdate");?>
        </div>
        <div class="time-box col-md-6 col-6" id="pick_ur_time_div">
            <?php echo $this->getChildHtml("appointments_popup_picktime");?>
        </div>
    </div>
</div>
