<div id="price-list" class="col-md-12">
    <a id="icon-price-close" class="navbar-toggler navbar-close" href="#price-list" data-target="#price-list">
        <i class="fa fa-close" style="font-size: 30px"></i>
    </a>
    <?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('nordstrom-price-list')->toHtml();?>
    <div class="mt-0">
        <p class="xpaces translate-popup">Price List</p>

        <div class="">

            <table class="table">
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Earlobe</span> ...</span>
                        <span class="jewelry"><span class="translate-popup">jewelry starts at</span> 120.00 €</span></td>
                    <td class="td-price">€30</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Helix</span> ...</span>
                        <span class="jewelry"><span class="translate-popup">jewelry starts at</span> 120.00 €</span></td>
                    <td class="td-price">€35</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe">Forward Helix ...</span>
                        <span class="jewelry"><span class="translate-popup">jewelry starts at</span> 120.00 €</span></td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe">Tash Rook ...</span>
                        <span class="jewelry"><span class="translate-popup">jewelry starts at</span> 120.00 €</span></td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe">Rook ...</span>
                        <span class="jewelry"><span class="translate-popup">jewelry starts at</span> 120.00 €</span></td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe">Tragus ...</span>
                        <span class="jewelry"><span class="translate-popup">jewelry starts at</span> 120.00 €</span></td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe">Anti-Tragus ...</span>
                        <span class="jewelry"><span class="translate-popup">jewelry starts at</span> 295.00 €</span></td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe">Conch ...</span>
                        <span class="jewelry"><span class="translate-popup">jewelry starts at</span> 120.00 €</span></td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe">Daith ...</span>
                        <span class="jewelry"><span class="translate-popup">jewelry starts at</span> 125.00 €</span></td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Nostril</span> ...</span>
                        <span class="jewelry"><span class="translate-popup">jewelry starts at</span> 120.00 €</span></td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe">Septum ...</span>
                        <span class="jewelry"><span class="translate-popup">jewelry starts at</span> 95.00 €</span></td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Nipple</span> ...</span>
                        <span class="jewelry"><span class="translate-popup">jewelry starts at</span> 295.00 €</span></td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Navel</span> ...</span>
                        <span class="jewelry"><span class="translate-popup">jewelry starts at</span> 270.00 €</span></td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Dermal</span> ...</span>
                        <span class="jewelry"><span class="translate-popup">jewelry starts at</span> 55.00 €</span></td>
                    <td class="td-price">€80</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Eyebrow</span> ...</span>
                        <span class="jewelry"><span class="translate-popup">jewelry starts at</span> 125.00 €</span></td>
                    <td class="td-price">€45</td>
                </tr>
            </table>

        </div>

    </div>
</div>
