<?php
$storeId = Mage::helper('appointments')->getStoreId();
?>
<?php
$model = Mage::registry('apt_modify_data');
if($model){
    $fetch_aptId = $model->getId();
    $f_firstName = $model->getFirstname();
    $f_lastName = $model->getLastname();
    $f_email = $model->getEmail();
    $f_telephone = $model->getPhone();
    $f_notification_pref = $model->getNotificationPref();
    $fetch_piercing_qty = $model->getPiercingQty();
    $fetch_piercing_loc = $model->getPiercingLoc();
}

?>
<!--BOOKING SECTION-->

<link href="<?php echo $this->getSkinUrl('css/contact/intlTelInput.css');?>"  rel="stylesheet" />
<script src="<?php echo $this->getSkinUrl('js/contact/intlTelInput.min.js');?>"></script>
<script src="<?php echo $this->getSkinUrl('js/contact/intlTelInput.js');?>"></script>
<style>
    .intl-tel-input.allow-dropdown{
        margin-top: 20px;
    }
</style>
<div id="booking" class="container-fluid booking nopad">
    <div class="container nopad">
        <div class="row">
            <div class="col-md-6" id="booking-wrapper">
                <div class="booking-box">
                    <p class="xpaces">BOOK YOUR APPOINTMENT</p>

                    <form class="col-md-12 appointment-input-box" action="<?php echo $this->getActionUrl()?>" method="post" id="appointemnet_form">
                        <?php if($fetch_aptId):?> <input type="hidden" name="id" value="<?php echo $fetch_aptId;?>"><?php endif;?>
                        <input type="hidden" name="store_id" id="store_id" value="24">

                        <div class="name-box">
                            <input class="input-box required-entry" type="text" name="firstname" id="firstname" placeholder="FIRST NAME" value="<?php if($f_firstName):echo $f_firstName;else: echo $firstName; endif;?>"required>

                            <input class="input-box required-entry" type="text" name="lastname" id="lastname" placeholder="LAST NAME" value="<?php if($f_lastName): echo $f_lastName;else:echo $lastName;endif;?>" required>
                        </div>

                        <input class="input-box required-entry"  type="email" name="email" id="email" placeholder="EMAIL" value="<?php if($f_email):echo $f_email;else:echo $email;endif;?>" required>


                        <input class="input-box required-entry validate-intl-telephone" type="text" name="phone" id="phonenumber" placeholder="PHONE NUMBER" value="<?php if($f_telephone):echo $f_telephone;else:echo $telephone;endif;?>" required>

                        <p class="label notify-label">I would like to be notified by:</p>
                        <div class="box notify-box">
                            <p class="label">
                                <input type="checkbox" id="c1" name="noti_email">
                                <label class="label" for="c1">Email</label>
                            </p >
                            <p class="label">
                                <input type="checkbox" id="c2" name="noti_sms">
                                <label class="label" for="c2">Text Message</label>
                            </p>
                        </div>

                        <div class="box people">
                            <div class="people-wrapper">
                                <label class="label">Number of people in your party:</label>
                                <div class="peoplediv">
                                    <input type="button" value="-" class="minus-btn" onclick="decreaseQty();" >
                                    <?php if($fetch_piercing_qty):?>
                                        <input size="5" class="input-box" value="<?php echo $fetch_piercing_qty;?>" type="text" name="piercing_qty" id="count" readonly >
                                    <?php else:?>
                                    <input size="5" class="input-box"  value="1" type="text" name="piercing_qty" id="count"  readonly >
                                    <?php endif;?>
                                    <input type="button" value="+" class="plus-btn" onclick="increaseQty();" >
                                </div>
                            </div>
                        </div>
