<div class="btn-div">
    <button class="input-box btn"  type="submit">CONFIRM</button>
</div>

</form>
</div>
</div>
<!--PIERCING LIST STATIC BLOCK Will Appear Here-->
<?php
echo $this->getLayout()->createBlock('cms/block')->setBlockId('nordstrom-price-list')->toHtml();
?>

</div>
</div>
<a id="about-maria-arrow" href="#about-maria"  class="down-arrowfrm" >
    <img src="<?php echo $this->getSkinUrl("images/allure/popup/down.png")?>" class="down-arrow-size " >
</a>
</div>

<!--END OF BOOKING SECTION-->


<?php
//FAQ STATIC BLOCK
echo $this->getLayout()->createBlock('cms/block')->setBlockId('nordstrom-about-maria')->toHtml();
?>
