<?php
$model = Mage::getSingleton("core/session")->getData('appointment_submitted');
Mage::getSingleton("core/session")->setData('appointment_submitted',false);
?>
<div class="modal fade bd-example-modal-lg modal-confirm-appointment" tabindex="-1" role="dialog" aria-labelledby="modalConfirmAppointment" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title detailofapt" id="exampleModalLongTitle"><?php echo $this->__('Appointment Details') ?></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id="popupConfirmAppointment" class="modal-body">
                <div id="wrapperConfirmAppointment" class="row">
                    <div class="checkout-success col-md-12">
                        <div class="success-field row">
                            <span class="apt-summary col-md-6"><?php echo $this->__('Name') ?></span>
                            <span class="apt-summary col-md-6" ><?php echo $model->getFirstname()." ".$model->getLastname() ?></span>
                        </div>
                        <div class="success-field row">
                            <span class="apt-summary col-md-6"><?php echo $this->__('Email') ?></span>
                            <span class="apt-summary col-md-6" style="font-weight: bold"><?php echo $model->getEmail() ?></span>
                        </div>
                        <div class="success-field row">
                            <span class="apt-summary col-md-6"><?php echo $this->__('Phone') ?></span>
                            <span class="apt-summary col-md-6" ><?php echo $model->getPhone() ?></span>
                        </div>
                        <div class="success-field row">
                            <span class="apt-summary col-md-6"><?php echo $this->__('No of People in Group') ?></span>
                            <span class="apt-summary col-md-6" ><?php echo $model->getPiercingQty() ?></span>
                        </div>
                        <div class="success-field row">
                            <span class="apt-summary col-md-6"><?php echo $this->__('Booking Location') ?></span>
                            <span class="apt-summary col-md-6" ><?php echo Mage::helper('appointments')->storeAppearName($model->getStoreId()); ?></span>
                        </div>
                        <?php if( $model->getPiercingLoc()):?>
                            <div class="success-field row">
                                <span class="apt-summary col-md-6"><?php echo $this->__('Piercing Location') ?></span>
                                <span class="apt-summary col-md-6" ><?php echo $model->getPiercingLoc() ?></span>
                            </div>
                        <?php endif;?>
                        <div class="success-field row">
                            <span class="apt-summary col-md-6"><?php echo $this->__('Appointment Start') ?></span>
                            <span class="apt-summary col-md-6" ><?php
                                /* $appStartDate= new Zend_Date(strtotime($model->getAppointmentStart()));
                                $appStartDate = $appStartDate->toString(); */
                                $appStartDate=date("F j, Y H:i", strtotime($model->getAppointmentStart()));
                                if($model->getStoreId())
                                    $format = Mage::helper('appointments')->getTimezoneShortCodeForeStore($model->getStoreId());
                                else
                                    $format = "EST";

                                echo  $appStartDate." ".$format?></span>
                        </div>

                        <div id="btnContinue" class="buttons-set apt-buttons-set row">
                            <button type="button" class="input-box b" data-dismiss="modal" aria-label="Book Another Piercing">
                              <span aria-hidden="true">Book Another Piercing</span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
