<a id="navbar-icon" class="navbar-main navbar-close navbar-icon" href="#navbar-menu" data-toggle="collapse" data-target="#navbar-menu" area-expanded="false">
    <i class="fa fa-bars"></i>
    <i class="fa fa-close"></i>
</a>

<!--TOP SECTION-->
<div id="top" class="container-fluid hero-image" >
    <div class="mt_logo">MARIA TASH</div>
    <div class="pop-up-div">
        <div class="fluid-container">
            <div id="top-popup-wrapper" class="row">
                <div class="pop-up-title">
                    <p class="xpaces">Maria Tash x SPACE <br> Los Angeles Pop-up</p>
                </div>
                <div class="col-md-12 pop-up-content">
                    <p id="top-subheading" class="p-white d-block d-sm-none">Join the Maria Tash team of global experts in <br>Los Angeles for four days only.</p>

                    <div id="btnBookTop" class="btn-div d-block d-sm-none">
                        <a href="#booking">
                            <button id="btnBooking" class="input-box btn" type="submit">BOOK NOW</button>
                        </a>
                    </div>

                    <p id="top-subtitle" class="subtitle">Exclusively at Nordstrom Local Melrose</p>
                    <p class="p-white d-none d-sm-block">Renowned for her innovation in piercing, Tash has
                        developed a technique through which each client’s
                        personal style, complexion, and anatomy guide the
                        curation of jewelry combined to best flatter the
                        wearer. The brand’s unique approach to piercing
                        and styling looks makes it one of the most coveted
                        brands today. Shop the fine jewelry collections and
                        experience Luxury Piercing and custom styling.</p>
                    <p class="p-center">Thursday April 4th - Saturday April 6th <br>
                        10am - 8pm<br>
                        Sunday April 7th<br>
                        11am - 7pm
                    </p>
                    <p class="p-center" >
                        Nordstrom Local Melrose<br> 8401 Melrose Place<br>
                        Los Angeles, CA 90069<br>
                        323-602-2201<br>
                    </p>

                    <p class="p-center">For Piercing or Appointment questions,<br>please reach us at<br>
                        833-775-TASH
                    </p>
                    <p class="p-center">
                        Walk-ins for each day subject to availability
                    </p>
                    <div id="btnBookBottom" class="btn-div d-none d-sm-block">
                        <a href="#booking">
                            <button  id="btnBooking" class="input-box btn"  type="submit">BOOK NOW</button>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="down-arrow">
        <a href="#booking" id="booking-dwn" class="link-down"><img src="<?php echo $this->getSkinUrl("images/allure/popup/down.png")?>" class="down-arrow-size" ></a>
    </div>
</div>

<!--END OF TOP SECTION-->
<?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('nordstrom-popup-top')->toHtml();?>
