
<!doctype html>
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body layout="1C" <?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="container-fluid">
	<div class="wrapper">
	    <?php echo $this->getChildHtml('global_notices') ?>
	    <div class="page layout-grid">
	        <div class="main-container col1-layout">
	            <div class="main">
	                <div class="col-main">
	                    <?php 
							echo $this->getChildHtml('content');
						?>
	                </div>
	            </div>
	        </div>
	        
	        <?php echo $this->getChildHtml('before_body_end') ?>
	        
	    </div>
	</div>
</div>
</body>
</html>