<?php
$_htmlId = $this->getElement()->getHtmlId();
$_htmlClass = $this->getElement()->getClass();
$_htmlName = $this->getElement()->getName();
$_readonly = $this->getElement()->getReadonly();
$_priceValueValidation = $this->getPriceValidation('validate-zero-or-greater');

?>
<tr>
    <td class="label"><?php echo $this->getElement()->getLabel(); ?></td>
    <td colspan="10" class="grid tier">
    <table cellspacing="0" class="data border" id="group_prices_table">
        <col width="120" />
        <col />
        <col width="1" />
        <thead>
            <tr class="headings">
                <th><?php echo $this->getPriceColumnHeader(Mage::helper('teamwork_cegiftcards')->__('Amount')); ?></th>
                <th class="last"><?php echo Mage::helper('catalog')->__('Action'); ?></th>
            </tr>
        </thead>
        <tbody id="<?php echo $_htmlId; ?>_container"></tbody>
        <tfoot>
            <tr>
                <td colspan="4" class="a-right"><?php echo $this->getAddButtonHtml(); ?></td>
            </tr>
        </tfoot>
    </table>

<script type="text/javascript">
//<![CDATA[
var groupPriceRowTemplate = '<tr>'
    + '<td><input class="<?php echo $_htmlClass; ?> required-entry <?php echo $_priceValueValidation; ?>" type="text" name="<?php echo $_htmlName; ?>[{{index}}][price]" value="{{price}}" id="group_price_row_{{index}}_price" /></td>'
    + '<td class="last"><input type="hidden" name="<?php echo $_htmlName; ?>[{{index}}][delete]" class="delete" value="" id="group_price_row_{{index}}_delete" />'
    + '<button title="<?php echo Mage::helper('teamwork_cegiftcards')->__('Delete Amount'); ?>" type="button" class="scalable delete icon-btn delete-product-option" id="group_price_row_{{index}}_delete_button" onclick="return amountControl.deleteItem(event);">'
    + '<span><?php echo Mage::helper('catalog')->__('Delete'); ?></span></button></td>'
    + '</tr>';

var amountControl = {
    template: new Template(groupPriceRowTemplate, new RegExp('(^|.|\\r|\\n)({{\\s*(\\w+)\\s*}})', '')),
    itemsCount: 0,
    addItem : function () {
        var data = {
            price: '',
            readOnly: false,
            index: this.itemsCount++
        };

        if(arguments.length == 2) {
            data.price = arguments[0];
            data.readOnly = arguments[1];
        }

        Element.insert($('<?php echo $_htmlId; ?>_container'), {
            bottom : this.template.evaluate(data)
        });

        if (data.readOnly == '1') {
            ['price', 'delete'].each(function(element_suffix) {
                $('group_price_row_' + data.index + '_' + element_suffix).disabled = true;
            });
            $('group_price_row_' + data.index + '_delete_button').hide();
        }

        <?php if ($_readonly): ?>
        $('<?php echo $_htmlId; ?>_container').select('input', 'select').each(this.disableElement);
        $('<?php echo $_htmlId; ?>_container').up('table').select('button').each(this.disableElement);
        <?php else: ?>
        $('<?php echo $_htmlId; ?>_container').select('input', 'select').each(function(element) {
            Event.observe(element, 'change', element.setHasChanges.bind(element));
        });
        <?php endif; ?>
    },
    disableElement: function(element) {
        element.disabled = true;
        element.addClassName('disabled');
    },
    deleteItem: function(event) {
        var tr = Event.findElement(event, 'tr');
        if (tr) {
            Element.select(tr, '.delete').each(function(element) {
                element.value='1';
            });
            Element.select(tr, ['input', 'select']).each(function(element) {
                element.hide();
            });
            Element.hide(tr);
            Element.addClassName(tr, 'no-display template');
        }
        return false;
    }
};
<?php foreach ($this->getValues() as $_item) : ?>
amountControl.addItem('<?php echo sprintf('%.2f', $_item['price']); ?>', <?php echo (int)!empty($_item['readonly']); ?>);
<?php endforeach; ?>
<?php if ($_readonly) : ?>
$('<?php echo $_htmlId; ?>_container').up('table').select('button')
    .each(amountControl.disableElement);
<?php endif; ?>
//]]>
</script>
</td></tr>
