<?php
if($this->isAdmin())
    echo "<style>header{display: none} .footer{display: none}</style>";
?>


<div class="modal fade bd-example-modal-lg modal-confirm-appointment" tabindex="-1" role="dialog" aria-labelledby="modalConfirmAppointment" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <style>
                .zopim{
                    display: none;
                }
            </style>
<?php
/**
 *
 *	Allure checkout step success order.
 *
 */

if(Mage::app()->getRequest()->getParam('user')=="admin")
    $user="admin";
else
    $user="";

if (Mage::getSingleton("core/session")->getData('appointment_availablity')):

if(Mage::getSingleton("core/session")->getData('appointment_expired'))
{ ?>
            <div class="modal-header">
                <h5 class="modal-title w-100 text-center translate-popup"
                    id="exampleModalLongTitle"><?php echo $this->__('Appointment No Longer Available For Modify') ?></h5>
            </div>
            <div id="popupConfirmAppointment" class="modal-body">
                <div id="wrapperConfirmAppointment" class="row">
                 <div class="apt-buttons-set w-100 text-center">
                                    <button type="button" class="button input-box b translate-popup" style="width: 200px"
                                            title="<?php echo $this->__('Book Another Piercing') ?>"
                                            onclick="window.location.href='<?= $this->getStoreShortUrl() ?>'">
                                        <span><span class="translate-popup"><?php echo $this->__('Book Another Piercing') ?></span></span>
                                    </button>
                                </div>
                            </div>
                        </div>
                        </div>
<?php
}
else
{
$model = Mage::registry('appointment_modified');
if(Mage::app()->getRequest()->getParam('user')=="admin")
    $apt_id =  $model->getId();
else
    $apt_id =  urlencode(Mage::getModel('core/encryption')->encrypt($model->getId()));

    $customer = Mage::getModel('appointments/customers')->getCollection()
        ->addFieldToFilter(
            'appointment_id' ,array('eq'=>$model->getId())
        )->getFirstItem();
    $language = ($this->isAdmin())? "en" :$customer->getLanguagePref();
    $cancel_apt_id =  $model->getId();




$apt_email = $model->getEmail();
//$encryptedId = Mage::helper('core')->encrypt($apt_id)->toString();
//$encryptedEmail = Mage::helper('core')->encrypt($apt_email)->toString();

?>

            <div class="modal-header">
                <h5 class="modal-title text-center w-100 translate-popup"
                    id="exampleModalLongTitle"><?php echo $this->__('Appointment Details') ?></h5>
            </div>

            <div id="popupConfirmAppointment" class="modal-body">
                <div id="wrapperConfirmAppointment" class="row">
                    <?php if ($apt_id): ?>
                        <div class="checkout-success col-md-12">
                            <div class="success-field row row">
                                <span class="apt-summary col-md-6 col-6 text-right"><span class="translate-popup"><?php echo $this->__('Appointment Id');?></span>:</span>
                                <span class="apt-summary col-md-6 col-6"><?php echo $model->getId() ?></span>
                            </div>
                            <div class="success-field row">
                                <span class="apt-summary col-md-6 col-6 text-right "><span class="translate-popup"><?php echo $this->__('No of People in Group');?></span>:</span>
                                <span class="apt-summary col-md-6 col-6"><?php echo $model->getPiercingQty() ?></span>
                            </div>
                            <div class="success-field row">
                                <span class="apt-summary col-md-6 col-6 text-right"><span class="translate-popup"><?php echo $this->__('Booking Location') ?></span>:</span>
                                <span class="apt-summary col-md-6 col-6"><?php echo Mage::helper('appointments')->storeAppearName($model->getStoreId()); ?></span>
                            </div>
                            <div class="success-field row">
                                <span class="apt-summary col-md-6 col-6 text-right"><span class="translate-popup"><?php echo $this->__('Appointment Start');?></span>:</span>
                                <span class="apt-summary col-md-6 col-6 translate-popup app-confirm"><?php
                                    /* $appStartDate= new Zend_Date(strtotime($model->getAppointmentStart()));
                                    $appStartDate = $appStartDate->toString(); */
                                    $appStartDate = date("F j, Y H:i", strtotime($model->getAppointmentStart()));
                                    if ($model->getStoreId())
                                        $format = Mage::helper('appointments')->getTimezoneShortCodeForeStore($model->getStoreId());
                                    else
                                        $format = "EST";

                                    echo $appStartDate . " " . $format ?></span>
                            </div>

                            <div class="btns-setDiv row mt-4">
                                <div class="apt-cancel-buttons-set col-md-4 col-6 form-group">
                                    <button type="button" class="button input-box b translate-popup"
                                            title="<?php echo $this->__('Cancel Appointment') ?>"
                                            onclick="confirmCancelApt();">
                                        <?php echo $this->__('Cancel') ?></button>
                                </div>
                                <div class="apt-modify-buttons-set col-md-4 col-6 form-group">
                                    <button type="button" class="button input-box b translate-popup"
                                            title="<?php echo $this->__('Modify Appointment') ?>"
                                            onclick="window.location.href='<?php echo $this->getUrl('*/book/', array('_secure' => true,'_query'=>'id='.$apt_id ,'user' => $user)); ?>'">
                                        <?php echo $this->__('Modify') ?></button>
                                </div>

                                <div class="apt-buttons-set col-md-4 col-12">
                                    <button type="button" class="button input-box b translate-popup"
                                            title="<?php echo $this->__('Book Another Piercing') ?>"
                                            onclick="window.location.href='<?= $this->getStoreShortUrl() ?>'">
                                        <?php echo $this->__('Book Another Piercing') ?>
                                    </button>
                                </div>
                            </div>
                        </div>
                    <?php endif; ?>
                    <!--  If the id or email not correct  -->

                    <?php
                    }
else:
    ?>
                    <div class="modal-header">
                        <h5 class="modal-title w-100 text-center translate-popup"
                            id="exampleModalLongTitle"><?php echo $this->__('Sorry,Record not found !') ?></h5>
                    </div>
                    <div id="popupConfirmAppointment" class="modal-body">
                        <div id="wrapperConfirmAppointment" class="row">
                            <div class="apt-buttons-set w-100 text-center">
                                <button type="button" class="button input-box b translate-popup" style="width: 200px"
                                        title="<?php echo $this->__('Book Another Piercing') ?>"
                                        onclick="window.location.href='<?= $this->getStoreShortUrl() ?>'">
                                    <span><span class="translate-popup"><?php echo $this->__('Book Another Piercing') ?></span></span>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
<?php endif;?>

<script type="text/javascript">

    jQuery(document).ready(function() {
        jQuery('.modal-confirm-appointment').on('hide.bs.modal', function (e) {return false;});
        jQuery('.modal-confirm-appointment').modal('show', {backdrop: 'static', keyboard: false});
    });

    var conf=false;

    function confirmCancelApt() {

        if (!conf)
        {
            createCustomConfirm(__("Are you sure you want to cancel an scheduled appointment?"));
            return false;
        }

        //Logic to cancel the apt
        var reloadurl = '<?php echo $this->getUrl('*/book/cancelapt',array('id'=>$cancel_apt_id,'_secure' => true)); ?>';
        jQuery.ajax({
            url: reloadurl, //Relative or absolute path to response.php file
            method: 'get',
            success: function (data) {
                jQuery('#exampleModalLongTitle').html(__(data));
                //jQuery('.checkout-success .success-field').empty();
                jQuery('.checkout-success .apt-cancel-buttons-set').empty();
                jQuery('.checkout-success .apt-modify-buttons-set').empty();

            }
        });

    }

    function createCustomConfirm(txt) {
        d = document;

        if(d.getElementById("allureModalContainer")) return;

        mObj = d.getElementsByTagName("body")[0].appendChild(d.createElement("div"));
        mObj.id = "allureModalContainer";
        mObj.style.height = d.documentElement.scrollHeight + "px";

        alertObj = mObj.appendChild(d.createElement("div"));
        alertObj.id = "allureAlertBox";
        if(d.all && !window.opera) alertObj.style.top = document.documentElement.scrollTop + "px";
        alertObj.style.left = (d.documentElement.scrollWidth - alertObj.offsetWidth)/2 + "px";
        alertObj.style.visiblity="visible";

        msg = alertObj.appendChild(d.createElement("p"));
        //msg.appendChild(d.createTextNode(txt));
        msg.innerHTML = txt;

        btnc = alertObj.appendChild(d.createElement("a"));
        btnc.id = "cancelConfirm";
        btnc.appendChild(d.createTextNode(__("CANCEL")));
        btnc.href = "#";


        btnc.onclick = function() {
            removeCustomAlert();
            return false;
        }


        btn = alertObj.appendChild(d.createElement("a"));
        btn.id = "okConfirm";
        btn.appendChild(d.createTextNode(__("OK")));
        btn.href = "#";
        btn.focus();
        btn.onclick = function() {
            removeCustomAlert();
            conf=true;
            confirmCancelApt();
            return false;
        }

        alertObj.style.display = "block";
    }
</script>
</div>
</div>
</div>
</div>
</div>
