<div id="price-list" class="col-md-12">
    <a id="icon-price-close" class="navbar-toggler navbar-close" href="#price-list" data-target="#price-list">
        <i class="fa fa-close" style="font-size: 30px"></i>
    </a>
    <?php //echo $this->getPriceBlock();?>
    <div class="mt-0">
        <p class="xpaces translate-popup text-uppercase para-bold">Price List</p>

        <div class="" style="overflow: auto;">

            <table class="table">
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Earlobe</span> </span>
                    </td>
                    <td class="td-price">€30</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Ear Cartilage</span> </span>
                      </td>
                    <td class="td-price">€35</td>
                </tr>
                <!-- <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Helix</span> </span>
                      </td>
                    <td class="td-price">€35</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Forward Helix</span> </span>
                      </td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Tash Rook</span> </span>
                    </td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Rook</span> </span>
                    </td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Tragus</span> </span>
                    </td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Antitragus</span> </span>
                    </td>
                    <td class="td-price">€45</td>
                </tr>-->
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Contraconch</span> </span>
                    </td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Conch</span> </span>
                  </td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Daith</span> </span>
                    </td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Nostril</span> </span>
                    </td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe">Septum </span>
                    </td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Nipple</span> </span>
                    </td>                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Navel</span> </span>
                    </td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Dermal</span> </span>
                    </td>
                    <td class="td-price">€80</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Eyebrow</span> </span>
                    </td>
                    <td class="td-price">€45</td>
                </tr>
            </table>

        </div>

    </div>
</div>
