<div id="price-list" class="col-md-12">
    <a id="icon-price-close" class="navbar-toggler navbar-close" href="#price-list" data-target="#price-list">
        <i class="fa fa-close" style="font-size: 30px"></i>
    </a>
    <?php //echo $this->getPriceBlock();?>
    <div class="mt-0">
        <p class="xpaces translate-popup">Price List</p>

        <div class="" style="overflow: auto;">

            <table class="table">
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Earlobe</span> ...</span>
                        <span class="jewelry"><span class="translate-popup">Jewellery starts at</span> €120</span></td>
                    <td class="td-price">€30</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Helix</span> ...</span>
                        <span class="jewelry"><span class="translate-popup">Jewellery starts at</span> €120</span></td>
                    <td class="td-price">€35</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Forward Helix</span> ...</span>
                        <span class="jewelry"><span class="translate-popup">Jewellery starts at</span> €120</span></td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Tash Rook</span> ...</span>
                        <span class="jewelry"><span class="translate-popup">Jewellery starts at</span> €120</span></td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Rook</span> ...</span>
                        <span class="jewelry"><span class="translate-popup">Jewellery starts at</span> €120</span></td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Tragus</span> ...</span>
                        <span class="jewelry"><span class="translate-popup">Jewellery starts at</span> €120</span></td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Antitragus</span> ...</span>
                        <span class="jewelry"><span class="translate-popup">Jewellery starts at</span> €295</span></td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Contraconch</span> ...</span>
                        <span class="jewelry"><span class="translate-popup">Jewellery starts at</span> €120</span></td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Conch</span> ...</span>
                        <span class="jewelry"><span class="translate-popup">Jewellery starts at</span> €120</span></td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Daith</span> ...</span>
                        <span class="jewelry"><span class="translate-popup">Jewellery starts at</span> €125</span></td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Nostril</span> ...</span>
                        <span class="jewelry"><span class="translate-popup">Jewellery starts at</span> €120</span></td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe">Septum ...</span>
                        <span class="jewelry"><span class="translate-popup">Jewellery starts at</span> €95</span></td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Nipple</span> ...</span>
                        <span class="jewelry"><span class="translate-popup">Jewellery starts at</span> €295</span></td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Navel</span> ...</span>
                        <span class="jewelry"><span class="translate-popup">Jewellery starts at</span> €270</span></td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Dermal</span> ...</span>
                        <span class="jewelry"><span class="translate-popup">Jewellery starts at</span> €55</span></td>
                    <td class="td-price">€80</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Eyebrow</span> ...</span>
                        <span class="jewelry"><span class="translate-popup">Jewellery starts at</span> €125</span></td>
                    <td class="td-price">€45</td>
                </tr>
            </table>

        </div>

    </div>
</div>
