<div id="price-list" class="col-md-12">
    <a id="icon-price-close" class="navbar-toggler navbar-close" href="#price-list" data-target="#price-list">
      <img class="" src="<?php echo $this->getSkinUrl('images/redesign/exit-small-bk.png'); ?>"/>
    </a>
    <?php echo $this->getPriceBlock();?>


    <!--<div class="mt-0">
        <p class="xpaces translate-popup text-uppercase para-bold">Price List</p>

        <div class="" style="overflow: auto;">

            <table class="table">
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Earlobe</span> </span>
                    </td>
                    <td class="td-price">€30</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Ear Cartilage</span> </span>
                    </td>
                    <td class="td-price">€35</td>
                </tr>
                <!-- <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Helix</span> </span>
                      </td>
                    <td class="td-price">€35</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Forward Helix</span> </span>
                      </td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Tash Rook</span> </span>
                    </td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Rook</span> </span>
                    </td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Tragus</span> </span>
                    </td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Antitragus</span> </span>
                    </td>
                    <td class="td-price">€45</td>
                </tr>-->
               <!-- <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Contraconch</span> </span>
                    </td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Conch</span> </span>
                    </td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Daith</span> </span>
                    </td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Nostril</span> </span>
                    </td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe">Septum </span>
                    </td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Nipple</span> </span>
                    </td>                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Navel</span> </span>
                    </td>
                    <td class="td-price">€45</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Dermal</span> </span>
                    </td>
                    <td class="td-price">€80</td>
                </tr>
                <tr class="tr-piercing">
                    <td class="td-piercing-name">
                        <span class="earlobe"><span class="translate-popup">Eyebrow</span> </span>
                    </td>
                    <td class="td-price">€45</td>
                </tr>
            </table>

        </div>

    </div>-->
</div>


<!-- General Information -->
<!-- <div class="col-md-12 general-piercing-information">
  <div class="row">
    <div class="col-md-12 info-title">
        <p class="para-bold text-uppercase">Important Information</p>
    </div>
    <div class="col-md-12 price-information">
        <p class="para-normal">You must be over the age of 18 to get a piercing unaccompanied by an adult.</p>
        <p class="para-normal">Those under the age of 18 must be accompanied by their legal guardian. Both child and legal guardian must have a valid photographic id or equivalent with them on the day (e.g. passport, driver’s license, birth certificate). If child and legal guardian’s last name are different, proof of guardianship must also be presented (passport, birth certificate etc.).</p>
        <p class="para-normal">A valid photographic id or equivalent will be required for proof of age. Where this is not present, the piercing team have a legal right to refuse service.</p>
        <p class="para-normal">Children must be aged 8 or over to have an earlobe piercing, and aged 16 or over for cartilage piercings.</p>
        <p class="para-normal">You must be over the age of 18 for nipple, navel, eyebrow, lip, or tongue piercings.</p>
        <p class="para-normal">You must be aged 16 or over to have a nostril piercing. If you are under the age of 18 you must follow the terms in points two and three.</p>
    </div>
</div> -->
