<div id="booking" class="container-fluid booking nopad appointment-container pb-5">
    <div class="container nopad">
        <div class="row">
            <?php
            foreach ($this->getActiveStore() as $id=>$store):
                ?>

                <div class="col-12 p-0 ">
                    <div class="store-info-wrapper mt-3">

                        <div class="row">
                            <div class="col-12 store-name"><h1><?= $this->getStoreName($id) ?></h1></div>
                            <div class="col-12 store-details">
                                <div class="row">
                                    <div class="col-lg-6 col-md-6 col-12">
                                        <p class="para-lighter mb-0 store-left"><?= $this->getStoreAddress($id) ?></p>
                                        <p class="para-lighter"><?= $this->getStoreContact($id) ?></p>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-12 store-right text-lg-right">
                                        <a href="<?= $this->getStoreShortUrl($id) ?>"><button class="input-box btn translate-popup next-button light-button" type="button">BOOK NOW</button></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            <?php endforeach; ?>
        </div>
    </div>
</div>
