<div class="store-info-wrapper">
<div class="col-12 p-0 ">
    <div class="row">
        <div class="col-12 store-name"><h1><?= $this->getStoreName() ?></h1></div>
        <div class="col-12 store-details">
          <div class="row">
          <div class="col-lg-6 col-md-6 col-12">
              <p class="para-lighter mb-0 store-left"><?= $this->getStoreAddress() ?></p>
              <p class="para-lighter"><?= $this->getStoreContact() ?></p>
          </div>
          <div class="col-lg-6 col-md-6 col-12 store-right text-lg-right">
              <p class="para-lighter"><?= $this->getStoreHours() ?></p>
          </div>
        </div>
      </div>
    </div>
</div>
</div>
