<div class="store-info-wrapper">
<div class="col-12 p-0">
    <div class="row">
        <div class="col-12"><h1><?= $this->getStoreName() ?></h1></div>
        <div class="col-8">
            <p class="para-lighter"><?= $this->getStoreAddress() ?></p>
            <p class="para-lighter"><?= $this->getStoreContact() ?></p>
        </div>
        <div class="col-4">
            <p class="para-lighter"><?= strip_tags($this->getStoreHours()) ?></p>
        </div>
    </div>
</div>
</div>
