<div id="booking" class="container-fluid booking nopad appointment-container pb-5">
    <div class="container nopad">
        <div class="row">
            <!--Static Code for New York-->
            <div class="col-12 p-0 ">
                <div class="store-info-wrapper mt-3">
                    <?= $this->getLayout()->createBlock('cms/block')->setBlockId('new_york_address_store_list')->toHtml();?>
                </div>
            </div>
            <?php
            foreach ($this->getActiveStore() as $id=>$store):
                ?>

                <div class="col-12 p-0 ">
                    <div class="store-info-wrapper mt-3">

                        <div class="row">
                            <div class="col-12 store-name"><h1><?= $this->getStoreName($id) ?></h1></div>
                            <div class="col-12 store-details">
                                <div class="row">
                                    <div class="col-lg-6 col-md-6 col-12">
                                        <p class="para-lighter mb-0 store-left"><?= $this->getStoreAddress($id) ?></p>
                                        <p class="para-lighter"><?= $this->getStoreContact($id) ?></p>
                                    </div>
                                    <?php if($this->isStoreDisabled($id)):?>
                                    <div class="col-lg-6 col-md-6 col-12 store-right text-lg-right">
                                        <a href="<?= $this->getStoreShortUrl($id) ?>">
                                            <?php if(!empty($this->getIsDisabledStoreButton($id))):
                                                echo $this->getIsDisabledStoreButton($id);
                                            else: ?>
                                            <button class="input-box btn translate-popup next-button light-button" type="button" style="font-size: 13px;opacity:.65;">TEMPORARILY CLOSED</button>
                                            <?php endif; ?>
                                        </a>
                                    </div>
                                    <?php else:?>
                                    <div class="col-lg-6 col-md-6 col-12 store-right text-lg-right">
                                        <a href="<?= $this->getStoreShortUrl($id) ?>"><button class="input-box btn translate-popup next-button light-button" type="button">BOOK NOW</button></a>
                                    </div>
                                    <?php endif;?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            <?php endforeach; ?>
            
             <!--Static Code for coming-soon -->
                    <?= $this->getLayout()->createBlock('cms/block')->setBlockId('coming_soon_store_list')->toHtml();?>

        </div>
    </div>
</div>
