<?php
$model = Mage::getSingleton("core/session")->getData('appointment_submitted');
$isPiercingAppointment=Mage::getSingleton("core/session")->getData('isPiercingAppointment');
if($this->getPara("redirect-from")!="modify-success"):
?>
<div class="modal fade bd-example-modal-lg modal-confirm-appointment appointment-set" tabindex="-1" role="dialog" aria-labelledby="modalConfirmAppointment" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content pop-up-cover">
            <div id="popupConfirmAppointment" class="modal-body">
                <div id="wrapperConfirmAppointment" class="row">
                    <div class="checkout-success col-md-12 text-center">
                      <div class="pop-title modal-header m-0">
                        <button type="button" class="close success-appointment-btn" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true"><img class="d-lg-block d-md-block d-none" src="<?php echo $this->getSkinUrl('images/redesign/login-cross.png'); ?>"></span>
                            <span aria-hidden="true"><img class="d-block d-lg-none d-md-none" src="<?php echo $this->getSkinUrl('images/redesign/exit-small-grey.png'); ?>"></span>
                        </button>
                      </div>
                        </button>
                        <span class="translate-popup appointment-popup-text para-normal">Your Maria Tash Appointment on <?= date("d M Y",strtotime($model->getAppointmentStart())); ?> </span><span class="translate-popup para-normal">at</span> <span class="para-normal"><?= date("H:i",strtotime($model->getAppointmentStart())); ?></span> <span class="translate-popup para-normal">is <?= ($this->isModify())? 'updated' : 'confirmed'?>!<br>
                            You will receive a confirmation via email.<br>
                            Thanks!</span>
                        <div id="btnContinue" class="buttons-set apt-buttons-set row">
                            <button type="button"  <?= ($this->isModify())? "onclick=window.location.href='". $this->getStoreShortUrl()."/redirect-from/modify-success'": 'data-dismiss="modal"'?> class="input-box light-button mx-auto text-uppercase"  aria-label="Book Another Piercing">
                                <span aria-hidden="true" class="translate-popup">Book Another Appointment</span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
    <?php if($this->isModify()): ?>
    <script>
        jQuery(".modal").on("hidden.bs.modal", function () {
            var url=window.location.href;
            window.location = url.replace("index","modify");
        });
    </script>
    <?php endif; ?>
<?php
else:
 ?>
    <script>
        var currentUrl=window.location.href;
        var newUrl=currentUrl.replace("redirect-from/modify-success","");
        history.pushState({}, null, newUrl);
    </script>
<?php
endif; ?>
