<?php
$model = Mage::getSingleton("core/session")->getData('appointment_submitted');
$isPiercingAppointment=Mage::getSingleton("core/session")->getData('isPiercingAppointment');
if($this->getPara("redirect-from")!="modify-success"):
?>
<div class="modal fade bd-example-modal-lg modal-confirm-appointment" tabindex="-1" role="dialog" aria-labelledby="modalConfirmAppointment" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content pop-up-cover">
            <div id="popupConfirmAppointment" class="modal-body">
                <div id="wrapperConfirmAppointment" class="row">
                    <div class="checkout-success col-md-12 text-center">
                      <div class="pop-title modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true"><img src="<?php echo $this->getSkinUrl('images/redesign/login-cross.png'); ?>"></span>
                        </button>
                      </div>
                        </button>

                        <span class="translate-popup para-normal appointment-popup-text">Your Appointment on 08 Nov 2019 at 12:20 is confirmed!<br>
                            You will receive a confirmation via email.<br>
                            Thanks!</span>
                        <div id="btnContinue" class="buttons-set apt-buttons-set row">
                            <button type="button"  <?= ($this->isModify())? "onclick=window.location.href='". $this->getStoreShortUrl()."/redirect-from/modify-success'": 'data-dismiss="modal"'?> class="input-box light-button mx-auto text-uppercase"  aria-label="Book Another Piercing">
                                <span aria-hidden="true" class="translate-popup">Book Another Piercing</span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
