<?php
$model = Mage::getSingleton("core/session")->getData('appointment_submitted');
$isPiercingAppointment=Mage::getSingleton("core/session")->getData('isPiercingAppointment');
if($this->getPara("redirect-from")!="modify-success"):
?>
<div class="modal fade bd-example-modal-lg modal-confirm-appointment" tabindex="-1" role="dialog" aria-labelledby="modalConfirmAppointment" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <div id="popupConfirmAppointment" class="modal-body">
                <div id="wrapperConfirmAppointment" class="row">
                    <div class="checkout-success col-md-12 text-center">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        </button>

                        <span class="translate-popup">Your Appointment on</span> <span class="translate-popup app-confirm"><?= date("d M Y",strtotime($model->getAppointmentStart())); ?> </span><span class="translate-popup">at</span> <?= date("H:i",strtotime($model->getAppointmentStart())); ?> <span class="translate-popup">is <?= ($this->isModify())? 'updated' : 'confirmed'?>!</span> <br>
                        <span class="translate-popup">You will receive a confirmation via email.</span><br>
                        <span class="translate-popup">Thanks!</span>
                        </span>
                        <div id="btnContinue" class="buttons-set apt-buttons-set row">
                            <button type="button"  <?= ($this->isModify())? "onclick=window.location.href='". $this->getStoreShortUrl()."/redirect-from/modify-success'": 'data-dismiss="modal"'?> class="input-box b"  aria-label="Book Another Piercing">
                                <span aria-hidden="true" class="translate-popup">Book Another Piercing</span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>

