<?php
/**
 * Mageplace Magento to SugarCRM Bridge
 *
 * @package     Belitsoft_Sugarcrm
 * @copyright   Copyright (c) 2013 Mageplace. (http://www.mageplace.com)
 * @license     http://www.mageplace.com/disclaimer.html
 */
?>

<?php if($this->getStageType()): ?>
<?php echo $this->getStages(); ?>
<?php endif; ?>

<?php if(!$this->getStageType()): ?>
<?php echo Mage::helper('sugarcrm')->__("Please, select option from 'User orders to SugarCRM' field to load options"); ?>
<?php endif; ?>