<?php
/**
 * @var $this Mage_Checkout_Block_Onepage_Shipping_Method_Available
 *
 */
?>
<?php $_shippingRateGroups = $this->getShippingRates(); ?>
<?php if (!$_shippingRateGroups): ?>
    <p><?php echo $this->__('The information you entered does not match any known address with Fedex. Please check your shipping addresses for any errors.') ?></p>
<?php else: ?>
	<?php $_sole = count($_shippingRateGroups) == 1;?>
	<?php $_address = $this->getAddress();?>
	<?php $isIternational = (strtolower($_address->getCountryId()) != strtolower("us")) ? 1: 0; ?>
	<div class="gift-messages">
        <p class="info-text-two"><?= $this->__('Delivery Signature Option.')?></p>
        <p class="control">
            <label for="no_signature_delivery" class="para-normal custom-checkbox custom-checkbox-two">
              <input type="checkbox" name="no_signature_delivery" id="no_signature_delivery" value="1" checked="checked" class="checkbox shipping-signature" data-is_international="<?= $isIternational?>">
              <span class="checkmark"></span>
              Require signature upon delivery.</label>
        </p>
    </div>
    <div class="row">
	<div class="col-lg-6 col-md-6 col-12 first-shipment-method">
		<?php $shippingMethodHtml = "";?>
		<div>
			<p class="info-text-two">For 1st Shipment:
				<br><span>(Ready to ship now)</span>
			</p>
		</div>
		<select class="select-shipping-method select-type-one validate-select" name="shipping_method"  >
			<option value="">Select Method</option>
            <?php $ship_sign_national = array();?>
            <?php $ship_sign_without_national = array();?>
            <?php $ship_withoutsign_national = array();?>
            <?php $ship_withoutsign_without_national = array();?>

          	<?php foreach ($_shippingRateGroups as $code => $_rates): ?>
           	<?php $_sole = $_sole && count($_rates) == 1;?>
           	<?php foreach ($_rates as $_rate): ?>

            	<?php if ($_rate->getErrorMessage()): ?>
                <?php echo $this->escapeHtml($_rate->getErrorMessage()) ?>
                <?php else: ?>
                <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>

                <?php
                    $shipDataArr =  $_rate->getData();
                    $shipDataArr["excl"] = $_excl;
                    $shipDataArr["incl"] = $_incl;
                ?>
                <?php if($code == "matrixrate"){
                    $shipCodeArr = explode("#",$_rate->getCode());
                    if(count($shipCodeArr) == 3){
                        if($shipCodeArr[1] == 1){
                            if($shipCodeArr[2] == 1){
                                $ship_sign_national[$_rate->getCode()] = $shipDataArr;
                            } else {
                                $ship_sign_without_national[$_rate->getCode()] = $shipDataArr;
                            }
                        ?>
                	<?php } else {
                            if($shipCodeArr[2] == 1){
                                $ship_withoutsign_national[$_rate->getCode()] = $shipDataArr;
                            } else {
                                $ship_withoutsign_without_national[$_rate->getCode()] = $shipDataArr;
                            } ?>

						<?php } ?>
						
                  	<?php if($isIternational == $shipCodeArr[2]):?>
                        <option value="<?= $this->htmlEscape($_rate->getCode()) ?>" <?php if($_rate->getCode()===$this->getAddressShippingMethod()) echo ' selected="selected"' ?>>
                       	<?= $this->escapeHtml($_rate->getMethodTitle()) ?>
                       	<?php echo $_excl; ?>
                        <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                       		(<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                       	<?php endif; ?>
                      	</option>

                      	<?php
                      	$shippingMethodHtml .= '<option ';
                      	$shippingMethodHtml .= 'value="'.$this->htmlEscape($_rate->getCode()) .'"';
                      	if(($_rate->getCode()===$this->getAddressShippingMethod())){
                      	    $shippingMethodHtml .= 'selected="selected"';
                      	}
                      	$shippingMethodHtml .= '>';
                      	$shippingMethodHtml .= $this->escapeHtml($_rate->getMethodTitle()).$_excl;
                      	if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl){
                      	    $shippingMethodHtml .= $this->__('Incl. Tax')." ".$_incl;
                      	}
                      	$shippingMethodHtml .= '</option>';
                      	?>

                   	<?php endif;?>
                   
                    <?php    }
                    } else {
                            $ship_sign_national[$_rate->getCode()] = $shipDataArr;
                            $ship_sign_without_national[$_rate->getCode()] = $shipDataArr;
                            $ship_withoutsign_national[$_rate->getCode()] = $shipDataArr;
                            $ship_withoutsign_without_national[$_rate->getCode()] = $shipDataArr;
                    ?>
                    <option value="<?= $this->htmlEscape($_rate->getCode()) ?>" <?php if($_rate->getCode()===$this->getAddressShippingMethod()) echo ' selected="selected"' ?>>
                    	<?= $this->escapeHtml($this->getCarrierName($code))?>-<?= $this->escapeHtml($_rate->getMethodTitle()) ?>
                    	<?php echo $_excl; ?>
                    	<?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                        	(<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                        <?php endif; ?>
                   	</option>

                   	<?php
                   	$shippingMethodHtml .= '<option ';
                   	$shippingMethodHtml .= 'value="'.$this->htmlEscape($_rate->getCode()) .'"';
                   	if(($_rate->getCode()===$this->getAddressShippingMethod())){
                   	    $shippingMethodHtml .= 'selected="selected"';
                   	}
                   	$shippingMethodHtml .= '>';
                   	$shippingMethodHtml .= $this->escapeHtml($_rate->getMethodTitle()).$_excl;
                   	if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl){
                   	    $shippingMethodHtml .= $this->__('Incl. Tax')." ".$_incl;
                   	}
                   	$shippingMethodHtml .= '</option>';
                    ?>

                  <?php } ?>
            	<?php endif ?>
                <?php endforeach; ?>
              <?php endforeach; ?>
            </select>
    	</div>

    	<div class="col-lg-6 col-md-6 col-12 second-shipment-method">
    		<div>
    			<p class="info-text-two">For 2nd Shipment:
    				<br><span>(Shipped when items available)</span>
    			</p>
			</div>
    		<select class="select-shipping-method select-type-one validate-select" name="mt_shipping_method"  >
				<option value="">Select Method</option>
				<?= $shippingMethodHtml;?>
			</select>
    	</div>
</div>
    	<?php
            $shippingConfig = array(
                '1_1' => $ship_sign_national,
                '1_0' => $ship_sign_without_national,
                '0_1' => $ship_withoutsign_national,
                '0_0' => $ship_withoutsign_without_national
            );
       ?>

 <script type="text/javascript">
    if (typeof Allure == "undefined") {
        var Allure = {};
    }
   	//Allure.shippingConfig = <?php echo json_encode($shippingConfig,true)?>;
</script>

<script type="text/javascript">
	/*jQuery(document).ready(function(){
		if (typeof Allure == "undefined") {
	        var Allure = {};
	    }
	   	Allure.shippingConfig = <?php //echo json_encode($shippingConfig,true)?>;
		jQuery('.shipping-signature').on('change',function(){
			var selector = jQuery(this);
			var isInternational = selector.data("is_international");
			var value = (selector.is( ":checked" )) ? 1 : 0;
			var genKey = value+"_"+isInternational;
			jQuery(this).val(value);
			if(Object.entries(Allure.shippingConfig).length){
				if(Allure.shippingConfig[genKey]){
					var shippingOptions = Allure.shippingConfig[genKey];
					if(shippingOptions){
						var shippingHtml = '';
						for (var objKey in shippingOptions) {
							var shipObj = shippingOptions[objKey];
							shippingHtml += '<option value="'+shipObj.code+'">'+shipObj.method_title +' '+shipObj.excl +'</option>';
					    }
						jQuery('.select-shipping-method').html("");
						jQuery('.select-shipping-method').html(shippingHtml);
					}
				}
			}
		});
	});*/
</script>
<?php endif;?>
