<?php
/**
 * One page checkout payment methods
 *
 * @see Mage_Checkout_Block_Onepage_Payment_Methods
 */

$quote = Mage::getModel('checkout/cart')->getQuote();
$codeExists = ($quote->getCouponCode())
    ? true
    : false;
?>
<div class='promoDiv'>
    <div class="coupons">        
        
			
		<?php $oGiftCardSession = Mage::getSingleton('giftcards/session'); ?>

<div class="discount">
    <div class="sp-methods">
        <form method="post" action="<?php echo $this->getUrl('giftcards/cart/giftcardActive'); ?>" id="giftcardAgree">
            <div class="input-box">
                <input type="checkbox" value="1" name="giftcard_use" id="giftcard_use" class="checkbox"  <?php echo $oGiftCardSession->getActive() ? 'checked="checked"' : '' ?>>
                <label for="giftcard_use"><?php echo $this->__('Gift Card'); ?></label>
            </div>
        </form>
    </div>
    <?php if(1==1): ?>
    <div class="discount-form giftcard-payment-method">
        <form method="post" action="<?php echo $this->getUrl('giftcards/cart/activateGiftCard'); ?>" id="activateGiftCard">
            <div class="input-box">
                <input value="" name="giftcard_code" id="giftcard_code" class="input-text">
            </div>
            <div class="buttons-set">
                <button value="<?php echo $this->__('Apply') ?>" onclick="activateGiftCard.save()" class="button_coupon"
                        title="Apply" type="button" ><span><span><?php echo $this->__('Apply') ?></span></span>
                </button>
            </div>
        </form>

        <?php $currencySymbol = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); $temp = 0; ?>
        <?php if($oGiftCardSession->getActive()) {
            foreach($oGiftCardSession->getFrontOptions() as $k => $v)
            {
                if($temp) {
                    echo '<br/><br/>';
                }
                echo '<p><b>'.$currencySymbol.$v['applied'].' '.$this->__('applied from Gift Card').' **********'.$v['code'].'.</b><br/>';
                echo $this->__('Remaining card balance').': '.$currencySymbol.$v['remaining'].'.</p><a href="#" onclick="deActivateGiftCard.deactivate('.$k.');" class="button_coupon" style="position:relative; top:-9px;"><span><span>'.$this->__('Remove').'</span></span></a>';
                $temp = 1;
            }
        }
        ?>
    </div>

    <?php endif;?>

</div>
<div class="discount">
            <div class="discount-form">
                <label>Promo Code</label>

                    <input class="input-text" id='promoCode' value="<?php echo $quote->getCouponCode() ?>" />
     
                    <a style="display:<?php echo ($codeExists) ? 'none' : '' ?>" id="promoCodeLinkAdd" class="button_coupon" onclick="javascript:couponApply(0)"><span><span>APPLY</span></span></a>
                    <a style="display:<?php echo (!$codeExists) ? 'none' : '' ?>" id="promoCodeLinkRemove" class="button_coupon" onclick="javascript:couponApply(1)"><span><span>REMOVE</span></span></a>
					<span style="display:none;" id="advice-required-entry-promoCode_code" ></span>
          
            </div>
        </div>	
    </div>
</div>

