<?php
$mfpValue = $this->getMFPValue();
$learnMore = ($this->helper('affirm/promo_asLowas')->isVisibleLearnMore()) ? 'true' : 'false';
$color = $this->helper('affirm/promo_asLowAs')->asLowAsColor();
?>
<style>
    .affirm_checkout_promo{
        font-family: urw-din-medium!important;
        font-size: 13px;
        color: rgba(41,41,41,0.90);
        letter-spacing: 0.25px;
        line-height: 17px;
        text-align: right;
    }
    .__affirm-logo.__affirm-logo-blue.__ligature__affirm_full_logo__:after, .__affirm-logo.__affirm-logo-blue.__ligature__affirm_short_logo__:after{
        color: black;
    }
</style>
<div>
    <?php echo '<div class="affirm-as-low-as affirm_checkout_promo" data-page-type="cart" ' . (!empty($mfpValue) ? 'data-promo-id="' . $mfpValue . '"' : '') . ' data-amount="' . $this->getCheckoutGrandTotal() .'" data-learnmore-show="'.$learnMore.'" data-affirm-color="'.$color.'"></div>'; ?>
</div>

<script type="text/javascript">
    if (!AFFIRM_AFFIRM.promos.getIsInitialized()) {
        AFFIRM_AFFIRM.promos.initialize("<?php echo $this->helper('affirm')->getApiKey(); ?>",
            "<?php echo $this->helper('affirm')->getAffirmJsUrl(); ?>");
    }
    <?php if ($this->helper('affirm')->isProductConfigurable()): ?>
    if (!AFFIRM_AFFIRM.promos.getIsConfigurableOptionsInitialized()) {
        AFFIRM_AFFIRM.promos.initConfigurableOptions(<?php echo $this->helper('affirm')->getConfigurableBackOrderedInfo(); ?>);
    }
    <?php endif; ?>
    AFFIRM_AFFIRM.promos.initLimitation("<?php echo $this->helper('affirm')->getMinOrderThreshold(); ?>", "<?php echo $this->helper('affirm')->getMaxOrderThreshold(); ?>");

    if (!AFFIRM_AFFIRM.promos.getIsScriptLoaded()) {
        AFFIRM_AFFIRM.promos.loadScript();
    }
</script>