<script type="text/javascript">

    var miVar = 0;
    function isTouch() {
        var iOS = ( navigator.userAgent.match(/(iPad|iPhone|iPod)/g) ? true : false );
        return iOS;
    }
    
    jQuery(document).ready(function() {
        jQuery('<img src="" id="current-press-cover" style="display: none"/>').appendTo('body');
        jQuery('.images-press').show();


        jQuery('.prev').css('opacity', '.13');
        jQuery('body').removeClass('categorypath-discover-maria-tash-press-html');
        jQuery('body').addClass('categorypath-discover-maria-tash-press-html-w');

        var numPress = jQuery('ul.gallery').length - 1;
        for (num = 0; num <= numPress; num++) {
            if (jQuery('#gallery' + num + ' li').length == 1) {
                jQuery('#foo3_prev' + num + ', #foo3_next' + num).remove();
            }
        }

        jQuery(".fancybox").fancybox({
            afterLoad: function() {
                if (!isTouch()) {
                    jQuery('div.fancybox-wrap').mouseover(function() {
                        jQuery('div.fancybox-wrap').find('a.next, a.prev').css('display', 'block');
                    });

                    jQuery('div.fancybox-wrap').mouseout(function() {
                        jQuery('div.fancybox-wrap').find('a.next, a.prev').css('display', 'none');
                    });
                }
            },
            onUpdate: function() {
                jQuery('body').addClass('showtitle');
                var newImageUrl = jQuery('.fancybox-inner .gallery img:first-child').attr('src');
                jQuery('meta[property=og\\:image]').attr('content', newImageUrl);

            },
            afterShow: function() {
                if (isTouch()) jQuery('div.fancybox-wrap').find('a.next, a.prev').show();
                var press = parseInt(jQuery('.fancybox-inner .press:first').attr('id').substr(4));
                imageSrc = jQuery('.pressGallery' + press + ':first img').attr('src');
                jQuery('#current-press-cover').attr('src', imageSrc);
                var pressSheets = jQuery('.pressGallery' + press).length;
                if (pressSheets > 1) {
                    updateImageNum(press, 1);
                    fancyboxBeforeUpdate(press, 0);
                    jQuery.fancybox.update();
                } else if (pressSheets == 1) {
                    var sheet = parseInt(jQuery('.pressGallery' + press + ' img').attr('data')) == 1 ? 0 : 1;
                    updateImageNum(press, 1);
                    fancyboxBeforeUpdate(press, 0);
                    jQuery.fancybox.update();
                }
            },
            afterClose: function() {
                // miVar = 3;

                //console.info(miVar);
                jQuery('ul.gallery li').each(function(index) {
                    jQuery('#counterClick' + index).text('0');
                    if (jQuery(this).hasClass('re-set')) {
                        //alert(index+' == '+0);
                        jQuery(this).eq(0).css('display', 'block');
                        jQuery('.fancybox-wrap').mouseover(function() {
                            jQuery('.prev, .next').show();
                        }).mouseout(function() {
                            jQuery('.prev, .next').hide();
                        });
                    }
                    else {
                        jQuery(this).css('display', 'none');
                    }
                });
                jQuery('.next').css('opacity', '1');
                jQuery('.prev').css('opacity', '.13');
                jQuery('body').removeClass('showtitle');
            },
            fitToView: true,
            scrolling: 'no',
            autoSize: true,
            closeClick: false,
            openEffect: 'none',
            closeEffect: 'none'
        });

<?php
$pressId = Mage::app()->getRequest()->getParam('press');
if (!empty($pressId)) {
    ?>
            jQuery('#fancybox<?php echo Mage::app()->getRequest()->getParam('press'); ?>').trigger('click');
    <?php
}
?>
    });
    function updateImageNum(press, num) {
        jQuery('#presspopup-title-' + press + ' span:first').text(num);
    }
    
    function fancyboxBeforeUpdate(press, itemIndex) {
        var imgWidth = jQuery('.pressGallery' + press + ' :eq(' + itemIndex + ') img').width();
        if (imgWidth) {
            jQuery('#data' + press + ' p:first').css('max-width', imgWidth + 'px');
            jQuery('#data' + press).css('width', (imgWidth + 42) + 'px');
        }
    }


    function nextImage(numImg) {
        var elements = jQuery('ul li.pressGallery' + numImg).length - 1;
        if (parseInt(jQuery('#counterClick' + numImg).text()) < elements) {
            jQuery('li.pressGallery' + numImg).each(function(index) {
                var currentImageIndex = parseInt(jQuery('#counterClick' + numImg).text());
                if (index == currentImageIndex + 1) {
                    updateImageNum(numImg, index + 1);
                    jQuery(this).css('display', 'block');
                    imageSrc = jQuery('li.pressGallery' + numImg + ' :eq(' + index + ') img').attr('src');
                    jQuery('#current-press-cover').attr('src', imageSrc);
                    fancyboxBeforeUpdate(numImg, index);
                    jQuery.fancybox.update();
                    var val = index + 1;
                }
                else {
                    jQuery(this).css('display', 'none');
                }
            });
            jQuery('#foo3_next' + numImg).css("opacity", "1");
            jQuery('#foo3_prev' + numImg).css('opacity', '1');
            counterClick = parseInt(jQuery('#counterClick' + numImg).text()) + 1;
            jQuery('#counterClick' + numImg).text(counterClick);
            //console.info(parseInt(jQuery( '#counterClick'+numImg).text())+' > '+elements);
            if (parseInt(jQuery('#counterClick' + numImg).text()) == elements) {
                jQuery('#foo3_next' + numImg).css('cursor', 'default');
                jQuery('#foo3_next' + numImg).css('opacity', '.13');
                jQuery('#foo3_prev' + numImg).css('opacity', '1');
            }
        }
    }

    function prevImage(numImg) {
        if (parseInt(jQuery('#counterClick' + numImg).text()) > 0) {
            jQuery('li.pressGallery' + numImg).each(function(index) {
                countClick = parseInt(jQuery('#counterClick' + numImg).text()) - 1;
                if (index == countClick) {
                    updateImageNum(numImg, index + 1);
                    jQuery(this).css('display', 'block');
                    imageSrc = jQuery('li.pressGallery' + numImg + ' :eq(' + index + ') img').attr('src');
                    jQuery('#current-press-cover').attr('src', imageSrc);
                    fancyboxBeforeUpdate(numImg, index);
                    jQuery.fancybox.update();
                    var val = index + 1;
                }
                else {
                    if (countClick >= 0) {
                        jQuery(this).css('display', 'none');
                    }
                }
            });
            var counterClick = parseInt(jQuery('#counterClick' + numImg).text()) - 1;
            counterClick = counterClick > 0 ? counterClick : 0;
            jQuery('#counterClick' + numImg).text(counterClick);
            jQuery('#foo3_prev' + numImg).css("opacity", "1");
            jQuery('#foo3_next' + numImg).css("opacity", "1");

            if (parseInt(jQuery('#counterClick' + numImg).text()) == 0) {
                jQuery('#foo3_prev' + numImg).css('opacity', '.13');
                jQuery('#foo3_next' + numImg).css("opacity", "1");
            }
        }
    }

    function getParam(name) {
        var regexS = "[\\?&]" + name + "=([^&#]*)";
        var regex = new RegExp(regexS);
        var tmpURL = window.location.href;
        var results = regex.exec(tmpURL);
        if (results == null)
            return "";
        else
            return results[1];
    }

</script>
<?php $collection = Mage::getModel('ecp_press/press')->getCollection()->addFilter('status', 1)->setOrder('publish_date'); ?>
<div class="ecp-press-index-index">
    <div class="press-list">
        <ul class="images-press" style="display:none;">
            <?php $i = 0; ?>  
            <?php foreach ($collection as $item) {
                $numImages = 1; ?>   
                <li><a class="fancybox" href="#data<?php echo $i; ?>" id="fancybox<?php echo $i; ?>" data="<?php echo $i; ?>"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "/press/" . $item->getImageOne(); ?>"/></a></li>
                <div id="data<?php echo $i; ?>" class="press" style="display:none">
                    <p style="text-align:left;"><?php echo $item->getTitle() . ' ' . $item->getDescription() .' ';
                $date = date_create($item->getPublishDate());
                echo date_format($date, 'd/M/Y'); ?></p>
                 <?php if(!empty($item->getOriginalLink())):?>
                <p style="text-align:left; margin-bottom: 10px;"><a target="_blank" href='<?php echo $item->getOriginalLink()?>'><?php echo $item->getOriginalName() ?></a></p>
                <?php endif;?>
                    <div class="navi">
                        <a href="#" id="foo3_prev<?php echo $i; ?>" onclick="prevImage(<?php echo $i; ?>);" class="prev disabled" style="display: none;"><span>prev</span></a>
                        <ul class="gallery" id="gallery<?php echo $i; ?>">
                            <?php if ($item->getImageOne() != '' && $item->getImageTwo() == '') { ?>
                                <li class="pressGallery<?php echo $i; ?> re-set" style="text-align:center;">
                                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "/press/" . $item->getImageOne(); ?>" data="1"/>
                                </li>
    <?php } else { ?>
                                <?php if ($item->getImageTwo() != '') {
                                    $numImages++; ?>   
                                    <li class="pressGallery<?php echo $i; ?> re-set" style="text-align:center;"><!-- re-set -->
                                        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "/press/" . $item->getImageTwo(); ?>" data="2"/>
                                    </li>
                                <?php } ?>
                                <?php if ($item->getImageTree() != '') {
                                    $numImages++; ?>
                                    <li class="pressGallery<?php echo $i; ?>" style="display:none;text-align:center;">
                                        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "/press/" . $item->getImageTree(); ?>" data="3"/>
                                    </li><!-- 666,868-->         
                                <?php } ?>
                                <?php if ($item->getImageFour() != '') {
                                    $numImages++; ?>
                                    <li class="pressGallery<?php echo $i; ?>" style="display:none;text-align:center;">
                                        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "/press/" . $item->getImageFour(); ?>" data="4"/>
                                    </li>
                               <?php } ?>
                                <?php if ($item->getImageFive() != '') {
                                    $numImages++; ?>
                                    <li class="pressGallery<?php echo $i; ?>" style="display:none;text-align:center;">
                                        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "/press/" . $item->getImageFive(); ?>" data="5"/>
                                    </li>
                                <?php } ?>
                                <?php if ($item->getImageSix() != '') {
                                    $numImages++; ?>
                                    <li class="pressGallery<?php echo $i; ?>" style="display:none;text-align:center;">
                                        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "/press/" . $item->getImageSix(); ?>" data="6"/>
                                    </li>
                                <?php } ?>
                                <?php if ($item->getImageSeven() != '') {
                                    $numImages++; ?>
                                    <li class="pressGallery<?php echo $i; ?>" style="display:none;text-align:center;">
                                        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "/press/" . $item->getImageSeven(); ?>" data="7"/>
                                    </li>
                                <?php } ?>
                                <?php if ($item->getImageEight() != '') {
                                    $numImages++; ?>
                                    <li class="pressGallery<?php echo $i; ?>" style="display:none;text-align:center;">
                                        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "/press/" . $item->getImageEight(); ?>" data="8"/>
                                    </li>
                                <?php } ?>
                                <?php if ($item->getImageNine() != '') {
                                    $numImages++; ?>
                                    <li class="pressGallery<?php echo $i; ?>" style="display:none;text-align:center;">
                                        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "/press/" . $item->getImageNine(); ?>" data="9"/>
                                    </li>
                                <?php } ?>
                                <?php if ($item->getImageTen() != '') {
                                    $numImages++; ?>
                                    <li class="pressGallery<?php echo $i; ?>" style="display:none;text-align:center;">
                                        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "/press/" . $item->getImageTen(); ?>" data="10"/>
                                    </li>
                                <?php } ?>
    <?php } ?>
                        </ul>
                        <a href="#" id="foo3_next<?php echo $i; ?>" onclick="nextImage(<?php echo $i; ?>);" class="next" style="display: none;"><span>next</span></a>
                    </div>
                    <!--p style="text-align:center;"><?php echo $item->getDescription(); ?></p-->  
                    <script type="text/javascript">
       //vertical align gallery buttons
       var top = ((jQuery('.pressGallery' + '<?php echo $i; ?> img').eq(0).height()) / 2) - 25;
       jQuery('.pressGallery' + '<?php echo $i; ?> img').css('top', top);
                    </script>
                    <div class="presspopup-bottom">
                            <span class="number_img" id="presspopup-title-<?php echo $i ?>"><span></span> of <?php echo ($numImages - 1) <= 1 ? '1 Image' : ($numImages - 1) . ' Images' ?></span>
                            
                    </div>
                    <p id="counterClick<?php echo $i; ?>" style="display: none">0</p>
                </div>
    <?php $i++; ?>
<?php } ?>             
        </ul>
    </div>
</div>