
<?php $_orders = $this->getOrders();
	if($_orders) :
?>

                <?php $_odd = ''; ?>
                <?php $i = 0 ?>
                <?php foreach ($_orders as $_order): ?>
                <tr>
                    <td style="padding-left:10px;">
                    	<a class="mt-oder-num" onclick="loadOrderView(this)" data-order-id="<?php echo $_order->getId()?>" data-href="<?php echo $this->getViewUrl($_order).'#receipt' ?>">
                    		<?php echo $_order->getRealOrderId() ?>
                    	</a>
                    </td>
                    
                    
                    <td class="a-left" style="padding-left:20px;" ><span class="nobr">
										<?php echo Mage::app()->getLocale()->date(strtotime($_order->getCreatedAtStoreDate()), null, null, false)->toString('MM/dd/yyyy') ?>
					<?php //echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></span></td>
                    <td class="a-left" style="padding-left:0;"><span><?php echo $_order->getShippingAddress() ? $this->htmlEscape($_order->getShippingAddress()->getName()) : '&nbsp;' ?></span></td>
                    <td class="a-left" style="padding-left:18px;"><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
                    <td class="a-left" style="padding-left:15px;"><?php echo $_order->getStatusLabel() ?></td>
                    <td class="a-left" style="padding-left:10px;">
                        <span class="nobr"><a href="<?php echo $this->getViewUrl($_order).'#receipt' ?>"><?php echo $this->__('View Order') ?></a>
                            <?php /*<span class="separator">|</span><a href="<?php echo $this->getTrackUrl($_order) ?>"><?php echo $this->__('Track Order') ?></a>&nbsp;*/ ?>
                            <?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
                            <span>|</span> <a href="<?php echo $this->getReorderUrl($_order) ?>" class="link-reorder"><?php echo $this->__('Reorder') ?></a>
                        <?php endif ?>
                        </span>
                    </td>
                </tr>
                <?php endforeach; ?>
<?php endif; ?>