<h3>My Products</h3>
<div class="mt-myaccount-page">
<?php if(0):?>
	<div class="tab">
		  <button data-link="purchase" id="mt-myproduct-purchase" data-tab="tab1" class="tablinks active" onclick="changeTab(this);">Purchased</button>
		  
		  <button data-link="wishlist" id="mt-myproduct-wishlist" data-tab="tab2" class="tablinks" 
		  	onclick="changeTab(this);">Wishlist
		  	<span id="myaccount-wishlist-total-item" class="total-wishlist-count total-count-box"></span>
		  	</button>
		  
		  <button data-link="cart" id="mt-myproduct-cart" data-tab="tab3" class="tablinks" 
		  	onclick="changeTab(this);">Cart
		  	<span id="myaccount-cart-total-item" class="total-cart-count total-count-box"></span>
		  </button>
		  
		  <button data-link="receipt" id="mt-myproduct-receipts" data-tab="tab4" class="tablinks" 
		  	onclick="changeTab(this);">All Receipts
		  	<span id="total-orders-count" class="total-orders-count total-count-box"></span>
		  </button>
	</div>
	
	<div id="new-mt-myproduct-purchase" class="tabcontent tab1 active">
	 	 <div class="mt-new-purchase">
	  		<?php echo $this->getChildHtml("myaccount_filter");?>
	  		<?php //echo $this->getChildHtml('purchased_items')?>
	 	</div>
	</div>
	
	<div id="new-mt-myproduct-wishlist" class="tabcontent tab2">
		<div class="mt-my-wishlist">
	  		Hiii
	  	</div>
	</div>
	
	<div id="new-mt-myproduct-cart" class="tabcontent tab3">
	 	<div class="mt-my-cart">
	  		Hiiiiiiii
	 	</div>
	</div>
	
	<div id="new-mt-myproduct-receipts" class="tabcontent tab4">
	 	<div class="mt-my-orders">
	  		<?php echo $this->getChildHtml("myaccount_filter");?>
	  		Hiiiiiiii
	 	</div>
	</div>
	
	<?php endif;?>
	
	
	<div id="sns_tab_products" class="product-collateral clearfix">
    	<ul class="nav-tabs gfont">
    		<li class="dropdown pull-left tabdrop">
    			<a class="dropdown-toggle" data-toggle="dropdown">
    				<i class="fa fa-align-justify"></i> 
    			</a>
    			<ul id="mt-account-tab-dropdown-menu" class="dropdown-menu">
					<li class="mt-account-active-tab">
						<a onclick="changeTabView(this)" data-link="wishlist" data-toggle="tab-pane" data-target="#mt-wishlist-tab">
							WISHLIST 
						</a>
					</li>
					<li class="mt-account-active-tab">
						<a onclick="changeTabView(this)" data-link="cart" data-toggle="tab-pane" data-target="#mt-cart-tab"> 
							CART
						</a>
					</li>
					<li class="mt-account-active-tab">
						<a onclick="changeTabView(this)" data-link="receipt" data-toggle="tab-pane" data-target="#mt-report-tab"> 
							ALL ORDERS
						</a>
					</li>
					<li class="mt-account-active-tab">
						<a onclick="changeTabView(this)" data-link="openorders" data-toggle="tab-pane" data-target="#mt-openorders-tab"> 
							OPEN OREDERS
						</a>
					</li>
				</ul>
			</li>
              
            <li class="mt-account-active-tab active">
               <a data-toggle="tab-pane" data-target="#mt-purchase-item-tab">
                   PURCHASED ITEM
               </a>
            </li>
       </ul>
	    		
       <div class="tab-content">
       		<div id="mt-purchase-item-tab" class="tab-pane active">
                 <div class="collateral-box">
                 	<?php echo $this->getChildHtml("myaccount_filter");?>
                 	<?php echo $this->getChildHtml('purchased_items')?>
                  </div>
             </div>
             
            <div id="mt-wishlist-tab" class="tab-pane">
                 <div class="collateral-box">
                      <?php echo $this->getChildHtml('customer.wishlist')?>
                 </div>
            </div>
            
            <div id="mt-cart-tab" class="tab-pane">
                 <div class="collateral-box">
                      <?php echo $this->getChildHtml('checkout.cart')?>
                 </div>
            </div>
             
            <div id="mt-report-tab" class="tab-pane">
                  <div class="collateral-box">
                  	<?php echo $this->getChildHtml("myaccount_filter");?>
                  	<?php echo $this->getChildHtml('sales.order.history_list')?>
                  </div>
        	</div>
        	
        	<div id="mt-openorders-tab" class="tab-pane">
                  <div class="collateral-box">
                  	<?php echo $this->getChildHtml("myaccount_filter");?>
                  	<?php echo $this->getChildHtml('sales.order.openorder_list')?>
                  </div>
        	</div>
                    
        </div>
	    		
    </div>
	

</div>


<script>
	jQuery(document).ready(function(){

		var type = window.location.hash.substr(1);
		if(type!="" && type!="undefined" && type!=null){
			var element = jQuery('.mt-account-active-tab ').find('a[data-link='+type+']')
			changeTabView(element);
		}else{
			var element = jQuery('.mt-account-active-tab.active a');
			changeTabView(element);
		}
		
		
		
	});

	function changeTabView(event){
		var newTargetId = jQuery(event).attr('data-target');
		var newLabel = jQuery(event).text();
		var activeSelector = jQuery('.mt-account-active-tab.active').find('a');
		var oldTargetId = activeSelector.attr('data-target');
		var oldLabel = activeSelector.text();
		activeSelector.attr('data-target',newTargetId);
		activeSelector.text(newLabel);
		jQuery(event).attr('data-target',oldTargetId);
		jQuery(event).text(oldLabel);

		var dataLink = jQuery(event).attr('data-link');
		window.location.hash = dataLink;

		jQuery('.tab-content .tab-pane').removeClass('active');
		jQuery(newTargetId).addClass('active');
	}
</script>


<script>

	function getParams(mkey,mval){
		var uri = window.location;
		var key = mkey;
		var queryString = ""+(uri.search.indexOf("?") !== -1) ? uri.search.split("?")[1] : "";
		var params = "";
		if (queryString !== "" && queryString != undefined) {
			 params = params + "?";
		     var params_arr = queryString.split("&");
		     params = params + key + "=" + mval+"&";
		     for (var i = params_arr.length - 1; i >= 0; i -= 1) {
		          var param = params_arr[i].split("=")[0];
		          if(param!==key){
				     params = params + params_arr[i]+"&";
			      }
		     }
		     params = params.replace(/\&$/, '');
		}else{
			 params = "?" + mkey + "=" + mval;
		}
		return params;
	}
	
	function showLoadingFancybox1(element){
		if (Allure.showLoading) {
			Allure.showLoading = false;
			jQuery('#'+element+' .box-content').append(Allure.loader);
			//jQuery('#box-history .allure-fancybox-overlay').height(jQuery('#box-history table').height() + jQuery('#box-history table')[0].scrollHeight);
			jQuery('#'+element+' .allure-fancybox-overlay').show();
		}
	}

	function showLoadingFancybox(){
		jQuery.fancybox.showLoading();
        jQuery.fancybox.helpers.overlay.open({parent: $('body'),closeClick : false});
	}

	function hideLoadingFancybox(){
		jQuery.fancybox.hideLoading();
    	jQuery('.fancybox-overlay.fancybox-overlay-fixed').hide();
	}

	function hideLoadingFancybox1(element){
		if (!Allure.showLoading) {
			Allure.showLoading = true;
			//jQuery.fancybox.hideLoading();
	    	//jQuery('.fancybox-overlay.fancybox-overlay-fixed').hide();
	
			jQuery('#'+element+' .allure-fancybox-overlay').remove();
		}
	}

	
</script>

