<?php
/**
 * Mageplace Magento to SugarCRM Bridge
 *
 * @package     Belitsoft_Sugarcrm
 * @copyright   Copyright (c) 2013 Mageplace. (http://www.mageplace.com)
 * @license     http://www.mageplace.com/disclaimer.html
 */
?>
<script type="text/javascript">
var stagesSelectTemplate = '<div id="<?php echo $this->getStageId(); ?>_{{index}}"  class="option-box"> ' +
	'<table class="option-header" cellpadding="0" cellspacing="0">' +
		'<thead>' +
			'<tr>' +
				'<th class="opt-type"><?php echo Mage::helper('sugarcrm')->__('Magento'); ?></th>' +
                '<th class="opt-req"><?php echo Mage::helper('sugarcrm')->__('SugarCRM'); ?></th>' +
				'<th>&nbsp;</th>' +
			'</tr>' +
		'</thead>' +
		'<tbody>' +
			'<tr>' +
				'<td><?php echo $this->getStageOptionField(); ?></td>' +
				'<td><?php echo $this->getSugarStageField(); ?></td>' +
				'<td>&nbsp;<?php echo $this->getDeleteButtonHtml(); ?></td>' +
			'</tr>' +
		'</tbody>' +
	'</table>' +
'</div>';
var optionIndex = 0;
MageplaceSugarBridge = {};
MageplaceSugarBridge.Stages = Class.create();
MageplaceSugarBridge.Stages.prototype = {
	idLabel : '<?php echo $this->getStageId(); ?>',
	top : '<?php echo $this->getStageTopId(); ?>',
	templateSyntax : /(^|.|\\r|\\n)({{(\w+)}})/,
	templateText : '',
	itemsCount : 0,

	initialize : function(template) {
		this.templateText = template;
	},

	add : function(data) {
		if(!data){
			data = {};
		}

		data.index = this.itemsCount++;
		this.template = new Template(this.templateText, this.templateSyntax);
		Element.insert(this.top, {'after':this.template.evaluate(data)});
		this.top = $(this.idLabel+'_'+data.index);

		for(stage_name in data) {
			if(stage_name != 'index' && stage_name != 'id'
				&& $(this.idLabel+'_'+data.index+'_'+stage_name) && data[stage_name])
			{
				$(this.idLabel+'_'+data.index+'_'+stage_name).value = data[stage_name];
			}
		}
	},

	remove : function(event){
		var element = $(Event.findElement(event, 'div'));
		if(element) {
			Element.select(element, '.delete').each(function(elem){elem.value='1'});
			Element.select(element, ['input', 'select']).each(function(elem){elem.hide(); elem.className = '';});
			Element.hide(element);
		}
	},

	checkSave : function() {
		var check_all_empty = true;
		$('<?php echo $this->getStageId(); ?>').select('[id$="_<?php echo $this->getStageTextString(); ?>"]').each(function(elem) {
			if((elem.className != '') && elem.value) {
				check_all_empty = false;
			}
		});

		if(check_all_empty) {
			alert("<?php echo Mage::helper('sugarcrm')->__("Please, provide a stage options"); ?>");
			return false;
		}

		return true;
	}
}

MageplaceSugarBridge.Operations = Class.create();
MageplaceSugarBridge.Operations.prototype = {
	initialize : function() {},

	save : function() {
		return mpSugarcrmStages.checkSave();
	}
}


try {
	mpSugarcrmStages = new MageplaceSugarBridge.Stages(stagesSelectTemplate);
	mpSugarcrmOperations = new MageplaceSugarBridge.Operations();
} catch(e) {
	alert(e);
}
</script>
<div class="entry-edit custom-options bundle" id="sugarcrm_stages_container">
	<div class="entry-edit-head">
		<div class="right"><?php echo $this->getAddButtonHtml(); ?></div>
	</div>

	<div id="<?php echo $this->getStageId(); ?>" class="box">
		<div id="<?php echo $this->getStageTopId(); ?>"></div>
	</div>
</div>

<?php if($stages = $this->getStages()): ?>
<script type="text/javascript">
	<?php foreach ($stages as $data): ?>
	mpSugarcrmStages.add(<?php echo $this->getParentBlock()->_toJson($data); ?>);
	<?php endforeach; ?>
</script>
<?php endif; ?>
