<?php $code   = Mage::registry('tokenbase_method'); ?>
<?php $method = Mage::helper('payment')->getMethodInstance( $code ); ?>

<div id="add-main-form"></div>
<div id="add-main">

<form class="" action="<?php echo $this->getAction(); ?>" method="post" id="form-validate-mt" <?php echo ( $this->isEdit() ) ? 'style="display:block"' : 'style="display:block"'; ?> data-edit="<?php echo ($this->isEdit())?"edit":"add"?>">
	<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
	<input type="hidden" name="id" value="<?php //echo $this->getCard()->getId(); ?>" />
	<input type="hidden" name="method" value="<?php echo $code; ?>" />
	
	<input type="hidden" name="mode_type" value="add" />
	
	<?php if( $method->isAcceptJsEnabled() === true ): ?>
		<input type="hidden" name="payment[acceptjs_key]" id="<?php echo $code; ?>_acceptjs_key" value="" />
		<input type="hidden" name="payment[acceptjs_value]" id="<?php echo $code; ?>_acceptjs_value" value="" />
		<input type="hidden" name="payment[cc_last4]" id="<?php echo $code; ?>_cc_last4" value="" />
	<?php endif; ?>
	<ul class="form-list">
	
	<li id="mt-credit-card-info">
		<ul>
			<li class="card-info-title"><p class="mt-paycard-title"><?php echo $this->__('Credit Card Information'); ?></p></li>
		
			<?php if(0&& $this->isEdit() ): ?>
				<li>
					<input type="radio" class="left" name="payment[sameCard]" value="1" id="<?php echo $code; ?>_sameCard_1" checked="checked" /> <label for="<?php echo $code; ?>_sameCard_1"><?php echo $this->__( 'Continue using payment data %s', $this->getCard()->getLabel() ); ?></label><br />
					<input type="radio" class="left" name="payment[sameCard]" value="0" id="<?php echo $code; ?>_sameCard_0" /> <label for="<?php echo $code; ?>_sameCard_0"><?php echo $this->__('Change payment data'); ?></label>
				</li>
			<?php endif; ?>
			<?php $style = ' style="display:block"' ; ?>
			<li class="mt-card-info <?php echo $code; ?>_add"<?php echo $style; ?>>
				<label style="display: none" for="<?php echo $code; ?>_cc_type" class="required"><em>*</em><?php echo $this->__('Credit Card Type'); ?></label>
				<div class="input-box">
					<select id="<?php echo $code; ?>_cc_type" name="payment[cc_type]" class="<?php echo $code; ?>_require <?php if(1 || !$this->getCard()->getId() ): ?>required-entry main-dropdown-box<?php endif; ?>">
						<option value=""><?php echo $this->__('--Please Select--')?></option>
						<?php foreach( Mage::helper('tokenbase')->getCcAvailableTypes( $code ) as $k => $v ): ?>
							<option value="<?php echo $k ?>" <?php if(0&& $k == $this->getCard()->getAdditional('cc_type') ): ?>selected="selected"<?php endif; ?>><?php echo $v ?></option>
						<?php endforeach ?>
					</select>
				</div>
			</li>
			<li class="mt-card-info mt-cc-number <?php echo $code; ?>_add"<?php echo $style; ?>>
				<label style="display: none" for="<?php echo $code; ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number'); ?></label>
				<div class="input-box">
					<input placeholder="Credit Card Number" type="text" id="<?php echo $code; ?>_cc_number" autocomplete="off" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number'); ?>" class="input-text <?php echo $code; ?>_require <?php if(1 ||!$this->getCard()->getId() ): ?>required-entry validate-cc-number<?php endif; ?>" value="" />
				</div>
			</li>
			
			<li class="mt-card-info name-on-card <?php echo $code; ?>_add"<?php echo $style; ?>>
				<label style="display: none" for="<?php echo $code; ?>_name_on_card" class="required"><em>*</em><?php echo $this->__('Name on the card'); ?></label>
				<div class="input-box">
					<input placeholder="Name on the Card" type="text" id="<?php echo $code; ?>_name_on_card" autocomplete="off" name="payment[name_on_card]" title="<?php echo $this->__('Name on the card'); ?>" class="input-text <?php echo $code; ?>_require <?php if(1 ||!$this->getCard()->getNameOnCard() ): ?>required-entry validate-on-card<?php endif; ?>" value="" />
				</div>
			</li>
			
			<li id="<?php echo $code; ?>_cc_type_exp_div" class="mt-card-info <?php echo $code; ?>_add sp-methods"<?php echo $style; ?>>
				<label style="display: none" for="<?php echo $code; ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date'); ?></label>
				<div class="input-box card-exp">
					<div class="v-fix ">
						<span class="para-normal date-label"><?php echo $this->__('Expiration Date'); ?></span>
					</div>
					<div class="v-fix exp-month">
						<select id="<?php echo $code; ?>_cc_exp_month" name="payment[cc_exp_month]" class="month <?php echo $code; ?>_require <?php if(1 ||!$this->getCard()->getId() ): ?>required-entry main-dropdown-box<?php endif; ?>">
							<option value=""><?php echo $this->__('Month'); ?></option>
							<?php $_ccExpMonth = $this->getCard()->getAdditional('cc_exp_month'); ?>
							<?php foreach( Mage::helper('tokenbase')->getCcMonths() as $k=>$v ): ?>
								<option value="<?php echo $k?$k:'' ?>"<?php if(0&&$k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
							<?php endforeach ?>
						</select>
					</div>
					<div class="v-fix exp-year">
						<select id="<?php echo $code; ?>_cc_exp_year" name="payment[cc_exp_year]" class="year <?php echo $code; ?>_require <?php if(1 ||!$this->getCard()->getId() ): ?>required-entry main-dropdown-box<?php endif; ?>">
							<option value=""><?php echo $this->__('Year'); ?></option>
							<?php $_ccExpYear = $this->getCard()->getAdditional('cc_exp_year'); ?>
							<?php foreach( Mage::helper('tokenbase')->getCcYears() as $k=>$v ): ?>
								<option value="<?php echo $k?$k:'' ?>"<?php if(0&&$k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
							<?php endforeach ?>
						</select>
					</div>
				</div>
			</li>
			<?php if( $method->getConfigData('useccv') ): ?>
				<?php $requireCvv = ($method->getAdvancedConfigData('require_ccv') == 1); ?>
				<li id="<?php echo $code; ?>_cc_type_cvv_div" class="mt-card-info <?php if( $requireCvv == 0 ): ?> <?php echo $code; ?>_add<?php endif; ?>" <?php if( $requireCvv == 0 ): ?><?php echo $style; ?><?php endif; ?>>
					<label style="display: none" for="<?php echo $code; ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number'); ?></label>
					<div class="input-box">
						<span class="card-code para-normal">Security Code</span>
						<div class="v-fix cvv-box">
							<input placeholder="CCV" type="text" title="<?php echo $this->__('Card Verification Number'); ?>" autocomplete="off" class="cvv input-patern card-cvv <?php echo $code; ?>_require <?php if(1 || !$this->getCard()->getId() ): ?>required-entry validate-cc-cvn<?php elseif( $requireCvv ): ?>required-entry<?php endif; ?>" id="<?php echo $code; ?>_cc_cid" name="payment[cc_cid]" value="" />
						</div>
					</div>
				</li>
			<?php endif; ?>
		</ul>
	</li>
	
		<li><p class="mt-paycard-title cardholder-title"><?php echo $this->__('Cardholder Information'); ?></p></li>
			<?php /*		<li>
			<div class="input-box"><?php echo $this->getAddressesHtmlSelect('billing'); ?></div>
				</li> */ ?>
		<li id="billing-new-address-form">
			<div class="">
				<ul>
					<li class="list-even">
						<label style="display: none" for="<?php echo $code; ?>_fn" class="required"><em>*</em><?php echo $this->__('First Name'); ?></label>
						<div class="input-box">
							<input placeholder="First Name *" type="text" id="<?php echo $code; ?>_fn" name="billing[firstname]" class="input-patern required-entry" value="<?php //echo $this->escapeHtml( $this->getCard()->getAddress('firstname') ); ?>" />
						</div>
					</li>
					<li class="list-odd">
						<label style="display: none" for="<?php echo $code; ?>_ln" class="required"><em>*</em><?php echo $this->__('Last Name'); ?></label>
						<div class="input-box">
							<input placeholder="Last Name *" type="text" id="<?php echo $code; ?>_ln" name="billing[lastname]" class="input-patern  required-entry" value="<?php //echo $this->escapeHtml( $this->getCard()->getAddress('lastname') ); ?>" />
						</div>
					</li>
					<li class="list-even">
						<label style="display: none" for="<?php echo $code; ?>_company"><?php echo $this->__('Company'); ?></label>
						<div class="input-box">
							<input placeholder="Company" type="text" id="<?php echo $code; ?>_company" name="billing[company]" class="input-patern " value="<?php //echo $this->escapeHtml( $this->getCard()->getAddress('company') ); ?>" />
						</div>
					</li>
					<li class="list-odd">
						<label style="display: none" for="<?php echo $code; ?>_street" class="required"><em>*</em><?php echo $this->__('Street Address'); ?></label>
						<div class="input-box">
							<input placeholder="Street Address *" type="text" id="<?php echo $code; ?>_street" name="billing[street][]" class="input-patern required-entry <?php echo Mage::helper('tokenbase')->getAttributeValidationClass('street') ?>" value="<?php //echo $this->escapeHtml( $this->getStreetLine(1) ); ?>" />
						</div>
					</li>
					<?php for ($i = 2, $n = Mage::helper('customer/address')->getStreetLines(); $i <= $n; $i++): ?>
						<li class="<?php echo ($i%2==0)?'list-even':'list-odd'?>">
							<div class="input-box">
								<input placeholder="Street Address 2" type="text" id="<?php echo $code; ?>_street_<?php echo $i ?>" name="billing[street][]" class="input-patern <?php echo str_replace( 'required-entry', '', Mage::helper('tokenbase')->getAttributeValidationClass('street') ); ?>" value="<?php //echo $this->escapeHtml( $this->getStreetLine($i) ); ?>" />
							</div>
						</li>
					<?php endfor; ?>
					<li class="list-odd">
						<label style="display: none" for="<?php echo $code; ?>_city" class="required"><em>*</em><?php echo $this->__('City'); ?></label>
						<div class="input-box">
							<input placeholder="City *" type="text" id="<?php echo $code; ?>_city" name="billing[city]" class="input-patern required-entry <?php echo Mage::helper('tokenbase')->getAttributeValidationClass('city') ?>" value="<?php //echo $this->escapeHtml( $this->getCard()->getAddress('city') ); ?>" />
						</div>
					</li>
					<li class="list-even">
						<label style="display: none" for="<?php echo $code; ?>_st" class="required"><em>*</em><?php echo $this->__('State/Province'); ?></label>
						<div class="input-box">
							<select style="display:none;" class="validate-select required-entry main-dropdown-box state-payment" title="State/Province" name="billing[region_id]" id="region_id" >
								<option value=""><?php echo $this->__('Please select region, state or province'); ?></option>
							</select>
							<input placeholder="State/Province *" type="text" class="input-patern required-entry <?php echo Mage::helper('tokenbase')->getAttributeValidationClass('region') ?>" title="State/Province" value="<?php //echo $this->escapeHtml( $this->getCard()->getAddress('region') ); ?>" name="billing[region]" id="region" />
						</div>
					</li>
					<li class="list-odd">
						<label style="display: none" for="<?php echo $code; ?>_postcode" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code'); ?></label>
						<div class="input-box">
							<input placeholder="Zip/Postal Code *" type="text" id="<?php echo $code; ?>_postcode" name="billing[postcode]" class="input-patern required-entry <?php echo Mage::helper('tokenbase')->getAttributeValidationClass('postcode') ?>" value="<?php //echo $this->escapeHtml( $this->getCard()->getAddress('postcode') ); ?>" />
						</div>
					</li>
					<li class="list-even">
						<label style="display: none" for="<?php echo $code; ?>_country" class="required"><em>*</em><?php echo $this->__('Country'); ?></label>
						<div class="input-box countrys">
							<?php echo Mage::helper('tokenbase')->getCountryHtmlSelect( 'billing[country_id]', $this->getCard()->getAddress('country_id'), 'country' ); ?>
						</div>
					</li>
					<li class="list-odd">
						<label style="display: none"  for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
						<div class="input-box">
							<input placeholder="Telephone *" type="text" name="billing[telephone]" value="<?php //echo $this->escapeHtml( $this->getCard()->getAddress('telephone') ) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-patern <?php echo Mage::helper('tokenbase')->getAttributeValidationClass('telephone') ?>" id="telephone" />
						</div>
					</li>
					<li class="list-even">
						<label style="display: none" for="fax"><?php echo $this->__('Fax') ?></label>
						<div class="input-box">
							<input placeholder="Fax" type="text" name="billing[fax]" id="fax" title="<?php echo $this->__('Fax') ?>" value="<?php //echo $this->escapeHtml( $this->getCard()->getAddress('fax') ) ?>" class="input-patern <?php echo Mage::helper('tokenbase')->getAttributeValidationClass('fax') ?>" />
						</div>
					</li>
				</ul>
			</div>
		</li>
		
		<li class="buttons-set">
			<button class="button dark-button save_button" type="submit"><span><span><?php echo $this->__('Continue'); ?></span></span></button>
			<a href="<?php //echo $this->getUrl('*/*', array('_secure' => true)); ?>"><?php //echo $this->__('Cancel'); ?></a>
		</li>
		
	</ul>
</form>
<script type="text/javascript">
//<![CDATA[
<?php /*	$('billing-address-select').observe( 'change', function(e) {
		if( $(this).value == '' ) {
			$('billing-new-address-form').show();
		}
		else {
			$('billing-new-address-form').hide();
		}
	}); */ ?>
	
	$('region_id').setAttribute('defaultValue', '<?php echo $this->getCard()->getAddress("region_id"); ?>');
	
	var dataForm = new VarienForm('form-validate-mt', true);
	new RegionUpdater('country', 'region', 'region_id', <?php echo Mage::helper('directory')->getRegionJson(); ?>, undefined, '<?php echo $code; ?>_postcode');
	
	
//]]>
</script>
<?php if( $method->isAcceptJsEnabled() === true ): ?>
	<script type="text/javascript">
	//<![CDATA[
		<?php /** We have to load our scripts dynamically as such, because opc will not load them otherwise. Injecting via layout would only cause compatibility problems. **/ ?>
		if( typeof Accept == 'undefined' ) {
			var s = document.createElement('script');
			s.type = "text/javascript";
			s.src = "https://<?php echo $method->getConfigData('test') ? 'jstest' : 'js'; ?>.authorize.net/v1/Accept.js";
			var fs = document.getElementsByTagName('script')[0];
			fs.parentNode.insertBefore(s, fs);
		}
		
		if( typeof pdlAcceptJs == 'undefined' ) {
			var acceptJs_<?php echo $code; ?>_init = function() {
				acceptJs_<?php echo $code; ?> = new pdlAcceptJs(
					'form-validate-mt',
					'<?php echo addslashes($method->getConfigData('login')); ?>',
					'<?php echo addslashes($method->getConfigData('client_key')); ?>',
					'<?php echo $code; ?>',
					'#form-validate-mt button'
				);
				
				if( typeof window['acceptJs_<?php echo $code; ?>_callback'] == 'undefined' ) {
					window['acceptJs_<?php echo $code; ?>_callback'] = function(response) {
						acceptJs_<?php echo $code; ?>.handlePaymentResponse(response);
					}
					
					<?php /** TODO: Remove following expected 9/2016 fix round with deferred loading support **/ ?>
					window.isReady = true;
				}
			}
			
			var s = document.createElement('script');
			s.type = "text/javascript";
			s.src = "<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) . 'paradoxlabs/authnetcim/accept.js'; ?>";
			s.onreadystatechange = s.onload = function() {
				if (!acceptJs_<?php echo $code; ?>_init.done && (!s.readyState || /loaded|complete/.test(s.readyState))) {
					acceptJs_<?php echo $code; ?>_init.done = true;
					acceptJs_<?php echo $code; ?>_init();
				}
			};
			var fs = document.getElementsByTagName('script')[0];
			fs.parentNode.insertBefore(s, fs);
		}
		else {
			acceptJs_<?php echo $code; ?>.bind();
		}
	//]]>
	</script>
<?php endif; ?>
</div>
