<?php if (Mage::app()->getFrontController()->getAction()->getFullActionName() == 'checkout_cart_index'):?>
    <!--checkout login popup-->
    <div id="openModal" class="popupLoginModel checkoutPopupLoginModel">
        <div class="pop-up-cover col-12">
            <form class="form-signin row" action="<?php echo $this->getPostActionUrl() ?>" method="post" id="popup-login-form">
              <a href="#close" title="Close" class="close exit-large position-absolute sign-in-cross">
                  <img class="d-lg-block d-md-block d-none" src="<?php echo $this->getSkinUrl('images/redesign/login-cross.png'); ?>" alt="x">
                  <img class="d-block d-lg-none d-md-none" src="<?php echo $this->getSkinUrl('images/redesign/exit-small-grey.png'); ?>" alt="x">
              </a>
                <input type="hidden" id="redirectUrl" name="redirectUrl" value="">
                <div class="col-lg-7 col-md-12 col-12 signin-left">
                  <div class="row">
                    <div class="pop-title modal-header w-100">
                        <h1><?php echo $this->__("Sign In or Register")?></h1>
                    </div>
                    <div class="body modal-body">
                        <div id="login_msg_div">
                            <span class="invalid-login" id="login-msg"></span>
                        </div>
                        <div class="form-group input-form">
                            <!-- <label class="popup-login-lbl" for="email"><em>*</em> <//?php echo $this->__("Email Address")?></label> -->
                            <input id='username-login' type="text" name='login[username]' placeholder="Email*" class="ele_width required-entry validate-email"/>
                        </div>
                        <div class="form-group input-form">
                            <!-- <label class="popup-login-lbl" for="password"><em>*</em> <//?php echo $this->__("Password")?></label> -->
                            <input id="passwd-login" type="password" name="login[password]" placeholder="Password*" class="ele_width required-entry consistent-password"/>
                            <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
                            <div class="">
                                <img class="eye-image show-hide-on-click" src="<?php echo $this->getSkinUrl("images/redesign/eye.png")?>" alt="">
                                <img class="eye-image show-hide-on-click close-eye" src="<?php echo $this->getSkinUrl("images/eye-c.png")?>" alt="">
                            </div>
                        </div>
                        <div class="forget-password">
                            <a class="link-button" onclick="openRestPasswordModal()"><?php echo $this->__("Forgot Password")?></a>
                        </div>
                        <div class="submit-login text-right position-relative">
                    <span id="popup_loader" class="please-wait-popup" style="display: none;">
                    <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="Loading next step..." title="Loading next step..." class="v-middle"></span>
                            <button type="button" class="light-button pop-up-button sign-in-register" onclick="openRegisterModal()"><?php echo $this->__("Register")?></button>
                            <button type="button" id="signin-btn-popup" class="button dark-button pop-up-button"><?php echo $this->__("LogIn")?></button>
                        </div>
                    </div>
                  </div>
                </div>
                <div class="col-lg-5 col-md-12 col-12 guest-right">
                  <div class="row">
                      <div class="pop-link modal-footer col-12">
                          <div class="soc-login-btn row">
                            <div class="col-12 guest-checkout">
                              <div class="row justify-content-center">
                                <button type="button" onclick="guestCheckout()" class="light-button text-uppercase">Checkout as Guest</button>
                                </div>
                              </div>
                              <div class="option-text col-12">
                                  <div class="row justify-content-center">
                                      <p class="para-normal">Or sign in with:</p>
                                  </div>
                              </div>
                              <div class="col-12 social-options">
                                  <div class="row justify-content-center">
                                      <div class="mt-amazon-btn">
                                          <?php
                                          echo $this->getLayout()->createBlock('amazon_payments/login_button')->setTemplate('amazon_payments/login/popup_button.phtml')->toHtml();
                                          ?>
                                      </div>
                                      <?php //google connect code?>
                                      <?php if (Mage::helper('core')->isModuleEnabled('Allure_GoogleConnect')):?>
                                          <?php $isEnableGoogleSign = Mage::helper("allure_googleconnect")->_isEnabled();?>
                                          <?php if($isEnableGoogleSign):?>
                                              <div class="mt-googleconnect-btn">
                                                  <?php echo $this->getLayout()->createBlock('allure_googleconnect/button')
                                                      ->setTemplate("allure/googleconnect/button.phtml")->toHtml(); ?>
                                              </div>
                                          <?php endif;?>
                                      <?php endif;?>

                                      <?php //facebook connect code?>
                                      <?php if (Mage::helper('core')->isModuleEnabled('Allure_Facebook')):?>
                                          <?php $isEnableFacebook = Mage::getModel("facebook/config")->isEnabled();?>
                                          <?php if($isEnableFacebook):?>
                                              <div class="mt-facebookconnect-btn">
                                                  <?php echo $this->getLayout()->createBlock('facebook/button')
                                                      ->setTemplate("allure/facebook/button.phtml")->toHtml(); ?>
                                              </div>
                                          <?php endif;?>
                                      <?php endif;?>
                                  </div>
                              </div>

                          </div>
                      </div>
                    </div>
                  </div>
            </form>
        </div>
    </div>








<?php else: ?>
<div id="openModal" class="popupLoginModel">
    <div class="pop-up-cover">
        <form class="form-signin" action="<?php echo $this->getPostActionUrl() ?>" method="post" id="popup-login-form">
            <div class="pop-title modal-header">
                <a href="#close" title="Close" class="close exit-large">
                  <img class="d-lg-block d-md-block d-none" src="<?php echo $this->getSkinUrl('images/redesign/login-cross.png'); ?>" alt="x">
                  <img class="d-block d-lg-none d-md-none" src="<?php echo $this->getSkinUrl('images/redesign/exit-small-grey.png'); ?>" alt="x">                </a>
                <h1><?php echo $this->__("Login to My Account")?></h1>
            </div>
            <div class="body modal-body">
                <div id="login_msg_div">
                    <span class="invalid-login" id="login-msg"></span>
                </div>
                <div class="form-group input-form">
                    <!-- <label class="popup-login-lbl" for="email"><em>*</em> <//?php echo $this->__("Email Address")?></label> -->
                    <input id='username-login' type="text" name='login[username]' placeholder="Email*" class="ele_width required-entry validate-email"/>
                </div>
                <div class="form-group input-form">
                    <!-- <label class="popup-login-lbl" for="password"><em>*</em> <//?php echo $this->__("Password")?></label> -->
                    <input id="passwd-login" type="password" name="login[password]" placeholder="Password*" class="ele_width required-entry consistent-password"/>
                    <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
                    <div class="">
                      <img class="eye-image show-hide-on-click" src="<?php echo $this->getSkinUrl("images/redesign/eye.png")?>" alt="">
                        <img class="eye-image show-hide-on-click close-eye" src="<?php echo $this->getSkinUrl("images/eye-c.png")?>" alt="">
                    </div>
                </div>
                <div class="forget-password">
                    <a class="link-button" onclick="openRestPasswordModal()"><?php echo $this->__("Forgot Password")?></a>
                </div>
                <div class="submit-login text-right position-relative">
                <span id="popup_loader" class="please-wait-popup" style="display: none;">
                <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="Loading next step..." title="Loading next step..." class="v-middle"></span>
                    <button type="button" id="signin-btn-popup" class="button dark-button pop-up-button"><?php echo $this->__("LogIn")?></button>
                </div>
            </div>

            <div class="pop-link modal-footer col-12">
                <div class="soc-login-btn row">
                  <div class="option-text col-12">
                    <div class="row justify-content-center">
                      <p class="para-normal">Or sign in with:</p>
                    </div>
                  </div>
                  <div class="col-12 social-options">
                    <div class="row justify-content-center">
                      <div class="mt-amazon-btn">
                        <?php
                        echo $this->getLayout()->createBlock('amazon_payments/login_button')->setTemplate('amazon_payments/login/popup_button.phtml')->toHtml();
                        ?>
                      </div>
                    <?php //google connect code?>
                    <?php if (Mage::helper('core')->isModuleEnabled('Allure_GoogleConnect')):?>
                        <?php $isEnableGoogleSign = Mage::helper("allure_googleconnect")->_isEnabled();?>
                        <?php if($isEnableGoogleSign):?>
                        <div class="mt-googleconnect-btn">
                            <?php echo $this->getLayout()->createBlock('allure_googleconnect/button')
                                ->setTemplate("allure/googleconnect/button.phtml")->toHtml(); ?>
                        </div>
                        <?php endif;?>
                    <?php endif;?>

                    <?php //facebook connect code?>
                    <?php if (Mage::helper('core')->isModuleEnabled('Allure_Facebook')):?>
                        <?php $isEnableFacebook = Mage::getModel("facebook/config")->isEnabled();?>
                        <?php if($isEnableFacebook):?>
                        <div class="mt-facebookconnect-btn">
                            <?php echo $this->getLayout()->createBlock('facebook/button')
                                ->setTemplate("allure/facebook/button.phtml")->toHtml(); ?>
                        </div>
                        <?php endif;?>
                    <?php endif;?>
                  </div>
                </div>
                <div class="new_account col-12">
                  <div class="row justify-content-center">
                    <a class="link-button" onclick="openRegisterModal()"><?php echo $this->__("Create an account")?></a>
                  </div>
                </div>
                </div>
            </div>
        </form>
    </div>
</div>

<?php endif; ?>



<script type="text/javascript">
    if (typeof Allure == "undefined") {
        var Allure = {};
    }

    Allure.Wishlist='<?php echo Mage::getBaseUrl('web').'myaccount/#wishlist';?>';
    Allure.LoginFormKey = '<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>';
    Allure.LoginUrlAjax = '<?php echo Mage::getBaseUrl('web').'customers/account/ajaxLogin';?>';




</script>
