<div id="openModal" class="popupLoginModel">
    <div>
        <form class="form-signin" action="<?php echo $this->getPostActionUrl() ?>" method="post" id="popup-login-form">
            <div class="pop-title">
                <a href="#close" title="Close" class="close">
                  <img src="<?php echo $this->getSkinUrl('images/redesign/login-cross.png'); ?>" alt="">
                </a>
                <h1><?php echo $this->__("Log In to Your Account")?></h1>
            </div>
            <div class="body">
                <div id="login_msg_div">
                    <span id="login-msg"></span>
                </div>
                <div class="form-group">
                    <!-- <label class="popup-login-lbl" for="email"><em>*</em> <//?php echo $this->__("Email Address")?></label> -->
                    <input id='username-login' type="text" name='login[username]' placeholder="Email*" class="ele_width required-entry validate-email"/>
                </div>
                <div class="form-group">
                    <!-- <label class="popup-login-lbl" for="password"><em>*</em> <//?php echo $this->__("Password")?></label> -->
                    <input id="passwd-login" type="password" name="login[password]" placeholder="Password*" class="ele_width required-entry"/>

                    <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />

                </div>
            </div>
            <div class="pop-link">
                <div class="forget-password">
                    <a onclick="openRestPasswordModal()"><?php echo $this->__("Forgot Password")?></a>
                </div>
                <div class="new_account">
                    <a onclick="openRegisterModal()"><?php echo $this->__("Click here to create new account!")?></a>
                </div>
                <div class="submit-login">
                <span id="popup_loader" class="please-wait-popup" style="display: none;">
                <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="Loading next step..." title="Loading next step..." class="v-middle"></span>
                    <button type="button" id="signin-btn-popup" class="button"><?php echo $this->__("Log In")?></button>
                </div>

                <div class="soc-login-btn">
                    <?php //google connect code?>
                    <?php if (Mage::helper('core')->isModuleEnabled('Allure_GoogleConnect')):?>
                        <?php $isEnableGoogleSign = Mage::helper("allure_googleconnect")->_isEnabled();?>
                        <?php if($isEnableGoogleSign):?>
                            <div class="mt-googleconnect-btn">
                                <?php echo $this->getLayout()->createBlock('allure_googleconnect/button')
                                    ->setTemplate("allure/googleconnect/button.phtml")->toHtml(); ?>
                            </div>
                        <?php endif;?>
                    <?php endif;?>
                    <?php
                   echo $this->getLayout()->createBlock('amazon_payments/login_button')->setTemplate('amazon_payments/login/popup_button.phtml')->toHtml();

                    ?>
                    <?php //facebook connect code?>
                    <?php if (Mage::helper('core')->isModuleEnabled('Allure_Facebook')):?>
                        <?php $isEnableFacebook = Mage::getModel("facebook/config")->isEnabled();?>
                        <?php if($isEnableFacebook):?>
                            <div class="mt-facebookconnect-btn">
                                <?php echo $this->getLayout()->createBlock('facebook/button')
                                    ->setTemplate("allure/facebook/button.phtml")->toHtml(); ?>
                            </div>
                        <?php endif;?>
                    <?php endif;?>

                </div>

                <!-- <div class="benifits">
                    <p><strong><//?php echo $this->__("Create an account to access these benefits:")?></strong></p>
                    <ul class="popup-benifits">
                        <li><//?php echo $this->__("Keep track of your jewelry sizes")?></li>
                        <li><//?php echo $this->__("See your purchase history")?></li>
                        <li><//?php echo $this->__("Faster Checkout")?></li>
                        <li><//?php echo $this->__("Share your wishlist")?></li>
                        <li><//?php echo $this->__("Receive  personalized online service")?></li>
                        <li><//?php echo $this->__("$20 off your next purchase if you subscribe to our newsletter")?></li>
                    </ul>
                </div> -->

            </div>
        </form>
    </div>
</div>


<script type="text/javascript">
    if (typeof Allure == "undefined") {
        var Allure = {};
    }

    Allure.Wishlist='<?php echo Mage::getBaseUrl('web').'myaccount/#wishlist';?>';
    Allure.LoginFormKey = '<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>';
    Allure.LoginUrlAjax = '<?php echo Mage::getBaseUrl('web').'customers/account/ajaxLogin';?>';
</script>
