<style>
	#popup-wholesale-application-form label{
		width: 100%;
		font-size:12px;
		font-family: urw-din-light;
		text-align: left;
		text-transform: uppercase;
	}
	#popup-wholesale-application-form .pop-up-button{
		width: 100%;
		padding: 0 20px;
	}
	.popupApplicationModal .pop-up-cover{
		width: 1000px;
	}
	.popupApplicationModal .input-form input{
		width: 100%;
		height: 30px !important;
	}
	.popupApplicationModal .input-form textarea{
		min-height: 70px;
	}
	.popupApplicationModal .input-form{
		width: 100%;
		margin-bottom: 13px;
	}
	.popupApplicationModal .modal-footer{
		justify-content: start;
	}
	.popupApplicationModal .input-set {
	 	margin-bottom: 0;
	}

@media (max-width:1023px){
	.popupApplicationModal .pop-up-cover{
		width: 100%;
	}
}

</style>



<div id="openModal" class="popupRegisterModel popupApplicationModal">
	<div class="pop-up-cover">
		<form class="form-signup" method="post" id="popup-wholesale-application-form">
			<div class="pop-title modal-header">
				<a href="#close" title="Close" class="close exit-large">
					<img class="d-lg-block d-md-block d-none" src="<?php echo $this->getSkinUrl('images/redesign/login-cross.png'); ?>" alt="x">
					<img class="d-block d-lg-none d-md-none" src="<?php echo $this->getSkinUrl('images/redesign/exit-small-grey.png'); ?>" alt="x">
				</a>
			<h1 class="text-uppercase para-bold"><?php echo $this->__("Request a Trade Account")?></h1>
		</div>
		<div class="modal-body">
			<div class="input-set">
				<div id="reg_msg_div">
					<span id="register-msg"></span>
				</div>
				<div class="application-name col-12">
					<div class="row">
						<div class="application-info info-text-two mb-3">Please enter your details to request your free trade account or call us on: <span class="text-underline">+44203 8722545</span></div>
						<div class="input-form col-lg-6 col-md-6 col-12 pl-lg-0 pl-md-0">
								<label for="first_name">Please Enter your Name*</label>
				  		    <input id='firstname' placeholder="First Name" type="text" name='firstname' class="ele_width required-entry"/>
						</div>
						<div class="input-form col-lg-6 col-md-6 col-12 pr-lg-0 pr-md-0">
								<label class="invisible" for="first_name">Please Enter your Name*</label>
				  		    <input id='lastname' placeholder="Last Name" type="text" name='lastname' class="ele_width required-entry"/>
						</div>
					</div>
				</div>
				<div class="col-12">
					<div class="row">
					<div class="input-form">
						<label for="company_name">Please Enter your Company Name*</label>
			  		    <input id='company-name' type="text" name='company' class="ele_width required-entry required-entry"/>
					</div>
				</div>
			</div>
			<div class="application-name col-12">
				<div class="row">
					<div class="input-form">
						<label for="email_name">Please Enter your Email Address*</label>
			  		    <input id='email-register' type="text" name='email' class="ele_width required-entry validate-email"/>
					</div>
				</div>
			</div>
			<div class="application-name col-12">
				<div class="row">
					<div class="input-form">
						<label for="phone-number">Please Enter your Telephone Number*</label>
			  		    <input id='phone-no' type="text" name='phone-number' class="ele_width required-entry"/>
					</div>
				</div>
			</div>
			<div class="application-name col-12">
				<div class="row">
					<div class="input-form">
						<label for="company_website">Please Enter your Company company Website</label>
			  		    <input id='company-website' type="text" name='company-web' class="ele_width"/>
					</div>
				</div>
			</div>
			<div class="application-name col-12">
				<div class="row">
					<div class="input-form">
						<label for="message">Message</label>
			  		    <textarea class="w-100" id='company-website' type="text" name='company-web' class="ele_width"/>If you have any requests or require a quote please let us know.</textarea>
					</div>
				</div>
			</div>
		</div>
		<div class="pop-link modal-footer">
			<div class="pop-up-button-set row m-0">

				<div class="submit-login mb-5">
            <span id="popup_loader_register" class="please-wait-popup-register" style="display: none;">
                <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="Loading next step..." title="Loading next step..." class="v-middle"></span>
						<button type="button" id="" class="button dark-button pop-up-button"><?php echo $this->__("Submit Request")?></button>
				</div>
			</div>
        </div>
    </form>
	</div>
</div>
</div>

<!-- Notifiaction Popup -->
<div id="openModal" class="popupSignUpConfirmationModel">
	<div class="pop-up-cover">
		<div class="pop-title modal-header">
			<a  href="javascript:void(0);" title="Close" class="close towhishred exit-large">
				<img src="<?php echo $this->getSkinUrl('images/redesign/login-cross.png'); ?>" alt="">
			</a>
			<h1><?php echo $this->__("New Account Confirmation")?></h1>
		</div>
		<div class="body modal-body">
			<p class="para-normal">Thank you for joining Maria Tash!</p>

		</div>
	</div>
</div>



<script type="text/javascript">
if (typeof Allure == "undefined") {
	 var Allure = {};
}
Allure.RegisterModelFormKey = '<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>';
Allure.RegisterModelUrlAjax = '<?php echo Mage::getBaseUrl('web').'customers/account/createCustomer';?>';

            jQuery('.towhishred').click(function(event){
                event.preventDefault();event.stopPropagation();
                var wishvar = '<?php echo Mage::getSingleton("core/session")->getMywish();?>';
                var pid = '<?php echo Mage::getSingleton("core/session")->getPwish();?>';
                    if(pid && pid != ''){
                    jQuery('.link-wishlist').trigger('click');
                    <?php echo Mage::getSingleton("core/session")->unsPwish();?>;
                    setTimeout(function(){
                    window.location.href='<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) ?>'+"/myaccount/#wishlist";
                    }, 2000);
                     exit;
                }

});

Validation.addAllThese([
	['validate-password-custom', 'Please enter 6 or more characters without leading or trailing spaces.', function(v) {
        var pass=v.strip(); /*strip leading and trailing spaces*/
        return (!(v.length>0 && v.length < 6) && v.length == pass.length);
    }],
    ['validate-cpassword-custom', 'Please make sure your passwords match.', function(v) {
        var conf = $('confirmation1') ? $('confirmation1') : $$('.validate-cpassword-custom')[0];
        var pass = false;
        if ($('password1')) {
            pass = $('password1');
        }
        var passwordElements = $$('.validate-password-custom');
        for (var i = 0; i < passwordElements.size(); i++) {
            var passwordElement = passwordElements[i];
            if (passwordElement.up('form').id == conf.up('form').id) {
                pass = passwordElement;
            }
        }
        if ($$('.validate-admin-password').size()) {
            pass = $$('.validate-admin-password')[0];
        }
        return (pass.value == conf.value);
    }]
]);
</script>
