<div id="openModal" class="popupResetPasswordModel">
	<div class="pop-up-cover">
	<form class="form-resetpassword" method="post" id="popup-resetpassword-form">
		<div class="pop-title modal-header">
			<a href="#close" title="Close" class="close exit-large">
				<img class="d-lg-block d-md-block d-none" src="<?php echo $this->getSkinUrl('images/redesign/login-cross.png'); ?>" alt="x">
				<img class="d-block d-lg-none d-md-none" src="<?php echo $this->getSkinUrl('images/redesign/exit-small-grey.png'); ?>" alt="x">
			</a>
			<h1><?php echo $this->__("Forgot Password")?></h1>
		</div>
		<div class="body modal-body">
			<div id="resetpassword_msg_div">
				<span id="resetpassword-msg"></span>
			</div>
			<div class="form-group input-form">
	 		    <!-- <label class="popup-login-lbl" for="email"><//?php echo $this->__("Email Address")?></label> -->
	  		    <input id='resetEmail' type="text" name='email' placeholder="Email*" class="ele_width form-control required-entry validate-email"/>
			</div>
		</div>
        <div class="pop-link modal-footer">
					<div class="pop-up-button-set row">
						<div class="back-to-login col">
	        		<button id="resetpass-back-link" onclick="gotoLoginPage();" type="button" class="resetpass-back-link button light-button pop-up-button"><?php echo $this->__("Cancel")?></button>
						</div>
            <div class="submit-login col">
            	<span id="popup_loader_resetpassword" class="please-wait-popup" style="display: none;">
                <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="Loading next step..." title="Loading next step..." class="v-middle"></span>
                <button type="button" id="reset_pass_btn" class="button button dark-button pop-up-button"><?php echo $this->__("Submit")?></button>
            </div>
					</div>
        </div>
	</form>
	</div>
</div>


<script type="text/javascript">
if (typeof Allure == "undefined") {
	 var Allure = {};
}
Allure.ResetPassFormKey = '<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>';
Allure.ResetPassUrlAjax = '<?php echo Mage::getBaseUrl('web').'customers/account/forgotPasswordPost';?>';
</script>
