<div id="openModal" class="popupResetPasswordModel">
	<div>
	<form class="form-resetpassword" method="post" id="popup-resetpassword-form">
		<div class="pop-title">
			<a href="#close" title="Close" class="close">X</a>
			<h2><?php echo $this->__("Retrieve your password here")?></h2>
		</div>
		<div class="body">
			<div id="resetpassword_msg_div">
				<span id="resetpassword-msg"></span>
			</div>
			<div class="form-group">
	 		    <label class="popup-login-lbl" for="email"><?php echo $this->__("Email Address")?></label>
	  		    <input id='resetEmail' type="text" name='email' class="ele_width form-control required-entry validate-email"/>
			</div>
		</div>
        <div class="pop-link">
        	<a id="resetpass-back-link" onclick="gotoLoginPage();" class="resetpass-back-link"><?php echo $this->__("Back to login")?></a>
            <div class="submit-login">
            	<span id="popup_loader_resetpassword" class="please-wait-popup" style="display: none;">
                <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="Loading next step..." title="Loading next step..." class="v-middle"></span>
                <button type="button" id="reset_pass_btn" class="button"><?php echo $this->__("Submit")?></button>
            </div>
        </div>
	</form>
	</div>
</div>


<script type="text/javascript">
if (typeof Allure == "undefined") {
	 var Allure = {};
}
Allure.ResetPassFormKey = '<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>';
Allure.ResetPassUrlAjax = '<?php echo Mage::getBaseUrl('web').'customers/account/forgotPasswordPost';?>';
</script> 