<div class="cart-mt-checkout">
    <!-- <h2>Your Shopping Cart <a href="<//?php echo $this->getUrl('checkout/cart')?>">Edit</a></h2> -->
    <!-- <//?php $i=0; $prices = array(); $skus= array(); ?>
    <//?php foreach($this->getItems() as $_item): ?>
        <//?php if($i == 4) break; ?>
        <div class="cart-product">
            <//?php echo $this->getItemHtml($_item) ?>
            <//?php $prices[$i]=floatval($_item->getPrice()); $skus[$i] = $_item->getSku();  $i++?>
        </div>
    <//?php endforeach ?>
    <div class="viewAll">
        <a href="<//?php echo $this->getUrl('checkout/cart')?>">View All Items In Cart</a>
    </div> -->
    <div id="totalsDivRightNav" class="totals-right-nav">
        <?php echo $this->getChildHtml('totals'); ?>
    </div>
</div>
<div class="checkout-sidebar-bottom">
    <p class="para-normal">If you need any additional information,
        please use our <a class="link-button" target="_blank" href="https://v2.zopim.com/widget/livechat.html?key=33nWlKc4nRNVEDy4l4t8oH6sCLUod6pr&lang=en">live chat</a> or email us at <a class="link-button" href="mailto:cs@mariatash.com">cs@mariatash.com</a></p>
    <div class="links">
        <div class="info-text-three"><a href="/shipping-information" target="_self">Shipping Information</a></div>
        <div class="info-text-three"><a href="/policies" target="_self">Return Policy</a></div>
    </div>
</div>