<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    OnTap
 * @package     OnTap_Merchandiser
 * @copyright   Copyright (c) 2014 On Tap Networks Ltd. (http://www.ontapgroup.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
    $key = Mage::getSingleton('adminhtml/url')->getSecretKey('adminhtml/merchandiser/', 'saveOrdering'); 
    $url = $this->getUrl('adminhtml/merchandiser/saveOrdering');
?>

<script type="text/javascript">
    //<![CDATA[
    var merJSObject = new merchandiserJS();
    //]]>
</script>

<button type="button" class="button" onclick="var f=$('product-ordering-form'); f.action='<?php echo $url ?>'; merJSObject.showDimWindow(); merJSObject.removeResults(); f.submit();">
    <span>
        <span><?php echo Mage::helper('merchandiser')->__('Save positions') ?></span>
    </span>
</button>

<div id="dimwindow"></div>

<div id="dimwindow-inner">
    <img src ="<?php echo $this->getSkinUrl('merchandiser/images/rule-ajax-loader.gif') ?>" >
    <?php echo Mage::helper('merchandiser')->__('Saving category') ?>
</div>
