<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    OnTap
 * @package     OnTap_Merchandiser
 * @copyright   Copyright (c) 2014 On Tap Networks Ltd. (http://www.ontapgroup.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if (Mage::getSingleton('core/session')->getData('adminFormKey')): ?>
    <?php if ($_category = $this->getCurrentCategory()): ?>
        <?php
            $url = $this->getUrl("merchandiser/merchandiser", array('category_id' => $_category->getId()));
            $windowParams = 'menubar=no,location=no,width=1000px,left=140px';
        ?>
        <button type="button" onclick="window.open('<?php echo $url ?>', 'merchandiser.category.edit', '<?php echo $windowParams ?>')"><?php echo Mage::helper('merchandiser')->__('Launch Merchandiser') ?></button>
    <?php endif; ?>
<?php endif; ?>
