<?php
$embedded = $this->getRequest()->getParam('embedded');
$storeId = Mage::helper('appointments')->getStoreId();
?>
<?php
		$model = Mage::registry('apt_modify_data');
		if($model){
			$fetch_aptId = $model->getId();
		}

?>

<div class="appointmentContainer" >
<div class="<?php if($embedded=='1'): echo 'appointment-header'; endif;?>">
	<div class="app-col-6-left">
		<div class="page-title firsttitle"><h1>BOOK MY PIERCING</h1></div>
		<div class="secondtitle">Walk-in always welcome</div>
	</div>
	<?php if($embedded=='1'):?>
	<div class="app-col-6-right">
	<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId(Mage::helper('ecp_storelogo/data')->getConfigCmsBlock())->toHtml() ?>
	</div>
	<?php endif;?>
</div>
	<div id="aptformDiv">
	<?php if(Mage::getSingleton("core/session")->getData('appointment_submitted')):
			echo $this->getChildHtml('appointments_success');
		else:
		?>
		<?php //if(Mage::getSingleton("core/session")->getData('appointmentData_availablity')):?>
			<form action="<?php echo $this->getActionUrl()?>" name="" id="appointemnet_form" method="POST">
			<?php if($fetch_aptId):?> <input type="hidden" name="id" value="<?php echo $fetch_aptId;?>"><?php endif;?>
			<?php echo $this->getBlockHtml('formkey');?>
					<div class="field">
					      <div class="storeLocDiv">
					      	<?php echo $this->getChildHtml('appointments_storelocation')?>
					      </div>

					      <div class="AptPierDiv">
					      	<?php echo $this->getChildHtml('appointments_piercing')?>
					      </div>
					</div><!-- field end -->
					<div class="field">
						<div id="fetchpickurday"><?php echo $this->getChildHtml('appointments_pickurday')?></div>
						<div id="pick_ur_time_div"><?php echo $this->getChildHtml('appointments_pickurtime')?></div>
					</div><!-- field end -->
					<?php echo $this->getChildHtml('appointments_signin_register')?>


					<?php echo $this->getChildHtml('appointments_signin')?>


			</form>
		<?php //else:?>

		<?php //endif;?>
	<?php endif;?>
	</div>
	<!-- </div> -->
</div>
<div style="display:none;" id="appointment_loader" class="loading">Loading&#8230;</div>
<script type="text/javascript">
if (typeof Allure == "undefined") {
    var Allure = {};
}
Allure.appointmentId = '<?php echo $this->getRequest()->getParam('id')?>';
//console.log(Allure.appointmentId);
Allure.ajaxGetTimeUrl = '<?php echo $this->getTimeActionUrl()?>';
Allure.ajaxGetWorkingDaysUrl = '<?php echo $this->getWorkingDaysActionUrl()?>';
</script>

<script type="text/javascript">
    //< ![CDATA[

    <?php
    if(Mage::getSingleton('core/session')->getSlotInvalid()=="true")
    {
        echo "alert('This appointment time is no longer available.<br> Please select another time.');";
        Mage::getSingleton('core/session')->setSlotInvalid("false");
    }

    ?>
       var myForm = new VarienForm('appointemnet_form', false);

       var conf=false;

       /* Validation.add('required-entry-time', "Please Select Time.", function(v) {
            return !Validation.get('IsEmpty').test(v);
		});*/

        Validation.add('validate-phone-len', "Enter valid phone number with country code.", function(v) {
        	var telInput = jQuery("#phone").val();
            if(telInput.charAt(0)=='+' && v.length > 6){
            	return true;
            }
		});


        var formAlreadySubmitted = false;
        jQuery('#appointemnet_form').submit(function(e){
            if(myForm.validator.validate()) {
                if (formAlreadySubmitted) {
                    e.preventDefault();
                    return false;
                }


                var app_date = formatDate(new Date(jQuery("#datepicker-13_hidden").val()));
                var app_starttime = jQuery("#starttime_hidden").val();
                var app_endtime = jQuery("#endtime_hidden").val();
                var no_pepole = jQuery(".pierqtyTxt").val();

                var store = jQuery(".storeLocDiv p b").html();

                if(typeof store==="undefined")
                    store=jQuery(".storeLocationSelect :selected").text();


                if (no_pepole < 1) {
                    alert("Please select the number of people in your party.");
                    jQuery("html, body").animate({scrollTop: 0}, "slow");
                    jQuery("#count").focus();
                    return false;
                }

                if (no_pepole == 1)
                    var p = "person";
                else
                    var p = "people";


                if (jQuery(".required-entry-time").val().length == 0) {
                    alert("Please select Time slot.");
                    var position = jQuery(".pickur_time_main_container").position();
                    jQuery('body').scrollTo(position.top - 20);
                    return false;
                }

                if (!conf)
                {
                    var response = confirm("Please confirm your appointment at " + store + " on " + app_date + " from " + app_starttime + " - " + app_endtime + " for " + no_pepole + " " + p+".");
                return false;
            }
               // var response = confirm("Confirm your booking date:"+app_date+" from "+app_starttime+" to "+app_endtime+" for "+no_pepole+" "+p+" in "+store+" store");

                if (response == false) {
                    return false;
                }



                var submitChildren = jQuery(this).find('input[type=submit]');
                submitChildren.attr('disabled', 'disabled');
                submitChildren.addClass('disabled');
                formAlreadySubmitted = true;
              }

            });

    function formatDate(date) {
        var monthNames = [
            "Jan", "Feb", "Mar",
            "Apr", "May", "Jun", "Jul",
            "Aug", "Sep", "Oct",
            "Nov", "Dec"
        ];

        var day = date.getDate();
        var monthIndex = date.getMonth();
        var year = date.getFullYear();

        return monthNames[monthIndex] + ' ' +  day + ', ' + year;
    }






    if(document.getElementById) {
        window.confirm = function(txt) {
           return createCustomConfirm(txt);
        }
    }




    function createCustomConfirm(txt) {
        d = document;

        if(d.getElementById("allureModalContainer")) return;

        mObj = d.getElementsByTagName("body")[0].appendChild(d.createElement("div"));
        mObj.id = "allureModalContainer";
        mObj.style.height = d.documentElement.scrollHeight + "px";

        alertObj = mObj.appendChild(d.createElement("div"));
        alertObj.id = "allureAlertBox";
        if(d.all && !window.opera) alertObj.style.top = document.documentElement.scrollTop + "px";
        alertObj.style.left = (d.documentElement.scrollWidth - alertObj.offsetWidth)/2 + "px";
        alertObj.style.visiblity="visible";

        msg = alertObj.appendChild(d.createElement("p"));
        //msg.appendChild(d.createTextNode(txt));
        msg.innerHTML = txt;

        btnc = alertObj.appendChild(d.createElement("a"));
        btnc.id = "cancelConfirm";
        btnc.appendChild(d.createTextNode("CANCEL"));
        btnc.href = "#";


        btnc.onclick = function() {
            removeCustomAlert();
            return false;
        }


        btn = alertObj.appendChild(d.createElement("a"));
        btn.id = "okConfirm";
        btn.appendChild(d.createTextNode("OK"));
        btn.href = "#";
        btn.focus();
        btn.onclick = function() {
            removeCustomAlert();
            conf=true;
            jQuery('#appointemnet_form').trigger('submit');
        return false;
        }

        alertObj.style.display = "block";

    }





    //]]>
</script>
