<?php
$getCustomersInfo = Mage::helper('appointments/data')->getCustomersInfoSetting();
?>
<?php
$fetch_model = Mage::registry('apt_modify_data');
$customers=null;
if($fetch_model){
    $fetch_aptId = $fetch_model->getId();
    $f_custId = $fetch_model->getCustomerId();
    $f_firstName = $fetch_model->getFirstname();
    $f_lastName = $fetch_model->getLastname();
    $f_email = $fetch_model->getEmail();
    $f_telephone = $fetch_model->getPhone();
    $f_street = $fetch_model->getStreet();
    $f_city = $fetch_model->getCity();
    $f_cntry = $fetch_model->getCountry();
    $f_state = $fetch_model->getState();
    $f_postcode = $fetch_model->getPostalCode();
    $f_special_notes = $fetch_model->getSpecialNotes();
    $f_notification_pref = $fetch_model->getNotificationPref();

    $getCustomersInfo = Mage::helper('appointments/data')->getCustomersInfoSetting($fetch_model->getStoreId());

    $customers = Mage::getModel('appointments/customers')->getCollection();
    $customers->addFieldToFilter('appointment_id', $fetch_aptId);

}
/* else{
    $f_custId = '';
    $f_firstName = '';
    $f_lastName = '';
    $f_email = '';
    $f_telephone = '';
    $f_street = '';
    $f_city = '';
    $f_cntry = '';
    $f_state = '';
    $f_postcode = '';
} */
?>
<?php
$session = Mage::getSingleton('customer/session');
/* If the cust is logged in and Modifying record */
if ($session->isLoggedIn()) {
    $customer = Mage::getSingleton('customer/session')->getCustomer();
    $customerModel = Mage::getModel('customer/customer')->load($customer->getId());

    /* Fetching Data */
    $custId = $customer->getId();
    $firstName = $customerModel->getFirstname();
    $lastName = $customerModel->getLastname();
    $email = $customerModel->getEmail();
    $addressId = $customerModel->getDefaultBilling();
    if($addressId)
    {
        $address = Mage::getModel('customer/address')->load($addressId);
        $telephone = $address->getTelephone();
        $street = $address->getStreet();
        $city = $address->getCity();
        $cntry = $address->getCountry();
        $state = $address->getRegion();
        $postcode = $address->getPostcode();
    }
}
?>
<link href="<?php echo $this->getSkinUrl('css/contact/intlTelInput.css');?>"  rel="stylesheet" />
<!--<script src="--><?php //echo $this->getSkinUrl('js/contact/intlTelInput.min.js');?><!--"></script>-->
<script src="<?php echo $this->getSkinUrl('js/contact/intlTelInput.js');?>"></script>


<?php if($getCustomersInfo == 1):
?>
<input  type="hidden" name="id"   value="<?= $fetch_aptId ?>">

<?php
$count=1;
    if($customers):
foreach ($customers as $customer):
?>
<input  type="hidden" name="customer[<?= $count ?>][id]"   value="<?= $customer->getId() ?>">

<div class="field" id="reg_form">
    <div class="regDiv">
        <div id="customer_info_div" >
        <div id="customer_info_<?= $count ?>">
            <h6>Customer: <?= $count ?></h6>
            <div class="fieldDiv">
                <label><?= $this->__('First Name')?>*:</label><br/>
                <input class="ele_width apt_firstname" type="text" name="customer[<?= $count ?>][firstname]" id="firstname_1" placeholder="First Name*" value="<?= $customer->getFirstname() ?>">
            </div>
            <div class="fieldDiv">
                <label><?= $this->__('Last Name')?>*:</label><br/>
                <input class="ele_width apt_lastname" type="text" name="customer[<?= $count ?>][lastname]" id="lastname_1" placeholder="Last Name*" value="<?= $customer->getLastname() ?>">
            </div>
            <div class="fieldDiv">
                <label><?= $this->__('Email')?>*:</label><br/>
                <input class="ele_width apt_email" type="text" name="customer[<?= $count ?>][email]" id="email_1" placeholder="Email" value="<?= $customer->getEmail() ?>">
            </div>
            <div class="fieldDiv">
                <label><?= $this->__('Phone')?>*:</label><br/>
                <input class="ele_width apt_phone" type="text" name="customer[<?= $count ?>][phone]" id="phone_1" placeholder="Phone" value="<?= $customer->getPhone() ?>">
            </div>

            <div class="fieldDiv">
                <label><?= $this->__('Notify Me')?>:</label><br/>
                <div><input type="checkbox" name="customer[<?= $count ?>][noti_email]" title="" value="1" class="notifyRadio" <?php if($customer->getSmsNotification()=='0'):echo "checked"; endif?>  <?php if($f_notification_pref==null):echo "checked";endif?>><p><?= $this->__('By Email')?></p></div>
                <div><input type="checkbox" name="customer[<?= $count ?>][noti_sms]" title="" value="2" class="notifyRadio" <?php if($customer->getSmsNotification()=='1'):echo "checked";endif?>><p><?= $this->__('By Text Message - Message and Data Rates May Apply')?></p></div>
            </div>
        </div>
    </div>
    <div class="">
        <input type="submit" Value="CONFIRM" class="submitbtn" id="submitappt">
    </div>

    </div>
    <?php
    $count++;
    endforeach;
    else: ?>

    <div class="field" id="reg_form">
        <div class="regDiv"  >
            <div id="customer_info_div">
            <div id="customer_info_1">
                <h6>Customer: 1</h6>
                <div class="fieldDiv">
                    <label><?= $this->__('First Name')?>*:</label><br/>
                    <input class="ele_width apt_firstname" type="text" name="customer[1][firstname]" id="firstname_1" placeholder="First Name*" value="">
                </div>
                <div class="fieldDiv">
                    <label><?= $this->__('Last Name')?>*:</label><br/>
                    <input class="ele_width apt_lastname" type="text" name="customer[1][lastname]" id="lastname_1" placeholder="Last Name*" value="">
                </div>
                <div class="fieldDiv">
                    <label><?= $this->__('Email')?>*:</label><br/>
                    <input class="ele_width apt_email" type="text" name="customer[1][email]" id="email_1" placeholder="Email" value="">
                </div>
                <div class="fieldDiv">
                    <label><?= $this->__('Phone')?>*:</label><br/>
                    <input class="ele_width apt_phone" type="text" name="customer[1][phone]" id="phone_1" placeholder="Phone" value="">
                </div>

                <div class="fieldDiv">
                    <label><?= $this->__('Notify Me')?>:</label><br/>
                    <div><input type="checkbox" name="customer[1][noti_email]" title="" value="1" class="notifyRadio" <?php if($f_notification_pref=='1'):echo "checked"; endif?>  <?php if($f_notification_pref==null):echo "checked";endif?>><p><?= $this->__('By Email')?></p></div>
                    <div><input type="checkbox" name="customer[1][noti_sms]" title="" value="2" class="notifyRadio" <?php if($f_notification_pref=='2'):echo "checked";endif?>><p><?= $this->__('By Text Message - Message and Data Rates May Apply')?></p></div>
                </div>
            </div>
            </div>
            <div class="">
                <input type="submit" Value="CONFIRM" class="submitbtn" id="submitappt">
            </div>
        </div>
        <?php endif; ?>

        <div class="createaccDiv" >
            <div id="appointment-pricing">
                <?php echo $this->getChildHtml('appointments_piercing_pricing')?>
            </div>

        </div>
    </div>
    <script>country_code = "<?= Mage::getSingleton('allure_geolocation/geoLocation')->getCountryCode();?>";</script>
    <script src="<?php echo $this->getSkinUrl('js/allure/appointments/popupCustomerInfo.js');?>"></script>
    <style>
        input.apt_phone {
            width: 70%;
        }
    </style>
<?php else:?>

    <style>
        .hide {
            display: none;
        }
        #error-msg {
            color: red;
        }
        #valid-msg {
            color: #00C900;
        }
        input.error {
            border: 1px solid #FF7C7C;
        }
    </style>

    <?php if (!$session->isLoggedIn()) :?>
        <div class="field signin-field" >
            <button type="button" name="sign_in" href="#" id="signin-maria" class="button signin">Sign In With Mariatash</button>
        </div>
    <?php endif;?>

    <div class="field" id="reg_form">
        <div class="regDiv" >
            <input type="hidden" name="customer_id" value="<?php echo $custId?>">
            <div class="fieldDiv">
                <label><?= $this->__('First Name')?>*:</label><br/>
                <!-- <input class="ele_width required-entry validate-alpha" type="text" name="firstname" value="<?php //echo $firstName?>" />-->
                <input class="ele_width required-entry" type="text" name="firstname" value="<?php if($f_firstName):echo $f_firstName;else: echo $firstName; endif;?>" />
            </div>

            <div class="fieldDiv">
                <label><?= $this->__('Last Name')?>*:</label><br/>
                <!-- <input class="ele_width required-entry validate-alpha" type="text" name="lastname" value="<?php //echo $lastName?>" />-->
                <input class="ele_width required-entry"  type="text" name="lastname" value="<?php if($f_lastName): echo $f_lastName;else:echo $lastName;endif;?>" />
            </div>

            <div class="fieldDiv">
                <label><?= $this->__('Email')?>*:</label><br/>
                <!-- <input class="ele_width required-entry validate-email" type="text" name="email" value="<?php //echo $email?>" />-->
                <input class="ele_width required-entry validate-email"  type="text" name="email" value="<?php if($f_email):echo $f_email;else:echo $email;endif;?>" />
            </div>
            <div class="fieldDiv appt_ph">
                <label><?= $this->__('Phone Number')?>*:</label><br/>
                <input id="phone" name="phone" type="text" class="input-text ele_width validate-intl-telephone" value="<?php if($f_telephone):echo $f_telephone;else:echo $telephone;endif;?>">
            </div>

            <div class="fieldDiv">
                <label><?= $this->__('Address')?>:</label><br/>
                <!-- <input class="ele_width" type="text" name="street" value="<?php //echo $street['0']?>">-->
                <input class="ele_width" type="text" name="street" value="<?php if($f_street):echo $f_street;else: echo $street['0'];endif;?>" >
            </div>

            <div class="fieldDiv appt_country">
                <?php
                $countryList = Mage::getResourceModel('directory/country_collection')
                    ->loadData()
                    ->toOptionArray(Mage::helper('appointments')->__("Please Select Country"));
                ?>
                <label for="country"><?php echo Mage::helper('appointments')->__('Country') ?>:</label>
                <div class="">
                    <select name="country" class="ele_width countrySelect" onchange="getstate(this.value);">
                        <?php foreach ($countryList as $country) { ?>
                            <option	<?php if ($country['value']==$cntry || $country['value']==$f_cntry) echo 'selected' ; ?>
                                    value="<?php echo $country['value']; ?>" >
                                <?php echo $country['label']; ?></option>
                        <?php } ?>
                    </select>
                </div>
            </div>
            <div class="fieldDiv">
                <label for="state"><?php echo Mage::helper('appointments')->__('State') ?>:</label>
                <div class="input-box1" id='statediv'>
                    <?php

                    $statearray = array();
                    if ($cntry) {
                        $statearray = Mage::getModel('directory/region')->getResourceCollection()->addCountryFilter($cntry)->load();
                    }

                    if(count($statearray) > 0) :
                        $html .= "<select name='state' class='ele_width stateSelect'><option value=''>--Please Select--</option>";
                        foreach ($statearray as $_state) {
                            $selected = ($state == $_state->getDefaultName()) ? "selected" : "";
                            $html .= "<option value='" . $_state->getCode() . "' $selected>" . $_state->getDefaultName() . "</option>";
                        }
                        $html .= "</select>";
                        echo $html;
                    else :
                        ?>
                        <input name="state" id="state"  title="<?php echo Mage::helper('appointments')->__('State') ?>" value="<?php if($f_state): echo $f_state; else: echo $state; endif;?>" class="ele_width" type="text" />
                    <?php endif;?>
                </div>
            </div>
            <div class="fieldDiv">
                <label><?= $this->__('City')?>:</label><br/>
                <!--<input class="ele_width" type="text" name="city" value="<?php //echo $city?>"/>  -->
                <input class="ele_width" type="text" name="city" value="<?php if($f_city):echo $f_city;else: echo $city;endif;?>"/>
            </div>
            <div class="fieldDiv">
                <label><?= $this->__('Postal Code')?>:</label><br/>
                <!-- <input class="ele_width" type="text" name="postal_code" value="<?php //echo $postcode?>" /> -->
                <input class="ele_width" type="text" name="postal_code"  value="<?php if($f_postcode):echo $f_postcode;else: echo $postcode;endif;?>" />
            </div>

            <div class="fieldDiv splnotesDiv">
                <label><?= $this->__('Special Notes')?>:</label>
                <textarea class="splnotesTxtarea" name="special_notes" placeholder="<?php  echo Mage::helper('appointments')->__("Optional:Please specify names of people being pierced.") ?>" rows="4" ><?php if($f_special_notes):
                        echo $f_special_notes;
                    endif;?></textarea>
            </div>

            <div class="fieldDiv">
                <label><?= $this->__('Notify Me')?>:</label><br/>
                <div><input type="radio" name="notification_pref" title="" value="1" class="notifyRadio" <?php if($f_notification_pref=='1'):echo "checked"; endif?>  <?php if($f_notification_pref==null):echo "checked";endif?>><p><?= $this->__('By Email')?></p></div>
                <div><input type="radio" name="notification_pref" title="" value="2" class="notifyRadio" <?php if($f_notification_pref=='2'):echo "checked";endif?>><p><?= $this->__('By Text Message - Message and Data Rates May Apply')?></p></div>
            </div>
            <div class="fieldDiv " id="app_create_account">
                <?php if(!$session->isLoggedIn()):?>
                    <input type="checkbox" id="createaccCheck" name="create_acc" value="create_acc" style="position:inherit;"><?= $this->__('Create Account')?>:
                    <div class="pwdBlock">
                        <div class="fieldDiv">
                            <label><?= $this->__('Password')?>:</label><br/>
                            <input class="pass pwdele_width input-text validate-password " type="password" name="password" id="password" value="" />
                        </div><!-- validate-password validate-both-passwords -->
                        <div class="fieldDiv">
                            <label><?= $this->__('Confirm Password')?>:</label><br/>
                            <input class="pwdele_width input-text validate-cpassword" type="password" name="confirmpassword" id="confirmpassword" value="" />
                        </div>
                    </div>
                <?php endif;?>
            </div>

            <div class="fieldDiv">
                <?php echo $this->getChildHtml('studioforty9.recaptcha.explicit')?>
            </div>

            <div class="">
                <input type="submit" Value="CONFIRM" class="submitbtn" id="submitappt">
            </div><!-- field end -->
        </div>
        <div class="createaccDiv" >
            <div id="piercer_schedule" class="fieldDiv">

            </div>

            <?php if(0):?>
                <div class="fieldDiv splnotesDiv">
                    <label><?= $this->__('Special Notes')?>:</label>
                    <textarea class="splnotesTxtarea" name="special_notes" placeholder="<?php  echo "Optional:Please specify names of people being pierced or desired piercer for appointment" ?>" rows="4" ><?php if($f_special_notes):
                            echo $f_special_notes;
                        endif;?></textarea>
                </div>


                <div class="fieldDiv">
                    <label><?= $this->__('Notify Me')?>:</label><br/>
                    <div><input type="radio" name="notification_pref" title="" value="1" class="notifyRadio" <?php if($f_notification_pref=='1'):echo "checked";else: echo checked; endif?> ><p><?= $this->__('By Email')?></p></div>
                    <div><input type="radio" name="notification_pref" title="" value="2" class="notifyRadio" <?php if($f_notification_pref=='2'):echo "checked";endif?>><p><?= $this->__('By Text Message - Message and Data Rates May Apply')?></p></div>
                </div>
                <div class="fieldDiv " id="app_create_account">
                    <?php if(!$session->isLoggedIn()):?>
                        <input type="checkbox" id="createaccCheck" name="create_acc" value="create_acc" style="position:inherit;"><?= $this->__('Create Account')?>:
                        <div class="pwdBlock">
                            <div class="fieldDiv">
                                <label><?= $this->__('Password')?>:</label><br/>
                                <input class="pwdele_width input-text validate-password pass" type="password" name="password" id="password" value="" />
                            </div><!-- validate-password validate-both-passwords -->
                            <div class="fieldDiv">
                                <label><?= $this->__('Confirm Password')?>:</label><br/>
                                <input class="pwdele_width input-text validate-cpassword" type="password" name="confirmpassword" id="confirmpassword" value="" />
                            </div>
                        </div>
                    <?php endif;?>
                </div>
            <?php endif;?>

            <div id="appointment-pricing">
                <?php echo $this->getChildHtml('appointments_piercing_pricing')?>
            </div>

        </div>
    </div>
    <script type="text/javascript">
        jQuery(document).ready(function(){
            Allure.UtilPath = "<?= Mage::getDesign()->getSkinUrl(); ?>js/phone_validation/utils.js";

            //initialize itel tel input
            var input = document.querySelector("#phone")
            var iti = window.intlTelInput(input, {
                autoFormat: false,
                autoHideDialCode: false,
                autoPlaceholder: false,
                nationalMode: false,
                utilsScript: Allure.UtilPath
            });

            // take phone number and check if it exist
            // if it does not exist then
            // first check if we can get Geo Location based Country Code if its there then set it
            // otherwise set default as country as 'us'
            // Magento module - Allure/GeoLocation
            var phone = "<?php if($f_telephone):echo $f_telephone;else:echo $telephone;endif;?>";
            //console.log('[signing_register.phtml] length',phone.length)
            if(phone.length <= 0){
                var country_code = "<?= Mage::getSingleton('allure_geolocation/geoLocation')->getCountryCode();?>";

                if (country_code == undefined || country_code == null || country_code == "") {
                    country_code = "us"
                }

                iti.setCountry(country_code.toLowerCase());
            } else if (phone.charAt(0) != '+') {

                <?php if ((isset($f_cntry) && !empty($f_cntry))) { ?>
                var country_code = '<?php echo $f_cntry;?>';
                iti.setCountry(country_code.toLowerCase());
                <?php } ?>

                <?php if ((isset($cntry) && !empty($cntry))) { ?>
                var country_code = '<?php echo $cntry;?>';
                iti.setCountry(country_code.toLowerCase());
                <?php } ?>
            }

            //custom validator for itel tel input
            //FileName - intel-tel-validation.js
            allureIntlTelValidate(jQuery("#phone"),iti);
            jQuery(".flag-container").css("height","29px");

            jQuery.noConflict();
            /* jQuery("#createaccCheck").live('click',function(event){
                jQuery(".pwdBlock").toggle("show");
            }); */

            jQuery("#createaccCheck").change(function (){
                if(jQuery(this).is(":checked")){
                    jQuery(".pwdBlock").show();
                    jQuery(".pwdBlock input").addClass('required-entry');
                }
                else{
                    jQuery(".pwdBlock input").removeClass('required-entry');
                    jQuery(".pwdBlock").hide();

                }

            });

            jQuery( "#submitappt" ).click(function() {
                var password=jQuery('.pass').val();
                var confirmPass=jQuery('#confirmpassword').val();
                if(password!=confirmPass){
                    alert("Your Confirm Password is Wrong");
                    return false;
                }
                return true;
            });

        });

        function getstate(countryValue) {
            var reloadurl = '<?php echo $this->getUrl('*/index/state',array('_secure' => true)); ?>' + 'country/' + countryValue;
            jQuery.ajax({
                url: reloadurl, //Relative or absolute path to response.php file
                method: 'get',
                success: function (data) {
                    jQuery('#statediv').html(data);
                }
            });
        }
    </script>
    <script type="text/javascript">
        function isNumber(event){
            var keycode=event.keyCode;
            if((keycode>=48 && keycode<=57) ||(keycode==43))
            {
                return true;
            }
            return false;
        }

        function isText(event){
            var keycode=event.keyCode;
            if(((keycode>=65 && keycode<=90) ||(keycode>=97 && keycode<=122))||(keycode==32))
            {
                return true;
            }
            return false;
        }

        function isSymbol(event){

            return true;
            var keycode=event.keyCode;
            if(((keycode>=65 && keycode<=90) ||(keycode>=97 && keycode<=122)) || (keycode>=48 && keycode<=57) ||((keycode==64) ||(keycode==46)))
            {
                return true;
            }
            return false;
        }


        function isLocationText(event){
            var keycode=event.keyCode;
            if(((keycode>=65 && keycode<=90) ||(keycode>=97 && keycode<=122))||(keycode==32) ||(keycode==44))
            {
                return true;
            }
            return false;
        }

        function isAddressText(event) {
            var keycode=event.keyCode;
            if(((keycode>=33 && keycode<=43) ||(keycode>=60 && keycode<=64) ||(keycode>=91 && keycode<=96) || (keycode>=123 && keycode<=126)))
            {
                return false;
            }
            return true;
        }
    </script>
<?php endif;?>


