<?php
$embedded = $this->getRequest()->getParam('embedded');
?>
<?php 	
		$model = Mage::registry('apt_modify_data');
		if($model){
			$fetch_aptId = $model->getId();
		}		
		
?>
<div class="appointmentContainer" >
<div class="<?php if($embedded=='1'): echo 'appointment-header'; endif;?>">
	<div class="app-col-6-left">
		<div class="page-title firsttitle"><h1>BOOK MY PIERCING</h1></div>
		<div class="secondtitle">Walk-in always welcome</div>
	</div>
	<?php if($embedded=='1'):?>
	<div class="app-col-6-right">
	<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId(Mage::helper('ecp_storelogo/data')->getConfigCmsBlock())->toHtml() ?>
	</div>
	<?php endif;?>
</div>
	<div id="aptformDiv">
	<?php if(Mage::getSingleton("core/session")->getData('appointment_submitted')):
			echo $this->getChildHtml('appointments_success');
		else:
		?>
		<?php //if(Mage::getSingleton("core/session")->getData('appointmentData_availablity')):?>
			<form action="<?php echo $this->getActionUrl()?>" name="" id="appointemnet_form" method="POST">		
			<?php if($fetch_aptId):?> <input type="hidden" name="id" value="<?php echo $fetch_aptId;?>"><?php endif;?>
			<?php echo $this->getBlockHtml('formkey');?>
					<div class="field">
					      <div class="storeLocDiv">  
					      	<?php echo $this->getChildHtml('appointments_storelocation')?>    
					      </div>
					      
					      <div class="AptPierDiv">   
					      	<?php echo $this->getChildHtml('appointments_piercing')?>
					      </div>
					</div><!-- field end -->
					<div class="field">
						<div id="fetchpickurday"><?php echo $this->getChildHtml('appointments_pickurday')?></div>
						<div id="pick_ur_time_div"><?php echo $this->getChildHtml('appointments_pickurtime')?></div>
					</div><!-- field end -->
					<?php echo $this->getChildHtml('appointments_signin_register')?>
					<?php echo $this->getChildHtml('appointments_signin')?>
				   
					
			</form>
		<?php //else:?>
			
		<?php //endif;?>			
	<?php endif;?>
	</div>
	<!-- </div> -->
</div>

<script type="text/javascript">
if (typeof Allure == "undefined") {
    var Allure = {};
} 
Allure.appointmentId = '<?php echo $this->getRequest()->getParam('id')?>';
Allure.ajaxGetTimeUrl = '<?php echo $this->getTimeActionUrl()?>';
Allure.ajaxGetWorkingDaysUrl = '<?php echo $this->getWorkingDaysActionUrl()?>';
</script>

<script type="text/javascript">
    //< ![CDATA[
         
       var myForm = new VarienForm('appointemnet_form', false); 
        Validation.add('required-entry-time', "Please Select Time.", function(v) {
            return !Validation.get('IsEmpty').test(v);
		});
        
        Validation.add('validate-phone-len', "Enter Valid Mobile No with country code.", function(v) {
        	var telInput = jQuery("#phone").val();
            if(telInput.charAt(0)=='+' && v.length > 6){
            	return true;
            }               
		});

        
        var formAlreadySubmitted = false; 
        jQuery('#appointemnet_form').submit(function(e){ 
            if(myForm.validator.validate()){ 
                    if(formAlreadySubmitted){ 
                        e.preventDefault(); 
                        return false; 
                     } 
                   
                var submitChildren = jQuery(this).find('input[type=submit]'); 
                submitChildren.attr('disabled', 'disabled'); 
                submitChildren.addClass('disabled'); 
                formAlreadySubmitted = true; 
              } 

            });
     
    //]]>
</script>


