<?php
/**
*
*	Allure checkout step success order.
*
*/
if(Mage::getSingleton("core/session")->getData('appointment_availablity')):

	$model = Mage::registry('appointment_modified');
	$apt_id = $model->getId();
	$apt_email = $model->getEmail();
	//$encryptedId = Mage::helper('core')->encrypt($apt_id)->toString();
	//$encryptedEmail = Mage::helper('core')->encrypt($apt_email)->toString();	

?>
	<?php if($apt_id):?>
			<div class="page-title">
			    <h1><p class="detailofapt"><?php echo $this->__('Appointment Details') ?></p></h1>
			</div><hr/>
			<div class="checkout-success">
				<div class="success-field">
				<span class="apt-summary"><?php echo $this->__('Name') ?></span>
				<span class="apt-summary" style="font-weight: bold"><?php echo $model->getFirstname()." ".$model->getLastname() ?></span>
				</div>
				<div class="success-field">
				<span class="apt-summary"><?php echo $this->__('Email') ?></span>
				<span class="apt-summary" style="font-weight: bold"><?php echo $model->getEmail() ?></span>
				</div>
				<div class="success-field">
				<span class="apt-summary"><?php echo $this->__('Phone') ?></span>
				<span class="apt-summary" style="font-weight: bold"><?php echo $model->getPhone() ?></span>
				</div>
				<div class="success-field">
				<span class="apt-summary"><?php echo $this->__('No of People in Group') ?></span>
				<span class="apt-summary" style="font-weight: bold"><?php echo $model->getPiercingQty() ?></span>
				</div>
				<?php if($model->getPiercingLoc()):?>
				<div class="success-field">
				<span class="apt-summary"><?php echo $this->__('Piercing Location') ?></span>
				<span class="apt-summary" style="font-weight: bold"><?php echo $model->getPiercingLoc() ?></span>
				</div>
				<?php endif;?>
				<div class="success-field">
				<span class="apt-summary"><?php echo $this->__('Appointment Start') ?></span>
				<span class="apt-summary" style="font-weight: bold"><?php 
				$appStartDate=date("F j, Y H:i", strtotime($model->getAppointmentStart()));
				if($model->getStoreId())
					$format = Mage::helper('appointments')->getTimezoneShortCodeForeStore($model->getStoreId());
				else
					$format = "EST";
				
				echo  $appStartDate." ".$format?></span>
				</div>
				
				<div class="btns-setDiv">
					<div class="apt-cancel-buttons-set">
				         <button type="button" class="button" title="<?php echo $this->__('Cancel Appointment') ?>" onclick="confirmCancelApt();"><span><span><?php echo $this->__('Cancel') ?></span></span></button>
				    </div>
				    <div class="apt-modify-buttons-set">
				         <button type="button" class="button" title="<?php echo $this->__('Modify Appointment') ?>" onclick="window.location.href='<?php echo $this->getUrl('*',array('id'=>$apt_id,'email'=>$apt_email)); ?>'"><span><span><?php echo $this->__('Modify') ?></span></span></button>
				    </div>
				    
				   	<div class="apt-buttons-set">
				         <button type="button" class="button" title="<?php echo $this->__('Book Another Piercing') ?>" onclick="window.location.href='<?php echo Mage::getBaseUrl().$this->__('appointments');?>'"><span><span><?php echo $this->__('Book Another Piercing') ?></span></span></button>
					</div>
				</div>
			</div>
			
		<?php endif;?>
<!--  If the id or email not correct  -->	
<?php else:?>
			<div class="page-title">
			    <h1><p class="detailofapt"><?php echo $this->__('Sorry,Record not found to cancel the appointment!') ?></p></h1>
			</div><hr/>
			<div class="sryBookPierbtn" >
			     <button type="button" class="button" title="<?php echo $this->__('Book Another Piercing') ?>" onclick="window.location.href='<?php echo Mage::getBaseUrl().$this->__('appointments');?>'"><span><span><?php echo $this->__('Book Another Piercing') ?></span></span></button>
			</div>
<?php endif;?>


<script>
	/*function confirmCancelApt(){
		var result = confirm("Are you sure you want to Cancel an Scheduled Appointment?");

		if (result) {
		    //Logic to cancel the apt
			var reloadurl = '<?php echo $this->getUrl('*!/index/cancelapt',array('id'=>$apt_id,'email'=>$apt_email,'_secure' => true)); ?>';
		    jQuery.ajax({
		        url: reloadurl, //Relative or absolute path to response.php file
		        method: 'get',
		        success: function (data) {
					jQuery('.detailofapt').html(data);
					jQuery('.checkout-success .success-field').empty();
					jQuery('.checkout-success .apt-cancel-buttons-set').empty();
					jQuery('.checkout-success .apt-modify-buttons-set').empty();

		        }
		    });
		}
	}*/



    var conf=false;

    function confirmCancelApt() {

        if (!conf)
        {
            createCustomConfirm("Are you sure you want to cancel an scheduled appointment?");
            return false;
        }

        //Logic to cancel the apt
        var reloadurl = '<?php echo $this->getUrl('*/index/cancelapt',array('id'=>$apt_id,'email'=>$apt_email,'_secure' => true)); ?>';
        jQuery.ajax({
            url: reloadurl, //Relative or absolute path to response.php file
            method: 'get',
            success: function (data) {
                jQuery('.detailofapt').html(data);
                //jQuery('.checkout-success .success-field').empty();
                jQuery('.checkout-success .apt-cancel-buttons-set').empty();
                jQuery('.checkout-success .apt-modify-buttons-set').empty();

            }
        });

    }






    function createCustomConfirm(txt) {
        d = document;

        if(d.getElementById("allureModalContainer")) return;

        mObj = d.getElementsByTagName("body")[0].appendChild(d.createElement("div"));
        mObj.id = "allureModalContainer";
        mObj.style.height = d.documentElement.scrollHeight + "px";

        alertObj = mObj.appendChild(d.createElement("div"));
        alertObj.id = "allureAlertBox";
        if(d.all && !window.opera) alertObj.style.top = document.documentElement.scrollTop + "px";
        alertObj.style.left = (d.documentElement.scrollWidth - alertObj.offsetWidth)/2 + "px";
        alertObj.style.visiblity="visible";

        msg = alertObj.appendChild(d.createElement("p"));
        //msg.appendChild(d.createTextNode(txt));
        msg.innerHTML = txt;

        btnc = alertObj.appendChild(d.createElement("a"));
        btnc.id = "cancelConfirm";
        btnc.appendChild(d.createTextNode("CANCEL"));
        btnc.href = "#";


        btnc.onclick = function() {
            removeCustomAlert();
            return false;
        }


        btn = alertObj.appendChild(d.createElement("a"));
        btn.id = "okConfirm";
        btn.appendChild(d.createTextNode("OK"));
        btn.href = "#";
        btn.focus();
        btn.onclick = function() {
            removeCustomAlert();
            conf=true;
            confirmCancelApt();
            return false;
        }

        alertObj.style.display = "block";

    }

</script>


