<?php
/**
*
*	Allure checkout step success order.
*
*/
$model = Mage::getSingleton("core/session")->getData('appointment_submitted');
Mage::getSingleton("core/session")->setData('appointment_submitted',false);
?>
<div class="page-title">
    <h1><p class="detailofapt"><?php echo $this->__('Your Appointment has been confirmed!') ?></p></h1>
</div><hr/>
<div class="checkout-success">
    <h4><p class="detailofapt"><?php echo $this->__('Details of Appointment') ?></p></h4>
	<div class="success-field">
	<span class="apt-summary"><?php echo $this->__('Name') ?></span>
	<span class="apt-summary" style="font-weight: bold"><?php echo $model->getFirstname()." ".$model->getLastname() ?></span>
	</div>
	<div class="success-field">
	<span class="apt-summary"><?php echo $this->__('Email') ?></span>
	<span class="apt-summary" style="font-weight: bold"><?php echo $model->getEmail() ?></span>
	</div>
	<div class="success-field">
	<span class="apt-summary"><?php echo $this->__('Phone') ?></span>
	<span class="apt-summary" style="font-weight: bold"><?php echo $model->getPhone() ?></span>
	</div>
	<div class="success-field">
	<span class="apt-summary"><?php echo $this->__('No. of Piercings') ?></span>
	<span class="apt-summary" style="font-weight: bold"><?php echo $model->getPiercingQty() ?></span>
	</div>
	<div class="success-field">
	<span class="apt-summary"><?php echo $this->__('Piercing Location') ?></span>
	<span class="apt-summary" style="font-weight: bold"><?php echo $model->getPiercingLoc() ?></span>
	</div>
	<div class="success-field">
	<span class="apt-summary"><?php echo $this->__('Appointment Start') ?></span>
	<span class="apt-summary" style="font-weight: bold"><?php 
	$appStartDate= new Zend_Date(strtotime($model->getAppointmentStart()));
	$appStartDate = $appStartDate->toString();
	if($model->getStoreId())
		$format = Mage::helper('appointments')->getTimezoneShortCodeForeStore($model->getStoreId());
	else
			$format = "EST";
	echo  $appStartDate." ".$format?></span>
	</div>

    <div class="buttons-set apt-buttons-set">
         <button type="button" class="button" title="<?php echo $this->__('Book Another Piercing') ?>" onclick="window.location.reload();"><span><span><?php echo $this->__('Book Another Piercing') ?></span></span></button>
    </div>
</div>

