<?php 
/**
 * @category    Mana
 * @package     ManaPro_FilterCheckboxes
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */
/** 
 * Template for showing options for filter as a list of checkboxes 
 * @author Mana Team
 * Injected instead of standard catalog/layer/filter.phtml in Mana_Filters_Block_Filter_Attribute init() method.
 * This template is overridden by copying (template body was pasted from catalog/layer/filter.phtml 
 * and modified as needed). All changes are marked with comments.
 */
/* @var $this Mana_Filters_Block_Filter_Attribute */
?>
<ol class="m-filter-checkboxes">
<?php // print "<pre>";  var_export(get_class($this));    var_export(get_class_methods(get_class($this))); debug_print_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS); die;?>
<?php foreach ($this->getItems() as $_item): ?>
    <li <?php /*if ($_item->getMSelected()): ?>class="m-selected-ln-item"<?php endif;*/ ?>>

		
		<?php //Old code of Mana
			if(0):
		?>
	        <?php // MANA BEGIN ?>
			<input   type="checkbox" id="<?php echo $_item->getUniqueId($_item) ?>" value="<?php echo $_item->getValue() ?>" <?php if ($_item->getMSelected()): ?>checked="checked"<?php endif; ?> onClick="setLocation('<?php echo $this->urlEscape($_item->getMSelected() ? $_item->getRemoveUrl() : $_item->getUrl()) ?>');" />
	        <label onClick="setLocation('<?php echo $this->urlEscape($_item->getMSelected() ? $_item->getRemoveUrl() : $_item->getUrl()) ?>');" for="<?php echo $_item->getUniqueId($_item) ?>"><span></span></label>
			<label onClick="setLocation('<?php echo $this->urlEscape($_item->getMSelected() ? $_item->getRemoveUrl() : $_item->getUrl()) ?>');" for="<?php echo $_item->getUniqueId($_item) ?>"><span <?php if ($_item->getMSelected()): ?>class="m-selected-checkbox-item"<?php endif; ?>><?php echo $_item->getLabel() ?></span></label>
	        <?php // MANA END ?>
        <?php endif;?>
        
        <?php // Allure changed code Start ?>
		<input   type="checkbox" id="<?php echo $_item->getUniqueId($_item) ?>" value="<?php echo $_item->getValue() ?>" <?php if ($_item->getMSelected()): ?>checked="checked"<?php endif; ?> onClick="location.href='<?php echo $this->urlEscape($_item->getMSelected() ? $_item->getRemoveUrl() : $_item->getUrl()) ?>';" /> 
        <label onClick="location.href='<?php echo $this->urlEscape($_item->getMSelected() ? $_item->getRemoveUrl() : $_item->getUrl()) ?>';" for="<?php echo $_item->getUniqueId($_item) ?>"><span></span></label>
		<label onClick="location.href='<?php echo $this->urlEscape($_item->getMSelected() ? $_item->getRemoveUrl() : $_item->getUrl()) ?>';" for="<?php echo $_item->getUniqueId($_item) ?>"><span <?php if ($_item->getMSelected()): ?>class="m-selected-checkbox-item"<?php endif; ?>><?php echo $_item->getLabel() ?></span></label>
        <?php // Allure changed code End ?>
        
        <?php /*?>(<?php echo $_item->getCount() ?>)<?php */?>
    </li>
<?php endforeach ?>
</ol>
<?php echo Mage::helper('mana_core')->getNamedHtml('mana_filters/markup', 'after_items', array('block' => $this)) ?>
