<?php 
	$collection = $this->getCollection();
	$helper = Mage::helper("inventory");
?>

<div class="content-header">
    <h3 class="icon-head"><?php echo $helper->__('Create  Purchase Order')?></h3>
  		
    <button id="create_po_btn" class="create_po_btn" ><?php echo $helper->__('Create Order')?></button>
     <button type="button"  style="float: right;
    margin-top: 10px;"  onclick="location.href='<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/inventory_purchase/confirm')?>'">
  		<?php echo $helper->__('View Items')?></button>
  		
    <button id="reset_po_btn" class="reset_po_btn" ><?php echo $helper->__('Reset')?></button>
    <button id="add_custom_item" style="float: right;
    margin-top: 10px;" class="add_custom_item" onclick="javascript:openMyPopup()" ><?php echo $helper->__('Add Custom Item')?></button>
</div>

<div class="success" style="display: none;"></div>
<div class="input-group">
	<label><?php echo $helper->__('STORE')?></label>
	<?php echo $this->getChildHtml('inventory_store');?>
	
  	<label><?php echo $helper->__('SCAN OR ENTER')?></label>
  	<input id="search" name="search" type="text" maxlength="150" placeholder="Sku,Name" 
  		value="<?php if($_GET['search']!=null){echo $_GET['search'];}?>" 
  		class="form-control"  aria-describedby="basic-addon2"/>
  	<button type="button" onclick="submitsearch()"><?php echo $helper->__('Search')?></button>
  	<button type="button" onclick="location.href='<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/inventory_purchase/new')?>'">
  		<?php echo $helper->__('Reset Filter')?></button>
 	<input style="float:right"  type="text" id="refence_no" class="refence_no" 
 		placeholder="<?php echo $helper->__('Add reference No')?>" />
</div>

<div class="pager-inventory">
	<?php echo $this->getPagerHtml(); ?>
</div>
<div class="prod-data">

	<table class="iventory-product table" style="width: 100%">
		<th><?php echo $helper->__('Image')?></th>
		<th><?php echo $helper->__('PRODUCT NAME')?></th>
        <th><?php echo $helper->__('Current Qty')?></th>
		<th><?php echo $helper->__('Vendor Sku')?></th>
		<th><?php echo $helper->__('Order Qty')?></th>
		<th><?php echo $helper->__('Cost/Item')?></th>
		<th><?php echo $helper->__('VMT Comment')?></th>
		<th><?php echo $helper->__('Include ?')?></th>
					
		<?php 
		$websiteId=1;
		if(Mage::getSingleton('core/session')->getMyWebsiteId())
			$websiteId=Mage::getSingleton('core/session')->getMyWebsiteId();
		$website=Mage::getModel( "core/website" )->load($websiteId);
		$stockId=$website->getStockId();
		?>
					
	    <?php 
	    	foreach ($collection as $_product):
	    	$product = Mage::getModel ( 'catalog/product' )->setStoreId($stockId)->load ( $_product->getId() );
	    ?>
			    <tr id="inventory-row-<?php echo $_product->getId(); ?>" class="inventory_tr">

					<td><img style="width: 50px; height: 50px;" class="product_inventory_thumbnail" src="<?php  echo  Mage::helper('catalog/image')->init($_product, 'thumbnail')->resize(75);?>"/></td>
					
					<td style="padding-left:20px;text-align:left">
						<p><?php echo $product->getName();?></p>
						<p><strong>SKU:</strong><?php echo $product->getSku();?></p>
				    </td>
				
					
					<td>
						<div>
							<label><?php echo round($_product->getQty())?></label>
						</div>
						
				   </td>
				    <td><input id="vendor_sku_<?php  echo $product->getId() ?>" style="width:150px"  
					 		name="qty[<?php echo $product->getId() ?>][<?php echo "vendor_sku" ?>]" 
					 		type="text" value="<?php echo $product->getVendorItemNo()?>"/>
					</td>
					<td>
					 	<input id="max_qty_<?php  echo $product->getId() ?>" style="width:50px"  
					 		name="qty[<?php echo $product->getId() ?>][<?php echo "max_qty" ?>]" 
					 		type="text" value="<?php echo round($product->getMaxQty())?>"/>
					</td>
						
					<td>
						<input id="cost_<?php  echo $product->getId() ?>" style="width:50px"  
							 name="qty[<?php echo $product->getId() ?>][<?php echo "cost" ?>]" 
							type="text" value="<?php echo round($product->getCost(),2)?>" />
							
						<div>
							<span>
								<?php 
								if($product->getCost()){ 
									echo  round($product->getCost(),2);
									}else {
										echo "0";
									}
								?>
							</span>
						</div>
					</td>
					<td>
						<div>
							<input type="hidden" id="is_custom_<?php echo $_product->getId()?>"name="qty[<?php echo $_product->getId() ?>][<?php echo "is_custom" ?>]" value="0">
							<textarea id="comment_<?php echo $_product->getId()?>" cols="15" rows="3"  name="qty[<?php echo $_product->getId() ?>][<?php echo "admin_comment" ?>]"/></textarea>
						</div>
					</td>
					<td>
						<div>
							<input id="<?php echo $product->getId()?>" type="checkbox" class="include_items" name="inclide"/>
							<br/>
							<?php $items=Mage::getModel('inventory/orderitems')->getCollection()->addFieldToFilter('product_id',$product->getId())
							->addFieldToFilter('is_custom',0)->addFieldToFilter('stock_id',$stockId)->setOrder('po_id','DESC');
							if(count($items)):
							$orderDetails=Mage::getModel('inventory/purchaseorder')->load($items->getFirstItem()->getPoId());
							?>
							<label><?php echo date('Y-m-d',strtotime($orderDetails->getCreatedDate()))."(".$items->getFirstItem()->getRequestedQty().")"?></label>
						   <?php endif;?>
						</div>
					</td>
				</tr>		
	    <?php endforeach ;?>
	 </table>
	 <div class="pager-inventory">
		<?php echo $this->getPagerHtml(); ?>
	</div>
	<?php if(!Mage::helper('allure_vendor')->isUserVendor()) :?>
     <table style="width:100%">
     	<tr>
      		<td>
      	 		<div style="float:right;margin-right: 10px">
      	 			<label><?php echo $helper->__('Order Total:')?></label>
      	 			<input disabled="disabled" id="order_total" style="margin-bottom: 10px" 
      	 				type="text" value="0">
      	 		</div>
      	 	</td>
      	</tr>
    </table>
 <?php endif;?>
</div>     	 
<div>
    <button id="create_po_btn2" class="create_po_btn"><?php echo $helper->__('Create Order')?></button>
</div>



<?php 
$podataCount=0;
$podata = Mage::getSingleton('core/session')->getMyItemsInfo();
if($podata['items'])
	$podataCount=count($podata['items']);
?>
    
<script type="text/javascript">
	jQuery.noConflict();
</script>
<script type="text/javascript">
	if (typeof Allure == "undefined") {
	   var Allure = {};
	}
	Allure.ViewPurchaseOrderFormKey = '<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>';
	Allure.InventoryStoreSwitch = '<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/inventory_stock/store', array('_secure' => true));?>';
	Allure.AddPurchaseItem = '<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/inventory_purchase/addpurchaseitem', array('_secure' => true));?>';
	Allure.GetStoredInfo = '<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/inventory_purchase/getstoredinfo', array('_secure' => true));?>';
	Allure.InventoryPurcaseCreateOrder = '<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/inventory_purchase/createOrder', array('_secure' => true));?>';
	Allure.Reset = '<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/inventory_purchase/reset', array('_secure' => true));?>';

	function openMyPopup() {

        var url = '<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/inventory_purchase/addCustomItem') ?>?';

        var dialogWindow = Dialog.info(null, {
            closable:true,
            resizable:false,
            draggable:true,
            className:'magento',
            windowClassName:'popup-window',
            title:'Add custom item to purchase order',
            top:50,
            width:600,
            height:200,
            zIndex:1000,
            recenterAuto:false,
            hideEffect:Element.hide,
            showEffect:Element.show,
            id:'browser_window',
            url:url,
            onClose:function (param, el) {
               // alert('onClose');
            	getStoredData();
            }
        });
    }

    function closePopup() {
        Windows.close('browser_window');
    }
	</script>