<?php
/**
 * Created by PhpStorm.
 * User: ajay
 * Date: 1/8/17
 * Time: 6:10 PM
 */


$helper = Mage::helper("inventory");
$websiteId=1;
if(Mage::getSingleton('core/session')->getMyWebsiteId())
    $websiteId=Mage::getSingleton('core/session')->getMyWebsiteId();
$website=Mage::getModel( "core/website" )->load($websiteId);
$stockId=$website->getStockId();
$orderItems=$helper->getPurchaseOrderItems($stockId);
/* echo "<pre>";
print_r($orderItems); */

?>

<div class="content-header">
    <h3 class="icon-head"><?php echo $helper->__('Create  Purchase Order Confirmation')?></h3>

    <button id="create_po_btn" class="create_po_btn" ><?php echo $helper->__('Create Order')?></button>
    <button id="reset_po_btn" class="reset_po_btn" ><?php echo $helper->__('Reset')?></button>
    <button type="button" style="float: right;
    margin-top: 10px;" onclick="location.href='<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/inventory_purchase/new')?>'">
  		<?php echo $helper->__('Add More Items')?></button>
</div>

<div class="success" style="display: none;"></div>
<div class="input-group">
    <label><?php echo $helper->__('STORE')?></label>
    <select id="store">
        <?php
        $websiteId=1;
        if(Mage::getSingleton('core/session')->getMyWebsiteId())
            $websiteId=Mage::getSingleton('core/session')->getMyWebsiteId();
        ?>
        <?php foreach (Mage::app()->getWebsites() as $website) :?>
            <option <?php if($website->getId()==$websiteId) echo "selected"?>
                value="<?php echo $website->getId()?>"><?php echo $website->getName();?>
            </option>
        <?php endforeach;?>
    </select>

    <?php echo $this->getChildHtml('inventory_store');?>
    <label><?php echo $helper->__('SCAN OR ENTER')?></label>
    <input id="search" name="search" type="text" maxlength="150" placeholder="Sku,Name"
           value="<?php if($_GET['search']!=null){echo $_GET['search'];}?>"
           class="form-control"  aria-describedby="basic-addon2"/>
    <button type="button" onclick="submitsearch()"><?php echo $helper->__('Search')?></button>
    <button type="button" onclick="location.href='<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/inventory_purchase/new')?>'">
        <?php echo $helper->__('Reset Filter')?></button>
    <input style="float:right"  type="text" id="refence_no" class="refence_no"
           placeholder="<?php echo $helper->__('Add reference No')?>" ;/>
</div>

<div class="pager-inventory">
    <?php echo $this->getPagerHtml(); ?>
</div>
<div class="prod-data">

    <table class="iventory-product table" style="width: 100%">
        <th><?php echo $helper->__('SKU')?></th>
        <th><?php echo $helper->__('Image')?></th>
        <th><?php echo $helper->__('PRODUCT NAME')?></th>
        <th><?php echo $helper->__('VENDOR SKU')?></th>
        <th><?php echo $helper->__('Order Qty')?></th>
        <th><?php echo $helper->__('Cost/Item')?></th>
        <th><?php echo $helper->__('VMT Comment')?></th>
        <th><?php echo $helper->__('Include ?')?></th>

        <?php
        foreach ($orderItems as $item):
            if ($item['is_custom']) {
                $product = Mage::getModel('inventory/customitem')->load($item['item_id']);
                $thumnailURL='';
            } else {
                $product = Mage::getModel('catalog/product')->setStoreId($stockId)->load($item['item_id']);
             
                $thumnailURL=Mage::helper('catalog/image')->init($product, 'thumbnail')->resize(75);
            }
            ?>
            <tr id="inventory-row-<?php echo $product->getId(); ?>" class="inventory_tr">
                <td><?php echo $product->getSku();?></td>
                <?php ?>
                <td><img style="width: 75px; height: 75px;" class="product_inventory_thumbnail" src="<?php  echo $thumnailURL  ;?>"/></td>
                <td><?php echo $product->getName();?></td>

                <td><input id="vendor_sku_<?php  echo $product->getId() ?>" style="width:150px"  
					 		name="qty[<?php echo $product->getId() ?>][<?php echo "vendor_sku" ?>]" 
					 		type="text" value="<?php echo $item['vendor_sku']?>"/>
					</td>
                <td>
                    <div>
                        <label><?php echo round($item['qty'])?></label>
                       <input id="max_qty_<?php  echo $product->getId() ?>" style="width:50px"  
					 		name="qty[<?php echo $product->getId() ?>][<?php echo "max_qty" ?>]" 
					 		type="text" value="<?php echo round($item['qty'])?>"/>
                    </div>
                </td>
                <td>
                    <div>
							<span>
								<?php
								if($item['cost']){
								    echo  round($item['cost'],2);
                                }else {
                                    echo "0";
                                }
                                ?>
							</span>
                    </div>
                    <input id="cost_<?php  echo $product->getId() ?>" style="width:50px"
                           type="hidden" name="qty[<?php echo $product->getId() ?>][<?php echo "cost" ?>]"
                           type="text" value="<?php echo round($item['cost'])?>" />
                </td>
                <td>
                    <div>
                    	<input type="hidden" id="is_custom_<?php echo $product->getId()?>"name="qty[<?php echo $product->getId() ?>][<?php echo "is_custom" ?>]" value="<?php echo $item['is_custom']?>">
                        <textarea id="comment_<?php echo $product->getId()?>" cols="15" rows="3"  name="qty[<?php echo $product->getId() ?>][<?php echo "admin_comment" ?>]"/><?php echo $item['comment']?></textarea>
                    </div>
                </td>
                <td>
                    <div>
                        <input id="<?php echo $product->getId()?>" type="checkbox" name="inclide"/>
                    </div>
                </td>
            </tr>

        <?php endforeach ;?>
       
    </table>
    <div class="pager-inventory">
        <?php echo $this->getPagerHtml(); ?>
    </div>
    <table style="width:100%">
        <tr>
            <td>
                <div style="float:right;margin-right: 10px">
                    <label><?php echo $helper->__('Order Total:')?></label>
                    <input disabled="disabled" id="order_total" style="margin-bottom: 10px"
                           type="text" value="0">
                </div>
            </td>
        </tr>
    </table>

</div>
<div>
    <button id="create_po_btn2" class="create_po_btn"><?php echo $helper->__('Create Order')?></button>
</div>

<?php
$podataCount=0;
$podata = Mage::getSingleton('core/session')->getMyItemsInfo();
if($podata['items'])
    $podataCount=count($podata['items']);
?>

<script type="text/javascript">
    jQuery.noConflict();
</script>

<script type="text/javascript">
    if (typeof Allure == "undefined") {
        var Allure = {};
    }
    Allure.ViewPurchaseOrderFormKey = '<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>';
    Allure.InventoryStoreSwitch = '<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/inventory_stock/store', array('_secure' => true));?>';
    Allure.AddPurchaseItem = '<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/inventory_purchase/addpurchaseitem', array('_secure' => true));?>';
    Allure.GetStoredInfo = '<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/inventory_purchase/getstoredinfo', array('_secure' => true));?>';
    Allure.InventoryPurcaseCreateOrder = '<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/inventory_purchase/createOrder', array('_secure' => true));?>';
    Allure.Reset = '<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/inventory_purchase/reset', array('_secure' => true));?>';

</script>