<?php $oGiftCardSession = Mage::getSingleton('giftcards/session'); ?>

<div class="discount">
    <h2><?php echo $this->__('Gift Cards'); ?></h2>

    <div class="discount-form">
        <form method="post" action="<?php echo $this->getUrl('giftcards/cart/activateGiftCard'); ?>" id="activateGiftCard">
            <div class="input-box">
                <input value="" name="giftcard_code" id="giftcard_code" class="input-text">
            </div>
            <div class="buttons-set">
                <button value="<?php echo $this->__('Activate') ?>" onclick="applyGiftcard(true)" class="button_coupon" title="Apply" type="button"><span><span><?php echo $this->__('Apply') ?></span></span>
                </button>
            </div>
            
            <div class="myaccount-discount-msg">
            	<p></p>
            </div>
            
        </form>

        <?php $currencySymbol = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); $temp = 0; ?>
        <?php if($oGiftCardSession->getActive())
                    foreach($oGiftCardSession->getFrontOptions() as $k => $v)
                    {
                        if($temp) {
                            echo '<br/><br/>';
                        }
                        echo '<p><b>'.$currencySymbol.$v['applied'].' '.$this->__('applied from Gift Card').' **********'.$v['code'].'.</b><br/>';
                        echo $this->__('Remaining card balance').': '.$currencySymbol.$v['remaining'].'.</p><a onclick="removeCoupan('.$k.')" href="javascript:void(0);" class="button_coupon" style="position:relative; top:-20px;"><span><span>'.$this->__('Remove').'</span></span></a>';
                        $temp = 1;
                    }
        ?>
    </div>
    <script type="text/javascript">
        //&lt;![CDATA[
        var deActivateGiftCardForm = new VarienForm('deActivateGiftCard');
        var giftCardForm = new VarienForm('activateGiftCard');
        //]]&gt;

        function applyGiftcard(remove){
       	 var coupon_code = jQuery('#giftcard_code').val();
       	 if(coupon_code==null || coupon_code==""){
       		jQuery('.myaccount-discount-msg p').text("Enter coupan code.");
	        jQuery('.myaccount-discount-msg').show();
	        return false;
       	 }
       	 
       	 showLoadingFancybox();
       	 jQuery.ajax({
       	        url: '<?php echo Mage::getBaseUrl('web').'checkout/cart/activateGiftCardAjax';?>',
       	        dataType : 'json',
       			type : 'POST',
       			data: {giftcard_code:coupon_code,remove:remove},
       	        success: function(data) {
       	        	if(data.success){
       	        		jQuery('.mt-my-cart').html("");
			        	jQuery('.mt-my-cart').html(data.html);
       	        	}else{
      	        		jQuery('.myaccount-discount-msg p').text(data.message);
          	        	jQuery('.myaccount-discount-msg').show();
      	        	}
       	        	hideLoadingFancybox();
       	        }
       	    });
       }

       function removeCoupan(id){
    	   showLoadingFancybox();
    	   jQuery.ajax({
      	        url: '<?php echo Mage::getBaseUrl('web').'checkout/cart/deActivateGiftCardAjax';?>',
      	        dataType : 'json',
      			type : 'POST',
      			data: {id:id},
      	        success: function(data) {
      	        	if(data.success){
      	        		jQuery('.mt-my-cart').html("");
			        	jQuery('.mt-my-cart').html(data.html);
      	        	}
      	        	hideLoadingFancybox();
      	        }
      	    });
       }
    </script>

</div>
