<?php 
	$collection = $this->getCollection();
	$helper = Mage::helper("inventory");
?>
<div class="content-header">
	<h3 class="icon-head"><?php echo $helper->__('Min/Max Updates')?></h3>
    <button style="float:right" form="inventory_receive"><?php echo $helper->__('Update')?></button>
</div>
<div class="input-group">
	<label><?php echo $helper->__('STORE')?></label>
	<?php echo $this->getChildHtml('inventory_store');?>
	
  	<label><?php echo $helper->__('SCAN OR ENTER')?></label>
  	<input id="search" name="search" type="text" maxlength="150" placeholder="<?php echo $helper->__('Sku, Name')?>" 
  		value="<?php if($_GET['search']!=null){echo $_GET['search'];}?>" class="form-control"  
  		aria-describedby="basic-addon2"/>
  	<button  type="button" onclick="submitsearch()"><?php echo $helper->__('Search')?></button>
  	<button  type="button" onclick="resetSearch()"><?php echo $helper->__('Reset Filter')?></button>
</div>

<form id="inventory_receive" action="<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/inventory_stock/minmaxUpdate', array('_secure' => true));?>" method="post">
	<div class="pager-inventory">
		<?php echo $this->getPagerHtml(); ?>
	</div>

	<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
	<table class="iventory-product table" style="width: 100%">
		<th><?php echo $helper->__('SKU')?></th>
		<th><?php echo $helper->__('Image')?></th>
		<th><?php echo $helper->__('PRODUCT NAME')?></th>
		<th><?php echo $helper->__('Total Qty')?></th>
		<th><?php echo $helper->__('Min Qty')?></th>
		<th><?php echo $helper->__('Max Qty')?></th>
		<th><?php echo $helper->__('Cost')?></th>
		<?php 
		$websiteId=1;
		if(Mage::getSingleton('core/session')->getMyWebsiteId())
			$websiteId=Mage::getSingleton('core/session')->getMyWebsiteId();
		$website=Mage::getModel( "core/website" )->load($websiteId);
		$stockId=$website->getStockId();
		?>
	    <?php 
	    	foreach ($collection as $_product):
	    	$product = $_product;//Mage::getModel ( 'catalog/product' )->setStoreId($stockId)->load ( $_product->getId() );
	    ?>
		<tr id="inventory-row-<?php echo $product->getId(); ?>">
			<td><?php echo $_product->getSku();?></td>
			<td>
				<img style="width: 100px; height: 100px;" class="product_inventory_thumbnail" 
					src="<?php  echo  Mage::helper('catalog/image')->init($product, 'thumbnail')->resize(100);?>"/>
			</td>
			<td><?php echo $_product->getName();?></td>
			<?php 
				/* $inven=Mage::getModel('cataloginventory/stock_item')->
					loadByProductAndStock($_product,$stockId) */
			?>
						
			<td>
				<div><label><?php echo round($product->getQty())?></label>
				</div>
			</td>
						
			<td>
				
				<input style="width:50px"  name="qty[<?php echo $product->getId() ?>][<?php echo "notify_stock_qty" ?>]" 
				type="text" value=""/>
				
				<div>
					<span><?php echo "(". round($product->getData()['notify_stock_qty']).")"?></span>
				</div>
			</td>
						
			<td>
				
				<input style="width:50px"  name="qty[<?php echo $product->getId() ?>][<?php echo "max_qty" ?>]" 
					type="text" value=""/>
				<div>
					<span><?php echo "(". round($product->getMaxQty()).")"?></span>
				</div>
			</td>
						
			<td>
				<input style="width:50px"  name="qty[<?php echo $product->getId() ?>][<?php echo "cost" ?>]" 
					type="text" value=""/>
					<div>
						<span>
							<?php 
							if($product->getCost()){
								echo round($product->getCost(),2);
								}else {
									echo "Not Set";
								}
							?>
						</span>
					</div>
					
			</td>
		</tr>		
	   <?php endforeach ;?>
	 </table>
	 <div class="pager-inventory">
		<?php echo $this->getPagerHtml(); ?>
	</div>
 </form>   	 
<script type="text/javascript">
	jQuery.noConflict();
</script>
<script type="text/javascript">
	if (typeof Allure == "undefined") {
	   var Allure = {};
	}

	Allure.currentStore = 1; //main website default
	Allure.ViewPurchaseOrderFormKey = '<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>';
	Allure.InventoryStoreSwitch = '<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/inventory_stock/store', array('_secure' => true));?>';
</script>