<div id="notfound">
    <div class="notfound-bg"></div>
    <div class="notfound">
        <div class="notfound-404">
            <h1>404</h1>
        </div>
        <h2>Oops! Page Not Found</h2>
        <div class="notfound-social">
            <a href="https://www.instagram.com/maria_tash/"><i class="fa fa-instagram"></i></a>
            <a href="http://www.facebook.com/VenusbyMariaTash"><i class="fa fa-facebook"></i></a>
            <a href="https://twitter.com/mariatash/"><i class="fa fa-twitter"></i></a>
            <a href="https://www.pinterest.com/maria_tash/"><i class="fa fa-pinterest"></i></a>
            <a href="https://www.yelp.com/biz/maria-tash-new-york"><i class="fa fa-yelp"></i></a>
        </div>
        <a href="https://www.mariatash.com">Back To Homepage</a>
    </div>
</div>