
<div class="content-header">
	<h3 class="icon-head"><?php echo "Update Prices"?></h3>
</div>
<div class="main_outer" style="border:1px solid black;">
 <div class="sub_main" style="margin: 30px">
		<form id="priceUpdateForm" method="post" enctype="multipart/form-data" action="<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/scripts_index/priceupdatepost', array('_secure' => true));?>">
			<ul>
				<li>
		    		<label for="attachment"><?php echo Mage::helper('contacts')->__('File') ?></label>
		    		<div class="input-box">
		      		   <input name="attachment" id="attachment" class="input-text" type="file" />
		      		   <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
		    		</div>
				</li>
				<li>
					<label for="store"><?php echo Mage::helper('contacts')->__('STORE') ?></label>
		    		<div class="input-box">
			    		<select id="store" name="store">
						<?php foreach (Mage::app()->getWebsites() as $website) :?>  
						<option
						      value="<?php echo $website->getId()?>"><?php echo $website->getName();?>
						</option>
						<?php endforeach;?>
						</select>
					</div>
				</li>
				<li>
					<div class="">
		      		   <input name="submit" id="submit" class="input_submit" type="submit" />
		    		</div>
				</li>
			</ul>
		</form>

</div>
</div>
<script type="text/javascript">
var el = document.getElementById('priceUpdateForm');

el.addEventListener('submit', function(){
    return confirm('Are you sure you want to submit this form?');
}, false);
</script>

