<?php ?>
<div class="content-header">
	<h3 class="icon-head"><?php echo 'BOOK MY PIERCING' ?></h3>
</div>

<?php
$embedded = $this->getRequest()->getParam('embedded');
?>
<?php 	
		$model = Mage::registry('apt_modify_data');
		if($model){
			$fetch_aptId = $model->getId();
		}		
		
?>
<div class="appointmentContainer">
<div class="<?php if($embedded=='1'): echo 'appointment-header'; endif;?>"

	<?php if($embedded=='1'):?>
	<div class="app-col-6-right">
	<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId(Mage::helper('ecp_storelogo/data')->getConfigCmsBlock())->toHtml() ?>
	</div>
	<?php endif;?>
</div>
	<div id="aptformDiv">
	<?php if(Mage::getSingleton("core/session")->getData('appointment_submitted')):
			echo $this->getChildHtml('appointments_success');
		else:
		?>
		<?php //if(Mage::getSingleton("core/session")->getData('appointmentData_availablity')):?>
			<form action="<?php echo   Mage::getBaseUrl('web').'admin_appointments/index/save' ?>" name="" id="appointemnet_form" method="POST">		
			<?php if($fetch_aptId):?> <input type="hidden" name="id" value="<?php echo $fetch_aptId;?>"><?php endif;?>
			<?php echo $this->getBlockHtml('formkey');?>
					<div class="field">
					      <div class="storeLocDiv">  
					      	<?php echo $this->getChildHtml('appointments_storelocation')?>    
					      </div>
					      
					      <div class="AptPierDiv">   
					      	<?php echo $this->getChildHtml('appointments_piercing')?>
					      </div>
					</div><!-- field end -->
					<div class="field">
						<div id="fetchpickurday"><?php echo $this->getChildHtml('appointments_pickurday')?></div>
						<div id="pick_ur_time_div"><?php echo $this->getChildHtml('appointments_pickurtime')?></div>
					</div><!-- field end -->
					<?php echo $this->getChildHtml('appointments_signin_register')?>
					<?php echo $this->getChildHtml('appointments_signin')?>
					<div class="field">
						<input type="submit" Value="CONFIRM" class="submitbtn" >
					</div><!-- field end -->
			</form>
		<?php //else:?>
			
		<?php //endif;?>			
	<?php endif;?>
	</div>
	<!-- </div> -->
</div>

<script type="text/javascript">
Allure.adminAjaxGetTimeUrl = '<?php echo  Mage::getBaseUrl('web').'admin_appointments/index/ajaxGetTime'?>';
Allure.adminAjaxGetWorkingDaysUrl = '<?php echo Mage::getBaseUrl('web').'admin_appointments/index/ajaxGetWorkingDays';?>';
</script>

<script type="text/javascript">
    //< ![CDATA[
         
      
     
    //]]>
</script>


