<?php ?>
<div class="content-header">
	<h3 class="icon-head"><?php echo 'Book New Appointment' ?></h3>
	<button  onclick="location.href='<?php echo Mage::helper('adminhtml')->getUrl('admin_appointments/adminhtml_appointments/')?>'" style="float:right" id="book_another" class="book_another" ><?php echo 'Back' ?></button>
</div>

<?php
$embedded = $this->getRequest()->getParam('embedded');
?>
<?php
		$model = Mage::registry('apt_modify_data');
		if($model){
			$fetch_aptId = $model->getId();
		}

?>
<div class="appointmentContainer">

	<div id="aptformDiv">
	<?php if(Mage::getSingleton("core/session")->getData('appointment_submitted')):
			echo $this->getChildHtml('appointments_success');
		else:
		?>
		<?php //if(Mage::getSingleton("core/session")->getData('appointmentData_availablity')):?>
			<form action="<?php echo Mage::helper('adminhtml')->getUrl('admin_appointments/adminhtml_index/save'); ?>" name="" id="admin_appointemnet_form" method="POST">
			<?php if($fetch_aptId):?> <input type="hidden" name="id" value="<?php echo $fetch_aptId;?>"><?php endif;?>
			<?php //echo $this->getBlockHtml('formkey');?>
			<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
					<div class="field">
					      <div class="storeLocDiv">
					      	<?php echo $this->getChildHtml('appointments_storelocation')?>
					      </div>

					      <div class="AptPierDiv">
					      	<?php echo $this->getChildHtml('appointments_piercing')?>
					      </div>
					</div><!-- field end -->
					<div class="field">
						<div id="fetchpickurday"><?php echo $this->getChildHtml('appointments_pickurday')?></div>
						<div id="pick_ur_time_div"><?php echo $this->getChildHtml('appointments_pickurtime')?></div>
					</div><!-- field end -->
					<?php echo $this->getChildHtml('appointments_signin_register')?>
					<?php echo $this->getChildHtml('appointments_signin')?>
					<div class="field">
						<input type="submit" Value="CONFIRM" class="submitbtn" >
					</div><!-- field end -->
			</form>
		<?php //else:?>

		<?php //endif;?>
	<?php endif;?>
	</div>
	<!-- </div> -->
</div>

<script type="text/javascript">
if (typeof Allure == "undefined") {
    var Allure = {};
}
Allure.appointmentId = '<?php echo $this->getRequest()->getParam('id')?>';
Allure.adminFormKey = '<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>';
Allure.adminAjaxGetTimeUrl = '<?php echo  Mage::helper('adminhtml')->getUrl('admin_appointments/index/ajaxGetTime');?>';
Allure.adminAjaxGetWorkingDaysUrl = '<?php echo Mage::helper('adminhtml')->getUrl('admin_appointments/adminhtml_index/ajaxGetWorkingDays');?>';

</script>

<script type="text/javascript">
    //< ![CDATA[

       var myForm = new VarienForm('admin_appointemnet_form', false);
        Validation.add('required-entry-time', "Please Select Time.", function(v) {
            return !Validation.get('IsEmpty').test(v);
		});

        Validation.add('validate-phone-len', "Enter Valid Mobile No with country code.", function(v) {
        	var telInput = jQuery("#phone").val();
            if(telInput.charAt(0)=='+' && v.length > 6){
            	return true;
            }
		});


        var formAlreadySubmitted = false;
        jQuery('#admin_appointemnet_form').submit(function(e){
            if(myForm.validator.validate()){
                    if(formAlreadySubmitted){
                        e.preventDefault();
                        return false;
                     }

                var submitChildren = jQuery(this).find('input[type=submit]');
                submitChildren.attr('disabled', 'disabled');
                submitChildren.addClass('disabled');
                formAlreadySubmitted = true;
              }

            });

    //]]>
</script>





