<?php
/*
 *
 * Calender Events
 *
 *
 */
?>
<?php  echo Mage::app()->getLayout()->createBlock('appointments/adminhtml_switcher')->toHtml();

//echo Mage::app()->getLayout()->createBlock('appointments/registration','appointment_store',array('template' => 'appointments/appointment_store.phtml'))->toHtml();?>

<div class="content-header">
	<h3 class="icon-head"><?php echo 'Manage Piercers' ?></h3>
    <button  onclick="location.href='<?php echo Mage::getBaseUrl('web').'admin_appointments/adminhtml_appointments/new'?>'" style="float:right" id="book_another" class="book_another" ><?php echo 'Book New Appointment' ?></button>
</div>

<div id='calendar'></div>
<div id="loading-indicator-calender" ></div>

<?php $piercer_id = $this->getRequest()->getParam('piercer');?>

<script src="<?php echo $this->getSkinUrl('js/jQuery/jquery.min.js');?>"></script>


<script src="<?php echo $this->getSkinUrl('js/jQuery/jquery-ui.min.js');?>"></script>

<script src="<?php echo $this->getSkinUrl('js/jQuery/noconflict.js');?>"></script>

<link href="<?php echo $this->getSkinUrl('css/calender/fullcalendar.css');?>"  rel="stylesheet" />
<link href='<?php echo $this->getSkinUrl('css/calender/fullcalendar.print.css');?>' rel='stylesheet' media='print' />
<script src="<?php echo $this->getSkinUrl('js/calender/moment.min.js');?>"></script>
<script src="<?php //echo $this->getSkinUrl('js/calender/fullcalendar.js');?>"></script>
<script src="<?php echo $this->getSkinUrl('js/calender/fullcalendar.min.js');?>"></script>


<script>
	$j(document).ready(function() {

		var initialLangCode = 'en';
		$j('#loading-mask').show();

		var convertDate = function (dateString) {
			return new Date(dateString);
		}

 		<?php $k = Mage::getSingleton('core/session')->getFormKey(); ?>
		$j('#loading-indicator-calender').show();
		$j.ajax({
			url : '<?php echo $this->getUrl('*/*/calenderevents',array('_secure' => true));?>',
	 		dataType : 'json',
	 		type : 'POST',
	 		data: {'piercer_id':'<?php echo $piercer_id; ?>',form_key:'<?php echo $k ?>'},
	 		success : function(data){
		 		console.log(data.response.events);
		 		if(data.response.lang){
		 			initialLangCode = data.response.lang;
		 		}

		 		var events = [];

		 		var data = data.response.events;
				//console.log(data);
		 		for(var i = 0; i< data.length; i++){

					var startDate = convertDate(data[i].start);

					var endDate = convertDate(data[i].end);

					var color = data[i].color;

					events[i] =  {
	 					title: data[i].title,
	                    start: startDate,
	                    end: endDate,
	                    allDay: false,
	                    url : data[i].url,
	                    backgroundColor: color
		 			};
		 		}

				console.log(events);

		 		$j('#loading-mask').hide();

		 		$j('#calendar').fullCalendar({
		 			header: {
						left: 'prev,next today',
						center: 'title',
						right: 'month,agendaWeek,agendaDay,listMonth'
					},

					// customize the button names,
					// otherwise they'd all just say "list"
					slotDuration: '00:30:01',
					lang: initialLangCode,
					defaultDate: new Date(),
					navLinks: true, // can click day/week names to navigate views
					editable: true,
					eventLimit: true, // allow "more" link when too many events
					events: events,
					defaultView: 'agendaWeek',
				    aspectRatio: 1.5
				});
	 		}
		});
	});
			//jQuery(".appointments-adminhtml-appointments-viewcalender .myacc-heading").prepend(jQuery('#store_switcher :selected').text());
</script>
<style>


	#calendar {
		max-width: 1300px;
		margin: 0 auto;
	}

</style>
