<?php 
	$fetch_model = Mage::registry('apt_modify_data');
	
	if($fetch_model){
		$f_custId = $fetch_model->getCustomerId();
		$f_firstName = $fetch_model->getFirstname();
		$f_lastName = $fetch_model->getLastname();
		$f_email = $fetch_model->getEmail();
		$f_telephone = $fetch_model->getPhone();
		$f_street = $fetch_model->getStreet();
		$f_city = $fetch_model->getCity();
		$f_cntry = $fetch_model->getCountry();
		$f_state = $fetch_model->getState();
		$f_postcode = $fetch_model->getPostalCode();
		$f_special_notes = $fetch_model->getSpecialNotes();
		$f_notification_pref = $fetch_model->getNotificationPref();
	}	
	/* else{
		$f_custId = '';
		$f_firstName = '';
		$f_lastName = '';
		$f_email = '';
		$f_telephone = '';
		$f_street = '';
		$f_city = '';
		$f_cntry = '';
		$f_state = '';
		$f_postcode = '';
	} */
?>
<?php
$session = Mage::getSingleton('customer/session');
/* If the cust is logged in and Modifying record */
if ($session->isLoggedIn()) {
	$customer = Mage::getSingleton('customer/session')->getCustomer();
	$customerModel = Mage::getModel('customer/customer')->load($customer->getId());

	/* Fetching Data */
	$custId = $customer->getId();
	$firstName = $customerModel->getFirstname();
	$lastName = $customerModel->getLastname();
	$email = $customerModel->getEmail();
	$addressId = $customerModel->getDefaultBilling();
	if($addressId)
	{
		$address = Mage::getModel('customer/address')->load($addressId);
		$telephone = $address->getTelephone();
		$street = $address->getStreet();
		$city = $address->getCity();
		$cntry = $address->getCountry();
		$state = $address->getRegion();
		$postcode = $address->getPostcode();
	}
}
?>

		<div class="field" id="reg_form">
			  <div class="regDiv" >
				  	<input type="hidden" name="customer_id" value="<?php echo $custId?>">
					  	<div class="fieldDiv">
					  	   	<label>First Name*:</label><br/>
					    	<!-- <input class="ele_width required-entry validate-alpha" type="text" name="firstname" value="<?php //echo $firstName?>" />-->
					    	<input class="ele_width required-entry" type="text" name="firstname" value="<?php if($f_firstName):echo $f_firstName;else: echo $firstName; endif;?>" />
					    </div>
						
						<div class="fieldDiv">
					    	<label>Last Name*:</label><br/>
					    	<!-- <input class="ele_width required-entry validate-alpha" type="text" name="lastname" value="<?php //echo $lastName?>" />-->
					    	<input class="ele_width required-entry" type="text" name="lastname" value="<?php if($f_lastName): echo $f_lastName;else:echo $lastName;endif;?>" />
					    </div>
					
					  	<div class="fieldDiv">
					  	   	<label>Email*:</label><br/>
					    	<!-- <input class="ele_width required-entry validate-email" type="text" name="email" value="<?php //echo $email?>" />-->
					    	<input class="ele_width required-entry validate-email" type="text" name="email" value="<?php if($f_email):echo $f_email;else:echo $email;endif;?>" />
					    </div>
						<div class="">
					    	<label>Phone Number*:</label><br/>
					    	<!-- <input class="ele_width required-entry validate-number" type="text" name="phone" value="<?php //echo $telephone?>" />-->
					    	<input class="ele_width required-entry validate-phone-len" type="text" id="phone" name="phone" value="<?php if($f_telephone):echo $f_telephone;else:echo $telephone;endif;?>" />
					    </div>
					
						<div class="fieldDiv">
						  	<label>Address:</label><br/>
						    <!-- <input class="ele_width" type="text" name="street" value="<?php //echo $street['0']?>">-->
						    <input class="ele_width" type="text" name="street" value="<?php if($f_street):echo $f_street;else: echo $street['0'];endif;?>">
						</div>	
								
						<div class="fieldDiv">
					    	<?php 
					    	$countryList = Mage::getResourceModel('directory/country_collection')
							        ->loadData()
							        ->toOptionArray("Please Select Country");
							?>
						    <label for="country"><?php echo Mage::helper('appointments')->__('Country') ?>:</label>
						    <div class="">
						        <select name="country" class="ele_width countrySelect" onchange="getstate(this.value);">
						            <?php foreach ($countryList as $country) { ?>
						                <option	<?php if ($country['value']==$cntry || $country['value']==$f_cntry) echo 'selected' ; ?>
						                  value="<?php echo $country['value']; ?>" >
						                <?php echo $country['label']; ?></option>
						            <?php } ?>
						        </select>
						    </div>			    	
					    </div>
					    <div class="fieldDiv">
						    <label for="state"><?php echo Mage::helper('appointments')->__('State') ?>:</label>
						    <div class="input-box1" id='statediv'>
						    <?php 

						    $statearray = array();
						    if ($cntry) {
						    	$statearray = Mage::getModel('directory/region')->getResourceCollection()->addCountryFilter($cntry)->load();
						    }

						    if(count($statearray) > 0) :
						    	$html .= "<select name='state' class='ele_width stateSelect'><option value=''>--Please Select--</option>";
						    	foreach ($statearray as $_state) {
						    		$selected = ($state == $_state->getDefaultName()) ? "selected" : "";
						    		$html .= "<option value='" . $_state->getCode() . "' $selected>" . $_state->getDefaultName() . "</option>";
						    	}
						    	$html .= "</select>";
						    	echo $html;
						    else :
						    ?>
                    			<input name="state" id="state" title="<?php echo Mage::helper('appointments')->__('State') ?>" value="<?php if($f_state): echo $f_state; else: echo $state; endif;?>" class="ele_width" type="text" />
 							<?php endif;?>
                			</div>		    	
					    </div>
					    <div class="fieldDiv">
					  	   	<label>City:</label><br/>
					    	<!--<input class="ele_width" type="text" name="city" value="<?php //echo $city?>"/>  -->
					    	<input class="ele_width" type="text" name="city" value="<?php if($f_city):echo $f_city;else: echo $city;endif;?>"/>
					    </div>						    
					    <div class="fieldDiv">
					    	<label>Postal Code:</label><br/>
					    	<!-- <input class="ele_width" type="text" name="postal_code" value="<?php //echo $postcode?>" /> -->
					    	<input class="ele_width" type="text" name="postal_code" value="<?php if($f_postcode):echo $f_postcode;else: echo $postcode;endif;?>" />
					    </div>
		  	</div>
		  	<div class="createaccDiv" >
			  	  	<div class="fieldDiv splnotesDiv">
				  	   	<label>Special Notes:</label>			    		
				    	<textarea class="splnotesTxtarea" name="special_notes"  placeholder="<?php echo "Optional:Please specify names of people being pierced or desired piercer for appointment" ?>" rows="4" ><?php if($f_special_notes):
				    	echo $f_special_notes;
				    	endif;?></textarea>		    	
				    </div>
					<div class="fieldDiv">
				    	<label>Notify Me:</label><br/>
				    	<div><input type="radio" name="notification_pref" title="" value="1" class="notifyRadio" <?php if($f_notification_pref=='1'):echo "checked";else: echo checked; endif?> ><p>By Email</p></div>
				    	<div><input type="radio" name="notification_pref" title="" value="2" class="notifyRadio" <?php if($f_notification_pref=='2'):echo "checked";endif?>><p>By Text Message - Message and Data Rates May Apply</p></div>
				    </div>
				   
			</div>
		</div>
	
	<script type="text/javascript">
	jQuery(document).ready(function(){
		jQuery('#phone').intlTelInput();
		jQuery.noConflict();
		/* jQuery("#createaccCheck").live('click',function(event){
			jQuery(".pwdBlock").toggle("show");
		}); */	

		jQuery("#createaccCheck").change(function (){
			 if(jQuery(this).is(":checked")){
				 jQuery(".pwdBlock").show();
				 jQuery(".pwdBlock input").addClass('required-entry');					
			}
			 else{
				 jQuery(".pwdBlock input").removeClass('required-entry');
				 jQuery(".pwdBlock").hide();

			 }
			
		});	

		

	});
	
function getstate(countryValue) {
    var reloadurl = '<?php echo $this->getUrl('*/index/state',array('_secure' => true)); ?>' + 'country/' + countryValue;
    jQuery.ajax({
        url: reloadurl, //Relative or absolute path to response.php file
        method: 'get',
        success: function (data) {
            jQuery('#statediv').html(data);
        }
    });
}
</script>