<?php
	$model = Mage::registry('apt_modify_data');
	//$fetch_storeId = $model->getStoreId();
$storeIdNone = Mage::helper('appointments/data')->getPopupStoreId();

if($model){
	$fetch_storeId = $model->getStoreId();
	}
?>
<label for="store_location">Store Location:</label>
	<?php 
	$storeId = $this->getRequest()->getParam('store');
	$storeId_arr = explode(",", $storeId);
	$activeStores = $this->getActiveStore();
	 
	$multi_stores=array();
	
	if(count($storeId_arr) >= 1){
		
		if($storeId):
			foreach($storeId_arr as $st_key => $st_value){
				foreach ($activeStores as $key=>$store){
					if($st_value == $key){
						$requestStoreName = $store;
						$requestStoreId = $key;	
						
						$multi_stores[$requestStoreId]= $requestStoreName;					
					}
				}				
			}
			
		else:			
			foreach ($activeStores as $key=>$store){
                if($key!=$storeIdNone) {
                    $requestStoreName = $store;
                    $requestStoreId = $key;
                    $multi_stores[$key] = $store;
                }
			}
		endif;		
	}
	
	if(count($multi_stores) <= 1):
	?>
		<p><b><?php echo $requestStoreName;?></b></p>
		<input type="hidden" name="store_id" id="store-id" value="<?php echo $requestStoreId;?>"/>
		<?php else:?>
		<div>
		<select id="store-id" name="store_id" class="storeLocationSelect">
		<?php
		foreach ($multi_stores as $key=>$store):
		?><!--FOR BROWNTHOMAS POPUPS-->
            <?php if($getCustomersInfo = Mage::helper('appointments/data')->getCustomersInfo($key)):?>
            <option value="specialStore" data-url="<?=Mage::getBaseUrl()?>appointments/book/store/code/<?=Mage::helper('allure_virtualstore')->getStoreCode($key)?>" ><?=$store?></option>
        <?php else:?>
            <!--CODE END-->
            <option value="<?php echo $key;?>" <?php if($fetch_storeId==$key):echo "selected";endif;?>><?php echo $store;?></option>
        <?php endif;?>
		<?php endforeach;?>
		</select>
		</div>
<?php endif;?>
