

<?php 
	$count = 0;
	$one_ship = Mage::getSingleton('checkout/session')->getOrdered();
	if(isset($one_ship) && !empty($one_ship)):
?>

<?php
		$count = $count+1; 
        
        $quote = Mage::getSingleton("allure_multicheckout/ordered_session")->getQuote();
        $quote->collectTotals()->save();
        
        ?>

<div id="ordered-two-ship">
<h2>Shipment-<?php echo $count;?></h2>
<?php echo $this->getChildHtml('items_before'); ?>
<div class="shipping-address-mt">
<?php 
echo "<h4>Shipping address</h4>";
 
$shipping = $quote->getShippingAddress();
echo '<p>' . $shipping->getFormated('html') . '</p>';
?>

<?php if( $this->helper('customer')->isLoggedIn() ): ?>
<!--    <span><a href="--><?php //echo Mage::getUrl('customer/address/edit', array('id' => $shipping->getCustomerAddressId())); ?><!--">Edit</a></span>-->
    <span><a href="javascript: accordion.openSection('opc-shipping');">Edit</a></span>
<?php endif; ?>
</div>


<div class="billing-address-mt">
<h4>Billing Address</h4>
<?php
$billing = $quote->getBillingAddress();
echo '<p>' . $billing->getFormated('html') . '</p>';
?>

<?php if( $this->helper('customer')->isLoggedIn() ): ?>
<!--<span><a href="--><?php //echo Mage::getUrl('customer/address/edit', array('id' => $billing->getCustomerAddressId())); ?><!--">Edit</a></span>-->
        <span><a href="javascript: accordion.openSection('opc-billing');">Edit</a></span>
<?php endif; ?>
</div>


<div class="shipping-method-mt">
<?php 
echo "<h4>Shipping method</h4>";
$shippingAddress = $quote->getShippingAddress();

echo '<p>'.$shippingAddress->getShippingDescription() .'</p>';
?>
<span><a href="javascript: accordion.openSection('opc-shipping_method');">Edit</a></span>
</div>

<div class="payment-method-mt">
<?php
$payment = $quote->getPayment();
echo "<h4>Payment method</h4>";
switch ($payment->getMethod()) {
    case 'authorizenet':
        $cardTypes = Mage::getModel('payment/config')->getCcTypes();
        $cardTypeName = $cardTypes[$payment->getCcType()];
        $cardLast4 = $payment->getCcLast4();
        echo '<p>' . $cardTypeName . ' XXX XXX XXX ' . $cardLast4 . '</p>';
        break;
    default:
        echo '<p>' . $payment->getMethodInstance()->getTitle() . '</p>';
        break;
}
?>
<span><a href="javascript: accordion.openSection('opc-payment');">Edit</a></span>
</div>
<?php echo $this->getChildHtml('items_after'); ?>



<div id="checkout-review-table-wrapper">
    <table class="data-table cart-table-items" id="checkout-review-table">
        <?php echo $this->getChildHtml('totals_ordered'); ?>
        <thead>
            <tr>
                <th><?php echo $this->__('Product Name') ?></th>
                <th class="a-right"><?php echo $this->__('Price') ?></th>
                <th class="a-right"><?php echo $this->__('Qty') ?></th>
                <th class="a-right"><?php echo $this->__('Subtotal') ?></th>
            </tr>
        </thead>
        
        <?php foreach($this->getOrderedItems() as $_item): ?>
            <?php echo $this->getItemHtml($_item)?>
        <?php endforeach ?>
    </table>
</div>


</div>
<?php endif;?>



<?php 
	$two_ship = Mage::getSingleton('checkout/session')->getBackorder();
	if(isset($two_ship) && !empty($two_ship)):
?>

 <?php 
 		$count = $count+1;
        
        $quote1 = Mage::getSingleton("allure_multicheckout/backordered_session")->getQuote();
        $quote1->collectTotals()->save();
        ?>

<div id="backordered-two-ship">
<h2>Shipment-<?php echo $count;?></h2>

<?php echo $this->getChildHtml('items_before'); ?>
<div class="shipping-address-mt">
<?php 
echo "<h4>Shipping address</h4>";
 
$shipping = $quote1->getShippingAddress();
echo '<p>' . $shipping->getFormated('html') . '</p>';
?>

<?php if( $this->helper('customer')->isLoggedIn() ): ?>
<!--    <span><a href="--><?php //echo Mage::getUrl('customer/address/edit', array('id' => $shipping->getCustomerAddressId())); ?><!--">Edit</a></span>-->
    <span><a href="javascript: accordion.openSection('opc-shipping');">Edit</a></span>
<?php endif; ?>
</div>


<div class="billing-address-mt">
<h4>Billing Address</h4>
<?php
$billing = $quote1->getBillingAddress();
echo '<p>' . $billing->getFormated('html') . '</p>';
?>

<?php if( $this->helper('customer')->isLoggedIn() ): ?>
<!--<span><a href="--><?php //echo Mage::getUrl('customer/address/edit', array('id' => $billing->getCustomerAddressId())); ?><!--">Edit</a></span>-->
        <span><a href="javascript: accordion.openSection('opc-billing');">Edit</a></span>
<?php endif; ?>
</div>


<div class="shipping-method-mt">
<?php 
echo "<h4>Shipping method</h4>";
$shippingAddress = $quote1->getShippingAddress();

echo '<p>'.$shippingAddress->getShippingDescription() .'</p>';
?>
<span><a href="javascript: accordion.openSection('opc-shipping_method');">Edit</a></span>
</div>

<div class="payment-method-mt">
<?php
$payment = $quote1->getPayment();
echo "<h4>Payment method</h4>";
switch ($payment->getMethod()) {
    case 'authorizenet':
        $cardTypes = Mage::getModel('payment/config')->getCcTypes();
        $cardTypeName = $cardTypes[$payment->getCcType()];
        $cardLast4 = $payment->getCcLast4();
        echo '<p>' . $cardTypeName . ' XXX XXX XXX ' . $cardLast4 . '</p>';
        break;
    default:
        echo '<p>' . $payment->getMethodInstance()->getTitle() . '</p>';
        break;
}
?>
<span><a href="javascript: accordion.openSection('opc-payment');">Edit</a></span>
</div><?php echo $this->getChildHtml('items_after'); ?>

<div id="checkout-review-table-wrapper">
    <table class="data-table cart-table-items" id="checkout-review-table">
        <?php echo $this->getChildHtml('totals_backordered'); ?>
        <thead>
            <tr>
                <th><?php echo $this->__('Product Name') ?></th>
                <th class="a-right"><?php echo $this->__('Price') ?></th>
                <th class="a-right"><?php echo $this->__('Qty') ?></th>
                <th class="a-right"><?php echo $this->__('Subtotal') ?></th>
            </tr>
        </thead>
        
        <?php foreach($this->getBackorderedItems() as $_item): ?>
            <?php echo $this->getItemHtml($_item)?>
        <?php endforeach ?>
    </table>
</div>


</div>
<?php endif;?>





<script type="text/javascript">
//<![CDATA[
    decorateTable('checkout-review-table');
    truncateOptions();
//]]>
</script>
<div id="checkout-review-submit">
    <?php echo $this->getChildHtml('agreements') ?>
    <div class="buttons-set" id="review-buttons-container">
        <?php echo $this->getChildHtml('button') ?>
        <span class="please-wait" id="review-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Submitting order information...')) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Submitting order information...')) ?>" class="v-middle" /> <?php echo $this->__('Submitting order information...') ?>
        </span>
        <p class="f-left"><?php echo $this->__('Forgot an Item?') ?> <a href="<?php echo $this->getUrl('checkout/cart') ?>" onclick="return confirm('<?php echo Mage::helper('core')->jsQuoteEscape($this->__('Are you sure you want to leave this page? You will need to go through the checkout steps again.')); ?>')"><?php echo $this->__('Edit Your Cart') ?></a></p>
    </div>
    <script type="text/javascript">
    //<![CDATA[
        review = new Review('<?php echo $this->getUrl('checkout/onepage/saveOrder', array('form_key' => Mage::getSingleton('core/session')->getFormKey())) ?>', '<?php echo $this->getUrl('checkout/onepage/successorder') ?>', $('checkout-agreements'));
    //]]>
    </script>
</div>
