<?php $helper = Mage::helper('allure_smartanalytics');
$string = Mage::getModel('core/session')->getRefundOrder();
$result = json_decode($string,true);
$products = $result['products'];
$storeId =  $result["storeId"];
if($helper->isEnabled($storeId) && $helper->isEnhancedEcommerceEnabled($storeId) && strlen($string)>0): ?>
<script type="text/javascript">
    //<![CDATA[
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', '<?php echo $helper->getAccountId($storeId); ?>', '<?php echo $this->getMainDomain() ?>');
	<?php if (strlen($helper->isLinkAccountsEnabled($storeId))>0):?>
	ga('create','<?php echo $helper->getLinkedAccountId($storeId)?>',{'name':'<?php echo $helper->getLinkedAccountName($storeId)?>'});
	ga('<?php echo $helper->getLinkedAccountName($storeId)?>.require', 'ec');
	<?php endif;?>
    ga('require', 'ec');

    jQuery(document).ready(function($){
        <?php if(!$result['fullrefund']):?>
			<?php foreach($products as $product):?>
				ga('ec:addProduct', {
					'id': '<?php echo $product['id']?>',
					'quantity':  <?php echo $product['qty']?>
				});
			<?php endforeach;?>
		<?php endif;?>

		ga('ec:setAction', 'refund', {
			'id': '<?php echo $result['orderId']?>'
		});

		ga('send', 'event', 'Ecommerce', 'Refund', {'nonInteraction': 1});

		<?php if (strlen($helper->isLinkAccountsEnabled())>0):?>
			<?php if(!$result['fullrefund']):?>
				<?php foreach($products as $product):?>
					ga('<?php echo $helper->getLinkedAccountName()?>.ec:addProduct', {
						'id': '<?php echo $product['id']?>',
						'quantity':  <?php echo $product['qty']?>
					});
				<?php endforeach;?>
			<?php endif;?>

			ga('<?php echo $helper->getLinkedAccountName()?>.ec:setAction', 'refund', {
				'id': '<?php echo $result['orderId']?>'
			});

			ga('<?php echo $helper->getLinkedAccountName()?>.send', 'event', 'Ecommerce', 'Refund', {'nonInteraction': 1});
		<?php endif;
		Mage::getModel('core/session')->unsRefundOrder();?>
    });
	//]]>
</script>
<?php endif;?>
