<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    OnTap
 * @package     OnTap_Merchandiser
 * @copyright   Copyright (c) 2014 On Tap Networks Ltd. (http://www.ontapgroup.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<table class="form-list">
    <tr>
        <td class="scope-label">
            <button onclick="setLocation('<?php echo Mage::helper('adminhtml')->getUrl("adminhtml/merchandiser/rebuildcategories"); ?>')" type="button" class="scalable">
                <span>
                    <span>
                        <span><?php echo Mage::helper('merchandiser')->__('Re-build Visual Merchandiser categories') ?></span>
                    </span>
                </span>
            </button>
        </td>
        <td class="scope-label">
            <?php echo Mage::helper('merchandiser')->__('Rebuild Category Products for Smart Categories') ?>
        </td>
    </tr>
</table>