<!--<script>
    jQuery(document).ready(function(){
        jQuery('select#showPerPage').customStyle();
    });
</script>-->
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_orders = $this->getOrders();
	if($_orders) {
?>
<div class="col2-set">
    <div class="box">
        <div class="box-title">
            <h3>
                <?php
                    $request = Mage::app()->getRequest();
                   /*  if($request->getModuleName() == 'customer'):
                        echo $this->__('Recent Orders');
                    else:
                        echo $this->getOrders()->getSize()." ".$this->__('item(s)');
                    endif; */
                ?>
            </h3>
            <div class="pager-mt-1"><a style="display: none;" href="<?php echo $this->getUrl('sales/order/history/') ?>"><?php echo $this->__('View All') ?></a>
			<?php //echo $this->getPagerHtml(); ?></div>
        </div>
        <?php if($_orders->getSize()): ?>
        <table class="data-table" id="my-orders-table">
            <thead>
                <tr>
                    <th><div class="mt-myaccount-th" style="width:130px; padding-left:10px;"><?php echo $this->__('Order number') ?></div></th>
                    <th class="a-left" style="padding-left: 25px;"><div class="mt-myaccount-th" style="width:100px;"><?php echo $this->__('Date') ?></div></th>
                    <th class="a-left" style="padding-left: 0px;"><div class="mt-myaccount-th" style="width:100px;"><?php echo $this->__('Ship To') ?></div></th>
                    <th class="a-left" style="padding-left: 0;"><div class="mt-myaccount-th" style="width:100px;"><?php echo $this->__('Order Total') ?></div></th>
                    <th class="a-left" style="padding-left: 0;"><div class="mt-myaccount-th" style="width:110px;"><?php echo $this->__('Order Status') ?></div></th>
                    <th class="a-center" style="padding-left: 0px;"><div class="mt-myaccount-th" style="width:110px;"><?php //echo $this->__('Actions') ?></div></th>
                </tr>
            </thead>
            <tbody>
                <?php $_odd = ''; ?>
                <?php $i = 0 ?>
                <?php foreach ($_orders as $_order): ?>
                <tr>
                    <td style="padding-left:10px;"><a href="<?php echo $this->getViewUrl($_order) ?>"><?php echo $_order->getRealOrderId() ?></a></td>
                    
                    
                    <td class="a-left" style="padding-left:20px;" ><span class="nobr">
										<?php echo Mage::app()->getLocale()->date(strtotime($_order->getCreatedAtStoreDate()), null, null, false)->toString('MM/dd/yyyy') ?>
					<?php //echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></span></td>
                    <td class="a-left" style="padding-left:0;"><?php echo $_order->getShippingAddress() ? $this->htmlEscape($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
                    <td class="a-left" style="padding-left:18px;"><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
                    <td class="a-left" style="padding-left:15px;"><?php echo $_order->getStatusLabel() ?></td>
                    <td class="a-left" style="padding-left:10px;">
                        <span class="nobr"><a href="<?php echo $this->getViewUrl($_order) ?>"><?php echo $this->__('View Order') ?></a>
                            <?php /*<span class="separator">|</span><a href="<?php echo $this->getTrackUrl($_order) ?>"><?php echo $this->__('Track Order') ?></a>&nbsp;*/ ?>
                            <?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
                            <span>|</span> <a href="<?php echo $this->getReorderUrl($_order) ?>" class="link-reorder"><?php echo $this->__('Reorder') ?></a>
                        <?php endif ?>
                        </span>
                    </td>
                </tr>
                <?php 
				if(0 && Mage::app()->getRequest()->getControllerName() != 'order')
					if($i++ == 4) break;?>
                <?php endforeach; ?>
            </tbody>
        </table>
        <script type="text/javascript">decorateTable('my-orders-table');</script>
        <?php // echo $this->getPagerHtml(); ?>
        <?php else: ?>
            <p><?php echo $this->__('No orders found in your account.'); ?></p>
        <?php endif; ?>
        <?php if($request->getModuleName() != 'customer'): ?>
            <div class="box-title">
            <h3>
            <?php //echo $this->getOrders()->getSize()." ".$this->__('item(s)'); ?>
            </h3>
            <!--a href="<?php //echo $this->getUrl('sales/order/history/') ?>"><?php echo $this->__('View All') ?></a-->
			<?php //echo $this->getPagerHtml(); ?>
			<?php $totalPageSize = $this->getOrders()->getLastPageNumber()?>
			</div>
		<?php endif;?>
    </div>
</div>
<?php } ?>


<script>
var xhr = null;
var page = 2;
var totalPages = <?php echo $totalPageSize?>;
jQuery(function($){
	$('#my-orders-table').bind('scroll', function(){
		if($(this).scrollTop() + $(this).innerHeight()>=$(this)[0].scrollHeight){
			jQuery('.loader').css({"display":"block"});
			if(page<=totalPages){
				 if( xhr == null ) {
				    //xhr.abort();
				    //xhr = null;
				 	xhr =	jQuery.ajax({
						//async: false,
				        url: '<?php echo Mage::getBaseUrl('web').'myaccount/index/getOrderHistory';?>',
				        dataType : 'json',
						type : 'POST',
						data: {'page':page,'limit':10},
				        success: function(data) {
				        	jQuery('#my-orders-table').append(data.data.html);
				        	jQuery('.loader').css({"display":"none"});
				        }
				    });
				 	xhr = null;
				 	page ++;
				}
		    }else{
		    	jQuery('.loader').css({"display":"none"});
		    }
		}
 	});
});
</script>