<h1>My Products</h1>

<div class="tab">
  <button id="mt-myproduct-purchase" data-tab="tab1" class="tablinks active" onclick="changeTab(this);">Purchased</button>
  <button id="mt-myproduct-wishlist" data-tab="tab2" class="tablinks" onclick="changeTab(this);">Wishlist</button>
  <button id="mt-myproduct-cart" data-tab="tab3" class="tablinks" onclick="changeTab(this);">Cart</button>
  <button id="mt-myproduct-receipts" data-tab="tab4" class="tablinks" onclick="changeTab(this);">All Receipts</button>
</div>

<div id="new-mt-myproduct-purchase" class="tabcontent tab1 active">
  <div class="mt-new-payment">
  		Hii Pintya
   </div>
</div>

<div id="new-mt-myproduct-wishlist" class="tabcontent tab2">
  <div class="mt-my-wishlist">
  		<?php echo $this->getChildHtml('customer.wishlist')?>
  </div>
</div>

<div id="new-mt-myproduct-cart" class="tabcontent tab3">
  <div class="mt-my-cart">
  		<?php echo $this->getChildHtml('checkout.cart')?>
  </div>
</div>

<div id="new-mt-myproduct-receipts" class="tabcontent tab4">
  <div class="mt-my-orders">
  		<?php echo $this->getChildHtml('sales.order.history')?>
  	<div class='loader' style="display: none;">
	    <div class='loader--dot'></div>
	    <div class='loader--dot'></div>
	    <div class='loader--dot'></div>
	    <div class='loader--dot'></div>
	    <div class='loader--dot'></div>
	    <div class='loader--dot'></div>
	    <div class='loader--text'></div>
 	 </div>
  </div>
</div>

<script>
	function changeTab(event){
		var element = jQuery(event);
		var currentTab = element.attr('data-tab');
		jQuery('.tablinks').removeClass('active');
		element.addClass('active');
		jQuery('.tabcontent').removeClass('active');		
		jQuery('.tabcontent.'+currentTab).addClass('active');
	}
</script>