<?php
/**
 * @see Ebizmarts_BakerlooEmail_Block_Adminhtml_System_Config_Form_Processall
 */
?>
<table>
    <tr>
        <td>
            <button onclick="setLocation(<?php echo $this->getProcessUrl() ?>)" class="scalable" type="button" id="<?php echo $this->getHtmlId() ?>">
                <span><?php echo $this->escapeHtml($this->getButtonLabel()); ?></span>
            </button>
        </td>
    </tr>
</table>
