 <?php

$log = $this->logObject();

?>

<button onclick="setLocation('<?php echo $this->getBackUrl(); ?>');" class="scalable back" type="button" title="<?php echo $this->__('Back'); ?>" id="log-back"><span><span><span><?php echo $this->__('Back'); ?></span></span></span></button>

<ul style="margin-top:8px;">
    <li><strong><?php echo $this->__('Method:'); ?></strong> <?php echo $log->getRequestMethod(); ?> <?php echo '/', $log->getData('resource'); ?></li>
    <li><strong><?php echo $this->__('Time:'); ?></strong> <?php echo Mage::getModel('core/date')->date('M d, Y h:i a', $log->getCreatedAt()); ?></li>
<!--    <li><strong>--><?php //echo $this->__('Call Time:'); ?><!--</strong> --><?php //echo Mage::helper('bakerloo_restful')->formatTimeSeconds($log->getCallTime()); ?><!--s</li>-->
    <li><strong><?php echo $this->__('IP:'); ?></strong> <?php echo long2ip($log->getRemoteAddr()); ?></li>
    <li><strong><?php echo $this->__('URL:'); ?></strong> <?php echo $log->getRequestUrl(); ?></li>
    <li><strong><?php echo $this->__('User Agent:'); ?></strong> <?php echo $log->getUserAgent(); ?></li>
    <li><strong><?php echo $this->__('Call time:'); ?></strong> <?php echo $log->getCallTime() . $this->__(' seconds'); ?></li>
</ul>

<br />

<h3><?php echo $this->__('Request'); ?></h3>
<pre>
    <code class="json-hl">
        <?php echo $log->getRequestHeaders(); ?>
    </code>
</pre>
<pre>
    <code class="json-hl">
        <?php echo $log->getRequestBody(); ?>
    </code>
</pre>
<br />

<?php if($log->getResponseCode()): ?>
    <h3><?php echo $this->__('Response (%s)', $log->getResponseCode()); ?></h3>
<?php else: ?>
    <h3><?php echo $this->__('Response'); ?></h3>
<?php endif; ?>
<pre>
    <code class="json-hl">
        <?php echo $log->getResponseHeaders(); ?>
    </code>
</pre>
<pre>
    <code class="json-hl">
        <?php echo $log->getResponseBody(); ?>
    </code>
</pre>

<script type="text/javascript">
    document.observe('dom:loaded', function() {
        $$('.json-hl').each(function(block) {
            block.innerHTML = jsl.format.formatJson(block.innerHTML);
            hljs.highlightBlock(block);
        });
    });
</script>