<?php
$filter = $this->getFilters();
$categories = $metals = $gemstones = $prices = array();

    if(isset($filter['category'])):
        if(!empty($filter['category'])):
            $categories = $filter['category'];
        endif;
    endif;
    if(isset($filter['metal'])):
        if(!empty($filter['metal'])):
            $metals = $filter['metal'];
        endif;
    endif;
    if(isset($filter['gemstone'])):
        if(!empty($filter['gemstone'])):
            $gemstones = $filter['gemstone'];
        endif;
    endif;
    if(isset($filter['price'])):
        if(!empty($filter['price'])):
            $prices = $filter['price'];
        endif;
    endif;

?>

<ul id="narrow-by-list" class="mb-0" style="display: none">
    <!--Category-->
    <?php if(count($categories) > 0):?>
    <li class="common-filter filtru-category-dtn sel" data-name="category">
        <div class="optionfilter" style="">
            <dt class="even">Category</dt>
            <dd class="filtru-category-content-dtn even " style="display:none">
                <ol class="m-filter-checkboxes">
                    <?php foreach ($categories as $category):?>
                    <li>

                        <label class="custom-checkbox metal" data-color="<?=$category['code']?>" >
                            <input type="checkbox" data-name="category" class="category-checkbox categorySelect" id="<?=$category['code']?>" value="<?=$category['code']?>" >
                            <span class="checkmark"></span>
                        </label>
                        <label for="<?=$category['code']?>"><span><?=$category['label']?></span></label>
                    </li>
                    <?php endforeach;?>
                </ol>
            </dd>
        </div>
    </li>
    <script>
        jQuery(document).ready(function() {
            var config_currency_selector_category = {
                over: function () {
                    //jQuery('.filtru-category-content-dtn').slideDown(300);
                },
                timeout: 200,
                out: function () {
                    jQuery('.filtru-category-content-dtn').removeClass('show');
                    jQuery('.filtru-category-content-dtn').slideUp(300);
                }
            };

            jQuery(".filtru-category-dtn").hoverIntent(config_currency_selector_category);
        });
    </script>
    <?php endif;?>

    <!--Metal-->
    <?php if(count($metals) > 0):?>
      <li class="common-filter filtru-metal-dtn sel" data-name="metal">
        <div class="optionfilter" style="">
            <dt class="odd">METAL</dt>
            <dd class="filtru-metal-content-dtn odd" style="display: none;">
                <ol class="m-filter-checkboxes">
                    <?php foreach ($metals as $metal):?>
                    <li>
                        <label class="custom-checkbox " data-color="<?= $metal['code']?>" >
                            <input type="checkbox" data-name="metal" class="metalSelect" id="<?= $metal['code']?>" value="<?= $metal['code']?>" >
                            <span class="checkmark"></span>
                        </label>
                        <label for="<?= $metal['code']?>"><span><?= $metal['label']?></span></label>
                    </li>
                    <?php endforeach;?>
                </ol>
            </dd>
        </div>
    </li>
        <script>
            jQuery(document).ready(function(){
                var config_currency_selector_metal = {
                    over: function(){
                        //jQuery('.filtru-category-content-dtn').slideDown(300);
                    },
                    timeout: 200,
                    out: function(){
                        jQuery('.filtru-metal-content-dtn').removeClass('show');
                        jQuery('.filtru-metal-content-dtn').slideUp(300);
                    }
                };

                jQuery(".filtru-metal-dtn").hoverIntent( config_currency_selector_metal );
            });
        </script>
    <?php endif; ?>
    <!--Gemstone-->
    <?php if(count($gemstones) > 0):?>
    <li class="common-filter filtru-gemstone-dtn sel" data-name="gemstone">
        <div class="optionfilter" style="">
            <dt class="even">Gemstone</dt>
            <dd class="filtru-gemstone-content-dtn even" style="display:none">
                <ol class="m-filter-checkboxes">
                    <?php foreach ($gemstones as $gemstone):?>
                    <li>

                        <label class="custom-checkbox gemstone" data-gemestone="<?=$gemstone['code']?>" >
                            <input type="checkbox" data-name="gemstone" class="gemstoneSelect" id="<?=$gemstone['code']?>" value="<?=$gemstone['code']?>" >
                            <span class="checkmark"></span>
                        </label>
                        <label for="color1"><span><?=$gemstone['label']?></span></label>
                    </li>
                    <?php endforeach; ?>

                </ol>
            </dd>
        </div>
    </li>
        <script>
            jQuery(document).ready(function(){
                var config_currency_selector_gemstone = {
                    over: function(){
                        //jQuery('.filtru-category-content-dtn').slideDown(300);
                    },
                    timeout: 200,
                    out: function(){
                        jQuery('.filtru-gemstone-content-dtn').removeClass('show');
                        jQuery('.filtru-gemstone-content-dtn').slideUp(300);
                    }
                };

                jQuery(".filtru-gemstone-dtn").hoverIntent(config_currency_selector_gemstone);
            });
        </script>
    <?php endif; ?>
<!--    PRICE-->
    <?php if(count($prices) > 0):?>
    <li class="common-filter filtru-price-dtn sel" data-name="price">
        <div class="optionfilter" style="">
            <dt class="even">Price</dt>
            <dd class="filtru-price-content-dtn even" style="display:none">
                <ol class="m-filter-checkboxes">
                    <?php foreach ($prices as $price):?>
                    <li>

                        <label class="custom-checkbox metal" data-color="p1" >
                            <input type="checkbox" data-name="price" id="p1" value="p1" >
                            <span class="checkmark"></span>
                        </label>
                        <label for="p1"><span>p1</span></label>
                    </li>
                    <?php endforeach; ?>
                </ol>
            </dd>
        </div>
    </li>
        <script>
            jQuery(document).ready(function(){
                var config_currency_selector_price = {
                    over: function(){
                        //jQuery('.filtru-category-content-dtn').slideDown(300);
                    },
                    timeout: 200,
                    out: function(){
                        jQuery('.filtru-price-content-dtn').removeClass('show');
                        jQuery('.filtru-price-content-dtn').slideUp(300);
                    }
                };

                jQuery(".filtru-price-dtn").hoverIntent( config_currency_selector_price );
            });
        </script>
    <?php endif; ?>
</ul>
<script>

        jQuery(document).ready(function(){

            jQuery('.sel').click(function () {
                var selected = jQuery(this).attr('data-name');
                var showOrHide = jQuery('.filtru-'+selected+'-content-dtn').hasClass('show');
                if(!showOrHide) {
                    jQuery('.filtru-'+selected+'-content-dtn').addClass('show');
                    jQuery('.filtru-'+selected+'-content-dtn').slideDown(300);
                }
                else {
                    jQuery('.filtru-'+selected+'-content-dtn').removeClass('show');
                    jQuery('.filtru-'+selected+'-content-dtn').slideUp(300);
                }
            });
        });
</script>

<script>
    jQuery(window).bind("load resize", function (e) {
        var width = jQuery(window).width();
        if ((width < 1023)) {
            jQuery('#narrow-by-list').hide();
        }else{
            jQuery('#narrow-by-list').show();
        }
    });
</script>
<script>
    var categoryList = [];
    var metalList = [];
    var gemstoneList = [];
    var priceList = [];
    jQuery(document).ready(function(){
       var categorySelect = jQuery('input:checkbox.categorySelect');
       var metalSelect = jQuery('input:checkbox.metalSelect');
       var gemstoneSelect = jQuery('input:checkbox.gemstoneSelect');
       var priceSelect = jQuery('input:checkbox.priceSelect');

        jQuery('.categorySelect,.metalSelect,.gemstoneSelect,.priceSelect').change(function() {
            if(this.checked) {
                callCatalogsearch();
            }
        });

    var callCatalogsearch = function() {
       categoryList = [];
       metalList = [];
       gemstoneList = [];
       priceList = [];
        jQuery('.categorySelect,.metalSelect,.gemstoneSelect,.priceSelect').each(function () {
            if (this.checked) {
                var checkbox = jQuery(this);
                console.log(checkbox);
                console.log(checkbox.attr('data-name'));
                if (checkbox.attr('data-name') === 'category') {
                    categoryList.push(checkbox.val());
                }else
                if (checkbox.attr('data-name') === 'metal') {
                    metalList.push(checkbox.val());
                }else
                if (checkbox.attr('data-name') === 'gemstone') {
                    gemstoneList.push(checkbox.val());
                }else
                if (checkbox.attr('data-name') === 'price') {
                    priceList.push(checkbox.val());
                }
            }
        });
    }

    var clearFilters = function(){
        jQuery('.categorySelect,.metalSelect,.gemstoneSelect,.priceSelect').removeAttr('checked');
    }
    });

</script>
