<div class="col2-set addresses-list">
	<div class="col-1">
		<div id="mt-card-saved-data">
			<?php echo $this->getChildHtml('tokenbase_customer_method_left'); ?>
		</div>
	</div>
	
	<div class="col-2">
	 	<div id="mt-card-edit-data" style="display: none;"></div>
	 	<div id="mt-card-add-new-data">
			<?php echo $this->getChildHtml('tokenbase_customer_method_right'); ?>
		</div>
	</div> 
</div>
