login: ~
password: ~
namespace: "http://tempuri.org/"
wsdl: ~
options:
    classmap:
        ArrayOfListInfo:  "Mediapart\\Selligent\\ArrayOfListInfo"
        ListInfo: "Mediapart\\Selligent\\ListInfo"
        Property: "Mediapart\\Selligent\\Property"
        ArrayOfProperty: "Mediapart\\Selligent\\Properties"
        # System info
        GetSystemStatusResponse: "Mediapart\\Selligent\\Response\\GetSystemStatusResponse"
        # Manage Lists
        GetListsResponse: "Mediapart\\Selligent\\Response\\GetListsResponse"
        GetListIDResponse: "Mediapart\\Selligent\\Response\\GetListIDResponse"
        # Manage Segments
        CreateSegmentResponse: "Mediapart\\Selligent\\Response\\CreateSegmentResponse"
        AddToSegmentResponse: "Mediapart\\Selligent\\Response\\AddToSegmentResponse"
        GetSegmentsResponse: "Mediapart\\Selligent\\Response\\GetSegmentsResponse"
        GetSegmentRecordCountResponse: "Mediapart\\Selligent\\Response\\GetSegmentRecordCountResponse"
        # Manage Users
        CreateUserResponse: "Mediapart\\Selligent\\Response\\CreateUserResponse"
        UpdateUserResponse: "Mediapart\\Selligent\\Response\\UpdateUserResponse"
        UpdateUsersResponse: "Mediapart\\Selligent\\Response\\UpdateUsersResponse"
        GetUserByIDResponse: "Mediapart\\Selligent\\Response\\GetUserByIDResponse"
        RetrieveHashForUserResponse: "Mediapart\\Selligent\\Response\\RetrieveHashForUserResponse"
        CountUsersByConstraintResponse: "Mediapart\\Selligent\\Response\\CountUsersByConstraintResponse"
        GetUsersByConstraintResponse: "Mediapart\\Selligent\\Response\\GetUsersByConstraintResponse"
        GetUserByConstraintResponse: "Mediapart\\Selligent\\Response\\GetUserByConstraintResponse"
        CountUsersByFilterResponse: "Mediapart\\Selligent\\Response\\CountUsersByFilterResponse"
        GetUsersByFilterResponse: "Mediapart\\Selligent\\Response\\GetUsersByFilterResponse"
        GetUserByFilterResponse: "Mediapart\\Selligent\\Response\\GetUserByFilterResponse"
        # Manage Campaign
        TriggerCampaignResponse: "Mediapart\\Selligent\\Response\\TriggerCampaignResponse"
        TriggerCampaignWithResultResponse: "Mediapart\\Selligent\\Response\\TriggerCampaignWithResultResponse"
        TriggerCampaignForUserResponse: "Mediapart\\Selligent\\Response\\TriggerCampaignForUserResponse"
        TriggerCampaignForUserWithResultResponse: "Mediapart\\Selligent\\Response\\TriggerCampaignForUserWithResultResponse"