<?php
	$settings = Mage::helper('ddmenu')->getSettings();
?>
<ul class="nav navbar-nav">
    <?php $first     = 'first' ?>
    <?php if ($settings['home']): ?>
        <li class="first"><a href='<?php echo $this->getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) ?>'><span><?php echo $this->__('Home page')?></span></a></li>
        <?php $first = ''?>
    <?php else: ?>
        <?php $first = 'first' ?>
    <?php endif ?>
    <?php
        $this->_menu->setOutermostClass('level-top');
        $this->_menu->setChildrenWrapClass('');

        $children    = $this->_menu->getChildren();
        $count       = $children->count();
        $i           = 0;
    ?>
    <?php foreach ($children as $child): ?>
        <?php
            $i++;
            $categoryId  = $this->getCategoryId($child);
            $ddmenu      = $this->getDdmenuObject($categoryId);
            $showProduct = $ddmenu->getLastProduct();
            $this->categoryIds = array($categoryId);

            // html - sub categories
            $subHtml           = FALSE;
            if ($this->maxRows = $ddmenu->getRows()) {
                $subHtml       = $this->getMobileCategoryHtml($child);
            } else if ($showProduct) {
                $this->searchCategoriesForLastProduct($child);
            }

            // html - last product
            $prodHtml          = FALSE;
            if ($showProduct) {
                $prodHtml      = $this->getChild('ddmenu_last_product')
                                    ->setCategoryIds($this->categoryIds)
                                    ->_toHtml();
            }

            // html - friend category
            $friendHtml        = FALSE;
            if ($ddmenu->getCategoriesList()) {
                $friendHtml    = $this->getChild('ddmenu_category_friends')
                                    ->setCategoryIds($ddmenu->getCategoriesList())
                                    ->_toHtml();
            }

            $friendHtml = $friendHtml ? '<ul class="dropdown-menu">'.strip_tags($friendHtml,'<li><li/><a></a>').'</ul>' : null;
            
            // html - static block
            $staticHtml        = FALSE;
            if ($ddmenu->getStaticBlockId()) {
                $staticHtml    = $this->getChild('ddmenu_static_block')
                                    ->setId($ddmenu->getStaticBlockId())
                                    ->_toHtml();
            }


            if ($subHtml || $prodHtml || $friendHtml || $staticHtml) {
                $showMenu = TRUE;
            } else {
                $showMenu = FALSE;
            }
        ?>
        <li class="<?php echo $first?><?php echo ($showMenu)?' dropdown':'' ?><?php echo ($i==$count)?' last':'' ?><?php echo ($child->getIsActive())?' current':'' ?>">
		 <a <?php echo ($showMenu) ? 'style = "cursor:default;" onclick="return false;"' : '';?> href='<?php echo $child->getUrl() ?>' <?php echo ($showMenu) ? 'class="dropdown-toggle" data-toggle="dropdown" role="button"':''?>><?php echo $this->__($this->escapeHtml($child->getName())) ?><?php if ($showMenu) :?><span class="caret"></span><?php endif;?></a>

            <?php if ($showMenu): ?>
                    <?php
                        $blockIds = explode(',', $ddmenu->getBlocksLoc());
                        
                        foreach ($blockIds AS $blockId) {
                            if ($blockId=='b1' && !empty($subHtml))    echo trim($subHtml);
                            if ($blockId=='b2' && !empty($friendHtml)) echo trim($friendHtml);
                            if ($blockId=='b3' && !empty($prodHtml))   echo '<li id="b3">' . $prodHtml . '</li>';
                            if ($blockId=='b4' && !empty($staticHtml)) echo '<li id="b4">' . $staticHtml . '</li>';
                        }
                    ?>
            <?php endif ?>
            
            <?php if (false && $showMenu): ?>
                <div class="sub" style="display:none">
                    <table><tr>
                            <?php
                                $roleId = Mage::getSingleton('customer/session')->getCustomerGroupId();
                                $role = Mage::getSingleton('customer/group')->load($roleId)->getData('customer_group_code');
                                $role = strtolower($role);
                            ?>
                           
                    <?php
                        $blockIds = explode(',', $ddmenu->getBlocksLoc());
                        
                        foreach ($blockIds AS $blockId) {
                            if ($blockId=='b1' && $subHtml)    echo '<td>' . $subHtml . '</td>';
                            if ($blockId=='b2' && $friendHtml) echo '<td>' . $friendHtml . '</td>';
                            if ($blockId=='b3' && $prodHtml)   echo '<td>' . $prodHtml . '</td>';
                            if ($blockId=='b4' && $staticHtml) echo '<td>' . $staticHtml . '</td>';
                        }
                    ?>
                    </tr></table>
                </div>
            <?php endif ?>

        </li>
        <?php $first       = ''?>
    <?php endforeach ?>
    <!-- <li><?php //echo $this->getLayout()->createBlock('ecp_menu/menu')->setBlockId('menu')->toHTML(); ?></li> -->
    <li><a href="/store-locations.html">Find a Store</a></li>
    <?php if(Mage::getSingleton('customer/session')->isLoggedIn()):?>
    <li><a href="/customer/account/logout">Log Out</a></li>
    <?php endif;?>
</ul>