<?php 
/**
 * According to client requirement
 * in onepage checkout has added new step
 * i.e delivery_option
 * 
 * @var Allure_MultiCheckout_Block_Checkout_Onepage_Deliveryoption $this
 */
?>
<form id="co-delivery-method-form" action="">
	<div id="checkout-delivery-method">
    	<?php echo $this->getChildHtml('delivery_option_details') ?>
    </div>
</form>

<div class="buttons-set text-lg-right" id="delivery-option-buttons-container">
	<button type="button" class="button light-button next-button float-right" onclick="Delivery.save()">
		<span><span><?php echo $this->__('Next') ?></span></span>
	</button>
	<p class="back-link">
		<a href="#" onclick="checkout.back(); return false;"><?php echo $this->__('Back') ?></a>
	</p>
   	<span id="delivery-option-please-wait" class="please-wait" style="display:none;">
    	<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" class="v-middle para-normal" /> <?php echo $this->__('Loading next step...') ?>
    </span>
</div>

<script type="text/javascript">
	//<![CDATA[
        var Delivery = new Delivery('co-delivery-method-form', "<?php echo $this->getUrl('checkout/onepage/saveDeliveryOption') ?>");
    //]]>
</script>

<script>
jQuery(document).ready(function(){
	var $ = jQuery;
	$('.shipment-delivery-method li').click(function(){
		$('.shipment-delivery-method li').each(function(i){
			jQuery(this).find('input').removeAttr('checked');
		});
		$(this).find('input').attr('checked',true);
		if($(this).find('input').hasClass('shipment-one')){
			$('#two-shipping-method-layout').hide();
			$('#shipping-method-two').hide();
		}else{
			$('#two-shipping-method-layout').show();
		}
	});

	$('#select-delivery-shipment').on('change',function(){
		if($(this).val() == 2){
			$('#shipping-method-two').show();
		}else{
			$('#shipping-method-two').hide();
		}
	});
});

function switchMethod(that){
	var $ = jQuery;
	$(that).checked = true;
	if($(that).hasClass('shipment-one')){
		$('#two-shipping-method-layout').hide();
		$('#delivery-shiping-option').hide();
	}else{
		$('#two-shipping-method-layout').show();
		$('#delivery-shiping-option').show();
	}
}
</script>
