
<?php
$id = $this->getRequest()->getParam('id',false);     
$celebrity = ($id)
	? Mage::getModel('ecp_celebrities/celebrities')->load($id)
	: Mage::getModel('ecp_celebrities/celebrities')->getCollection()->getFirstItem();
$outfits = Mage::getModel('ecp_celebrities/outfits')->getCollection()->addFieldToFilter('celebrity_id', $id);
$celebrity_url = Mage::getBaseUrl('web').$celebrity->getUrl();
$celebrityEmailShare = Mage::getUrl('ecpcelebrities/index/send', array("page" => $celebrity->getUrl()));
?>

<?php
$firstElement = true;?>
<script type="text/javascript">
    var productAddToCartForm = new Array();
</script>

<?php if (!$outfits->getSize()): ?>
    <div class="celeb">
        <div class="img_celeb">
            <img class="d" src="<?php echo $this->getImageUrl($celebrity->getDefaultImage()) ?>"/>
        </div>

        <div class="content_celeb">
            <div class="celeb_block">
                <h3><?php echo $celebrity->getCelebrityName() ?></h3>
            </div>
            <?php echo $celebrity->getDescription(); ?>
            <div class="no-products-celeb-mt"><?php echo $this->__('There are no products matching the selection'); ?></div>
        </div>
    </div>

<?php else: ?>

    <?php
    $first = true;
    foreach ($outfits as $outfit): ?>
        <div class="celeb">
            <div class="img_celeb">
                <?php if ($first): ?>
                    <?php /*$celebId = $celebrity->getCelebrityId();*/ $celebId = 0; ?>
                    <img id="img_<?php echo $outfit->getCelebrityOutfitId(); ?>" class="g change_meta_og_image" src="<?php echo $this->getImageUrl($outfit->getOutfitImage()) ?>"/>
                <?php else: ?>
                    <?php $celebId = 0; ?>
                    <img id="img_<?php echo $outfit->getCelebrityOutfitId(); ?>" class="p change_meta_og_image" src="<?php echo $this->getImageUrl($outfit->getOutfitImage()) ?>"/>
                <?php endif; ?>
                <?php $first = false; ?>
            </div>

            <div class="content_celeb">
                <?php if ($firstElement): ?>
                    <div class="celeb_block">
                        <h3><?php echo $celebrity->getCelebrityName() ?></h3>
                    </div>
                    <?php echo Mage::helper('cms')->getPageTemplateProcessor()->filter($celebrity->getDescription()); ?>
                <?php endif; ?>
                <?php $firstElement = false; ?>
                <?php if ($outfit->getStatus() == 1) {
                    $products = $this->getAllOutfitProducts($outfit);
                } else {
                    $products = array();
                } ?>
                <div><?php if (count($products) <= 0):
                        echo $this->__('There are no products matching the selection');
                    else: ?></div>
            <?php foreach ($products as $product):
                if ($product->isSaleable()):?>
                    <div class="outfit-product">
                        <?php
                        $showSampleForm = false;
                        if ($product->getSizeSample() == 1) {
                            $showSampleForm = true;
                            $sampleProduct = Mage::getModel('catalog/product')->getCollection()
                                ->addAttributeToFilter('type_id', 'customproduct')
                                ->getFirstItem();
                            $sampleProduct = Mage::getModel('catalog/product')->load($sampleProduct->getEntityId());
                        }
                        ?>
                        <?php if ($showSampleForm): ?>
                            <div style="display: none;">
                                <form action="<?php echo $this->helper('checkout/cart')->getAddUrl($sampleProduct) ?>" method="post" id="product_addtocart_form_sample_<?php echo $sampleProduct->getId() ?>" <?php if ($sampleProduct->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
                                    <input type="hidden" name="product_sample" value="<?php echo $sampleProduct->getId() ?>"/>
                                    <input type="hidden" name="related_product" id="related-products-field" value=""/>
                                    <input type="hidden" value="1"/>
                                    <input type="hidden" name="qty_sample" id="qty_sample" maxlength="12" value="1"/>
                                    <button type="button" title="SIZE SAMPLE" class="button" id="sample-button" onclick="addToShoppingCart(this,this.form)"><span><span>SIZE SAMPLE</span></span></button>
                                </form>
                            </div>
                        <?php endif; ?>
                        <form action="<?php echo $this->helper('checkout/cart')->getAddUrl($product); ?>" method="post" id="product_addtocart_form_<?php echo $product->getId() . '_' . $outfit->getCelebrityOutfitId(); ?>" class="product_addtocart_celebrities_form" <?php if ($product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?> >
                            <?php $product = Mage::getModel('catalog/product')->load($product->getId()) ?>
                            <div class="image_thumb_celeb">
                                <a href="<?php echo $product->getProductUrl() ?>">
                                    <img src="<?php echo $this->helper('catalog/image')->init($product, 'image')->resize(74, 96) ?>"/>
                                </a>
                            </div>
                            <div class="product-shop">
                                <div class="product-name">
                                    <a href="<?php echo $product->getProductUrl() ?>">
                                        <h1><?php echo $product->getName() ?></h1>
                                    </a>
                                </div>
                                <?php echo $this->getProductPriceBlock($product)->toHtml() ?>
                                <div class="outfit-short-description">
                                    <div class="std"><?php echo $this->helper('catalog/output')->productAttribute($product, nl2br($product->getShortDescription()), 'short_description') ?></div>
                                </div>
                                <?php if ($product->getTypeId() == 'configurable' && 1==2): ?>
                                    <script type="text/javascript">
                                        var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig($product) ?>);
                                    </script>
                                    <div class="product-collateral">
                                        <div id="product-options-wrapper" class="product-options">
                                            <?php echo $this->getAttributesBlocks($product)->toHtml() ?>
                                        </div>
                                    </div>
                                <?php endif; ?>
                                <div class="product-options-bottom">
                                    <?php //echo $this->getAddToCartBlock($product)->toHtml() ?>
                                    <?php //echo $this->getAddToBlock($product)->toHtml() ?>
                                    <button class="fancybox fancybox.iframe button piercing-gallery-btn-quickview" id='product-quickview-<?php echo $product->getId() . '_' . $outfit->getCelebrityOutfitId(); ?>' href="<?php echo $this->getUrl('quickview/index/index', array('id' => $product->getId())) ?>"><span><span>View Product Details</span></span><span class="glyphicon glyphicon-shopping-cart"></span></button>
                                </div>
                            </div>
                        </form>
                        <script type="text/javascript">
                            jQuery.noConflict();
                            jQuery('#product-quickview-<?php echo $product->getId() . '_' . $outfit->getCelebrityOutfitId(); ?>').attr('rel', 'gallery').fancybox({
                                openEffect  : 'none',
                                closeEffect : 'none',
                                nextEffect  : 'none',
                                prevEffect  : 'none',
                                padding     : 0,
                                mouseWheel	: false,
                                loop		: false,
                                helpers		: {
                                    title	: null
                                },
                                margin      : [20, 60, 20, 60], // Increase left/right margin
                                width		: 785,
                                height		: 515
                            });

                            jQuery("#product_addtocart_form_<?php echo $product->getId() . '_' . $outfit->getCelebrityOutfitId(); ?> .add-to-cart .button").attr('onclick',"productAddToCartForm[<?php echo $product->getId() ?>].submit(this,this.form)");
                            jQuery("#product_addtocart_form_<?php echo $product->getId() . '_' . $outfit->getCelebrityOutfitId(); ?> .add-to-cart #button-sample").attr('onclick',"doClick()");
                        </script>
                        <script type="text/javascript">
                            productAddToCartForm[<?php echo $product->getId() . $outfit->getCelebrityOutfitId();?>] = new VarienForm('product_addtocart_form_<?php echo $product->getId() . '_' . $outfit->getCelebrityOutfitId();?>');
                            productAddToCartForm[<?php echo $product->getId() . $outfit->getCelebrityOutfitId();?>].submit = function (button, form) {
                                jQuery('.ajax-error-messages').hide();
                                jQuery('.ajax-error-messages').html('');

                                if (jQuery('#product_addtocart_form_<?php echo $product->getId() . '_' . $outfit->getCelebrityOutfitId();?> select.color-attribute').val() != '') {
                                    if (this.validator.validate()) {
                                        if (jQuery('#qty').val() > 0 && jQuery('#qty').val() != '') {
                                            addToShoppingCart(button, form);
                                        }
                                    }
                                } else {
                                    jQuery('.ajax-error-messages').show();
                                    jQuery('.ajax-error-messages').html('This is a required field.');
                                }
                            }.bind(productAddToCartForm[<?php echo $product->getId() . $outfit->getCelebrityOutfitId();?>]);

                            productAddToCartForm[<?php echo $product->getId() . $outfit->getCelebrityOutfitId();?>].submitLight = function (button, url, form) {
                                jQuery('.ajax-error-messages').hide();
                                jQuery('.ajax-error-messages').html('');

                                if (jQuery('#product_addtocart_form_<?php echo $product->getId() . '_' . $outfit->getCelebrityOutfitId();?> select.color-attribute').val() != '') {
                                    if (this.validator.validate()) {
                                        if (jQuery('#qty').val() > 0 && jQuery('#qty').val() != '') {
                                            this.form.action = url;
                                            this.form.submit();
//                                    location.href= url;
                                        }
                                    }
                                } else {
                                    jQuery('.ajax-error-messages').show();
                                    jQuery('.ajax-error-messages').html('This is a required field.');
                                }
                            }.bind(productAddToCartForm[<?php echo $product->getId() . $outfit->getCelebrityOutfitId();?>]);
                            //]]

                            if (jQuery('.product-options-bottom').prev('.outfit-short-description')) {
                                var divExpress = jQuery('.product-options-bottom').prev('.outfit-short-description');
                                var divBueno = jQuery(divExpress).next();

                                jQuery(divBueno).css('margin-top', '20px');
                                jQuery(divBueno).show();
                            }
                        </script>
                    </div>
                <?php endif; endforeach; ?>
            <?php endif; ?>
            </div>
        </div>
    <?php endforeach; ?>
<?php endif; ?>

