<?php
/**
 * @category    Allure
 * @package     Allure_ElasticSearch
 * @version     1.0.0
 * @copyright   Copyright (c) 2019 Allure Software, Inc. (https://www.allureinc.co)
 */
/**
 * @var $this Allure_ElasticSearch_Block_Catalogsearch_Autocomplete_Category
 */
$_category = $this->getEntity();
?>
<?php if ($_category): ?>
<li>
    <a href="<?php echo $this->escapeUrl($this->getCategoryUrl($_category)) ?>"
       title="<?php echo $this->escapeHtml($_category->getName()) ?>">
        <div class="info">
            <span class="name"><?php echo $this->escapeHtml($this->getCategoryPathName($_category)) ?></span>
        </div>
        <div class="clearer"><!-- --></div>
    </a>
</li>
<?php endif ?>