<?php
/**
 * @category    Allure
 * @package     Allure_ElasticSearch
 * @version     1.0.0
 * @copyright   Copyright (c) 2019 Allure Software, Inc. (https://www.allureinc.co)
 */
/**
 * @var $this Allure_ElasticSearch_Block_Catalogsearch_Autocomplete_Cms
 */
$_page = $this->getEntity();
?>
<?php if ($_page): ?>
<li>
    <a href="<?php echo $this->escapeUrl($this->getBaseUrl() . $_page->getIdentifier()) ?>"
       title="<?php echo $this->escapeHtml($_page->getTitle()) ?>">
        <div class="info">
            <span class="name"><?php echo $this->escapeHtml($_page->getTitle()) ?></span>
        </div>
        <div class="clearer"><!-- --></div>
    </a>
</li>
<?php endif ?>