<?php
/**
 * @var $this Allure_SmartAnalytics_Block_View
 */
?>
<?php
$helper = Mage::helper('allure_smartanalytics');

if (!$helper->isEnabled() || !$helper->isEnhancedEcommerceEnabled()) return;

$_product = $this->getProduct();

$_category = Mage::registry('current_category');

if ($_category){
    $_categoryName = $helper->getParentsCategory($_category);
}
else{
    $_categoryName = $helper->getProductCategoryName($_product);
}

$_relatedProductIds = $_product->getRelatedProductIds();

if (count($_relatedProductIds)){
    $_relatedProducts =  $this->getProducts($_relatedProductIds);

    $_relatedProductUrls = array();
    $_relatedProductItems = array();
    $_relatedImpressionList = 'Related Product';
    $_relatedClickLabel = 'Related';
    $_loop = 1;

    foreach ($_relatedProducts as $_relatedProduct){
        $_relatedProductUrls[] = $_relatedProduct->getProductUrl();
        //$_relatedProductUrls[] = substr($_relatedProductUrl,0, strpos($_relatedProductUrl, '?'));

        $_relatedProductItems[] = array(
            'id' => $this->jsQuoteEscape($_relatedProduct->getSku()),
            'name'  => $this->jsQuoteEscape($_relatedProduct->getName()),
            'category' => $this->jsQuoteEscape($helper->getProductCategoryName($_relatedProduct)),
            'brand' => $this->jsQuoteEscape($helper->getBrand($_relatedProduct)),
            'list'  => $_relatedImpressionList,
            'position' => $_loop
        );

        $_loop++;
    }

    $_JsRelatedProducts = json_encode($_relatedProductItems);
    $_JsRelatedProductUrls = json_encode($_relatedProductUrls);


	echo $this->getLayout()
		->createBlock('allure_smartanalytics/impression')
		->setJsProducts($_JsRelatedProducts)
		->setJsProductUrls($_JsRelatedProductUrls)
		->setclickLabel($_relatedClickLabel)
		->setPageView($_relatedClickLabel)
		->setTemplate('allure/smartanalytics/impression.phtml')
		->toHtml();
}

$_upsellProductIds = $_product->getUpSellProductIds();
$_JsUpsellProducts = '';
$_JsUpsellProductUrls = '';

if (count($_upsellProductIds)){
    $_upsellProducts = $this->getProducts($_upsellProductIds);

    $_upsellProductUrls = array();
    $_upsellProductItems = array();
    $_upsellImpressionList = 'Upsell Product';
    $_upsellClickLabel = 'Upsell';
    $_loop = 1;

    foreach ($_upsellProducts as $_upsellProduct) {
        $_upsellProductUrls[] = $_upsellProduct->getProductUrl();
        //$_upsellProductUrls[] = substr($_upsellProductUrl, 0, strpos($_upsellProductUrl, '?'));

        $_upsellProductItems[] = array(
            'id' => $this->jsQuoteEscape($_upsellProduct->getSku()),
            'name' => $this->jsQuoteEscape($_upsellProduct->getName()),
            'category' => $this->jsQuoteEscape($helper->getProductCategoryName($_upsellProduct)),
            'brand' => $this->jsQuoteEscape($helper->getBrand($_upsellProduct)),
            'list' => $_upsellImpressionList,
            'position' => $_loop
        );

        $_loop++;
    }

    $_JsUpsellProducts = json_encode($_upsellProductItems);
    $_JsUpsellProductUrls = json_encode($_upsellProductUrls);

	echo $this->getLayout()
			->createBlock('allure_smartanalytics/impression')
			->setJsProducts($_JsUpsellProducts)
			->setJsProductUrls($_JsUpsellProductUrls)
			->setclickLabel($_upsellClickLabel)
			->setPageView($_upsellClickLabel)
			->setTemplate('allure/smartanalytics/impression.phtml')
			->toHtml();
}
?>

<script>
    //<![CDATA[
    ga('ec:addProduct', {
        'id': '<?php echo $this->jsQuoteEscape($_product->getSku()) ?>',
        'name': '<?php echo $this->jsQuoteEscape($_product->getName()) ?>',
        'category': '<?php echo $this->jsQuoteEscape($_categoryName) ?>',
        'brand': '<?php echo $this->jsQuoteEscape($helper->getBrand($_product)) ?>'
    });

    ga('ec:setAction', 'detail');

	<?php if (strlen($helper->isLinkAccountsEnabled())>0):?>
	ga('<?php echo $helper->getLinkedAccountName()?>.ec:addProduct', {
        'id': '<?php echo $this->jsQuoteEscape($_product->getSku()) ?>',
        'name': '<?php echo $this->jsQuoteEscape($_product->getName()) ?>',
        'category': '<?php echo $_categoryName ?>',
        'brand': '<?php echo $helper->getBrand($_product) ?>'
    });

    ga('<?php echo $helper->getLinkedAccountName()?>.ec:setAction', 'detail');

	<?php endif;?>

	<?php echo $this->getLayout()
						->createBlock('allure_smartanalytics/sendview')
						->setEventLabel('Product Detail - '.$this->jsQuoteEscape($_product->getName()) . ' - '. $this->jsQuoteEscape($_product->getSku()))
						->setTemplate('allure/smartanalytics/sendview.phtml')
						->toHtml();?>

    //]]>
</script>
